### ISSUE TITLE
Make parsing type parameter public

### ISSUE THREAD

**Issue by WaDelma** [dtolnay/syn#100]
Currently you can parse where clauses or type parameter bounds, but parsing type paremeters themself is not public.

I am trying to make custom attribute with custom derive to have where clauses and I want it to have this kind of syntax:
````
#[derive(MyDerive)]
#[custom_attribute(AThing, Where = "T: Trait")]
struct MyStruct<T> { ... }
````
and I need to parse type bound for it.

**Comment by dtolnay** [comment]
We do the same thing in Serde for `#[serde(bound = "T: Trait")]`. Would this work?

```rust
syn::parse_where_clause(&format!("where {}", wh))
```

**Comment by WaDelma** [comment]
Ah yeah. That would work.
Was too focused on trying to find way to parse type parameters :D 

Btw. Is there reason that there isn't common trait for parsing and implementation for them for each language construct

**Comment by dtolnay** [comment]
The only reason is it hasn't been implemented yet. There are a couple better alternatives tracked in #5.
