### ISSUE TITLE
Version 1.0.66 and above break wasm-bindgen

### ISSUE THREAD

**Issue by afilini** [dtolnay/syn#1005]
I noticed this issue while building a crate that uses `js-sys`, which in turn depends on `wasm-bindgen`.

Pinning `syn` to `=0.1.65` makes it compile fine.

<s>I'm still trying to understand the root cause, but is it possible that something changed in `Punctuated` in those new releases? Specifically, when `wasm-bindgen` tries to parse the attribute arguments as a `Punctuated<BindgenAttr, Comma>` the `parse()` function of `BindgenAttr` gets all the tokens including commas and everything. It's almost as if instead of splitting up by commas first and then trying to parse the individual items it would just try to parse everything as the first item.</s>

This is the line:

https://github.com/rustwasm/wasm-bindgen/blob/0cec40630386e22a781f0f2723a92b92231cdbd9/crates/macro-support/src/parser.rs#L221

<s>The error I get at the end is also an "expected comma", which might suggest there's something wrong in `Punctuated`?</s>

Snippet of the errors:

```
error: expected `,`
    --> /home/user/Developer/wasm-bindgen/crates/js-sys/src/lib.rs:1775:39
     |
1775 |         #[wasm_bindgen(js_namespace = Math)]
     |                                       ^^^^

error: expected `,`
    --> /home/user/Developer/wasm-bindgen/crates/js-sys/src/lib.rs:2844:39
     |
2844 |         #[wasm_bindgen(js_namespace = Reflect, js_name = getPrototypeOf, catch)]
     |                                       ^^^^^^^
```

-----

EDIT: sorry, now that I'm looking into how `syn` parses stuff what I said above doesn't make any sense. The issue remains though, and it looks like it's hit whenever `js_namespace` is used, which is parsed here:

https://github.com/rustwasm/wasm-bindgen/blob/0cec40630386e22a781f0f2723a92b92231cdbd9/crates/macro-support/src/parser.rs#L301-L327

I noticed that they use `ExprArray` and that there were some changes done to it in 1.0.66, so could this issue be related to those changes?

**Comment by afilini** [comment]
Oh okay, I think I figured it out: the old way of parsing `ExprArray` was consuming the ident anyway, before returning an error because things like `Math` or `Reflect` are not arrays, but I believe it would still be a valid expression.

The new way probably leaves the tokens in the `ParseBuffer`, and that's where `Punctuated` fails because it expects a comma but it finds whatever was left in there.

I guess this is not your bug, in a way this might be fixing a bug that was present before, but still it's a breaking change.. not sure how you handle those.

Btw, please double-check everything I said, I think it makes sense but I might be completely wrong

**Comment by Charles-Schleich** [comment]
Same issue here. Caused failing build in `js-sys` `console_error_panic_hook`, among others. 
Pinning `syn = "=1.0.65"` seems to fix build issues.

**Comment by dtolnay** [comment]
https://github.com/dtolnay/syn/issues/1005#issuecomment-809303566 is correct. This is not an issue with Syn, it's brittle/wrong code in wasm-bindgen. The code is assuming the exact number of tokens consumed from the input stream by a failed expr parse, which has never been a guarantee of the API.
