### ISSUE TITLE
Access the value of a `const` variable?

### ISSUE THREAD

**Issue by MaikKlein** [dtolnay/syn#101]
See https://github.com/MaikKlein/enumflags/issues/2

```
const FOO: u8 = 0b0100;
 #[derive(EnumFlags, Copy, Clone, Debug)]
#[repr(u8)]
pub enum Test {
    A = 0b0001,
    B = 0b0010,
    C = FOO,
    D = 0b1000,
}
```

I would like to access the value of `FOO` here. Would that be possible?

**Comment by dtolnay** [comment]
That isn't possible with the current design of Rust macros. Currently the compiler does macro expansion before it does name resolution so during macro expansion it has no way to connect the word "FOO" to that constant.

You may be able to work around it in other ways, for example have the EnumFlags derive also emit the constant definition.

```rust
#[derive(EnumFlags, Copy, Clone, Debug)]
#[repr(u8)]
pub enum Test {
    A = 0b0001,
    B = 0b0010,
    #[enumflags(const = "FOO")]
    C = 0b0100,
    D = 0b1000,
}
```
