### ISSUE TITLE
Is there a way to tokenize LitInt as hex representation?

### ISSUE THREAD

**Issue by Robbepop** [dtolnay/syn#1029]
E.g. instead of `66u32` you get `0x42u32`?

For my use case it would make the proc. macro output more human readable and therefore improve debugability.

**Comment by russcam** [comment]
You can emit the hex representation with

```rust
let hex = syn::Lit::new(Literal::from_str(&format!("0x{:X}", 66u32)).unwrap());
quote!{ 
    #hex
}
```

which yields

```
0x42
```

**Comment by Robbepop** [comment]
Thanks a lot for the info - it works really well!
However, I think a more user friendly API might be useful.

**Comment by dtolnay** [comment]
I think this API is fine as is for this use case.
