### ISSUE TITLE
FromIterator<Into<PathSegment>>, Ord for Path

### ISSUE THREAD

**Issue by clarcharr** [dtolnay/syn#103]
Willing to write this up at some point, but figured I should open an issue for it.

**Comment by dtolnay** [comment]
For `FromIterator` I would prefer to solve this with `parse_quote!` instead to save on compile time and be maximally flexible.

```rust
let path_suffix = vec![Ident::from("collections"), Ident::from("HashSet")];
let path: Path = parse_quote!(::std #(:: #path_suffix)*);
// expands to ::std::collections::HashSet
```

For `Ord` I would prefer if people explicitly compare `path.into_tokens().to_string()` if that is the ordering they want.
