### ISSUE TITLE
Add associated constants for common paths.

### ISSUE THREAD

**Issue by XAMPPRocky** [dtolnay/syn#1032]
When building paths for imports in syn, you usually have to construct the whole type yourself from basic blocks, however there are some paths (specifically path roots) that very common, and it would nice if there were associated constants to make them easier to use, and harder to mistype.

The main two I'm currently thinking about is `self` and `crate`. It would be really for example if when creating different visibilities to be able to say something like the following. (well for visibilities it might be nice if they had associated constants also)

```rust
let path = None;

// parse use input...

// Current
syn::VisRestricted {
    pub_token: Default::default(),
    paren_token: Default::default(),
    in_token: None,
    path: path.unwrap_or_else(|| Path::from(Ident::new("crate", Span::mixed_site()),
}

// Proposed
syn::VisRestricted {
    pub_token: Default::default(),
    paren_token: Default::default(),
    in_token: None,
    path: path.unwrap_or(Path::CRATE),
}
```

**Comment by dtolnay** [comment]
These syntax trees are designed to be instantiated by a parser, not that kind of handwritten code. The recommended way to make those visibilities would be:

```rust
let vis: Visibility = parse_quote!(crate);
```

or:

```rust
let path: Path = parse_quote!(self);
```

**Comment by XAMPPRocky** [comment]
Thanks for the tip! It would be nice if there was a user guide of how to write "good" syn code, as these kinds of idioms are not always obvious when just going to docs.rs
