### ISSUE TITLE
Support extended_key_value_attributes syntax

### ISSUE THREAD

**Issue by kangalioo** [dtolnay/syn#1035]
The [`extended_key_value_attributes`](https://github.com/rust-lang/rust/pull/83366) Rust pull request was recently stabilized. Now, the Rust parser accept arbitrary expressions in key value attributes.

For example, this code now successfully compiles in Rust 1.53:
```rust
#[cfg(FALSE)]
#[hello = ["hello", 1 + 1, |a, b| a * b] / 3]
struct Foo;
```

I think syn's meta structs (`Meta`, `NestedMeta`, `MetaNameValue`, `MetaList`?) need to be adapted to support the new syntax.

(This will allow proc-macros to have much more intuitive and practical syntaxes :D)

**Comment by dtolnay** [comment]
I am not planning for Meta to accommodate this. You can find previous discussion in https://github.com/dtolnay/syn/issues/687#issuecomment-517933347 &ndash; https://github.com/dtolnay/syn/issues/687#issuecomment-517943389.
