### ISSUE TITLE
Parsing ambiguous for loop

### ISSUE THREAD

**Issue by 1tgr** [dtolnay/syn#1039]
Given my own definition of `ExprForLoop`, syn appears to be parsing the `expr {}` in `for pat in expr { }` as a struct initializer.

In the `Parse` implementation for the real `syn::ExprForLoop` I can see it's parsing the `expr` using the private `expr_no_struct` function, which asks `Expr` to parse itself against `AllowStruct(false)`.

Is there a way I can access the ambiguous expr parser so that I can use `AllowStruct(false)`, or else replicate the behaviour in my own code?

Here is my `ExprForLoop` definition, which shows a correct parse when the expr is not ambiguous, and an incorrect struct-style parse when it is ambiguous:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5486955005ae59a3087b8eae3e2bd61e

**Comment by dtolnay** [comment]
Yes, you'll need to use https://docs.rs/syn/1.0.73/syn/enum.Expr.html#method.parse_without_eager_brace.
