### ISSUE TITLE
Make more details pub?

### ISSUE THREAD

**Issue by dhardy** [dtolnay/syn#1092]
While building macros over `syn` (frequently copying parts) I have noticed that it has quite a large private API — many parsing functions, and e.g. `TypeGenerics` has a private field and no public constructor.

I'm not really sure if/how to address this hence no PR. Everything can be worked around, but in several cases I've essentially had to copy parsing functions.

**Comment by dtolnay** [comment]
The public constructor for `TypeGenerics` is `Generics::split_for_impl`, as mentioned in its rustdoc.

I think you would need to be more specific about what specific private APIs you are requesting be directly accessible. I can't just start exposing everything that is currently private.
