### ISSUE TITLE
Implement `.combine()` equivalent for `Option<Error>`

### ISSUE THREAD

**Issue by JakobDegen** [dtolnay/syn#1095]
This would be very useful for someone (me) who is accumulating zero or more errors; it should essentially look like this
```rust
impl Option<Error> {
    pub fn combine(&mut self, e: Error) {
        match self {
            Some(x) => x.combine(e),
            None => *self = Some(e),
        }
    }
}
```
Posting as an issue to get feedback, if this is something the library would be interested in I'd be happy to provide a PR as well.

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate.
