### ISSUE TITLE
Match doc strings

### ISSUE THREAD

**Issue by glennpierce** [dtolnay/syn#110]
Is it possible to match on doc strings applied to say a struct ?

I wish to describe some capabilities with doc strings so thought I could grab the docs string for a particular struct and then process them more from that points.

**Comment by dtolnay** [comment]
Yes, doc comments are preserved in the AST.

```rust
extern crate syn;

fn main() {
    let glennpierce = r#"/// struct
                         struct GlennPierce {
                             /// field
                             a: u8,
                         }"#;
    let ast = syn::parse_derive_input(glennpierce).unwrap();
    println!("{:#?}", ast);
}
```

That said, it would be more idiomatic to control behavior using attributes instead ([like these](https://serde.rs/attributes.html)).
