### ISSUE TITLE
`syn::parse` returns `TypePath` when parsing `Option<T>`

### ISSUE THREAD

**Issue by duskmoon314** [dtolnay/syn#1100]
Hi, I'm learning to write proc-macro and trying to do something on a struct's `Option<T>` fields.

To be more precise, I define a struct `TypeOption` like this to parse `Option<T>` because I think the type is `Type::Verbatim(TokenStream)` at first:

```rust
struct TypeOption {
    _option_token: kw::Option,
    _lt_token: Token![<],
    ty: Type,
    _rt_token: Token![>],
}
```

So I write my code like this:

```rust
let field_type = fields.named.iter().map(|f| {
                match &f.ty {
                    Type::Verbatim(tokens) => {
                        let parse_option =
                            syn::parse::<TypeOption>(TokenStream::from(tokens.clone()));
                        match parse_option {
                            Ok(_) => ...
```

And I use this to parse a struct like this:

```rust
pub struct Article<T> {
    author: String,
    content: String,
    liked: usize,
    comments: T,
    link: Option<String>,
}
```

But I cannot get into this branch when parsing `link: Option<String>`. Then I found out that `f.ty` is `TypePath` with `qself: None` instead of `Verbatim`.

The doc said that `TypePath` is "A path like `std::slice::Iter`". 😢 

Is this a bug or did I miss some instructions？

**Comment by dtolnay** [comment]
I believe this is behaving correctly. `Option<T>` is a path with 1 segment and angle bracketed path arguments.
