### ISSUE TITLE
Confuse with parse macro, Item or Expr ?

### ISSUE THREAD

**Issue by M-Adoo** [dtolnay/syn#1101]
There is a example when I try to parse a macro expression

```
fn parse_macro_expr() {
  let tokens = quote::quote! {
      declare! {}
  };

  let expr: syn::Stmt = syn::parse2(tokens).unwrap();
  println!("{:?}", expr);
}

```

The output is  `Item(Macro(ItemMacro { ... }))`.  

Would it perfer `Expr(Macro(ExprMacro(...)))`?

**Comment by dtolnay** [comment]
I think this behavior is fine. To get an Expr you can parse `declare!();` or `declare![];` instead.
