### ISSUE TITLE
[Bug?] A couple "Syn error: expected identifier"s in 1.57.0 standard library source

### ISSUE THREAD

**Issue by mhammerly** [dtolnay/syn#1103]
https://github.com/rust-lang/rust/blob/1.57.0/library/alloc/src/borrow.rs
https://github.com/rust-lang/rust/blob/1.57.0/library/core/src/intrinsics.rs

Using [Reindeer](https://github.com/facebookincubator/reindeer) to buckify the standard library. Reindeer uses the `srcfiles` crate to detect src files in a way that is more thorough/intelligent than globbing, and `srcfiles` uses `syn` internally.

Reindeer is reporting that `library/core/src/intrinsics.rs` and `library/alloc/src/borrow.rs` from 1.57.0's source fail to parse with `Syn error: expected identifier`. A before/after diff between a rev where it worked and the one where I first observed it didn't is pasted here: https://pastebin.com/7HtV8MMB

1.57.0 was literally just released so for that reason and I have a workaround so for those and other reasons this isn't a big deal - just collecting the information for you to consider. Thanks!

**Comment by dtolnay** [comment]
Both of the files you linked parse fine according to the following program, so I don't think this is an issue in syn.

```rust
// [dependencies]
// syn = { version = "1.0", features = ["full"] }

fn main() {
    syn::parse_file(include_str!("../borrow.rs")).unwrap();
    syn::parse_file(include_str!("../intrinsics.rs")).unwrap();
}
```
