### ISSUE TITLE
`span()` for all items?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [dtolnay/syn#1104]
In many cases an error might want to refer to the joined spans of multiple lower level items. If `syn::Stmt` implemented `span()` which returned the joined span of all its children, this would be much easier then having to manually join every child span, to refer to a line.

Is there a reason this hasn't or wouldn't be implemented or should I submit a pull request on this? (or quite possibly, am I missing something?)

**Comment by dtolnay** [comment]
All the syntax tree data structures including `syn::Stmt` already have a span function.
https://docs.rs/syn/1.0.82/syn/?search=span()
