### ISSUE TITLE
`syn::Arm` parses but `syn::Pat` does not with the "same" input

### ISSUE THREAD

**Issue by Dzejkop** [dtolnay/syn#1107]
It's possible to parse `"lit 1" | "lit 2" => todo!()` into `syn::Arm`, but parsing `"lit 1" | "lit 2"` into `syn::Pat` fails with `unexpected token`.

[Playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a28d125f5714ab4f45a194d1756a465c)

**Comment by dtolnay** [comment]
The tests in that playground link both pass as of syn 2.
