### ISSUE TITLE
Consider mentioning syn::parse() and syn::parse2() in the doc for syn::parse module

### ISSUE THREAD

**Issue by JohnScience** [dtolnay/syn#1112]
For simplicity, I was using `visit` feature

```rust
impl<'ast> Visit<'ast> for ReprCPubStructs {
    fn visit_item_struct(&mut self, node: &'ast syn::ItemStruct) {
        if is_repr_c_pub_struct(node) {
            self.0.push(LineColumnEnds::new(&node.span()))
        };
    }
}
```
and in my `is_repr_c_pub_struct()` function
```
let is_repr_c = node.attrs.iter().any(|attr| {
    attr.path.is_ident("repr") && matches!(parse2::<ParenthesizedC>(attr.tokens), Ok(_))
});
```
I needed `syn::parse2` to check if `tokens: proc_macro2::TokenStream` matched `(C)` as in `#[repr(C)]`. However, in order to find I needed it I went a long path.

I realized I needed to parse these tokens, so I found my way to `syn::parse` module. There was a catch, though. It neither contained all the things I needed for parsing and `syn` had to offer nor did it mention them. Assuming there could be good reasons for that, I bring up this issue.

Merry Christmas!

**Comment by dtolnay** [comment]
There is already a section in the `syn::parse` module documentation dedicated to mentioning `parse()` and `parse2()`.
https://docs.rs/syn/1.0.83/syn/parse/index.html#the-synparse-functions
