### ISSUE TITLE
Improvement for the doc in `syn::parse` module

### ISSUE THREAD

**Issue by JohnScience** [dtolnay/syn#1115]
# Problem

The sentence "The `syn::parse, syn::parse2`, and `syn::parse_str` functions serve as an entry point for parsing syntax tree nodes that can be parsed in an obvious default way." from https://docs.rs/syn/1.0.83/syn/parse/index.html#the-synparse-functions is misleading (in isolation). The next sentence in the paragraph does does clarify what these
functions can be used for but it doesn't make the former sentence good.

## Explanation

The original sentence "The `syn::parse, syn::parse2`, and `syn::parse_str` functions serve as an entry point for parsing syntax tree nodes that can be parsed in an obvious default way." can be understood as a [functional](https://www.ucfmapper.com/education/various-types-definitions/#:~:text=Functional%20definitions) definition through [definite description](https://en.wikipedia.org/wiki/Definite_description).

Since `syn::parse::Parse` trait can be implemented on arbitrary types, the sentence "The `syn::parse, syn::parse2`, and `syn::parse_str` functions serve as an entry point for parsing syntax tree nodes that can be parsed in an obvious default way." is then misleading in such interpretation.

I think the root of the problem is the restrictive relative clause "that can be parsed
in an obvious default way" 
(https://en.wikipedia.org/wiki/Relative_clause#Restrictive_and_non-restrictive).

## Original snippet from `syn/src/parse.rs`

```rust
//! # The `syn::parse*` functions
//!
//! The [`syn::parse`], [`syn::parse2`], and [`syn::parse_str`] functions serve
//! as an entry point for parsing syntax tree nodes that can be parsed in an
//! obvious default way. These functions can return any syntax tree node that
//! implements the [`Parse`] trait, which includes most types in Syn.
//!
//! [`syn::parse`]: crate::parse()
//! [`syn::parse2`]: crate::parse2()
//! [`syn::parse_str`]: crate::parse_str()
//!
```

# Proposed alternative
```rust
//! # The `syn::parse*` functions
//!
//! The [`syn::parse`], [`syn::parse2`], and [`syn::parse_str`] functions serve
//! as an entry point for parsing syntax tree nodes that implement
//! [`Parse`] trait, which is the case for most types in Syn.
//!
//! One example of many types in Syn that implement [`Parse`] is [`syn::Type`].
//!
//! [`syn::parse`]: crate::parse()
//! [`syn::parse2`]: crate::parse2()
//! [`syn::parse_str`]: crate::parse_str()
//! [`syn::Type`]: crate::Type
//!
```
 
# Context

The paragraph continues with an example

```rust
//! ```
//! use syn::Type;
//!
//! # fn run_parser() -> syn::Result<()> {
//! let t: Type = syn::parse_str("std::collections::HashMap<String, Value>")?;
//! #     Ok(())
//! # }
//! #
//! # run_parser().unwrap();
//! ```
```

# Warning

The alternative is proposed by a non-native English speaker and for that reason can be ungrammatical. However, the author believes the original sentence in the explanation is misleading.

**Comment by dtolnay** [comment]
Thanks for suggesting alternative wording! Ultimately I think I prefer this as currently written. The idea that syntax tree nodes shouldn't implement Parse / shouldn't be usable with those parse functions unless there is an obvious default interpretation of what parsing one should mean is an important aspect of the role of those parse functions, which this page is responsible for conveying.

**Comment by JohnScience** [comment]
@dtolnay Do I understand you correctly that you want to provide a recommendation (or prescriptive note) on the use of `syn::parse*` functions? If so, it would be better to replace the misleading "serves" to "should serve" in order to make the message clear.

Then the following snippet in `syn/src/parse.rs`

```rust
//! # The `syn::parse*` functions
//!
//! The [`syn::parse`], [`syn::parse2`], and [`syn::parse_str`] functions serve
//! as an entry point for parsing syntax tree nodes that can be parsed in an
//! obvious default way. These functions can return any syntax tree node that
//! implements the [`Parse`] trait, which includes most types in Syn.
//!
//! [`syn::parse`]: crate::parse()
//! [`syn::parse2`]: crate::parse2()
//! [`syn::parse_str`]: crate::parse_str()
//!
```
becomes

```rust
//! # The `syn::parse*` functions
//!
//! The [`syn::parse`], [`syn::parse2`], and [`syn::parse_str`] functions serve
//! as an entry point for parsing syntax tree nodes that can be parsed in an
//! obvious default way. These functions can return any syntax tree node that
//! implements the [`Parse`] trait, which includes most types in Syn.
//!
//! [`syn::parse`]: crate::parse()
//! [`syn::parse2`]: crate::parse2()
//! [`syn::parse_str`]: crate::parse_str()
//!
```
