### ISSUE TITLE
Where to put small utility functions in the codebase

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [dtolnay/syn#1124]
Recently I was trying to add some utilities functions including some unwrapping like [`Option::unwrap`](https://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap):
```rust
type UnwrapResult<'a, T> = Result<&'a T, &'static str>;
impl UnwrapStmt for syn::Stmt {
    fn local(&self) -> UnwrapResult<syn::Local> {
        match self {
            Self::Local(local) => Ok(local),
            _ => Err("called `Stmt::local()` on a non `Local` value"),
        }
    }
    // ...
}
```
And creating a derive macro for a trait `SetSpan` (which I am quite surprised is unimplemented) which might for example allow setting the span of a [`Expr`](https://docs.rs/syn/latest/syn/enum.Expr.html).
```rust
pub trait SetSpan {
    /// Sets all spans within `self` to the given `span`.
    fn set_span(&mut self, span: proc_macro::Span);
}
```
While the un-implementation of the former is a minor inconvenience it feels like the un-implementation of the later is quite a considerable piece of missing functionality (and would certainly be very useful for a couple of my current projects).

But in cloning and looking at the repo I am completely lost. Where would I even add some small functionality like unwrapping an enum variant?

I don't know if I'm being particularly dense but I just don't where to start. I would love to contribute some useful functionality (and I think it certainly has its place possibly in a new feature) and I would really appreciate if you could help me understand where to start  here.

**Comment by MingweiSamuel** [comment]
A lot of the code (specifically the code in the [`/src/gen`]) is generated by the [`/codegen`](https://github.com/dtolnay/syn/tree/master/codegen) subpackage. Any sort of code that needs to be applied to a lot of AST structs/enums should probably use the codegen.

**Comment by dtolnay** [comment]
I think neither of those are things I would want to include in this crate. This crate isn't intended to be a grab-bag of macro related utilities. It's focused as much as possible on parsing, so you'll find that the src directory is organized around the different elements of Rust syntax being parsed (expressions, statements, items, patterns, paths, types, etc).
