### ISSUE TITLE
`Reserved` type in `syn.json`

### ISSUE THREAD

**Issue by pushkine** [dtolnay/syn#1129]
https://github.com/dtolnay/syn/blob/7ff292d5ac9802a3cc7908c5641a060bd5cf0d78/syn.json#L1569-L1571

Hey there's this one symbol `Reserved` that is not defined, it's the only one that doesn't resolve in the file so I was wondering if its inclusion in `syn.json` was intended

related #678

**Comment by dtolnay** [comment]
Yes it's intended.
