### ISSUE TITLE
`syn::custom_keyword` as `&'static str`, to compare it to an ident.

### ISSUE THREAD

**Issue by ranfdev** [dtolnay/syn#1132]
`syn::custom_keyword` is useful, but I can't find a way to get the keyword as a `str`. This makes it impossible to compare a custom keyword to an `Ident`.

In my code I've found this workaround:
```rust
macro_rules! custom_keyword {
    ($ident:ident) => {
        syn::custom_keyword!($ident);
        impl $ident {
            #[allow(dead_code)]
            pub const STR: &'static str = stringify!($ident);
        }
    }
}

mod kw {
  custom_keyword!(set);
}

// To view the custom keyword as an `&str`
kw::set::STR
```

**Comment by dtolnay** [comment]
Your macro looks good to me. I don't think this needs to be built into this crate.
