### ISSUE TITLE
Provide an API to strip trailing punctuation in `Punctuated`

### ISSUE THREAD

**Issue by Veetaha** [dtolnay/syn#1134]
Hey, it would be cool if there was a method to remove the trailing punctuation in `syn::punctuated::Punctuated` type.
As for now, we are using this workaround to do this:

```rust
let val = seq.pop().map(|val| val.into_value());
seq.extend(val);
```

Which is very ugly. Better if `syn` exposed a method to strip trailing punctuation natively. Or if there is any better way to implement this using the existing API, I would be grateful if you could point out that.

**Comment by dtolnay** [comment]
I think the code you've shown is fine. I don't see this being a common enough operation that we'd need a method for it built into this library.
