### ISSUE TITLE
Can't parse 128-bit integer literals

### ISSUE THREAD

**Issue by Arnavion** [dtolnay/syn#114]
As part of updating the `tests/rust` submodule for the catch-expressions PR, I found syn can't parse u128 literals.

```rust
let raw = "0x112233445566778899aabbccddeeff11u128";
let actual = parse_expr(raw).unwrap(); // fails
```

Prevents `test_round_trip` from parsing atleast [`tests/rust/src/libstd/net/ip.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/libstd/net/ip.rs#L1675) (`parse_crate` stops before the entire `mod tests` item that contains the literal, then complains that there are unparsed tokens).

Affected files:

- [`tests/rust/src/libcompiler_builtins/lib.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/libcompiler_builtins/lib.rs#L548)
- [`tests/rust/src/libstd/net/ip.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/libstd/net/ip.rs#L1675)
- [`tests/rust/src/test/run-pass/i128.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/test/run-pass/i128.rs#L25)
- [`tests/rust/src/test/run-pass/i128-ffi.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/test/run-pass/i128-ffi.rs#L34)
- [`tests/rust/src/test/run-pass/issue-38987.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/test/run-pass/issue-38987.rs#L13)
- [`tests/rust/src/test/run-pass/u128.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/test/run-pass/u128.rs#L19)

**Comment by dtolnay** [comment]
Thanks! We will need to figure out how to represent the parsed result. Libsyntax just puts i128/u128 in the AST but we can't do that on stable.
