### ISSUE TITLE
Fails to parse a `use` statement with leading colons inside a `UseTree`

### ISSUE THREAD

**Issue by danielhenrymantilla** [dtolnay/syn#1143]
I tried this code:

```rust
use {
    ::{
        proc_macro2::{
            TokenStream,
        },
        syn::*,
    },
    crate::{
        utils::{
            // …
        },
    }, 
};

fn main() {
    parse_file(include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/", file!())))
        .unwrap()
    ;
}
```

I expected to see this happen: `parse_file` succeeding.

Instead, it fails because of the leading colons inside the braced use "trees".

  - [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3d33ca344bdbed255155ee9b6fde7b2b)

___

While fixing it ought to be easy enough for me to submit a PR, I'm struggling to come up with a fix that does not involve:

  - a lossy process (parsing the leading colon and then discarding it by lack of field to assign it to);
  - a breaking change (changing the structure of `ItemUse` or of its `UseTree`).

The only way I personally see would be to define a new `ItemUse2` variant of `Item`, and somehow have the parser fall back to `ItemUse2` while it is parsing a `ItemUse` if it finds out there is a leading colon inside the first braced `UseTree`…

___

I've discovered this bug by incidentally coming up with an example that https://github.com/dtolnay/prettyplease can't handle because of it.

**Comment by dtolnay** [comment]
I think it's fine not to parse this. No one should write code like that, so making the syntax tree more complicated for it would be a bad tradeoff.

**Comment by danielhenrymantilla** [comment]
A pity, I have to admit, but yeah, I understand that the _tradeoff_ may not warrant the ordeal that _full parse/AST support_ would suppose while under the `1.0` semver constraints[^1].

[^1]: I think it could be a nice thing to change for `2.0`, should such a release ever happen

___

### Do not parse, just _tolerate_ (example of a possible implementation in https://github.com/dtolnay/syn/pull/1145)

Then, what about dropping the full parsing/AST support, but trying to keep **a minimum amount of support** so that `prettyplease` or other stuff parsing whole files/modules can **tolerate/withstand such a `use`**.

Indeed, I don't think that occurrences such code would be _that_ rare, or even rare enough for `syn` to be able to afford this inconsistency with `rustc` parsing: some basic grep.app searches do show occurrences of both:

  - [1160](https://grep.app/search?q=%20use%20%7B&case=true&filter[lang][0]=Rust) + [644](https://grep.app/search?q=%5Euse%20%7B&regexp=true&case=true&filter[lang][0]=Rust) = 1804 top-level use trees: `use { … }`. This is indeed useful when `#[cfg(…)]`-gating such a `use`.
  - [2442](https://grep.app/search?current=100&q=use%20%3A%3A&case=true&filter[lang][0]=Rust) occurrences[^2] of `use ::`, that is, `use` that involve full paths. Sometimes for style/taste (less ambiguous for the human reader), but also sometimes for genuine disambiguation / for macro-generated code robustness.

[^2]: disclaimer: this is an _upper bound_ rather than an actual number, since it will include 2015-edition code, where `::`-leading paths had a different meaning that I don't think is fair to bring to the discussion (obsolete edition).

So it stands to reason that every now and then, the intersection between both cases be non-empty; that something like the following could be a _plausible_ (snippet of a) source file:

```rs
#[cfg(foo)]
use {
    ::fs::FsPool,
    ::std::fs,
    crate::something_else,
};

#[cfg(foo)]
fn bar() -> Result<()> {
    let thread_pool = FsPool::default();
    let file =
        fs::OpenOptions::new()
            .write(true)
            .create_new(true)?
    ;
    let mut thread_pooled_file = thread_pool.write(file);
    // …
}
```

#### Implementation

_Tolerating_ such `use` items is actually not that hard or annoying to maintain: it's a matter of adding a fallback branch when attempting to parse an `ItemUse`, so as to fall back to an `Item` of the `Verbatim` variant: this effectively still does not provide proper AST support, but at least it allows tools such as `prettyplease` or `build.rs` scripts that want to visit codebases to be able to withstand a snippet such as the one just above 🙂
