### ISSUE TITLE
Add more example of how to use "fold"

### ISSUE THREAD

**Issue by titaneric** [dtolnay/syn#1149]
I would like to share more example of fold in the docs which is  to "publicize" the main function. The similar technique could be used to import the "publicized function" from `lib.rs` into the `main.rs` of the library crates which is possible to accelerate the compiling speed by the power of `sccache`.

Example:

Suppose we have a library crates called `pub_fn`

Cargo.toml
```toml
[package]
name = "pub_fn"
version = "0.1.0"
edition = "2021"
```

original lib.rs
```rs
fn main() {
   println!("print from main fn");
}
```

transformed lib.rs
```rs
pub fn main() {
   println!("print from main fn");
}
```

main.rs
```rs
fn main() {
  pub_fn::main();
}
```

**Comment by dtolnay** [comment]
Thanks for the suggestion! I'll close this per https://github.com/dtolnay/syn/pull/1150#pullrequestreview-921231740.
