### ISSUE TITLE
LArrow placement syntax parsed incorrectly

### ISSUE THREAD

**Issue by Arnavion** [dtolnay/syn#115]
As part of updating the `tests/rust` submodule for the catch-expressions PR, I found syn parses `<-` placement syntax incorrectly.

```rust
let raw = r#"
    fn foo() {
        &mut a <- 1;
    }
"#;

let actual = parse_item(raw).unwrap();
println!("{:?}", actual); // Binary(Lt, Expr { &mut a }, Unary(Neg, Expr { node: Lit(Int(1, Unsuffixed)) })
```

Prevents `test_round_trip` from running on atleast [`tests/rust/src/libcollections/tests/binary_heap.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/libcollections/tests/binary_heap.rs#L317) (`after` emits `&mut a < -1` since it thinks it's a comparison to a negative number).

Seems the existing `expr_in_place` rule needs to be updated.

Aside: `LArrow` is already defined as a `Token`, but I guess the parser backtracks and re-parses it as an `Lt` instead since it doesn't understand placement as a valid expression. If so, that is probably something else to fix.

Affected files:

- [`tests/rust/src/libcollections/tests/binary_heap.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/libcollections/tests/binary_heap.rs#L317)
- [`tests/rust/src/libcollections/tests/vec.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/libcollections/tests/vec.rs#L691)
- [`tests/rust/src/libcollections/tests/vec_deque.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/libcollections/tests/vec_deque.rs#L1007)
- [`tests/rust/src/librustc_mir/build/matches/test.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/librustc_mir/build/matches/test.rs#L195)
- [`tests/rust/src/libstd/collections/hash/map.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/libstd/collections/hash/map.rs#L3410)

**Comment by mystor** [comment]
This parses correctly on `syn 0.12` (I think I fixed it in #168)
