### ISSUE TITLE
Move to non-exhaustive enums in 1.0.90, shouldn't this be a breaking change?

### ISSUE THREAD

**Issue by setzer22** [dtolnay/syn#1151]
I just realized I was one of the lucky first downloaders of 1.0.90 :tada: (just released a few minutes ago) First of all, where do I get my prize? :smile: 

But more importantly, this new version removes the `__TestExhaustive` enum variant in favor of a new mechanism. I'd say this is a breaking change? It definitely broke my build :sweat_smile:

**Comment by dtolnay** [comment]
If you were not exhaustively matching, I don't see how you would be affected.

If you were exhaustively matching using "the only supported idiom for exhaustive matching" that is described in syn's docs, that means you were explicitly requesting for your tests (not your library) to be broken periodically as the enum evolves, and be forced to update your code. Please do so.

If you were exhaustively matching in some other way that you invented, then that has never been supported and it's not my concern what happens with that code.
