### ISSUE TITLE
non_exhaustive_omitted_patterns lint is unstable

### ISSUE THREAD

**Issue by dhardy** [dtolnay/syn#1154]
According to #1067, this lint was to be stabilised in Rust 1.57. It is not stable yet according to the [tracking issue](https://github.com/rust-lang/rust/issues/89554).

Maybe #1067 should be reverted?

**Comment by dhardy** [comment]
I think it is a step backwards, considering the previous solution worked just fine. But never mind.

**Comment by dtolnay** [comment]
I think it is a step forward because it's no longer possible for a crate to break its downstream users when a variant gets added.
