### ISSUE TITLE
Make `syn::reserved::Reserved` public?

### ISSUE THREAD

**Issue by JElgar** [dtolnay/syn#1155]
Hello! I'm trying to create a function that creates a reference to an existing expression. It's very possible I'm missing something but I can't find a way to create the `ExprReference` struct without access to the `syn::reserved::Reserved` module.
I can't create an ExprReference without the raw attribute but I also can't create the raw attribute. Am I completely missing something or would it make sense to make the reserved package public so that an ExprReference can be created?

```
pub fn create_reference_of_expr(expr: &Expr) -> Expr {
    Expr::Reference(
        ExprReference{
            attrs: Vec::new(),
            and_token: token::And { spans: [Span::call_site()] },
            mutability: None,
            raw: syn::reserved::Reserved,
            expr: Box::new(expr.clone()),
        }
    )
}
```
Thanks for all your hard work on this package!

**Comment by dtolnay** [comment]
The syn data structures are only intended to be created by syn's parser.

```rust
use syn::parse_quote;

pub fn create_reference_of_expr(expr: &Expr) -> Expr {
    parse_quote!(&#expr)
}
```
