### ISSUE TITLE
Is it possible to peek for `EOF`?

### ISSUE THREAD

**Issue by ModProg** [dtolnay/syn#1161]
I need to check if I'm at the end of the input or in front of some delimiter, to parse in a certain way. Checking for the delimiter works perfectly with `peek2` but I cannot check if I'm at the end of the input with peeking.

**Comment by dtolnay** [comment]
#889 describes some ways to accomplish this.

**Comment by ModProg** [comment]
For anyone stumbling on this and looking for something that does not require forking everytime one wants to peek if the token is the last one, I found that there is a way to define ones own `Eof` token:

```rs
#[derive(Clone, Copy, Debug, Default)]
struct Eof {}

impl syn::token::CustomToken for Eof {
    fn peek(cursor: syn::buffer::Cursor) -> bool {
        cursor.eof()
    }

    fn display() -> &'static str {
        "EOF"
    }
}

#[allow(non_snake_case)]
fn Eof(_: impl syn::__private::IntoSpans<Span>) -> Eof {
    Eof {}
}
```

note though that this uses the `IntoSpans` trait which is inside `__private` and `CustomToken` which is `#[doc(hidden)]` and which probably do not have any stability guarantees. So tread carefully.

**Comment by ModProg** [comment]
The solution I proposed doesn not seem to work anymore (shouldn't use hidden API I guess), alternative is to create a helper function that just steps a bit to check for eof:
```rs
fn peek2_eof(input: ParseStream) -> bool {
    let mut ts = input.fork().parse::<TokenStream>().unwrap().into_iter();
    ts.next();
    ts.next().is_none()
}
```
