### ISSUE TITLE
maybe I can design an input to make this crate stackoverflow? 

### ISSUE THREAD

**Issue by Ren-ZY** [dtolnay/syn#1163]
Hello!
I have found a lot of recursive functions in this crate.
1. unary_expr -> unary_expr (src/expr.rs, line:1533)
2. parse_expr -> parse_expr (src/expr.rs, line: 1398)
3. span_of_unexpected_ignoring_nones -> span_of_unexpected_ignoring_nones (src/expr.rs, line: 446)
4. inner_new -> inner_new (src/buffer.rs, line: 59)
Maybe I can design an **nested** input to make these recursive function **recursive deeply** and **cause stackoverflow error**?

**Comment by dtolnay** [comment]
Closing as a duplicate of #901.
