### ISSUE TITLE
How to parse a `Vec<Item>`

### ISSUE THREAD

**Issue by cameron1024** [dtolnay/syn#1165]
This feels like a common use case, so perhaps there's a better way to do this that I'm unaware of.

I'm writing a macro to apply a particular attribute to every item defined in a block. The rough syntax is:
```rust
my_macro! {
  struct Foo;

  fn bar() {}

  mod baz {}

  // etc for any possible top-level item
}

// expands to

#[my_attr]
struct Foo;

#[my_attr]
fn bar() {}

#[my_attr]
mod baz {}
```
My understanding is that it's possible to parse items without explicit delimiters (i.e. without having to use `Punctuated` or friends), though admittedly this is more of an intuitive "feeling" based on the syntax of items. As such, I expected `Vec<Item>: Parse` to be satisfied, but it isn't.

Is this an oversight? Or is there a reason why it isn't implemented, and I should use some other strategy for this?

Thanks in advance :grin:

**Comment by cmyr** [comment]
I have previously handled something like this by having a custom type, like

```rust
struct Items(Vec<Item>);
```

and then having a simple `Parse` impl, like,

```rust
impl Parse for Items {
    fn parse(input: ParseStream) -> Result<Self, syn::Error> {
        let mut result = Vec::new();
        while !input.is_empty() {
            result.push(input.parse()?)
        }
        Ok(Self(result))
    }
}
```

I'm not sure if there is a better approach, but this one works for me. 🤷

**Comment by dtolnay** [comment]
cmyr's snippet is what I would write.
