### ISSUE TITLE
No mechanism to parse groups without `return`ing errors

### ISSUE THREAD

**Issue by cairomassimo** [dtolnay/syn#1172]
Hi there!! :)
I have the following concern about the `syn` public API.

AFAIK, the only way to parse, say, a `{...}`, is via the `braced!()` macro.
That macro (and similar ones for `(...)` and `[...]`) include a `return` statement.
This forbids any usage of those macros inside methods which have a different return type, hence the ability to parse those construct inside such methods.
On the other hand, following the macro invocation with a `?` would be idiomatic and more consistent with other cases (such as invoking `input.parse()`).

In my use case, I'm using `syn` to parse a DSL (not Rust). Since I need extra context during parsing, I'm using methods with a different signature and return type. Honestly, that's not a common use case for `syn`, but it's possible that this applies to someone else as well.

Thanks!

**Comment by dtolnay** [comment]
I think this is fine as implemented. Your use case is highly unusual. You can easily wrap the syn macro in whatever other signature is convenient for you. For example:

```rust
use syn::parse::{ParseBuffer, ParseStream};
use syn::token::Brace;

fn parse_brace(input: ParseStream) -> syn::Result<(Brace, ParseBuffer)> {
    let content;
    let token = syn::braced!(content in input);
    Ok((token, content))
}

fn whatever(input: ParseStream) -> Thing<usize> {
    let content = match parse_brace(input) {
        Ok((_brace, content)) => content,
        Err(err) => …,
    };
    content.parse::<…>();
```

**Comment by cairomassimo** [comment]
Thanks for the suggestion!
Keep up the good work :)
