### ISSUE TITLE
Proper way to parse multiple items?

### ISSUE THREAD

**Issue by Wandalen** [dtolnay/syn#1173]
What is proper way to parse multiple items?

Currently my code looks, like that

```rust
pub fn impls( input : proc_macro::TokenStream ) -> Result< proc_macro2::TokenStream >
{

  let _ast = match syn::parse::< syn::Item >( input )
  {
    Ok( syntax_tree ) => syntax_tree,
    Err( err ) => return Err( err ),
  };

  let result = parse_quote!
  {
  };

  Ok( result )
}
```

But it parse only one item.

By the way what is difference between TokenStream and ParseStream?
Any article explaining such things?

**Comment by dtolnay** [comment]
You just opened 3 beginner question issues in quick succession. Please go to the resources shown in https://www.rust-lang.org/community instead if you need guidance learning this library. Syn is one of the most widely used crates so lots of people will have experience with it.
