### ISSUE TITLE
Is it possible to refer a field with `quote` and `parse_quote`?

### ISSUE THREAD

**Issue by Wandalen** [dtolnay/syn#1175]
Is it possible to refer a field with `quote` and `parse_quote`?

```
quote!{ #( #attrs )* #( self.vis ) }
```

**Comment by dtolnay** [comment]
You just opened 3 beginner question issues in quick succession. Please go to the resources shown in https://www.rust-lang.org/community instead if you need guidance learning this library. Syn is one of the most widely used crates so lots of people will have experience with it.
