### ISSUE TITLE
Impl parse for Tuples of Types implementing parse

### ISSUE THREAD

**Issue by ModProg** [dtolnay/syn#1179]
What I propose is that e.g.

`(Ident, Token![:], Type)` would parse a field declaration and could be used in e.g. Punctuated like this:
`Punctuated::<(Ident, Token![:], Type), Token![,]>`.

This would lift the requirement to define a type and impl Parse on it for simple cases.

(I know that you can parse Field definitions already, but this would be more for custom syntax)

**Comment by ModProg** [comment]
Maybe this could also be done through a macro
```rs
macro_rules! sequence {
    ($($ty:ty),*) => {
        |input| Ok(($(<$ty as Parse>::parse(input)?),*))
    };
}

Punctuated::<_, Token![,]>;;parse_terminated_with(
    input, 
    sequence!(Ident, Token![:], Type)
)
```

**Comment by dtolnay** [comment]
I would prefer not to add those impls for tuples.

Your macro looks reasonable if this comes up frequently in your codebase.
