### ISSUE TITLE
Attribute::parse_meta unable to parse cfg_attr?

### ISSUE THREAD

**Issue by zsol** [dtolnay/syn#1180]
I'm trying to use `Attribute::parse_meta` to parse an attribute like `#[cfg_attr(foo=bar,baz)]`, but it doesn't seem to succeed.
As far as I can tell `#[cfg_attr(foo=bar,baz)]` should parse into a `Meta::List` that contains a nested `Meta::NameValue` and a `Meta::Path`.

Then again, I might be missing something obvious, as this is my first time doing attribute parsing.

Here's a quick repro: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2a28cb428a4f776ef5c0023604428fdd

**Comment by dtolnay** [comment]
I think this is behaving correctly. In `Meta`, the `NameValue` variant only applies if the `=` is followed by a literal.

**Comment by zsol** [comment]
Thanks for the quick response!

Would you be open to a PR that clarifies the documentation of `Meta` wrt. differences in supported values compared to [the spec](https://doc.rust-lang.org/reference/attributes.html#meta-item-attribute-syntax)?
