### ISSUE TITLE
Option-related features for `syn::Type`

### ISSUE THREAD

**Issue by jeertmans** [dtolnay/syn#1182]
Hello,

After doing the `builder` Derive macro example from the [proc-macro-workshop](https://github.com/dtolnay/proc-macro-workshop/tree/master/builder), I was wondering why no built-in method was provided to check whether a `syn::Type` is actually an `Option`, and how to convert a Type `T` into `Option<T>`?

In my opinion, adding the two following methods to `syn::Type` would be great:

```rust

fn is_option(ty: &Type) -> bool {
    match ty {
        Type::Path(typepath) if typepath.qself.is_none() => {
            let idents_of_path = typepath
                .path
                .segments
                .iter()
                .fold(String::new(), |mut acc, v| {
                    acc.push_str(&v.ident.to_string());
                    acc.push(':');
                    acc
                });
            vec!["Option:", "std:option:Option:", "core:option:Option:"]
                .into_iter()
                .find(|s| idents_of_path == *s)
                .and_then(|_| typepath.path.segments.last())
                .is_some()
        }
        _ => false,
    }
}

fn as_option(ty: &Type) -> Type {
    let ty = ty.clone();
    Type::Verbatim(quote! { ::core::option::Option<#ty> })
}
```

Then, a combination of `is_option` and `as_option` might help to transform, only when necessary, types into options.

*I hope this is not a duplicate of any previous issue / PR*

If you think this feature can be added to `syn`, then I would gladly propose a PR.

**Comment by dtolnay** [comment]
Thanks for the suggestion, but I would prefer not to build either of those into this library.

**Comment by notgull** [comment]
I wonder if there would be enough demand for a library with extension traits to implement methods like this.
