### ISSUE TITLE
Extending Rust Grammar with Syn

### ISSUE THREAD

**Issue by chichid** [dtolnay/syn#1185]
I don't know if Syn is designed for this use, but I'm experimenting with extending the rust syntax (avoiding compiler plugins since they're unstable). I'm having a hard time finding the starting point for something like this. 

I'm looking to add new types of expressions or instance. And the only way I see (with my limited knowledge of syn) is to fork the entire repo and add a hook at the parse_expr function. 

I think it'll be very cool if Syn provided some hooks before calling the parse method, to allow to extend what parse returns. 
Essentially, something similar to the visitor feature but that happens before the parsing of each node happens. 

Is something like this possible with Syn? Would grately appreciate any pointers, documentation or ideas..

**Comment by dtolnay** [comment]
This is not in scope for this library.
