### ISSUE TITLE
Purestake Moonbeam build failed, depending on changed mod visibility.

### ISSUE THREAD

**Issue by manylov** [dtolnay/syn#1187]
Hello, it looks like the last update crashed Parity's Substrate build when building Purestake Moonbeam:

It crashes here https://github.com/paritytech/substrate/blob/master/frame/support/procedural/tools/src/syn_ext.rs#L50

because here https://github.com/dtolnay/syn/blob/master/src/lib.rs#L304 group is not pub now.

The substrate depends on syn 1.0.82, but Moonbeam is on syn 1.0, so the last update has affected the build.

**Comment by dtolnay** [comment]
`group` has never been a public API in any previous release either.

**Comment by manylov** [comment]
> `group` has never been a public API in any previous release either.
 https://github.com/dtolnay/syn/blob/1.0.97/src/lib.rs#L306  ?

**Comment by dtolnay** [comment]
Nope, not in 1.0.97: https://docs.rs/syn/1.0.97/syn/index.html#modules
