### ISSUE TITLE
Latest point release is a breaking change

### ISSUE THREAD

**Issue by korken89** [dtolnay/syn#1188]
Hi, with the 1.0.98 point release the crate `rtic-syntax` stopped compiling with the following error.
Could you keep that change for syn 2.0? Thanks!

```
error[E0603]: module `group` is private
   --> /home/9names/.cargo/registry/src/github.com-1ecc6299db9ec823/rtic-syntax-1.0.1/src/parse.rs:13:5
    |
13  |     group::parse_parens,
    |     ^^^^^ private module
    |
note: the module `group` is defined here
   --> /home/9names/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.98/src/lib.rs:304:1
    |
304 | mod group;
    | ^^^^^^^^^^
    
```

**Comment by dtolnay** [comment]
`group` has never been a public API in any previous release either.

**Comment by korken89** [comment]
Hi,

We have been using that for over a year so somehow it's public until 1.0.98 :)

**Comment by dtolnay** [comment]
It is not public in any syn version. See https://docs.rs/syn/1.0.97/syn/index.html#modules for example.

**Comment by korken89** [comment]
Very odd, we've been using that for so long.
I'll look into how to replace it then.
