### ISSUE TITLE
Semver violation in 1.0.98

### ISSUE THREAD

**Issue by AaronErhardt** [dtolnay/syn#1189]
The upcoming release of relm4-macros uses the following imports:

```rust
use syn::group::{parse_braces, parse_brackets, parse_parens};
```

This has worked out well so far, but was changed in https://github.com/dtolnay/syn/commit/0000e6e911e456c82d90e4bf5937b4a4edaf643f, so our documentation CI workflow broke over night.

Now I would need to use the following code:

```rust
use syn::__private::{parse_braces, parse_brackets, parse_parens};
```

IMO, this change should have been part of a major semver version bump and the Rust guidelines seem to agree: https://doc.rust-lang.org/cargo/reference/semver.html#item-remove
Of course, this was never part of the documentation but it's still a breaking change.

I understand why the macro like `parenthesized!` are a decent solution for many use-cases but the macros are not flexible enough for all cases. For example, you cannot use the macros in any function that doesn't exactly return `syn::Result<T>` because the macro creates an implicit `return`. relm4-macros has it's own error type for better error reporting / recovery so we simply can't use the macro.

IMO, the macros are unnecessary anyway and should be deprecated in favor of regular Rust code, that is easier to understand and less error prone. So I don't understand why syn goes the other direction by making the functional API harder to access.

<table>
<tr>
<th></th>
<th>Macro</th>
<th>Regular Rust</th>
</tr>
<tr>

<td>Code</td>

<td>

```rust
let content;
parenthesized!(content in input);
```
</td><td>

```rust
let content = parse_parens(input)?.content;
```
</td>
</tr>
<tr>
<td>Comparison</td>
<td>

+ longer
+ "unidiomatic"
+ only works inside function that return `syn::Result<T>`
+ hides a `return` statement
</td>
<td>

+ shorter
+ "idiomatic"
+ works with custom error types
+ clear control flow
</td>
</tr>
</table>

**Comment by dtolnay** [comment]
> Of course, this was never part of the documentation but it's still a breaking change.

This is not how semver works. The versioning describes the public API only. You don't get to use undocumented internal APIs and expect that they will never change.
