### ISSUE TITLE
Can't parse type parameters containing parenthesized items

### ISSUE THREAD

**Issue by Arnavion** [dtolnay/syn#119]
```rust
let raw = r#"
    type A = Box<(Fn(D::Error) -> E) + 'static + Send + Sync>;
"#;

let actual = parse_item(raw).unwrap(); // Fails
```

Found in [`tests/rust/src/test/ui/token/bounds-obj-parens.rs`](https://github.com/rust-lang/rust/blob/ddc5d7bd4b9ea3e8a8ccf82cb443e950be311d61/src/test/ui/token/bounds-obj-parens.rs#L13) which should pass without the trailing `FAIL`

**Comment by dtolnay** [comment]
Fixed in 0a169d428305315bf14b033dbb15295432896b02.
