### ISSUE TITLE
Some documentation on how to access attributes from derive macros

### ISSUE THREAD

**Issue by tgross35** [dtolnay/syn#1191]
Hello Syn team,

I was trying to create a macro to be used with this sort of syntax:

```rs
#[derive(MyThing)]
#[mything(key = "MYKEY", newattr="SOMETHING")]
struct XXX;
```

And access `key` and `newattr` in the macro definition, which uses:

```rs
#[proc_macro_derive(AffixToken, attributes(key, newattr))]
```

But didn't see anything like that in the docs. It looks like the entire `key = "MYKEY", newattr="SOMETHING"` is stored here:

```
input.attrs.get(0).unwrap().tokens.get(0).unwrap().stream // iterate this
```

And is split across idents, punctuation, and literals. I'm just unsure whether this is the "correct" way to access them, and figured others would benefit from this being in the docs as well.

Thanks!

**Comment by dtolnay** [comment]
I believe this is now covered by the documentation on
https://docs.rs/syn/2/syn/struct.Attribute.html#method.parse_nested_meta
and
https://docs.rs/syn/2/syn/meta/struct.ParseNestedMeta.html.
