### ISSUE TITLE
Broken semver backwards compatibility?

### ISSUE THREAD

**Issue by TheEdda** [dtolnay/syn#1194]
It looks like multiple changes over the years have broken semver:
* https://github.com/dtolnay/syn/commit/61084dabcf454840ce86086e51fdcd8710e13bb7 in 1.0.1
* https://github.com/dtolnay/syn/pull/696 in 1.0.3
* https://github.com/dtolnay/syn/pull/712 in 1.0.6
* this also doesn't look like it's backwards compatible, it fails at runtime instead of compile-time [1.0.14..1.0.15](https://github.com/dtolnay/syn/compare/1.0.14...1.0.15#diff-ce4e3f87da05491a74818b9736b02d9c40274befb1e2c13f44c6995eb001b925R1436) (in 1.0.15)

This is just what a random check here caught https://github.com/Smithay/drm-rs/runs/7126146546?check_suite_focus=true#step:7:157

Shouldn't these have been minor bumps or does this crate not follow semver? There has to be a reason for this, right?

**Comment by dtolnay** [comment]
This crate's version numbers do not use (your interpretation of) semantic versioning.

**Comment by TheEdward162** [comment]
No need to be snarky, this is not just my interpretation. The check that detected this came directly from a nightly feature of Cargo (the `-Z minimal-versions` flag).

Also please state this somewhere visible, this crate is very pervasive throughout the ecosystem (not in a bad way) and I believe it not following semver Cargo is expecting is surprising at the very least.

**Comment by dtolnay** [comment]
I understand. You'd pointed to some changes and said "these are **not** backwards compatible" and what I now think you meant is "these are backwards compatible new functionality".

Correct, the version numbers do not follow semantic versioning in that way. People that prefer different numbering should use a crate that re-exports syn's public API under different numbers (not a fork; just doing `pub use syn::*`).

**Comment by notgull** [comment]
> People that prefer different numbering should use a crate that re-exports syn's public API under different numbers

Does such a crate currently exist?

Anyhow, I don't think this is *that* big of a deal. You can emulate semver-compatible versioning by putting a tilde next to the `syn` version in `Cargo.toml` (e.g. `syn = "~1.0.14`) and as far as I know it hasn't broken anything yet.
