### ISSUE TITLE
private module syn::group 

### ISSUE THREAD

**Issue by aniketfuryrocks** [dtolnay/syn#1197]
https://github.com/dtolnay/syn/blob/4dedca740a0347a481a6e4f039cb9fb6d6e64d97/src/lib.rs#L305

```rust
error[E0603]: module `group` is private
   --> gxi-transpiler-core/src/blocks/node/prop.rs:20:62
    |
20  |         if let Ok(syn::group::Parens { content, .. }) = syn::group::parse_parens(input) {
    |                                                              ^^^^^ private module
```

**here**

https://github.com/gxi-rs/gxi/blob/1d6069e20f2a9e70587e6d0e6ddbc42b0867d995/gxi-transpiler-core/src/blocks/node/prop.rs#L20

**Works in**

https://github.com/gxi-rs/gxi/blob/1d6069e20f2a9e70587e6d0e6ddbc42b0867d995/gxi-transpiler-core/Cargo.toml#L18

```rust
syn = { version = "1.0.92", features = ["full"] }
```

**Not working in**
```rust
syn = { version = "1.0.98", features = ["full"] }
```

**Comment by aniketfuryrocks** [comment]
**git blame** 
https://github.com/dtolnay/syn/commit/0000e6e911e456c82d90e4bf5937b4a4edaf643f

@dtolnay mind exporting `Brackets` and other structs in

https://github.com/dtolnay/syn/blob/4dedca740a0347a481a6e4f039cb9fb6d6e64d97/src/group.rs#L22

**Comment by dtolnay** [comment]
This module was not public in 1.0.92 either. See https://docs.rs/syn/1.0.92/syn/#modules.

The API for parsing brackets is https://docs.rs/syn/1/syn/macro.bracketed.html.

**Comment by aniketfuryrocks** [comment]
The doc is hidden, but `group` is `pub`.

https://github.com/dtolnay/syn/blob/069bdf5757adf533e7e0a2ec542413751fbbfec6/src/lib.rs#L325

**Comment by dtolnay** [comment]
The public API of this crate is what is documented in the documentation.

**Comment by aniketfuryrocks** [comment]
@dtolnay mind exporting `Brackets` and other structs in

https://github.com/dtolnay/syn/blob/4dedca740a0347a481a6e4f039cb9fb6d6e64d97/src/group.rs#L22 

or can you instruct me how to achieve me the same behavior.

I want to access `.content` which for some reason `bracketed!()` doesn't export 🙏
