### ISSUE TITLE
Would `TryFold` trait be useful ?

### ISSUE THREAD

**Issue by Narsil** [dtolnay/syn#1232]
I am trying to write a `proc_macro` to get Tensor type checking done. (Afaik it's not even close to be possible to support in regular Rust, and it's a fun project). https://github.com/Narsil/static_typing_tch

In order to do so I use 
`#![feature(proc_macro_diagnostic)]`
and `span().unwrap().error("..").emit()`  to get the error messages out.
It's extremely convenient to produce high quality errors.

It works great but requires nightly.

My understanding to make it work in `stable` would be to use `syn::Result` and `into_compiler_error`.
Is that correct ?

In the current code, I would like to abuse `Fold` trait, but since the trait doesn't return an `Error` then it seems impossible to write.

I am thinking of adding a `TryFold` trait in order to make it possible.

If I understand correctly we would need

- 1 feature gate `try_fold`
- New `codegen` file.
- New `TryFoldHeper`.
- Making sure `try_life` uses `Error::combine` to keep all compile errors at once.

Is there another way to go about this ?
Would this be interesting to implement here ?

**Comment by Narsil** [comment]
And I found https://docs.rs/proc-macro-error/latest/proc_macro_error/ afterwards...

I thought I looked before and couldn't use this crate:

The examples in `syn` do use the `proc_macro_diagnostic`.  Would you want to update to `proc-macro-error` (if possible) ?
That's what mislead me.

**Comment by dtolnay** [comment]
I would prefer not to add a `TryFold` implementation in this crate. However, using [syn-codegen](https://docs.rs/syn-codegen) and the syn.json file that comes with any syn release, anyone else could maintain a `TryFold` trait for syn's AST in a separate crate.
