### ISSUE TITLE
Combinator or_else and conditionals

### ISSUE THREAD

**Issue by mihaigalos** [dtolnay/syn#1233]
In the process of trying to understand https://github.com/xd009642/tarpaulin/issues/1066, I believe combinators (i.e.: `or_else`) are not parsed as a conditional (i.e. [`ExprIf`](https://github.com/dtolnay/syn/blob/691fc0676cd7c54f968bcb444fcdb44a28a18217/src/expr.rs#L151) or similar). 

Can somebody please confirm, how are they treated?

**Comment by dtolnay** [comment]
As far as I can tell, this is working as intended. `or_else` method calls are definitely not an `ExprIf`. That refers to use of the `if` keyword.

**Comment by mihaigalos** [comment]
Hi @dtolnay,
Yes, it makes sense. Into which type are `or_else` lexed?
