### ISSUE TITLE
Do not parse macro arguments

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#124]
I really like what [strata-rust](https://github.com/shepmaster/strata-rust) does with macros. It doesn't parse the inside, just gives you a string to do with what you want - possibly pass it to another parser function. This avoids corrupting any of the input by parsing to tokens. For example with syn right now you couldn't tell the difference between `m!(##)` and `m!(# #)`.

**Comment by dtolnay** [comment]
Uh-oh @Arnavion I guess this also applies to attributes now. Any thoughts?

```rust
#[inert **]
// vs
#[inert * *]
```

**Comment by Arnavion** [comment]
Span information to every struct will suffice, won't it? (#92)

**Comment by dtolnay** [comment]
I don't think so. With spans you have start/end indices into the input string of source code, but ToTokens and everything else is still implemented in terms of the AST only. So imagine:

```rust
#[my_attr]
fn f() {
    someone_elses_macro!(0_0);
}
```

The person implementing `my_attr` writes a proc macro that parses the whole item, does whatever (like replaces the return type or something), and writes it back out.

The person implementing `someone_elses_macro` gets the wrong input because the token is now `0` instead of `0_0`.

Although maybe that just means the Lit that is used inside of TokenTree needs to be smarter.

**Comment by Arnavion** [comment]
In my experience with code transformers in other languages, the AST node stores all the information it needs to reproduce the input as exactly as it wants. This can even include things like the indentation of every AST node if necessary.

So yes, in that example if you decide that parse->emit operations should preserve the literal as `0_0`, then `Lit` should remember that and emit itself accordingly.

**Comment by dtolnay** [comment]
Fair enough. I filed #125 to follow up on literals.
