### ISSUE TITLE
Wanted: a variant of `parse_macro_input` that produces the intermediate `Result`.

### ISSUE THREAD

**Issue by nathan-at-least** [dtolnay/syn#1240]
# Goal

I want to implement a `struct MyAttrArgs` with a method:

```
impl MacroArgs {
  fn parse(args: TokenStream) -> syn::Result<Self> { … }
}
```

I am attempting to use [darling](https://doc.rs/darling) because it provides the right user experience and nice developer ergonomics: the parameters get parsed into a custom struct.

# Problem

I cannot rely on `parse_macro_input!`, as the [darling example](https://github.com/TedDriggs/darling#macro-code) suggests, because that literally returns a `TokenStream` (which doesn't fit my desired return type).

I cannot use `syn::parse2` which has the right interface for my desired API, except `syn::AttributeArgs` doesn't implement `syn::parse::Parse`.

# Questions

The main big picture question is: am I just confused about how to design proc-macros implemetations well?

Specific questions:

- Why doesn't `syn::AttributeArgs` implement `Parse` so that I could use `parse2`?
- Why can `parse_macro_input!` parse things that `parse2` cannot? Is there a rationale for that? (And how does it accomplish this?)
- Why isn't there a variant of `parse_macro_input!` which produces the intermediate `Result` directly instead of hardcoding a return?
- (For `darling`:) Why doesn't `darling` implement `syn::parse::Parse` for the annotated structs so that they could be produced by `parse2`?
- (For `darling`:) Why doesn't `FromMeta` have a method like `from_tokenstream(TokenStream) -> syn::Result<Self>` ?

**Comment by nathan-at-least** [comment]
Update: if I call into a `doc(hidden)` API, my project compiles and tests pass. :-(

The call site is: `let args: syn::AttributeArgs = syn::parse_macro_input::parse(tokens.into())?;`

**Comment by nathan-at-least** [comment]
Update: I implemented a work-around by hand-rolling a parser with this signature:

```
/// We cannot use `parse_macro_input!` which returns a `TokenStream` and `AttributeArgs` does not
/// impl `syn::parse::Parse`, so we do this by hand. :-<
fn parse_attribute_args(tokens: TokenStream) -> Result<syn::AttributeArgs> { … }
```

Now tests pass. It really feels like I'm doing something wrong or missing a big picture about proc-macro implementation design, but it works for now.

**Comment by dtolnay** [comment]
`syn::AttributeArgs` no longer exists in syn 2 so I'm not sure whether this is still necessary.

**Comment by nathan-at-least** [comment]
I'll have to dust off that project and see what's the right replacement for `AttributeArgs`.

Meanwhile, I still remain confused about the macros returning `TokenStream` whereas I want to write many small functional building blocks that return `syn::Result<T>` and I'm not clear on how to match up the impedance mismatch.
