### ISSUE TITLE
Can't use Punctuated.span() if inner type is syn::Spanned

### ISSUE THREAD

**Issue by jgirardet** [dtolnay/syn#1243]
Hello,
Given a struct MyStruct implementing `syn::spanned::Spanned`.

```rust
let p =  Punctuated<MyStruct,Token[,]>::new();
p.span() // Error
```
`the trait bound MyStruct: ToTokens is not satisfied
the following other types implement trait... `

I understand the error message, but I don't really need to use `ToToken`, I just wanna use Spanned to aggregate some `MyStructs`'s span together.

Maybe I'm not using it as I should but at the end I think It seems logical to be able to use `Punctuated.span()` if inner type implements  `syn::Spanned`;

Thank you for the lib.

**Comment by dtolnay** [comment]
Handwritten `Spanned` impls are not an intended use case; I think it's fine not to support this.
