### ISSUE TITLE
Using new Span diagnostics

### ISSUE THREAD

**Issue by Qix-** [dtolnay/syn#1259]
I'm trying to figure out how to effectively use the new Diagnostic API in lieu of the `Parse` trait's `Result<T, syn::Error>` type, which only emits the old spanned `compiler_error!()` trick. In particular, when I want to replace a failed parse with a better error message complete with help text et al (there's currently no way to return an `Error` that has no span or associated error messages).

Would it be possible to either construct an empty `Error`, or otherwise enable the Diagnostics functionality? Perhaps behind an `unstable` feature flag?

**Comment by dtolnay** [comment]
For now, `compile_error!` is the only error reporting I am interested in supporting in this crate.
