### ISSUE TITLE
Crates.io documentation is mismatched against the version hosted there

### ISSUE THREAD

**Issue by Wallacoloo** [dtolnay/syn#126]
It looks to me that #95 has resurfaced. The doc link on crates.io links to the docs for master, which describe a different API than what is hosted on crates.io (for example, the documentation for `syn::Attribute` in master is not applicable to the current 0.11.11 API because the fields have changed).

I see that the previous fix of using docs.rs was explicitly reverted in 3150dfbf4e13f23fcf0f56b9d3f110baf531b1cc, but there's no explanation as to why, and it's very confusing when documentation examples fail to compile due to API differences.

**Comment by dtolnay** [comment]
I fixed this in https://github.com/dtolnay/syn/compare/3ddfffd531505c30f5e75c4f5735b2a61df3926d...4e5877676ad0cef926bcfc6a97ec444ca4f4aeab. Too bad I can't use docs.rs until [they let us specify non-default features to document](https://github.com/onur/docs.rs/issues/29).
