### ISSUE TITLE
How do I parse `#[doc = include_str!("path/to/file")]` using `Attribute::parse_meta()` ?

### ISSUE THREAD

**Issue by mythrnr** [dtolnay/syn#1262]
Hi,

I want to parse the `doc` attributes written using the `include_str!` macro.
But now `Attribute::parse_meta()` returns `Error("expected literal")`.

To reproduce this, please add following test function in `tests/test_attribute.rs`,

```rust
#[test]
fn test_meta_item_doc_include_str() {
    let _meta = test(r#"#[doc = include_str!("path/to/file")]"#);
}
```

and run `cargo test --all-features --release --tests`, so the output is next.

```
...

---- test_meta_item_name_value_include_str stdout ----
thread 'test_meta_item_name_value_include_str' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected literal")', tests/test_attribute.rs:340:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

...
```

I think that probably `syn::attr::parsing::parse_meta_after_path` needs to be able to parse macro_rules syntax.

https://github.com/dtolnay/syn/blob/1.0.105/src/attr.rs#L596-L604

Or is there another way to solve this?
If I have written something misguided, I apologize.

Thanks for this crate. And thanks for reading this issue.

**Comment by jf2048** [comment]
`syn::Meta` cannot work for this, it expects any attribute fields to be literals. You must use `parse_args` or `parse_args_with` to parse some other AST type, in your case probably `syn::Expr` and then you can check if it is an `ExprMacro`.

**Comment by mythrnr** [comment]
Thanks for your comment and knowledge. I'll try to solve my issue with it.
