### ISSUE TITLE
Perplexing `(/*ERROR*/)` output when using `VisitMut::visit_expr_mut`?

### ISSUE THREAD

**Issue by mstone** [dtolnay/syn#1283]
I'm not sure whether this is a `syn` issue or something lower-level but since I've made a minimal reproducer for the issue I'm having, I figure this is as good a place to ask for help as any: https://github.com/mstone/rust-macro-bug.

The symptom of the problem is, while using a custom impl of `VisitMut`, with `visit_expr_mut()` overridden, to replace all sub-expressions with braced copies of themselves, I'm getting an unexpected `(/*ERROR*/)` output where I'm expecting a braced sub-expression.

Thanks in advance for any thoughts!

**Comment by dtolnay** [comment]
This is a bug in your macro. "Braces around every subexpression" produces the following, which is not valid Rust syntax.

```rust
fn add(a: u64, b: u64) -> u64 { { { a } + { b } } }
```

**Comment by mstone** [comment]
Oh good, that’s very simple then — thank you + apologies for the noise/confusion!

(Also, for anyone else who stumbles across this issue in the future with a similar confusion: @saleemrashid very kindly pointed out to me a few minutes ago how the mysterious `(/*ERROR*/)` output that surprised me is likely coming from [rustc’s -Zunpretty=expanded](https://github.com/rust-lang/rust/blob/ddad1e1f15f77074738bb3d7fb7688a9177b6450/compiler/rustc_ast_pretty/src/pprust/state/expr.rs#L557) as it tries to signal where it has detected this problem!)
