### ISSUE TITLE
Parsing a list of named arguments

### ISSUE THREAD

**Issue by jimmycuadra** [dtolnay/syn#132]
I'm giving syn a shot for a Macros 2.0 proc macro and wondering how best to parse it. This is roughly what I am imagining my macro invocation to look like right now:

``` rust
ruma_api! {
    description: "Description of this API endpoint",
    method: Method::Get,
    name: "unique_name",
    path: "/foo/bar",
    rate_limited: false,
    requires_authentication: false,
    request: {
        /// Doc comment
        foo: String,
        /// Doc comment
        #[custom_ruma_api_attribute]
        bar: u8
    }
    response: {
        /// Doc comment
        baz: Vec<String>,
    },
}
```

Although it looks sort of like struct field declarations, all of the top level key-value pairs are actually named arguments. The value for the request and response fields are struct field declarations that will be expanded into a real `Request` and `Response` struct, but all the other argument values are normal expressions.

Right now I believe the only syn function that could parse this is `parse_token_trees`, but that leaves a lot of heavy lifting to do afterwards of building a higher level structure out of the individual token trees to make sense of it.

I could change the syntax of my macro to be more verbose (for example, a list of items) to something that syn could parse into a more useful value, but I thought I'd ask if there might be any planned additions to syn that would make this sort of custom syntax easier to work with.

**Comment by dtolnay** [comment]
Maybe something like this? Hopefully you've used nom before.

```rust
// [dependencies]
// syn = { version = "0.11", features = ["full"] }
// synom = "0.11"

extern crate syn;

#[macro_use]
extern crate synom;

use syn::{Ident, Expr, TokenTree};
use syn::parse::{ident, expr, tt};

#[derive(Debug)]
struct RumaApi {
    entries: Vec<Entry>,
}

#[derive(Debug)]
enum Entry {
    NamedArg(Ident, Expr),
    Request(TokenTree),
    Response(TokenTree),
}

named!(ruma_api -> RumaApi, do_parse!(
    entries: many0!(entry) >>
    (RumaApi { entries: entries })
));

named!(entry -> Entry, alt!(
    do_parse!(
        keyword!("request") >>
        punct!(":") >>
        peek!(punct!("{")) >>
        // TODO: this could be parsed into a more useful data structure
        // if you need.
        request: tt >>
        (Entry::Request(request))
    )
    |
    do_parse!(
        keyword!("response") >>
        punct!(":") >>
        peek!(punct!("{")) >>
        response: tt >>
        (Entry::Response(response))
    )
    |
    do_parse!(
        name: ident >>
        punct!(":") >>
        value: expr >>
        // TODO: some expressions do not require a trailing comma.
        // Check out how syn parses `match` statements in `expr_match`.
        punct!(",") >>
        (Entry::NamedArg(name, value))
    )
));

fn main() {
    let input = r#"description: "Description of this API endpoint",
                   method: Method::Get,
                   name: "unique_name",
                   path: "/foo/bar",
                   rate_limited: false,
                   requires_authentication: false,
                   request: {
                       /// Doc comment
                       foo: String,
                       /// Doc comment
                       #[custom_ruma_api_attribute]
                       bar: u8
                   }
                   response: {
                       /// Doc comment
                       baz: Vec<String>,
                   }"#;

    let parsed = ruma_api(input).expect("ruma api");
    println!("{:#?}", parsed);
}
```

**Comment by jimmycuadra** [comment]
Wow, thanks for the great answer! I haven't used nom before but I get the idea and will dig into it. Sounds like the level of custom syntax in my use case is beyond what syn is intended to do on its own, so I will close this.

**Comment by jimmycuadra** [comment]
Small follow up: In building the synom parser, I've found a few places where there is a parser in syn that is not public that I would've liked to use. I started with just copy/pasting simple ones, but I just came to `outer_attr` and it's big enough that I don't feel so comfortable copy pasting it and its dependencies. Any chance of opening up more of these parser macros publicly? Should I file a separate issue?

**Comment by dtolnay** [comment]
Sure, we can expose the ones that would be useful to you. At some point I would like to take a step back and design this more intelligently. We shouldn't need three different paths to expose every AST node (for example `syn::Expr`, `syn::parse_expr`, `syn::parse::expr`). Maybe you have some ideas for making this better.

I should mention that before long, this stuff will need to be scrapped and rewritten to use https://github.com/rust-lang/rust/pull/40939 with real error handling.

**Comment by jimmycuadra** [comment]
Sounds good. Maybe I'll work on a PR to restructure things a bit. I'm not too worried about breaking changes within syn/synom because of rust-lang/rust#40939 or otherwise, since this is all very young and unstable. :}

**Comment by MSleepyPanda** [comment]
I've come across this issue while searching for this exact problem. Meanwhile the example is outdated, since the `keyword!` macro doesn't accept strings anymore. Could you post an updated version? @dtolnay

**Comment by dtolnay** [comment]
Sure, here is the same solution translated to syn 0.13.

```rust
// [dependencies]
// syn = { version = "0.13.5", features = ["full", "extra-traits"] }
// proc-macro2 = "0.3"

#[macro_use]
extern crate syn;

extern crate proc_macro2;

use proc_macro2::TokenStream;
use syn::{Ident, Expr};
use syn::synom::Synom;

#[derive(Debug)]
struct RumaApi {
    entries: Vec<Entry>,
}

#[derive(Debug)]
enum Entry {
    NamedArg(Ident, Expr),
    Request(TokenStream),
    Response(TokenStream),
}

impl Synom for RumaApi {
    named!(parse -> Self, do_parse!(
        entries: many0!(syn!(Entry)) >>
        (RumaApi { entries })
    ));
}

impl Synom for Entry {
    named!(parse -> Self, alt!(
        do_parse!(
            custom_keyword!(request) >>
            punct!(:) >>
            // TODO: the content of the braces could be parsed into a more
            // useful data structure if you need.
            request: braces!(syn!(TokenStream)) >>
            (Entry::Request(request.1))
        )
        |
        do_parse!(
            custom_keyword!(response) >>
            punct!(:) >>
            response: braces!(syn!(TokenStream)) >>
            (Entry::Response(response.1))
        )
        |
        do_parse!(
            name: syn!(Ident) >>
            punct!(:) >>
            value: syn!(Expr) >>
            // TODO: some expressions do not require a trailing comma.
            // Check out how syn parses `match` expressions in `ExprMatch`.
            punct!(,) >>
            (Entry::NamedArg(name, value))
        )
    ));
}

fn main() {
    let input = r#"
        description: "Description of this API endpoint",
        method: Method::Get,
        name: "unique_name",
        path: "/foo/bar",
        rate_limited: false,
        requires_authentication: false,
        request: {
            /// Doc comment
            foo: String,
            /// Doc comment
            #[custom_ruma_api_attribute]
            bar: u8
        }
        response: {
            /// Doc comment
            baz: Vec<String>,
        }
    "#;

    let parsed: RumaApi = syn::parse_str(input).expect("ruma api");
    println!("{:#?}", parsed);
}
```

**Comment by MSleepyPanda** [comment]
Thanks for the quick patch!
