### ISSUE TITLE
Program unexpected panic when unwrap is called

### ISSUE THREAD

**Issue by bhao-Soo** [dtolnay/syn#1329]
### version of syn

1.0.107

### Bug description

Program unwrap on an "Err" value, which causing a panic

### Steps to reproduce the behavior

Using auto-generated fuzz target can reproduce the behavior. it was uploaded to the issue platform.
[unwrap_error.zip](https://github.com/dtolnay/syn/files/10526766/unwrap_error.zip)

### actual behavior, and expected behavior.

actual: Panic happens, the program crashes.
expected: Handle unwrap without causing a panic.

**Comment by dtolnay** [comment]
Please file a proper issue with a title that characterizes the bug uniquely, and a minimal compilable piece of code that reproduces the issue.

**Comment by bhao-Soo** [comment]
Sorry about that, but the panic just happen when the file is run with the input. The key code is src/lit.rs:362:47
