### ISSUE TITLE
Effective way to turn generics code into ::<>

### ISSUE THREAD

**Issue by chengyuhui** [dtolnay/syn#133]
I want to call something like `Option::<i64>::foo()` at runtime, while syn can only gives me `Option<i64>::foo()`, which is incorrect.

e.g.
```rust
struct F {
    a: Option<i64>
}

// Generated
impl F {
    fn call_foo() { Option::<i64>::foo(); }
}
```

**Comment by dtolnay** [comment]
In a macro I would recommend writing this as `<Option<i64>>::foo()`. That way it works for any type. For example `()::foo()` is not valid but `<()>::foo()` is.

**Comment by chengyuhui** [comment]
So it's OK to do the following?
```rust
let t = field.ty

quote! {
    <#t>::foo()
}
```

**Comment by dtolnay** [comment]
Yes exactly.

**Comment by chengyuhui** [comment]
Thanks. Closing
