### ISSUE TITLE
Integration with google/oss-fuzz

### ISSUE THREAD

**Issue by silvergasp** [dtolnay/syn#1334]
Hey David, first of all, thanks for all your hard work on this project ❤️I'd like to help with ensuring that this package reliable and secure. Some of your other projects [have already been integrated with oss-fuzz](https://github.com/google/oss-fuzz/search?q=dtolnay). Do you have plans to integrate this project with oss-fuzz? If not I'd happily champion the integration effort :)

**Comment by dtolnay** [comment]
See https://github.com/google/oss-fuzz/pull/5328.
