### ISSUE TITLE
Append to ImplGenerics & TypeGenerics

### ISSUE THREAD

**Issue by benluelo** [dtolnay/syn#1350]
(Similar to #732)

Consider the following trait and implementation:

```rust
trait Trait<'a> {}

struct Struct;

impl<'a> Trait<'a> for Struct {}
```

It would be very handy to be able to add to the `ImplGenerics` and `TypeGenerics` structs after they've been created. They could contain an extra field (something like `extra_params: Option<Punctuated<GenericParam, Token![,]>>`) to allow for an api like this:

```rust
// `generics` exists here, if it's mutated here then `impl_generics` and `ty_generics` both see the modifications

// would probably want this to be `Punctuated<GenericParam, Token![,]>`
let trait_params = [parse_quote!('q)];

let (mut impl_generics, ty_generics, where_clause) = generics.split_for_impl();

// add a lifetime required by the trait
// name is bikeshedding ofc
impl_generics.with_additional_generics(&trait_params);

// here, #impl_generics contains #trait_params
quote! {
    impl #impl_generics Trait<#trait_params> for #ident #ty_generics #where_clause {
        // etc
    }
}
```

Rather than needing to clone and do this:

```rust
let (_, ty_generics, where_clause) = generics.split_for_impl();

let (impl_generics, _, _) = generics.split_for_impl();
```

Note that #1092 asked for something similar, but that approach would require `split_for_impl`  to  take `&mut self`, which may or may not be desirable.

**Comment by dtolnay** [comment]
I think that use case is covered well enough by the approach described in the issue you linked.

**Comment by ModProg** [comment]
While #732 explains how to extend the `impl_generics` how would one extend the `ty_generics` with a non ident type, e.g., a tuple `(A, B, C)`.

```rs
gen.params.push_value(parse_quote!((A, B, C)));
```
Panics, because a tuple is not a valid generic param. But it is valid in the `ty_generics` position of an impl block.

**Comment by ModProg** [comment]
One idea I had was to have a function to get `generic_arguments()` from a `Generic`, that would return [`GenericArgument`s](https://docs.rs/syn/latest/syn/enum.GenericArgument.html).
