### ISSUE TITLE
`true` and `false` are not parsed as `Ident`.

### ISSUE THREAD

**Issue by GreenYun** [dtolnay/syn#1353]
According to [proc_macro2::Ident](https://docs.rs/proc-macro2/latest/proc_macro2/struct.Ident.html), keywords and legal variable names are expected to be parsed as `Ident`, while the following code will panic:

```rust
let i: proc_macro2::Ident = syn::parse_str("true").unwrap();
```

**Comment by GreenYun** [comment]
If keywords are intentionally not parsed as `Ident`, how can I safely parse a `str` and get (possibly) `Ident(true)` etc.

**Comment by dtolnay** [comment]
> According to [proc_macro2::Ident](https://docs.rs/proc-macro2/1.0.50/proc_macro2/struct.Ident.html), keywords and legal variable names are expected to be parsed as Ident

They are not. This is contradicted by the documentation you linked. _"parsing one through its `Parse` implementation rejects Rust keywords"_.
