### ISSUE TITLE
Redesign how parsing is exposed

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#137]
Currently there is a `syn::Expr` AST node for which parsing is exposed in two different ways:

- `syn::parse_expr` which returns `Result<Expr, String>`
- `syn::parse::expr` which returns `IResult<&str, Expr>` for use in synom parsers

Ideally both of these would somehow be trait impls on `syn::Expr` and not exposed any other way.

**Comment by dtolnay** [comment]
#131 added FromStr impls which is a step in the right direction.

**Comment by alexcrichton** [comment]
How about:

* Leave `syn::parse` for synom parsers
* Remove `syn::parse_*`
* Add `From<TokenStream> for T` for all requisite types

The `From` impl would panic for now if it fails and eventually use the "future proc_macro way of giving good error messages from procedural macros". Can you think of a use case for fallible parsing? If so we could add `try_from` style methods.

**Comment by alexcrichton** [comment]
Oh adding `FromStr` impls for these types also seems reasonable (just having trait impls exposed). I'd expect though that most procedural macros would prefer to operate over `TokenStream` (what they get from the compiler) rather than strings.

**Comment by dtolnay** [comment]
How reasonable would it be to expose synom parsers as traits instead? They might be used something like:

```diff
  named!(ty_tup -> Ty, do_parse!(
      punct!("(") >>
-     elems: terminated_list!(punct!(","), ty) >>
+     elems: terminated_list!(punct!(","), syn!(Ty)) >>
      punct!(")") >>
      (TyTup { tys: elems }.into())
  ));
```

where `syn!(Ty)` expands to `<Ty as WhateverTrait>::parse` with the same signature as the current `syn::parse::ty`.

**Comment by alexcrichton** [comment]
Sounds totally plausible to me (I'm not super familiar with nom, but looks reasonable!)

**Comment by dtolnay** [comment]
Okay. If you're not comfortable with that part then I can try to tackle the nom side.

**Comment by alexcrichton** [comment]
👍
