### ISSUE TITLE
Can't parse type defined inside unnamed constant

### ISSUE THREAD

**Issue by davidpdrsn** [dtolnay/syn#1378]
For proc-macros is quite common to put the generated code inside unnamed constants, to not pollute the surrounding namespace. However the name of types defined inside such constants cannot be parsed by `syn::Type`:

```rust
use std::any::type_name;
use syn::Type;

trait A {
    type T;
}

struct Foo;

const _: () = {
    struct Bar;

    impl A for Foo {
        type T = Bar;
    }
};

fn main() {
    syn::parse_str::<Type>(type_name::<<Foo as A>::T>()).unwrap();
}
```

This panics with

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected identifier")', src/main.rs:6:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The value of `type_name::<<Foo as A>::T>()` is `foo::_::Bar` (where `foo` is the crate), so maybe syn doesn't support `::_::`. I hadn't seen that before myself either 😅

**Comment by dtolnay** [comment]
This is behaving correctly as far as I can tell.
