### ISSUE TITLE
How to convert a type so that it uses turbofish syntax?

### ISSUE THREAD

**Issue by torkleyy** [dtolnay/syn#138]
I'd like to get `Foo::<T>` from `Foo<T>` given a `Ty`.
Is this possible at the moment and if not, is there an easy workaround?

**Comment by dtolnay** [comment]
Macros should always use `<Foo<T>>::torkleyy` instead of turbofish.

**Comment by torkleyy** [comment]
@dtolnay Thanks a bunch!
