### ISSUE TITLE
Why aren't the AST types immutable?

### ISSUE THREAD

**Issue by MariaSolOs** [dtolnay/syn#1388]
Some necessary clarifications: 

- I apologize for opening an issue for such a question. This isn't a bug report, just a humble request to satisfy my curiosity :)

- @dtolnay you're simply prolific and a superhero. The fact that you've authored so many crates that we all know and love is just... amazing.

Okay, moving on to the less important part: Why aren't the types in Syn immutable? In which scenario should a given node be modified after parsing? Is this to support custom parsers that slightly modified the Rust grammar?

**Comment by dtolnay** [comment]
Mutating the input is the entire point of attribute macros.

See any attribute macro. https://github.com/dtolnay/async-trait, https://github.com/dtolnay/no-panic

**Comment by MariaSolOs** [comment]
@dtolnay Thank you for the examples! I guess that the proc macros I've written have been trivial enough that I've only had to replace/append stuff to the parsed code. 

And sorry for the silly question 😅
