### ISSUE TITLE
Rewrite to operate on tokens

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#142]
Using https://github.com/rust-lang/rust/pull/40939 and [`proc-macro2`](https://github.com/alexcrichton/proc-macro2). **@​alexcrichton** is working on this.

**Comment by mystor** [comment]
I'm helping @alexcrichton with modifying the parser to run on TokenStream objects. My current unrebased branch is https://github.com/mystor/syn/tree/proc-macro2.

**Comment by dtolnay** [comment]
I love both of you.

@mystor question about `flatten_stream` - it looks like this would be lossy right? If you have a TokenStream containing `$a * 3` where the value of $a is `1 + 2`, this would turn it into something that is indistinguishable from `1 + 2 * 3`. (Not that we handle operator precedence anyway currently, but we will want to.) Any sense of how much harder it would be to support that correctly?

**Comment by mystor** [comment]
@dtolnay Yes, `flatten_stream` is currently lossy, which is quite unfortunate. I don't know off of the top of my head what the best way to handle the `None` delimiter sequences.

As you can probably tell from my current WIP branch, I was trying to do the minimal number of changes to the rest of `syn` to get the parser to work built on top of `proc-macro2`. I imagine that any attempt to get `None`-delimited sequences working with precedence will require a reworking of that entire part of the parser, as well as a change to the `synom` input format, which I figured we would probably have to do separately (although potentially before `0.12` is released, depending on how long it takes to get the real `proc-macro` into nightly).
