### ISSUE TITLE
Mention 5036fd9c6e9b89809f93a6ffa17ac6663652baed in release notes for 2.0.9

### ISSUE THREAD

**Issue by asomers** [dtolnay/syn#1424]
Could you please update the release notes to describe change 5036fd9c6e9b89809f93a6ffa17ac6663652baed ?  It caused mockall to fail in some cases, and I was surprised to see a breaking change missing from the release notes.

The offending syntax is
```rust
/// method doc comment
fn boo(&self);
```
when parsing this as an `ImplItem`, syn 2.0.8 would parse it as an `ImplItem::Fn`, but syn 2.0.9 parses it as `ImplItem::Verbatim`.

**Comment by dtolnay** [comment]
Done &mdash; sorry about the breakage.
