### ISSUE TITLE
`Ident::as_str()` method?

### ISSUE THREAD

**Issue by cameron1024** [dtolnay/syn#1432]
Hi, I was trying to get a `&str` representation of an `Ident`, and came across `.to_string()`, which works, but I don't need an owned `String`, I just need to compare it to a constant. Typically, I'd look for an `AsRef<str>` or an `.as_str()` method, but neither of those exist.

I'm assuming (since this seems like it would be a fairly common case) that there's a reason why this isn't possible, but if that's the case, perhaps it's worth adding a line to the docs explaining.

Happy to write a PR either way :grin: 

For context, I was trying to parse a custom syntax inside an attribute, e.g.:
```rust
#[(foo
  bar = 123,
  baz = 234,
)]
fn ...
```
where `bar` and `baz` are known ahead of time (they broadly correspond to fields of a `Config` struct).

**Comment by dtolnay** [comment]
I don't think this is implementable. Ident is just a handle to string data in the compiler's process. There is no string data in the proc macro's process to borrow from.
