### ISSUE TITLE
Syn 2.0 doesn't causes problems when parsing keywords in attributes

### ISSUE THREAD

**Issue by JelteF** [dtolnay/syn#1437]
The new parse_meta_path has some pretty annoying regression from 1.0, where if the attribute contains a keyword it is actually parsed as such.

Related issues:
1. https://github.com/jonasbb/serde_with/pull/578
2. https://github.com/JelteF/derive_more/pull/251
3. https://github.com/dtolnay/syn/pull/1413

**Comment by dtolnay** [comment]
I can't tell for sure from the description, but I am guessing this is a duplicate of #1414.
