### ISSUE TITLE
Add `parse_macro_input2` for `proc_macro2::TokenStream`

### ISSUE THREAD

**Issue by heckad** [dtolnay/syn#1438]
Now there is only a variant for proc_macro. In the case when we have a function like `fn testable_proc_macro_variant(input: proc_macro2::TokenStream) -> proc_macro2::TokenStream` you need to manually paint the macro. It would be grate to have the `parse_macro_input2`.

P. S. I can make the pull request.

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate.
