### ISSUE TITLE
"unexpected token" error even when all input has been parsed

### ISSUE THREAD

**Issue by dcov** [dtolnay/syn#1443]
Not sure if this is a bug, or an error in my usage.

I'm using the `quote` crate to generate a `TokenStream` that gets fed into `parse2`.
`input.is_empty()` returns `true`.
`cursor.eof()` returns `true`.

The error comes from the `ParseBuffer.unexpected` values. The final call to `check_unexpected` returns a span with a start `LineColumn`  of `{ line: 1, column: 0 }`, and an end `LineColumn` of `{ line: 1, column: 0 }`.

I'm using the latest version `2.0.14`.

**Comment by dtolnay** [comment]
This means you haven't parsed all the tokens.

**Comment by dcov** [comment]
The main parsing loop loops until `input.is_empty()` is `true` though, so either `ParseBuffer::is_empty` is returning true when there are still tokens that haven't been parsed, or the final call to `ParseBuffer::check_unexpected` (and/or any logic that deals with the `ParseBuffer::unexpected` values), has a bug. This is my first time using syn though so maybe I'm wrong on that.

That said I am using a local clone with the `state.check_unexpected` line removed from the `parse2` function impl, and the parsed output is correct, so it does seem to be parsing all the tokens from what I can gather.

**Comment by dtolnay** [comment]
I am very confident that the implementation is correct. 

You haven't shared enough about your code to reproduce the issue, but please take a more detailed version of this to any of the resources shown in https://www.rust-lang.org/community. Syn is one of the most widely used Rust libraries so plenty of people will be able to provide you with guidance.

**Comment by dcov** [comment]
Yeah I'm likely doing something wrong I just don't know what :/

I've pulled out the relevant code into this repo: https://github.com/dcov/cycle_define

The test fails with 'unexpected token' on the latest version, but if I use the local clone with that line I mentioned before, removed, the test succeeds.
