### ISSUE TITLE
How to avoid from the specific error when parsing nested meta?

### ISSUE THREAD

**Issue by dadamu** [dtolnay/syn#1448]
I met a error which shows "expected `,`" when running `attr.parse_nested_meta` on the structure like:
```rust
#[proto_message(type_url = "/desmos.profiles.v3.QueryProfileResponse")]
#[serde(rename_all = "snake_case")]
pub struct QueryProfileResponse {
    #[prost(message, optional, tag = "1")]
    pub profile: ::core::option::Option<crate::shim::Any>,
}
```

The thing I would like to do is to get the target of enumeration `#[prost(enumeration = "target" )]`, but it always returns the error mentioned above, so currently I filtered the specific error, the implementation code is:
```rust
fn find_prost_enumeration_value(attrs: &[Attribute]) -> Option<String> {
    attrs.iter().find_map(|attr| {
        // Check if the attribute name is "prost".
        if !attr.path().is_ident("prost") {
            return None;
        }

        // Search all nested attributes and look for the "enumeration" attribute, then getting its value.
        let mut enumeration_value = None::<String>;
        attr.parse_nested_meta(|meta| {
            if !meta.path.is_ident("enumeration") {
                return Ok(());
            }

            let value = meta.value()?;
            let s: syn::LitStr = value.parse()?;
            enumeration_value = Some(s.value());
            return Ok(());
        })
        .unwrap_or_else(|e| {
            // Do nothing if the error is "expected `,`"
            if e.to_string() != "expected `,`".to_string() {
                panic!("{}", e)
            }
        });

        enumeration_value
    })
}
```

Is any way I can avoid from filtering the specific error "expected `,`" in the code?

**Comment by dtolnay** [comment]
You are not parsing the value that follows the `tag` attribute. In general you need to parse the whole attribute.

For example something like:

```rust
#[attribute(favorite_type = Q<u8, u8>, precondition_expr = Q < 12, postcondition_expr = Q > foo, bar)]
```

Blindly skipping around between the commas would not be correct.

**Comment by dadamu** [comment]
@dtolnay
In the case, the function only needs to get the `enumeration` value, is any other ways to parse partially then getting `enumeration` value?

**Comment by dadamu** [comment]
I found the solution which using `parse_args_with(Punctuated::<Meta, Token![,]>::parse_terminated);` to get the nested meta without parsing whole the details of attribute, instead.

Thanks for the help!
