### ISSUE TITLE
Bare trait objects

### ISSUE THREAD

**Issue by daxpedda** [dtolnay/syn#1451]
I just noticed that `Option<Fn()>` can not be parsed with `syn` v2 anymore because it doesn't expect bare trait objects. So `Option<dyn Fn()>` can be parsed.

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=38c0142423032baff8f1ae86a8d0e0b4):
```rust
let _: TypePath = syn::parse_quote! { Option<Fn()> };
```

Is there some way valid edition 2018 code can still be parsed? Is this intended?

I'm surprised nobody stumbled on this yet, but maybe I just couldn't find the appropriate issue, apologies if I missed it!

**Comment by dtolnay** [comment]
It is intentional. That code has produced deprecation warnings (in all additions) for nearly 4 years.

**Comment by daxpedda** [comment]
Alright, thank you!
