### ISSUE TITLE
attribute macro has no access to attributes defined before it

### ISSUE THREAD

**Issue by roignpar** [dtolnay/syn#1452]
Hi! Thank you for syn and all your Rust work!

I ran into this issue while debugging this: https://github.com/roignpar/optfield/issues/4
It seems that attribute macros have no access to attrs defined before them.
```rs
#[before]
#[after]
struct Item;
```
If both `before` and `after` are attribute macros:
* `before` will have `after` in `Item`'s `attrs` field
* `after` will not have `before` in `Item`'s `attrs` field

The same happens with any kind of attribute in relation to attribute macros.

I haven't tried this with other proc macro types.

Most documentation I could find was here: https://doc.rust-lang.org/reference/procedural-macros.html#attribute-macros, but it says that "The second [TokenStream](https://doc.rust-lang.org/proc_macro/struct.TokenStream.html) is the rest of the [item](https://doc.rust-lang.org/reference/items.html) including other [attributes](https://doc.rust-lang.org/reference/attributes.html) on the [item](https://doc.rust-lang.org/reference/items.html)."
I couldn't find any mention of attribute order or anything like that.

Is this intended behavior?

**Comment by dtolnay** [comment]
This issue is not related to syn. Syn is not in control of what tokens rustc passes into an attribute macro.
