### ISSUE TITLE
How to save syn::File to disk? 

### ISSUE THREAD

**Issue by divflex** [dtolnay/syn#1456]
I'm trying to use syn to parse a rust file and add some comments.
I dont' know how to save this `File` struct.

I have tried 
```rust
let data = result.into_token_stream();
std::fs::write("./test.rs", data.to_string())?;
```

the result is not as expected. It has extra white space and without line break;
```
# [doc = "hello world"] pub const A : u8 = 10u8 ; # [doc = "hello world"] pub const B : u8 = 
```

**Comment by atsmtat** [comment]
If you're trying to "unparse" the `syn::File` tree and print it as a source file, I think you can use `prettyplease` crate.

```rs
let formatted = prettyplease::unparse(&data);
std::fs::write("./test.rs", formatted);
```

Check this out: https://docs.rs/prettyplease/0.2.6/prettyplease/#example

**Comment by divflex** [comment]
> If you're trying to "unparse" the `syn::File` tree and print it as a source file, I think you might want to use `prettyplease` crate.
> 
> ```rust
> let formatted = prettyplease::unparse(&data);
> std::fs::write("./test.rs", formatted);
> ```
> 
> Check this out: https://docs.rs/prettyplease/0.2.6/prettyplease/#example

Thank you very much. I will try it.
