### ISSUE TITLE
Can't parse_macro_input with what used to be AttributeArgs

### ISSUE THREAD

**Issue by glandium** [dtolnay/syn#1463]
The release notes for syn 2 say that `AttributeArgs` was removed, and says to use `Punctuated<Meta, Token![,]>` instead. But while `parse_macro_input!(foo as AttributeArgs)` worked with syn 1, the equivalent (with `Punctuated<Meta, Token![,]>`) doesn't work with syn 2 because ParseMacroInput is gone, and Punctuated doesn't implement Parse. How does one do the equivalent of `parse_macro_input!(foo as AttributeArgs)` with syn 2?

**Comment by glandium** [comment]
Thanks, that was useful.

**Comment by penso** [comment]
That was indeed useful!
