### ISSUE TITLE
Group spans don't round-trip when run under rust-analyzer

### ISSUE THREAD

**Issue by jneem** [dtolnay/syn#1464]
I'd expect that a proc macro that does nothing but parse its input and convert it back to a token stream will be a no-op:
```rust
#[proc_macro_attribute]
pub fn foo(_args: TokenStream, input: TokenStream) -> TokenStream {
    dbg!(&input);
    let parsed_input = parse_macro_input!(input as ItemFn);
    dbg!(parsed_input.to_token_stream().into())
}
```

When I use this proc macro in some crate, and compile it with `cargo check`, it does indeed seem to round trip correctly. But when I run it with `rust-analyzer diagnostics .`, it does not: everything is identical between input and output except for the spans of Groups. For example, where the input has
```
    Group {
        delimiter: Parenthesis,
        stream: TokenStream [],
        span: 2,
    }
```
the output will have
```
   Group {
        delimiter: Parenthesis,
        stream: TokenStream [],
        span: 4294967295,
    }
```

I have a full example set up [here](https://github.com/jneem/macro-error-location)

**Comment by dtolnay** [comment]
If this behaves correctly using rustc's proc macro server, and behaves incorrectly using rust-analyzer's proc macro server, then this is a rust-analyzer bug.
