### ISSUE TITLE
QSelf isn't spanned

### ISSUE THREAD

**Issue by Qix-** [dtolnay/syn#1465]
Just working with some `syn` this morning and noticed that `QSelf` isn't spanned. Is that just a missing implementation or is there perhaps a good reason for it?

I can submit a PR if it's just a gap in the implementation :)

**Comment by bzm3r** [comment]
@Qix- See the docs [here](https://docs.rs/syn/latest/syn/struct.QSelf.html) on what the `position` field of  `QSelf` refers to. 

So, if you want the span of the `Self` part, then that would be the span of the `ty` field on `QSelf`. If you want the span of the associated item, it would be the span of the `position`-indexed item in the [`path`](https://docs.rs/syn/latest/syn/struct.TypePath.html#structfield.path) of `TypePath`.

**Comment by Qix-** [comment]
I know that I can get the specific spans of components in that type but I found it strange that pretty much everything implements the `Spanned` trait but this type does not. Usually that would return the joined spans of all child elements, no?
