### ISSUE TITLE
Blanket impl type should not be included in `TypeGenerics`

### ISSUE THREAD

**Issue by mversic** [dtolnay/syn#1470]
Let's consider a simple example:
```rs
/// This macro just returns the exact same impl as it received
#[proc_macro]
pub fn item_impl_identity(input: TokenStream) -> TokenStream {
    let impl_: syn::ItemImpl = syn::parse_macro_input!(input);
    let (impl_generics, ty_generics, _) = impl_.generics.split_for_impl();
    let trait_ = impl_.trait_.as_ref().map(|t| &t.1);
    let self_ty = &impl_.self_ty;

    quote! { impl #impl_generics #trait_ for #self_ty #ty_generics {} }.into()
}
```

and let's use it here:
```rs
item_impl_identity! {
    impl<U> Kita<U> for U {}
}
item_impl_identity! {
    impl<U> Kita<U> for (u32, U) {}
}
```

This produces:
```rs
impl<U> Kita<U> for U<U> {}
impl<U> Kita<U> for (u32, U)<U> {}
```

The problem is that `TypeGenerics`, returned from `Generics::split_for_impl`, contains blanket impl `self_ty` (in this case `U`)

**Comment by dtolnay** [comment]
`impl_.self_ty` already included any generics needed for the Self type. It included everything between the `for` and the next `where` or `{`. So writing `#self_ty #ty_generics` is not correct -- it should only be `#self_ty`.

**Comment by mversic** [comment]
> `impl_.self_ty` already included any generics needed for the Self type. It included everything between the `for` and the next `where` or `{`. So writing `#self_ty #ty_generics` is not correct -- it should only be `#self_ty`.

yes, I understand that but the problem is that I don't know beforehand whether or not my macro is being called for a blanket or a regular impl. Let me try to rephrase the question. How would you rewrite my macro impl so that the following code compiles:

```rs
item_impl_identity! {
    impl<U> Kita<U> for (u32, U) {}
}
item_impl_identity! {
    impl<U> Kita<U> for Vec<U> {}
}
```
