### ISSUE TITLE
Consider relaxing item types for a future syn 3

### ISSUE THREAD

**Issue by nox** [dtolnay/syn#1480]
First, sorry if there is already an issue somewhere about this, I couldn't find one.

Second, I understand that this is pretty niche, but nonetheless it would be nice to support what I'm going to explain below, if only to make things like prettyplease be able to support all files one can throw at it.

Consider this:

```rust
#[some_proc_macro_attribute]
mod some_mod {
    fn some_bodyless_fn();
}
```

Given the right `some_proc_macro_attribute` definition (e.g. one that completes any bodyless function definition with `{ todo!() }` or one that just sends all its input tokens to the void), this is actually valid code that rustc will be happy to support. AFAIU this is not a rustc bug, and this is expected behaviour.

I've also noticed that `pub impl Foo {}` can be happily parsed by proc macro attributes, not sure I should file a separate issue about that or not.

**Comment by dtolnay** [comment]
Both of those (`some_bodyless_fn` and `pub impl Foo`) are already parsed by syn, and formatted correctly by prettyplease.

**Comment by nox** [comment]
Oh damn I completely missed `Item::Verbatim` and only saw `ItemFn` having a non-optional `block` field, disregard me.
