### ISSUE TITLE
Add ability to strip doc / attributes info from the Span

### ISSUE THREAD

**Issue by Mingun** [dtolnay/syn#1488]
I'm working on and PR for fixing https://github.com/serde-rs/serde/issues/2105 and the related stuff and making compiletests for them. For the piece
```rust
#[derive(Serialize)]
#[serde(tag = "type")]
enum Serializable {
    /// Error should be reported
    Tuple2(u8, u8),
}
```
the error span would cover several lines:
```
error: #[serde(tag = "...")] cannot be used with tuple variants
  --> tests/ui/enum-representation/internal-tuple-variant.rs:10:5
   |
10 | /     /// Error should be reported
11 | |     Tuple2(u8, u8),
   | |__________________^
```
Because doc comments can be very long, it is impractical to bring them into error messages. I would like to get the following message:

```
error: #[serde(tag = "...")] cannot be used with tuple variants
  --> tests/ui/enum-representation/internal-tuple-variant.rs:10:5
   |
10 |       /// Error should be reported
11 |       Tuple2(u8, u8),
   |       ^^^^^^^^^^^^^^
```

That error is generated by the following code in serde ([here in action](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f58b5fa1f5be45471b4b021dc9605fa1)):
```rust
// variant.original is a `&syn::Variant`
cx.error_spanned_by(
    variant.original,
    "#[serde(tag = \"...\")] cannot be used with tuple variants",
);
```
Is there any way to strip span that related to doc comments (and probably to all other attributes) and keep only code span of `syn::Variant`, `syn::Field`, etc?

**Comment by dtolnay** [comment]
The range that the error points to is determined by providing a ToTokens implementation that contains the tokens which are to be highlighted in the error. So for this case, something like:

```rust
let error = syn::Error::new_spanned(
    WithoutAttrs(variant.original),
    "...",
);
```

where the ToTokens impl is:

```rust
struct WithoutAttrs<T>(T);

impl ToTokens for WithoutAttrs<&syn::Variant> {
    fn to_tokens(&self, tokens: &mut proc_macro2::TokenStream) {
        self.0.ident.to_tokens(tokens);
        self.0.fields.to_tokens(tokens);
    }
}
```
