### ISSUE TITLE
`Visitable` trait? 

### ISSUE THREAD

**Issue by smoelius** [dtolnay/syn#1492]
Have you considered, or would you be open to, having a `Visitable` trait that would be implemented by each type for which `Visit` has a `visit_...` method?

Essentially, an analog of this trait from `clippy_utils`: https://doc.rust-lang.org/beta/nightly-rustc/clippy_utils/visitors/trait.Visitable.html

Such a feature would facilitate writing functions that operate on arbitrary syntax, e.g.,:
```rust
fn contains_expr<T: Visitable>(ast: T, expr: &Expr) -> bool {
    let v = ExprFinder(expr);
    ast.visit(v);
    v.found
}
```

**Comment by dtolnay** [comment]
It is not something I would want in this crate.

But using https://docs.rs/syn-codegen, it wouldn't be burdensome for someone to maintain this functionality in a separate crate.
