### ISSUE TITLE
error[E0432]: unresolved import `syn::ItemStruct`

### ISSUE THREAD

**Issue by yuxinyu12345** [dtolnay/syn#1495]
```
error[E0432]: unresolved import `syn::ItemStruct`
 --> bft-crdt-derive/src/lib.rs:9:39
  |
9 |     Data, DeriveInput, Field, Fields, ItemStruct, LitStr, Type
  |                                       ^^^^^^^^^^ no `ItemStruct` in the root

```
syn: 1.0.109
rust： stable-aarch64-apple-darwin (default)
cargo：cargo 1.71.1 (7f1d04c00 2023-07-29)

i need you help, thanks.

**Comment by Fancyflame** [comment]
Please note `Available on crate feature full only` in [docs](https://docs.rs/syn/latest/syn/struct.ItemStruct.html#). Try adding feature `full` to your syn dependency.
