### ISSUE TITLE
Parse `c"…"` and `cr"…"` string literals

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#1502]
RFC: https://github.com/rust-lang/rfcs/pull/3348
Tracking issue: https://github.com/rust-lang/rust/issues/105723

**Comment by dtolnay** [comment]
Blocked on https://github.com/rust-lang/rust/issues/112820.

**Comment by Ddystopia** [comment]
Blocker appears to be resolved and `c"..."` and `cr"..."` string literals are stabilized in 1.77
