### ISSUE TITLE
Clearer parsing API for Generics ?

### ISSUE THREAD

**Issue by twiby** [dtolnay/syn#1505]
As a user, I was surprised at using `Generics::parse` in the regular way and seeing it not parse its `Option<WhereClause>` member. After some digging around, I kinda see why that is the case: the parser may want to handle other elements before getting to the `where` clauses (which are locating in different places depending on the item they are attached to).

Still, not accounting for the surprise of the `parse` function not parsing the `where` clauses (even if they are just after the parameters), a user of `Generics` (and indeed the internals of`syn`itself) have to resort to calling first `let generics: Generics = input.parse()?;` and then a strange
```
lookahead = input.lookahead1();
if lookahead.peek(Token![where]) {
    where_clause = Some(input.parse()?);
    lookahead = input.lookahead1();
}
```

If I'm not alone in finding that weird, I see 2 avenues to handle that situation, and I created this issue to check the need for an improvement, and help in deciding the best route to take:
 - either make `Generics` not implement `Parse`but instead have dedicated functions `parse_parameters` and `parse_where_clause` (kinda like how `Attribute` has `parse_outer` and `parse_inner`)
 - split `Generics` into `GenericParameters` and `GenericWhereClause` for example (renaming or wrapping existing types probably).
 - Maybe something else ?

**Comment by twiby** [comment]
I should add that I intend to push the PR myself ! This issue is simply to consider options and orient my potential work.

**Comment by dtolnay** [comment]
Thank you for the suggestions. Compared with the other options you named, I think the current way this is implemented is my preferred one.

Rustc's AST follows substantially the same approach, too.
