### ISSUE TITLE
Should syn::parse_file require the parse feature?

### ISSUE THREAD

**Issue by jmintb** [dtolnay/syn#1516]
I was trying out `syn::parse_file` and the required features confused me.

`syn::parse_file` requires `parse` and `full` features. This does not make sense to me as `full` would imply `parse`(assuming `full` actually enabled everything). I tested this and `full` is the only feature that ends up enabling `syn::parse_file` and `parse` is not required. 

Am I missing something or what is the idea here? 

Thanks for the awesome crate!

**Comment by dtolnay** [comment]
I think this is correct as implemented. "Full" does not imply "parse". One can build syn with "full" enabled and "parse" disabled, in which case `parse_file` would not be available.
