### ISSUE TITLE
why not used grammar and parser generator?

### ISSUE THREAD

**Issue by 3DRaven** [dtolnay/syn#1523]
Hi! I'm sorry, it just a question for my understanding. Why it is not generated by parser-generator library? Or it based on generated parser? As example antlr4 or may be other generators have grammars for Rust.

**Comment by dtolnay** [comment]
Hi 3DRaven, if you are still interested in this, I would recommend taking this question to any of the resources shown in https://www.rust-lang.org/community to discuss the tradeoffs.
