### ISSUE TITLE
Provide a mechanism for interpreting `Literal`

### ISSUE THREAD

**Issue by mystor** [dtolnay/syn#153]
Currently the master branch doesn't interpret the `Literal` tokens which it is passed, leaving that up to the consumer. `syn` 0.11 provides a mechanism for interpreting these values. We (or `proc-macro2`) should provide methods for interpreting these `Literal` objects into actual values. If this impacts build times, we may want to put it behind a feature (which may or may not be on-by-default), as not all procedural macros, but at least some, will need it.

**Comment by clarcharr** [comment]
This should be in by default; a super common use case is interpreting string literals. Right now, the best way to get at this is to call `to_string` and then un-escape the inside of the string, which is quite hacky.

**Comment by mystor** [comment]
I just threw together https://github.com/mystor/literalext which is an extension trait which adds methods to `Literal` for extracting values. It should be usable with master `syn` right now.

I think an API like this should probably be added to the real `Literal` type in `proc-macro` (and by extension `proc-macro2`), but I figure that a external crate with an extension trait will be a good tool to start with.

@alexcrichton, @dtolnay and @clarcharr, I'm curious what you think about the API which I put together. I tried to keep it extensible and non-exhaustive, while still doing the things you would want it to.

**Comment by alexcrichton** [comment]
Looks great to me! I might recommend `to_*` as a prefix as these will often require a lot of work (not free conversions) but otherwise the API looks good.

**Comment by mystor** [comment]
> Looks great to me! I might recommend `to_*` as a prefix as these will often require a lot of work (not free conversions) but otherwise the API looks good.

Good point. I think I originally called them `as_*` because I was thinking of the API as being part of rustc, which would have most of the work which I would need to do already done (although not all of it. IIRC we store interned strings inside of float and int literals until we need to use their value).

Calling them `to_*` is certainly better for the purposes of this crate.

**Comment by dtolnay** [comment]
Redesigned in https://github.com/dtolnay/syn/commit/360efd23b84a4165de3d7f77b4132c80b74c60e9.
