### ISSUE TITLE
How to create a WherePredicate with a type parameter?

### ISSUE THREAD

**Issue by turion** [dtolnay/syn#1534]
The docs for [`WherePredicate`](https://docs.rs/syn/latest/syn/enum.WherePredicate.html) mention:

> A single predicate in a where clause: `T: Deserialize<'de>`.

Let's assume I want to define this example. This is clearly a predicate on a type, so, I look into [`PredicateType`](https://docs.rs/syn/latest/syn/struct.PredicateType.html). Hmm, there the example is a different one:

> `for<'c> Foo<'c>: Trait<'c>`

Let's hope I don't need to specify the `for` and the `'c`. I can probably omit this by leaving the `lifetimes` field empty. On we go. I want to add a predicate to `T`, so I should add `T` in `PredicateType`. However, the `bounded_ty` field has type `Type`. My `T`, which I would get, e.g., from the `params` of a `Generics`, is a `TypeParam`! How do I get a `Type` from that?

It seems to me that maybe the type of `PredicateType` is a bit wrong. It doesn't have a field for type variables. If it would, I could get the `Ident` from a `TypeParam`. I clearly can't resolve the type variable at this stage, since we're not doing type checking.

**Comment by turion** [comment]
Also, the docs for [`Type`](https://docs.rs/syn/latest/syn/enum.Type.html) are very confusing: The examples are often with type variables, but I can't find a way to construct a type variable.

**Comment by dtolnay** [comment]
The best way to figure out the answer to this kind of thing is by looking at what syntax tree the parser produces.

```rust
// [dependencies]
// quote = "1"
// syn = { version = "2", features = ["extra-traits", "full"] }

use quote::quote;

fn main() {
    let tokens = quote! {
        fn f() where T: Deserialize<'de> {}
    };
    let item: syn::Item = syn::parse2(tokens).unwrap();
    println!("{:#?}", item);
}
```
