### ISSUE TITLE
Broken rust docs hyperlinks on sidebar when inside modules

### ISSUE THREAD

**Issue by Bryanlee99** [dtolnay/syn#1537]
When navigating to the `syn` rust docs in the `parse` module ([parse module link](https://docs.rs/syn/latest/syn/parse/index.html)), the left banner with section `In crate syn` lists hyperlinks which link to items outside the `parse` module but hyperlink to `syn/parse/[path]` instead of `syn/[path]` which gives broken hyperlinks (Example: [`parse_macro_input` incorrect link](https://docs.rs/syn/latest/syn/parse/macro.parse_macro_input.html), [`parse_macro_input` correct link](https://docs.rs/syn/latest/syn/macro.parse_macro_input.html)). 

This occurs for [all modules](https://docs.rs/syn/latest/syn/index.html#modules) in the syn crate. Links inside the main page's markdown docs are correct. 

This `In crate syn` section is not generated when I generate the docs locally with `cargo doc --open` so these broken hyperlinks do not appear. This `In crate X` section does not appear in the standard library docs, such as in [std::collections](https://doc.rust-lang.org/std/collections/index.html).

**Comment by dtolnay** [comment]
Could you report this as a rustdoc bug? I can't think of anything particular that would be syn-specific to trigger this.
