### ISSUE TITLE
Span bytes are not reset on subsequent calls to parse_file.

### ISSUE THREAD

**Issue by nigeleke** [dtolnay/syn#1560]
I would expect the two calls to `parse_file`, below, to return exactly the same `ast`.  It appears however that the byte offset is not set to zero at the start of `parse_file`.  Is the expectation wrong or is this a defect?

main.rs
```
use std::fs;

fn main() {
    let source = fs::read_to_string("./src/main.rs").unwrap();
    println!("Source:\n{}", source);

    let ast0 = syn::parse_file(&source).unwrap();
    println!("***** *****\nAST0::items:");
    for item in ast0.items.iter() {
        println!("      {:?}", item);
    }

    let ast1 = syn::parse_file(&source).unwrap();
    println!("***** *****\nAST1::items:");
    for item in ast1.items.iter() {
        println!("      {:?}", item);
    }
}
```

AST output:
```
***** *****
AST0::items:
      Item::Use { attrs: [], vis: Visibility::Inherited, use_token: Use, leading_colon: None,
          tree: UseTree::Path(UsePath { ident: Ident { sym: std, span: **bytes(5..8)** }, ...
      Item::Fn { attrs: [], vis: Visibility::Inherited, sig: Signature { constness: None, asyncness: None, unsafety: None, abi: None, fn_token: Fn, ident: Ident { sym: main, span: bytes(18..22) }, ...
***** *****
AST1::items:
      Item::Use { attrs: [], vis: Visibility::Inherited, use_token: Use, leading_colon: None,
          tree: UseTree::Path(UsePath { ident: Ident { sym: std, span: **bytes(481..484)** }, ...
      Item::Fn { attrs: [], vis: Visibility::Inherited, sig: Signature { constness: None, asyncness: None, unsafety: None, abi: None, fn_token: Fn, ident: Ident { sym: main, span: bytes(494..498) }, ...
```

Cargo.toml
```
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = { version = "*", features = ["proc-macro", "span-locations"] }
syn = { version = "*", features = ["extra-traits", "full", "visit"] }
```

**Comment by dtolnay** [comment]
I believe this is the intended behavior. Proc_macro works like this too. The numbers you are looking at in the Debug impl of Span are not relative to the beginning of the surrounding file.

```rust
// src/lib.rs

use proc_macro::TokenStream;

#[proc_macro]
pub fn repro(input: TokenStream) -> TokenStream {
    eprintln!("{:#?}", input);
    TokenStream::new()
}
```

```rust
// src/main.rs

mod a;
mod b;

fn main() {}
```

```rust
// src/a.rs

repro::repro!(..);
```

```rust
// src/b.rs

repro::repro!(..);
```

Output:

```console
TokenStream [
    Punct {
        ch: '.',
        spacing: Joint,
        span: #0 bytes(72..73),
    },
    Punct {
        ch: '.',
        spacing: Alone,
        span: #0 bytes(73..74),
    },
]
TokenStream [
    Punct {
        ch: '.',
        spacing: Joint,
        span: #0 bytes(105..106),
    },
    Punct {
        ch: '.',
        spacing: Alone,
        span: #0 bytes(106..107),
    },
]
```

**Comment by nigeleke** [comment]
Love the rapid Boxing Day response... thanks.
... I understand what you stated, but not why it's intended behaviour. If there's a link to the reasoning there I'd love to know...
... Nevertheless, any idea how I could determine the span's bytes offset from the start of the "file" / "string" being parsed by `parse_file`...

**Comment by dtolnay** [comment]
Spans from two different files are definitely not the same span. A bunch of APIs on `Span` need to behave differently depending on the span's source file, not only depending on the offset within some file. A span is not just a byte offset into a file.

For example consider `Span::source_text` or `Span::join`. Or `Span::start`/`Span::end`. The same byte offset is not necessarily going to be located at the same line/column in 2 different files.

If two spans are going to behave very differently, it makes sense to me that they would have different Debug representations.

For byte offset from start of file, you would need to reconstruct this from `Span::start` because the line number returned by that is counted from within the same file.

**Comment by nigeleke** [comment]
That makes sense now; thanks.
I had just uncovered `Span::start` and `Span::end` and had been mentally blanking them as I'd been trying to avoid the `nightly build`... and now realised it's `Span::start / end` in `proc_macro` that has the nightly build dependence.
Your help & explanation very much appreciated.
