### ISSUE TITLE
`StrStyle` does not implement common traits

### ISSUE THREAD

**Issue by madsmtm** [dtolnay/syn#1561]
It seems like [`syn::StrStyle`](https://docs.rs/syn/latest/syn/enum.StrStyle.html) does not implement the common traits `Clone`, `Copy`, `Debug`, `PartialEq`, `Eq` and `Hash`. Is this intentional, or an oversight?

**Comment by dtolnay** [comment]
StrStyle is vestigial as far as I can tell. It does not appear as a field in any syntax tree data structures, or in any public function signatures. Did you have a use case that benefits from using syn::StrStyle as opposed to your own enum?

Most likely we planned to add `impl LitStr { pub fn style(&self) -> StrStyle }` at some point but never found a use for it.

**Comment by madsmtm** [comment]
> Did you have a use case that benefits from using syn::StrStyle as opposed to your own enum?

Nope, I don't actually use it, I just spotted it in passing.

**Comment by dtolnay** [comment]
Great!

I'll plan to delete `StrStyle` in the next version. https://github.com/dtolnay/syn/issues/1566
