### ISSUE TITLE
ImplGenerics ToTokens ignores defaults of const Generics

### ISSUE THREAD

**Issue by JustSomeRandomUsername** [dtolnay/syn#1579]
```rust
let mut generics = syn::Generics::default();
generics.params.push(parse_quote!(const N: usize = 1));
println!("{:?}", generics.split_for_impl().0.to_token_stream().to_string());
```
prints:  ```"< const N : usize >"```
When I would expect ```"< const N : usize = 1 >"```

Looking at your source code this seems to be done on purpose, so I guess there are situations where it is preferred to leave out the defaults.
If this is the case, could it be possible to have an option to toggle this?

**Comment by dtolnay** [comment]
This is the point of `ImplGenerics`.

`impl<const N: usize = 1> T {}` is not valid.

**Comment by JustSomeRandomUsername** [comment]
Fair point, I should have read the docs for ```split_for_impl()``` again :facepalm: 
For future reference calling ```to_token_stream()``` on ```Generics``` gives the result I was looking for.
