### ISSUE TITLE
Parsing "let mut" and quote! directly without modification

### ISSUE THREAD

**Issue by Alphapage** [dtolnay/syn#1581]
Hello,

I'm trying to parse 
```
let mut t=0;
let l:u8=1;
```
First of all, I can't find any Expr... to parse the expression: it would be great to have a big file grouping all parsing features and usage. My goal is to replace `let mut t=0;` by `let t=0;`.

Finally, if I find a `let`, I need to push it as it was before parsing: I don't want to rewrite it in quote! by hand, but submit using something like`item.unchanged()` .

Is it possible ?

Thank you in advance for your help.

**Comment by dtolnay** [comment]
This question would be more appropriate for one of the resources shown in https://www.rust-lang.org/community. This library is one of the most widely used Rust libraries and plenty of people will be able to provide guidance about it.
