### ISSUE TITLE
Is there any way to get the Type what Type::Path points to?

### ISSUE THREAD

**Issue by uuhan** [dtolnay/syn#1584]
I want to check if a type is a large const sized array, 

```rust
fn big_array_p(ty: &Type) -> bool {
    match ty {
        Type::Array(n) => match &n.len {
            Expr::Lit(lit) => match &lit.lit {
                Lit::Int(size) => {
                    if let Ok(size) = size.base10_parse::<u32>() {
                        // big array size > 32
                        if size > 32 {
                            return true;
                        }
                    }
                }
                _ => {}
            },
            _ => {}
        },
        Type::Path(p) => {
            println!("{:?} {:?}", p.path, p.qself);
        }
        _ => {}
    }

    false
}
```

The Type::Array branch works well for the struct:

```rust
struct Big {
      pub field: [u8; 100],
}
```

But failed with the type alias version:

```rust
pub type B = [u8; 100],

struct Big {
    pub field: B,
}
```

Could I complete the Type::Path branch with what I need?

I read some of the source of `syn`, but seems the `Path` type does not hold the real type info which the `Path` points to.

**Comment by dtolnay** [comment]
Hi @uuhan, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community. This library is one of the most widely used Rust libraries and plenty of people will be able to provide guidance about it.
