### ISSUE TITLE
failed to resolve: use of undeclared type `Lit`

### ISSUE THREAD

**Issue by Raistah** [dtolnay/syn#1585]
At some point, the tests in my repository stopped running, I decided to create a completely new project and the same error occurred there
![image](https://github.com/dtolnay/syn/assets/29507215/c7832369-7398-49a9-ba64-9ede7168b0ec)
 i resoled this by changing version to "<2.0.47"
![image](https://github.com/dtolnay/syn/assets/29507215/325c162c-ed60-4193-a313-4a5d4896948b)

**Comment by dtolnay** [comment]
I was not able to reproduce this, and there is absolutely no relevant change between 2.0.46 and 2.0.48 that could cause that error. <https://github.com/dtolnay/syn/compare/2.0.46...2.0.48>

My guess is you made your own code changes to syn's source code in /home/raistah/.cargo/registry/src/index.crates.io-6f17d22bba15001f/syn-2.0.48 on your machine.

**Comment by Raistah** [comment]
Something very strange happened...
I realized that the problem is in rscss, there is some version conflict, but if in cargo.toml is written with the latest version but also with the < symbol, everything works.

At the same time, the test crate still has this error, although there are almost no dependencies.

I did not make any changes to the repository, but I can assume that the problem is in some cache, because in fact the problem completely disappears when I add "<" to the crate version
![image](https://github.com/dtolnay/syn/assets/29507215/4e0e6d5e-5fba-45fa-8f79-8a659ffb0321)
