### ISSUE TITLE
Rename syn::Crate

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#164]
The name comes from libsyntax's ast::Crate but it is misleading for us because I think libsyntax parses and inlines all the modules that are referenced by the code, while we parse a single file only.

**Comment by mystor** [comment]
This is probably a good idea, we could call it `Module` perhaps?

We could also add something like [`synmap`](https://github.com/mystor/rust-cpp/tree/master/cpp_synmap) (which I had built on top of my `cpp_syn` fork with spans), which handles parsing entire crates. Depending on what features `proc-macro` ends up supporting, we won't need very much code. (most of `cpp_synmap` is spent keeping track of which file each span comes from etc. to map back)

**Comment by clarcharr** [comment]
I think calling it `syn::SourceFile` would be most appropriate.
