### ISSUE TITLE
Struct Literals in ExprLet

### ISSUE THREAD

**Issue by OliverKillane** [dtolnay/syn#1670]
## Description
Struct literals are currently disallowed in the [Parse implementation for `ExprLet`](https://github.com/dtolnay/syn/blob/747f42f235f8e1b5551a6aeca1d2779dce413408/src/expr.rs#L2120)

I am unsure why this is the case
- ran `cargo test --release --all-features` with `let allow_struct = AllowStruct(true);` and it appears to work just fine, so there are currently no tests exposing this behaviour of the Parse implementation?
- is there a reason for the restriction?

### [Example](https://github.com/OliverKillane/bug-reports/blob/main/syn-expr-let-incorrect-fail/src/lib.rs)

**Comment by dtolnay** [comment]
Fixed in 2.0.66.
