### ISSUE TITLE
Parse `safe` items in extern blocks

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#1675]
Tracking issue: https://github.com/rust-lang/rust/issues/123743
RFC: https://github.com/rust-lang/rfcs/pull/3484

```rust
unsafe extern "C" {
    safe static TEST1: i32;
    safe fn test1(i: i32);
}
```

https://github.com/rust-lang/rust/blob/76e7a0849c07d73e4d9afde8036ee8c450127cc8/tests/ui/rust-2024/unsafe-extern-blocks/safe-items.rs

**Comment by jacks0n9** [comment]
cool
