### ISSUE TITLE
Parse precise capturing syntax

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#1677]
RFC: https://github.com/rust-lang/rfcs/pull/3617
Tracking issue: https://github.com/rust-lang/rust/issues/123432

```rust
fn f<'a, T>() -> impl Sized + use<'a, T> {}
```

**Comment by traviscross** [comment]
Just an update here that the [stabilization report](https://github.com/rust-lang/rust/pull/127672#issue-2406639114) for this has gone up.

The earliest this syntax could conceivably stabilize is with Rust 1.82, which will branch on 2024-08-30 and will be released on 2024-10-17.
