### ISSUE TITLE
[Feature Request] Add support for incomplete expression and statement

### ISSUE THREAD

**Issue by Fancyflame** [dtolnay/syn#1715]
Rust Analyzer will fail to give auto completion hints if a procedural macro fails to parse its content. This situation happens when a programmer is typing.

For instance, this is the parser to parse `let` statement:

```rust
fn parse_let(input: ParseStream) -> Result<(Pat, Expr)> {
    input.parse::<Token![let]>()?;
    let pat: Pat = input.parse()?;
    input.parse::<Token![=]>()?;
    let expr: Expr = input.parse()?;
    input.parse::<Token![;]>()?;
    Ok((pat, expr))
}
```

When a programmer is typing, he will get no hints.

```rust
my_macro! {
    // no auto completion hints, because the statement isn't complete,
    // which caused macro parsing to fail.
    //
    // expect completed: `let a = some + expression;`
    let a = |;
    //      ^____ the cursor is here
}
```

So it should be fine if there is a parser who could parse incomplete expressions, which can check the syntax loosely, help the macro continue to parse as possible instead of giving error.

And I'm willing to implement this, but I don't know how.

**Comment by dtolnay** [comment]
I would be interested to see this implemented in a separate crate to begin with. That would help decide whether I want it in this library (currently probably not).
