### ISSUE TITLE
Potential false-positive of rustdoc::broken_intra_doc_links lint

### ISSUE THREAD

**Issue by Techassi** [dtolnay/syn#1733]
It seems that the bug fixed in 7bfef4b2befee954bc002724c8331612fed3d47f re-appeared. I tested with both Rust `1.80.1` and `1.81.0`.

```rust
use syn::Ident;

/// Do stuff with [`Ident`].
#[allow(dead_code)]
fn do_stuff(_: Ident) {}
```

The error message only appears when running `cargo doc --document-private-items` (just `cargo doc` is fine). Previously, this didn't cause any hiccups. What is the suggested solution here?

<details>
<summary>Error Message</summary>

```
warning: `Ident` is both a function and a struct
 --> ../bug.rs:3:21
  |
3 | /// Do stuff with [`Ident`].
  |                     ^^^^^ ambiguous link
  |
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
help: to link to the function, add parentheses
  |
3 | /// Do stuff with [`Ident()`].
  |                          ++
help: to link to the struct, prefix with `struct@`
  |
3 | /// Do stuff with [`struct@Ident`].
  | 
```

</details>

**Comment by dtolnay** [comment]
I think in order to be compatible with `--document-private-items` you would need to write ``[`struct@Ident`]`` as suggested in the error message.

**Comment by Techassi** [comment]
Alright, thank!
