### ISSUE TITLE
Unable to create `Token` trait object

### ISSUE THREAD

**Issue by SpectralPixel** [dtolnay/syn#1735]
I am currently attempting to implement a function which accepts a token as an input, inserts that token into a TokenStream (using quote), and then returns said TokenStream.

Here's a (failing) example of what this code would look like:
```
extern crate syn; // 2.0.77
extern crate quote; // 1.0.37
extern crate proc_macro2; // 1.0.86

fn add_token(t: dyn syn::token::Token) -> proc_macro2::TokenStream {
    quote::quote!{
        // 4  + 2
        // 4  - 2
        // 4  * 2
        // 4  / 2
        // 4 >> 2
        // 4 << 2
        // 4  & 2
        // 4  | 2
        // 4  ^ 2
           4 #t 2
    }
}
```
[(Playground Link)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3cceb70bfb3e10cd31a241d59d475edc)

Currently, this code doesn't compile due to the trait not being object safe. Could it be possible to make the trait object safe (or why can it not?)? Is there any workaround that I could use to make this code work?

Thanks for your consideration. :)

**Comment by dtolnay** [comment]
This is not an intended use of syn's Token trait, but you could instead define your own Token trait implemented for any set of types you choose, or simply use `TokenStream` or `impl ToTokens`.
