### ISSUE TITLE
Somehow prevent the creation of invalid ASTs

### ISSUE THREAD

**Issue by mystor** [dtolnay/syn#177]
This was mentioned as a pitfall in https://github.com/serde-rs/serde/pull/980#issuecomment-313534403.

Alternatively, we could somehow provide an API for correcting an AST into a valid AST which we could potentially run before tokenifying each AST node.

Some examples of things which would be nice to prevent include:
1. Missing tokens in structs which are necessary for the output
2. Missing parentheses or none-delimited spans which make the generated tokens parse incorrectly.
3. Maybe more things?

**Comment by Arnavion** [comment]
Yes, I hit this in a few different ways with `Generics` and `ImplGenerics` while porting my own proc macro:

- Had to explicitly set the `Generic`'s `lt_token` and `gt_token` to `Some(Default::default())` because the emitted `ImplGenerics` would not have `<>` around its constituents if the `DeriveInput` didn't have any generics.

- Had to use `push_default()` + `push_trailing()` to add lifetimes to the `Generics` instead of `push_next()` because it would not emit the comma between `lifetimes` and `ty_params` if the `DeriveInput` already had existing `ty_params`.

- Had to set `colon_token` to `Some(Default::default())` when constructing a `TyParam` with `bounds` because it would not have the colon otherwise.

**Comment by dtolnay** [comment]
I would prefer not to make the user take action to convert an invalid AST into a valid AST. I think it would be best for ToTokens to do the right thing by inferring Default::default() where necessary.

**Comment by mystor** [comment]
I think my current idea which I might try to get some time to try out this weekend would be to make our `ToTokens` implementations more fault tolerant, so that they handle "doing the right thing" to make sure that if we re-interpret the tokens which we generate they have the same semantic meaning as our original AST, which might involve inserting parens or none-delimited spans around ambiguous expressions to make them parse correctly, and creating default-spanned tokens when needed.

It might also be nice to have a helper method and corresponding traits in syn's root for just creating a defaulted token, like `syn::tok()` (and perhaps `syn::stok(Span)` which can be used to make constructing AST nodes nicer to look at (as you don't need to explicitly default construct every token you don't care about the span for). 

If we do this we may want to also change some of the `Option<Token>` fields to just be `Token`, and have them be ignored when we don't need them, and defaulted when they don't actually appear in the source, but that is a bit of a more aggressive change.

**Comment by alexcrichton** [comment]
Changing `ToTokens` sounds ok to me. The logic has to live *somewhere* to fix these up, and canonicalizing seems relatively harmless.

**Comment by alexcrichton** [comment]
Note though that fixing up `ToTokens` goes directly against https://github.com/dtolnay/syn/issues/162, as the whole point of the feature would be to pull tokens out of thin air!

**Comment by mystor** [comment]
> Note though that fixing up ToTokens goes directly against #162, as the whole point of the feature would be to pull tokens out of thin air!

I think the fundamental distinction between this and #162 is that the only time these tokens should be coming out of thin air is when they are created by the procedural macro. We should continue to not pull tokens out of thin air in the parser for sure, and we should make sure that every token which we parse in the parser has its span reflected in the output, but I think it's reasonable to perform AST fixup as we generate the AST to add in these tokens.

For example, consider custom derives which want to add `Where` clauses. They shouldn't have to worry whether or not the original AST included any where clauses, and should just be able to add their clauses to the list. `syn` can then figure out if it needs to fabricate a `where` token for the procedural macro.

**Comment by alexcrichton** [comment]
Oh I'm definitely in favor of making `ToTokens` much more lenient, but I think we should reinterpret #162 as "during parsing"

**Comment by dtolnay** [comment]
Yep, #162 refers to during parsing.
