### ISSUE TITLE
Regression on `Breaking change to Generics::lifetimes in v2.0.73 #1718` if `attr(docsrs)`

### ISSUE THREAD

**Issue by rscarson** [dtolnay/syn#1789]
Relates to https://github.com/dtolnay/syn/issues/1718, and https://github.com/RustCrypto/formats/issues/1617

If `--cfg=docsrs` is passed to the compiler, the issue described in #1718 occurs:

```
error[E0502]: cannot borrow `generics.params` as mutable because it is also borrowed as immutable
  --> der_derive-0.7.3\src\sequence.rs:61:29
   |
57 |           let lifetime = generics
   |                          --------
   |                          |
   |  ________________________immutable borrow occurs here
   | |
58 | |             .lifetimes()
   | |________________________- a temporary with access to the immutable borrow is created here ...
...
61 |               .unwrap_or_else(|| {
   |                               ^^ mutable borrow occurs here
62 |                   let lt = default_lifetime();
63 | /                 generics
64 | |                     .params
   | |___________________________- second borrow occurs due to use of `generics.params` in closure
...
67 |               });
   |                 - ... and the immutable borrow might be used here, when that temporary is dropped and runs the destructor for type `impl Iterator<Item = &LifetimeParam>`
   ```

**Comment by dtolnay** [comment]
Building syn (and any other library) with `--cfg=docsrs` passed to the compiler is not supported. That flag is specifically only intended for passing to rustdoc.

**Comment by rscarson** [comment]
> Building syn (and any other library) with `--cfg=docsrs` passed to the compiler is not supported. That flag is specifically only intended for passing to rustdoc.

I would at least point out that This macro: <https://github.com/dtolnay/syn/blob/91ffc5c4c53e1b3ab961dd3bd7e3fcf79d15cb7c/src/macros.rs#L174>

Called here: <https://github.com/dtolnay/syn/blob/91ffc5c4c53e1b3ab961dd3bd7e3fcf79d15cb7c/src/generics.rs#L106>

Replaces the return type if docsrs is on to a type who's drop behavior differs from the real type

At the very least that is an error in the documentation
