### ISSUE TITLE
Factor out loop label parsing

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#18]
Currently we parse labels as lifetimes, then always need to do `lt.map(|lt| lt.ident)`. Let's factor this into a separate `label` parser.

**Comment by dtolnay** [comment]
Fixed in 8b07f37e6b28d57c3688a16b61293936a573f9c5. @gregkatz this may be useful to you.

**Comment by gregkatz** [comment]
Definitely useful. Thanks, @dtolnay. I'm working on a PR for break, continue and return. Hoping to get that in tomorrow.
