### ISSUE TITLE
Public function to parse a pm2::TokenStream to a Synom without round-tripping through pm::TokenStream

### ISSUE THREAD

**Issue by Arnavion** [dtolnay/syn#181]
Starting with a `syn::Attribute` like `#[foo(baz::quux)]`, I want to parse the `baz::quux` part as a `syn::Ty`

If I'm reading the API correctly, the flow should be be:

```rust
let attr: syn::Attribute = syn::parse_str("#[foo(baz::quux)]").unwrap();
let tt /*: syn::TokenTree */ = attr.tts[0];
let tt /*: proc_macro2::TokenTree */ = tt.0;
if let proc_macro2::TokenNode::Group(proc_macro2::Delimiter::Parenthesis, tts) = tt.kind {
    /* `tts: proc_macro2::TokenStream` represents `baz::quux` */
    let ty: syn::Ty = /* ??? */;
}
```

Since [the function to go from `proc_macro2::TokenStream` to `T: Synom`](https://github.com/dtolnay/syn/blob/c1b76f51/src/lib.rs#L154) isn't public, it seems I have to convert `tts` to a `proc_macro::TokenStream` using its `From<proc_macro2::TokenStream>` impl, only for `syn::parse()` to convert it back.

I do see this back-and-forth will be cheap with the unstable API since it just wraps and unwraps the original `proc_macro::TokenStream` without any processing. The stable API roundtrips it through a `String`, though the stream will be small enough in my case to not make this a big deal.

Would it make sense to export a public function to parse a `proc_macro2::TokenStream` directly?

---

On IRC @mystor suggested using `Cursor` directly as an alternative, which I think means the `???` bit is:

```rust
let buffer = SynomBuffer::new(tts);
let cursor /*: Cursor */ = buffer.begin();
let ty: syn::Ty = Synom::parse(cursor).unwrap();
```

**Comment by dtolnay** [comment]
Related: we shouldn't have so many different types of token tree. #205

**Comment by dtolnay** [comment]
This will be `syn::parse2` in the upcoming release.
