### ISSUE TITLE
Attribute helpers

### ISSUE THREAD

**Issue by theduke** [dtolnay/syn#188]
Almost every custom derive implementation will need to work with attributes.

I think working with them is really unergonomic right now though.
It often requires nested matches of 3 levels, which is quite cumbersome.

I'd really love some helper functions that make finding and identifying attributes easier.

If maintainers are ok with the idea, I'd start working on a PR.

**Comment by dtolnay** [comment]
I would prefer for this to be handled by other crates, for example [`darling`](https://github.com/TedDriggs/darling). There are a lot of design tradeoffs around how to handle attributes and different crates may be able to optimize for different use cases. This is especially true now that https://github.com/rust-lang/rust/issues/34981 intends to allow arbitrary tokens inside of attributes.
