### ISSUE TITLE
Expression followed by a tuple is parsed as a function call

### ISSUE THREAD

**Issue by plietar** [dtolnay/syn#189]
`syn` parses the following snippet as a function call, where `loop { }` is the function and `0` and `1` are the arguments, which differs from rustc, which parses that as two expressions, a loop and a tuple.
```rust
loop { }
(0, 1)
```

rustc will treat it as a function call only if brackets are put around the first expression , eg `(loop { }) (0, 1)`.

**Comment by mystor** [comment]
Is this a bug with syn 0.11 (the current version on crates.io), or with the current master version? 

The version of syn on master right now should handle this case correctly I think, while syn 0.11 doesn't make any effort to parse precedence correctly.

**Comment by plietar** [comment]
Both master and 0.11.11 have this issue

**Comment by mystor** [comment]
I did some fiddling and I am pretty sure that syn is parsing that snippet correctly right now. When you write a snippet like:

```rust
loop {}
(1, 2)
```

The way it is parsed depends on the current parsing environment. For example, if you're in a block (such as a function body etc.) you're in a Statement parsing environment which means that the loop {} will be interpreted as a semicolonless expression statement, and the (1, 2) will not be appended. For example the expression:

```rust
{
    loop {}
    (1, 2)
}
```
is parsed on master as (Debug output simplified slightly to avoid unnecessary details):
```rust
Expr {
    node: ExprBlock {
        block: Block {
            stmts: [
                Expr {
                    node: ExprLoop {
                        body: Block {
                            stmts: []
                        },
                        label: None,
                    }
                }
                Expr {
                    node: ExprTup {
                        args: [
                            Lit(1),
                            Lit(2)
                        ]
                    }
                }
            ]
        }
    }
}
```

While putting the `loop {} (1, 2)` in an expr-only position produces different results:

```rust
let x = loop {} (1, 2);
```
parses to
```rust
Local {
    pat: Ident(
        PatIdent {
            mode: ByValue(Immutable),
            ident: Ident {
                sym: Term("x"),
            },
            subpat: None,
        }
    ),
    ty: None,
    init: Some(
        Expr {
            node: ExprCall {
                func: Expr {
                    node: ExprLoop {
                        body: Block {
                            stmts: []
                        },
                        label: None,
                    }
                },
                args: [
                    Lit(1),
                    Lit(2)
                ]
            }
        }
    )
}
```

You can see that this matches the behavior of rustc in this playground link: https://play.rust-lang.org/?gist=f4cc983e93a4eac0c3b481a3eaaa9dd6&version=stable

**Comment by plietar** [comment]
You are correct, sorry for the noise.

I was using 0.11 in my code in a block context, and ran into this issue.
I only tried a minimal example with master, using `parse_str::<Expr>`, and didn't consider how that might affect parsing.

Thanks for the quick response !
