### ISSUE TITLE
Ultimate test of parsing

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#19]
Write a test to:

1. Iterate through Rust files in a directory
2. Parse using `syn` >> print using `syn` >> parse using `syntex`
3. Parse the original using `syntex`
4. Assert that the `syntex` AST from 2 and 3 are identical

I think this would give us more confidence in the parser than any unit test suite we could write, and it is also far easier to implement than individually testing every parser element. Once we make more progress on #4 we could run this test against a large repo like the full rustc source code.

cc @gregkatz. I plan to work on this today or tomorrow. In the meantime you don't have to worry about unit testing parsers you write (unless it is useful to you in implementing them). Let's focus on flying through #4 without tests and leave testing to this one.

**Comment by gregkatz** [comment]
Sure thing. I'll skip the unit tests in the future.

**Comment by dtolnay** [comment]
Added in 4a51dc70fc60b4030753ab6cfdf06e23eb522d63. Any *.rs file in the [`tests/cases` directory](https://github.com/dtolnay/syn/tree/4a51dc70fc60b4030753ab6cfdf06e23eb522d63/tests/cases) will be tested as outlined above.
