### ISSUE TITLE
Add the ability to apply macro_rules to the ast

### ISSUE THREAD

**Issue by jrmuizel** [dtolnay/syn#191]
This would be useful for cbindgen to get access to macro_rules defined types now that -Zunstable-options --pretty=expanded is gone from stable rust.

**Comment by mystor** [comment]
I think this would be best done in a separate crate. I don't think that it would need access to any unstable `syn` implementation details.

I don't think it would be possible right now to make a macro_rules! expander which respects hygiene right now, as the output will be a simple tokenstream without macro expansion information on it, so there will have to be that limitation. IIRC `--pretty=expanded` also had that limitation, as it generated raw text, so it shouldn't be too big of a deal.

**Comment by jrmuizel** [comment]
Does syn support parsing macro_rules! definitions to something more structured than a token stream?

**Comment by mystor** [comment]
No, it does not but there is nothing which is preventing it from being implemented outside of `syn`.
We could also potentially implement it within `syn`, but I would probably want it behind a feature flag so most people don't need to build it. Depends on how much of a build time impact it has.

**Comment by dtolnay** [comment]
Closing because I don't plan to prioritize this and it is not applicable to the proc macro use case. I would be interested in the cbindgen folks or anyone else pursuing this in a separate crate.
