### ISSUE TITLE
Allow rust keywords as attribute words/keys

### ISSUE THREAD

**Issue by kestred** [dtolnay/syn#196]
I've been writing some derive-based macros, and I found unexpected behavior while parsing an attribute.

Syn will fail to parse a `DeriveInput` if the input's attributes contain a rust keyword.

Some strawman-ish examples:

```rust
#[derive(RepeatStruct)]
#[repeat(for("Hello", "World"))]
struct Input {}

#[derive(SQLExample)]
#[sql(where = "expr IS TRUE")]
struct Thing {}
```

Is this intended behavior?  

If it is undecided, then IMO it'd be great to have it allowed; to me it doesn't seem that the normal rust keywords would ever gain special meaning in core rust attributes.  

If it is a bug, how I could help fix it?

**Comment by mystor** [comment]
Can you test this with the `master` version of `syn`? A lot has changed in how we parse rust code since the last time we made a release, and the new version potentially doesn't have this problem (unfortunately it also has a very different API and hasn't been published yet because it hasn't been polished enough).

**Comment by kestred** [comment]
Just spent some time attempting to update to use the new version--- its turning into quite a lot of work, so that'll wait till the API is more polished.

Instead, hopefully I'll be able to verify with a minimal test case soon.

This should be enough to set it off.
```
#[proc_macro_derive(Any)]
pub fn derive_any(input: TokenStream) -> TokenStream {
    let s = input.to_string();
    let ast = syn::parse_derive_input(&s).unwrap();
    let gen = quote!{};
    gen.parse().unwrap()
}
```

```
#[derive(Any)]
#[any(where = "true"))
struct Test {
}
```

**Comment by mystor** [comment]
I tested this with the master version of syn, and it parses just fine :-).
