### ISSUE TITLE
How to get function name?

### ISSUE THREAD

**Issue by SeunLanLege** [dtolnay/syn#197]
Actually i have a lot of problems, but the most immediate one is getting the function name from `FnDecl`, 
i'm stumped primarily because i'm using the master release (the undocumented one) not cargo release.

```rust

#[proc_macro_attribute]
pub fn service(attribute: TokenStream, function: TokenStream) -> TokenStream {
	let Item { attrs, node } = syn::parse(function)
		.expect("failed to parse tokens as a function");
	let ItemFn {
		ident,
		vis,
		unsafety,
		constness,
		block,
		decl,
		..
	} = match node {
		ItemKind::Fn(item) => item,
		_ => panic!("Whoops, try again. this time, with a function"),
	};
	
	println!("Ident! {:?}", block.stmts);
	
	// return the attribute for now, until i figure out the processing for the actual input.
	attribute
}
```

what am i trying to do?

get the function name and body.

replace it with a struct declaration and trait implementation.

pseudo code

```rust

#[proc_macro_attribute]
pub fn service(attribute: TokenStream, function: TokenStream) -> TokenStream {
	let Item { attrs, node } = syn::parse(function)
		.expect("failed to parse tokens as a function");
	let ItemFn {
		ident,
		vis,
		unsafety,
		constness,
		block,
		decl,
		..
	} = match node {
		ItemKind::Fn(item) => item,
		_ => panic!("#[service] can only be applied to functions"),
	};
	
	let output = qoute! {
           struct #decl.name;
           impl service for #decl.name	 {
            fn invoke(req: Request, res: Response) -> {
              #block
             }
         }
	
	output.parse().unwrap()
}
```

side note: I noticed debug isn't implemented for many structs/enums in master.

**Comment by mystor** [comment]
To get `Debug` impls, add the `extra-traits` feature.

The `item` object which you destructured from `ItemKind::Fn(item)` is of type `ItemFn`: https://github.com/dtolnay/syn/blob/d5e985994ca58039ea22d6fde8acb821d9058f2f/src/item.rs#L64-L72. The name is in the field `ident`.

If you want documentation for the master version of syn, you can try running `cargo doc` in your project, and all of your dependencies will also be documented (including `syn`), so you can read the docs there :-).

**Comment by SeunLanLege** [comment]
thanks, adding `extra-traits` fixed my debug problem. 

i was able to print the Ident object

```rust
Ident {
  sym: Term(test(80)),
  span: Span(
    Span(
      Span { lo: BytePos(4628), hi: BytePos(4632), ctxt: #0 }
      )
   )
}

```

i'm unsure what this means or how to get the function name out of it.

**Comment by SeunLanLege** [comment]
Oh never mind i looked through the code and found it has `AsRef<str>` implemented.

calling `ident.as_ref()` yields the function name. thanks!
