### ISSUE TITLE
Consider hosting master branch docs somewhere

### ISSUE THREAD

**Issue by mystor** [dtolnay/syn#198]
Issues like #197 could be easily fixed by providing people who want to use the unstable `master` branch API for syn with a place to read the docs.

It's possible for them to generate & read the docs locally with `cargo doc --open`, but it would be even easier if we didn't have to ask them to do that.

**Comment by dtolnay** [comment]
Let's close this for now because hopefully we never have another release that is this different from the previous one, but we can revisit if necessary leading up to the next major version.

**Comment by mystor** [comment]
Yeah, I hope that situation doesn't happen again ^.^ - sounds good.
