### ISSUE TITLE
Getting the type implementation

### ISSUE THREAD

**Issue by faulesocke** [dtolnay/syn#199]
Hey there,

just wanted to ask if it's possible to access the type implementations (functions implemented on the type) in some way? Basically what I need is a list of all functions (not trait methods) implemented for the type and their signature.

Best regards!

**Comment by mystor** [comment]
No it is not possible to do this - when in a procedural macro the only information which is provided to the procedural macro are the input tokens from the item which the attribute is on, or in the case of a `foo!` style macro, the input tokens passed between the parentheses.

We don't have access to other information from the compiler, such as the resolved types of fields or the methods defined on a particular object. In fact, in the compiler this information hasn't been computed yet by the time the procedural macro is invoked (as when attributes are invoked, the item hasn't been defined yet, and when custom derives are invoked, you can even do things such as add more inherent methods).
