### ISSUE TITLE
Parse error with unsafe expression

### ISSUE THREAD

**Issue by eqrion** [dtolnay/syn#202]
Tested with syn 0.11.11.
```rust
// test.rs
pub fn test() {
    for i in 1 .. unsafe { 100 } {
        println!("{:?}", i);
    }
}
```
```rust
// main.rs
extern crate syn;

fn main() {
    syn::parse_crate(include_str!("test.rs")).unwrap();
}
```
Output:
```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "failed to parse crate: \"pub fn test() {\\n    for i in 1 .. unsafe { 100 } {\\n        println!(\\\"{:?}\\\", i);\\n    }\\n}\\n\""', /checkout/src/libcore/result.rs:906:4
```
Changing `unsafe { 100 }` to be just `100` fixes the issue.

The attached rust (`test.rs`) compiles fine (with rustc 1.22 nightly), so I think it should be able to be parsed by `syn`.

Thanks for the great library!

**Comment by mystor** [comment]
The problem here is that we parse `unsafe {}` in the same parser as we parse `{}`, and in that position a normal, non-unsafe, block would not be allowed to be parsed, but an unsafe block would.

We'll need to split up the parsers for `unsafe {}` and `{}` so that we don't have to guard both.

**Comment by eqrion** [comment]
Thanks!
