### ISSUE TITLE
Upstream "assert parses" method in proc_macro, use it for errors

### ISSUE THREAD

**Issue by alexcrichton** [dtolnay/syn#210]
We should have a method of providing very nice error messages about Rust code, ideally using `proc_macro` itself with a stable interface

**Comment by dtolnay** [comment]
This is not something I intend to pursue myself, so closing in favor of #47.

A procedural macro that has tokens that Syn failed to parse as an expression can trigger an error message from the compiler against that input by expanding to:

```rust
macro_rules! assert_expr {
    ($e:expr) => {
        compile_error!{"unexpectedly succeeded"}
    };
}
assert_expr! {
    /* tokens from the caller */
}
```
