### ISSUE TITLE
Remove proc-macro as a public dependency

### ISSUE THREAD

**Issue by alexcrichton** [dtolnay/syn#211]
Makes it easy to panic!

**Comment by alexcrichton** [comment]
This may or may not be easy, but worth thinking about if we can reduce panics in "binary mode"

**Comment by mystor** [comment]
A big problem here will be figuring out what the story is for these features. If we make using the proc-macro API being a feature, then a dependency activating a feature can cause your program to panic somewhere else, while if we make using the proc_macro2 API be a feature, then if we turn it on suddenly we don't get span information which works well.

We could also have enums which we use to allow building against both backends at the same time, but I think that might have unacceptable perf impact.

**Comment by mystor** [comment]
I think this should be fixed now by the proc_macro2 autodetection work.
