### ISSUE TITLE
Update AST to hold extern types

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#230]
https://github.com/rust-lang/rust/issues/43467

```rust
extern {
    type T;
}
```

**Comment by mystor** [comment]
As part of this, we should probably also update the sha1 of the rust-lang repo which we run tests against if we can. Unfortunately, the syntex hasn't been being kept up to date so it won't support all of the features which we would want to support :-/.

Perhaps we should consider updating the tests to instead build against nightly rust & use libsyntax directly? We'd have to make them run periodically & not fail CI if they don't pass like clippy probably.

**Comment by dtolnay** [comment]
I agree. I filed #232 to follow up with moving to libsyntax.
