### ISSUE TITLE
Change syntax of auto traits

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#238]
The syntax has changed from:

```rust
trait Send {}
impl Send for .. {}
```

to:

```rust
auto trait Send {}
```

**Comment by mystor** [comment]
Do we still want to parse the old-style auto trait syntax, or should we only support parsing the new style syntax?

**Comment by dtolnay** [comment]
From the discussion in https://github.com/rust-lang/rust/pull/45247 it sounds like they intend to remove usage of the old form in rust-lang/rust as soon as stage0 is able to parse the new form, which may or may not happen before syn 0.12 is done. I would definitely prefer to remove the old form from the AST. The round trip test still needs to deal with the old form, so I leave it up to you whether we blacklist all the files containing `impl for ..` or parse it into some sentinel `Item::Macro` which is recognized and treated specially by `ToTokens for ItemMacro`.

```rust
// input tokens
impl Send for .. {}

// parsed into Item::Macro as if they had been this
syn::verbatim! {
    impl Send for .. {}
}

// printed by ToTokens
impl Send for .. {}
```
