### ISSUE TITLE
Simplify the Debug representation of newtype variants containing type of the same name

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#250]
For example the `{:#?}` for `syn::parse_token_trees("(a b)")` is currently:

```
[
    Delimited(
        Delimited {
            delim: Paren,
            tts: [
                Token(
                    Ident(
                        Ident(
                            "a"
                        )
                    )
                ),
                Token(
                    Ident(
                        Ident(
                            "b"
                        )
                    )
                )
            ]
        }
    )
]
```

The `Delimited(Delimited { ... })` and `Ident(Ident(...))` should be cut down to `Delimited { ... }` and `Ident(...)` by having the outer enum not add a layer of wrapping when the inner type has the same name as the variant. Same thing applies everywhere else we use this pattern.

**Comment by mystor** [comment]
IIRC I did this with a couple of types in #204, but we should definitely do it more pervasively.
