### ISSUE TITLE
Verbatim variants as an escape hatch

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#251]
I am not totally sold on this idea but it would be a neat way to deal with new Rust syntax that is added between syn releases. Basically anywhere a macro is printed, if the macro path is `syn::verbatim!` then only whatever tokens are inside of the macro are printed.

```rust
// AST contains this
syn::verbatim! {
    impl Send for .. {}
}

// printed by ToTokens
impl Send for .. {}
```

**Comment by mystor** [comment]
Why not have a dedicated type for this in the AST rather than using a macro type? We could have `TypeVerbatim`, `ExprVerbatim` and `ItemVerbatim` as escape hatches. Each would just hold a TokenStream internally and when ToTokens-ed would dump it out. We'd never parse them but if you wanted to build them into your AST you could.

**Comment by dtolnay** [comment]
That sounds good to me. Would you prefer separate types like ExprVerbatim and ItemVerbatim that may even contain a Vec\<Attribute> as well as tokens, or go for the less consistent but simpler way of holding a TokenStream directly?

```diff
  pub enum Item {
      ExternCrate(ItemExternCrate),
      ...
      Macro(ItemMacro),
+     Verbatim(TokenStream),
  }
```

**Comment by mystor** [comment]
I think that either approach is OK, but I do like the fact that the more consistent ExprVerbatim and ItemVerbatim types would let Fold/Visitor implementations visit these particular items/expressions explicitly.

**Comment by dtolnay** [comment]
That is a great point. Let's do it that way.

**Comment by dtolnay** [comment]
Added in 2ae520adce62e30e9f7be5280d08080ad0360028.
