### ISSUE TITLE
Get the span of an Expr

### ISSUE THREAD

**Issue by antoyo** [dtolnay/syn#267]
Hi.
Is there an easy way to get the Span of an Expr?
That is without having to use pattern matching on node and getting the span manually.
Thank you.

**Comment by mystor** [comment]
No, currently there is no easy way to extract the span of an individual AST node, as spans are only stored on the tokens at the leafs of the AST. It might be possible in the future to add a `fn span() -> Option<Span>` method which uses the `Span.join()` method to try to make a span for the full node, but we don't support it right now. (We'd also need https://github.com/alexcrichton/proc-macro2/pull/36 to merge before we could do that).

**Comment by antoyo** [comment]
I started to write such a function [here](https://github.com/antoyo/tql/blob/master/tql_macros/src/ast.rs#L404-L484) even though it is not completely accurate (I don't merge `Span`s yet).

**Comment by mystor** [comment]
I think we would probably want to generate that function, if we decided we wanted it, behind a feature flag and using syn_codegen so we can avoid manually writing large error-prone match statements.

cc @dtolnay to see if we'd want to have something like that in syn behind a feature gate

**Comment by dtolnay** [comment]
Seems reasonable! I like the idea of the implementations being generated.

**Comment by dtolnay** [comment]
This has been added in [`syn::spanned::Spanned`](https://github.com/dtolnay/syn/blob/4cf7db8185d0805be5ffc414397bc546b3ce4b2d/src/spanned.rs).
