### ISSUE TITLE
Parse an entire crate

### ISSUE THREAD

**Issue by neon64** [dtolnay/syn#268]
Is it within the scope of this library to support parsing an entire crate? ie: in a similar fashion to the Rust compiler itself, it would recurse through all `mod` statements, and if they lack a body, search the filesystem for a source file in the right place.

As far as I understand, this was something syntex used to do, although I guess with proc_macro 2.0 it is rendered more or less redundant, as you don't need to generate code in build scripts. Nevertheless, it would be beneficial for my use case.

I'll probably go and implement this myself as a wrapper to `parse_file`, but it would be great to know if there is a better way to do this.

**Comment by dtolnay** [comment]
I would prefer for this to be handled by a different crate, possibly built on top of `parse_file`. This crate is a **parser** for Rust syntax. I would like to steer away from packing in more **compiler** functionality like traversing the filesystem and ascribing meaning to `mod` statements and interpreting `#[path = "..."]` attributes.

**Comment by dtolnay** [comment]
Take care, because I believe correctly parsing an entire crate involves a *lot* of compiler functionality. You would also need to support specifying the set of Cargo features that are being used, the target, the platform, the architecture, maybe other things, and implement the logic for `cfg` expressions, and implement macro expansion.

```rust
macro_rules! mod_neon64 {
    ($feature:tt) => {
        #[cfg(feature = $feature)]
        #[cfg_attr(not(unix), path = "not_unix.rs")]
        #[cfg_attr(all(target_os="macos", target_arch = "powerpc"), path = "macos.rs")]
        mod neon64;
    }
}

mod_neon64!("neon64");
```

**Comment by mystor** [comment]
FYI i have written a crate for doing this in the past as [part of rust-cpp](https://github.com/mystor/rust-cpp/tree/ed6ea9db8b85b2e4a4c828ea535f4c46d09a8cac/cpp_synmap), and I've been working a bit on porting it to the new syn. I'll comment in here when I put it up somewhere.

(NOTE: I don't handle cfgs or macro expansion, but it still works well in most situations)

**Comment by clarcharr** [comment]
I actually already made a crate for this: [collapse-crate](https://docs.rs/collapse-crate).

Haven't actually updated to the latest version of syn though.

**Comment by neon64** [comment]
@dtolnay, thank you for outlining some of the issues with the functionality I'm trying to achieve. I didn't even consider that a macro could generate a `mod` statement which would then be included, though I imagine doing so would be somewhat unorthodox..
Is it the same with macros 2.0 though (ie: both `macro` and `proc_macro`)? I thought modules had to be resolved beforehand, as you now import macros with `use` instead of `#[macro_use]`

**Comment by dtolnay** [comment]
I believe macros 2.0 (both `macro` and `proc_macro`) can expand to `mod` statements.

```rust
#![feature(decl_macro)]

macro neon64() {
    mod m;
}

neon64!();
```

(Not macros 2.0 but) here are some instances of this [in cargo](https://github.com/rust-lang/cargo/blob/bda218fa62600193702f9a4d5eb7d325ce7328b5/src/bin/cargo.rs#L140) and [in rustc](https://github.com/rust-lang/rust/blob/3dfbc88a626625be01e112da11ec367e2fc71bb3/src/librustc_back/target/mod.rs#L81). I only searched for `mod $` meaning the module name is a macro variable -- I am sure there are lots more where a mod with a fixed name is declared in a macro, just don't know how to search for those.

As @mystor wrote, you can probably get pretty far by not handling any of these cases. You just can't rely on it to be exactly right.
