### ISSUE TITLE
ExprTupField allows any literal

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#270]
The parser for ExprTupField accepts `punct!(.)` followed by `syn!(Lit)`, which is too lenient. It should allow integer literals only.

```rust
extern crate syn;

fn main() {
    println!("{:#?}", syn::parse_str::<syn::Expr>("x.\"s\"").unwrap());
}
```

**Comment by mystor** [comment]
I consider this an over-leniency bug, which isn't too big of a deal IMO unless it conflicts with actual valid rust code. Checking this is going to be somewhat expensive, and I think I'd rather not do it unless it causes real problems when parsing code.

**Comment by dtolnay** [comment]
I redesigned it like this in 85b69a46e89c4ec9c4c3db9b0dd43ce1487b29e4. I believe macros pretty much never care about the difference between named struct fields `self.x` and unnamed tuple struct fields `self.0` and would just prefer to treat them uniformly, so let's make that easy.

```rust
pub struct ExprField {
    pub base: Box<Expr>,
    pub dot_token: Token![.],
    pub member: Member,
}

pub enum Member {
    Named(Ident),
    Unnamed(Index),
}

pub struct Index {
    pub index: u32,
    pub span: Span,
}
```
