### ISSUE TITLE
Parse 2.0 `macro` syntax

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#271]
The current syntax looks like [this](https://github.com/rust-lang/rust/blob/a3a7203e2c9ed30a501da86f3fa1f9efe707ac94/src/librustc_mir/transform/mod.rs#L155-L185).

```rust
pub macro run_passes($tcx:ident, $mir:ident, $def_id:ident, $suite_index:expr; $($pass:expr,)*) {{
    /* same as usual */
}}
```

**Comment by dtolnay** [comment]
I implemented the bare minimum to pass tests in 500d832545075a1f2ffbb07997daa766ac9b38da, will need to revisit what these look like in the AST.

**Comment by mystor** [comment]
I think that your implementation is fine for now. We can come back to it & clean up the AST once the AST used by rustc stabilizes some more.

**Comment by dtolnay** [comment]
I kept the AST but restricted the grammar in e0824038665c8f04dc677e906fa220426d356d6f -- the arguments must be parenthesized and the body must be braced.
