### ISSUE TITLE
Parsing enums with constant variables fails

### ISSUE THREAD

**Issue by Slabity** [dtolnay/syn#277]
The following is valid rust code:

```rust
const val: isize = 3;

enum Test {
    A = 1,
    B = 2,
    C = val
}
```

However, I get the following error attempting to parse (using the `num-derive` crate and `ToPrimitive`):

`"failed to parse macro input: \"pub enum Test { A = 1, B = 2, C = val, }\"`

This occurs in `syn::parse_macro_input`

**Comment by dtolnay** [comment]
It works when I tried it with syn 0.11.11. Can you share some code that reproduces the error?

```rust
extern crate syn;

fn main() {
    let source = "pub enum Test { A = 1, B = 2, C = val, }";
    println!("{:#?}", syn::parse_derive_input(source).unwrap());
}
```

**Comment by dtolnay** [comment]
It looks like num-derive is using syn 0.7 -- maybe file an issue over there asking them to upgrade.

**Comment by Slabity** [comment]
@dtolnay - Yep, that looks like the issue. Thanks
