### ISSUE TITLE
Examples for syn + proc_macro_attribute

### ISSUE THREAD

**Issue by danguafer** [dtolnay/syn#286]
I started reading about the lib today and I've been struggling to use syn with proc_macro_attribute. I would love to have an example for that.

**Comment by dtolnay** [comment]
Thanks for reporting this! I agree we should provide an example. For now, check out [any of these crates](https://github.com/search?utf8=%E2%9C%93&q=syn+proc_macro_attribute&type=Code).

**Comment by dtolnay** [comment]
I added the following example. https://github.com/dtolnay/syn/tree/master/examples/trace-var

```rust
#[trace_var(p, n)]
fn factorial(mut n: u64) -> u64 {
    let mut p = 1;
    while n > 1 {
        p *= n;
        n -= 1;
    }
    p
}
```

```
p = 1
p = 8
n = 7
p = 56
n = 6
p = 336
n = 5
p = 1680
n = 4
p = 6720
n = 3
p = 20160
n = 2
p = 40320
n = 1
```

**Comment by danguafer** [comment]
Thanks for the effort! I learned some nice tricks with this example.
