### ISSUE TITLE
syn's irc channel or any other instant messaging?

### ISSUE THREAD

**Issue by notdanilo** [dtolnay/syn#287]
Hey! Does the project have any instant messaging group? I have small questions that maybe wouldn't be suitable for new issues.

**Comment by dtolnay** [comment]
There isn't a dedicated channel yet but #rust on [irc.mozilla.org](https://wiki.mozilla.org/IRC) tends to be pretty knowledgeable about syn -- plenty of people there have used it heavily and can answer questions. I'm in there now if you want to chat.

Typically you will get a faster response in #rust than an issue here, but if #rust is not being helpful I am always happy to respond to an issue no matter how small!

**Comment by mystor** [comment]
You can also bother me (mystor on irc.mozilla.org). I am usually around during EST work hours as my job involves me being available on IRC, so if David isn't available you can always bother me :-P

I'd be open to having a channel for syn stuff, but I'm not sure if the volume of people with questions would be high enough for it to be useful.

**Comment by zmitchell** [comment]
What about Gitter?

**Comment by dtolnay** [comment]
Any of the resources listed in https://www.rust-lang.org/community will have people knowledgeable about syn, since it is now one of the most widely used crates.
