### ISSUE TITLE
What does "delimiter" mean

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#289]
In syn we have `Element::delimiter` which is for things like comma separators, and in proc-macro2 they have `Delimiter` which is for parenthesis, brace, bracket. Let's use "delimiter" to mean one of these things and standardize on a different name for the other.

**Comment by dtolnay** [comment]
Wikipedia distinguishes between "field delimiters" for comma-like things and "bracket delimiters (also called block delimiters, region delimiters or balanced delimiters)" for paren-like things. So both uses are technically correct but I think we should pick two different words.

**Comment by mystor** [comment]
I think we should use delimiter and separator, because proc-macro refers to bracket delimiters (https://doc.rust-lang.org/nightly/proc_macro/enum.Delimiter.html), so we should use a different term for field separators.

**Comment by dtolnay** [comment]
I think "punctuated" would fit our usage better than "separated". It makes it easier to keep our current distinction between "separated" and "terminated" which works well. What do you think?

```rust
enum Element<T, P> {
    Punctuated(T, P),
    End(T),
}
```

---

![selection_092](https://user-images.githubusercontent.com/1940490/34459382-820760fe-edbd-11e7-8f7b-90d13eef1971.png)

**Comment by mystor** [comment]
Sure. Works for me.

**Comment by dtolnay** [comment]
I did this rename in f2cfd72935d4bc7379c38c729062fc3ff2bd78de. I think it is better than Delimited but probably not perfect. Let me know if anyone has suggestions.
