### ISSUE TITLE
Output as code string?

### ISSUE THREAD

**Issue by jD91mZM2** [dtolnay/syn#294]
Hi! I've looked around and can't find anything for converting a syn object to a code string (like, fully working Rust code).
I'd like to use `syn` to modify source code. (Is that the wrong approach by the way?)

**Comment by dtolnay** [comment]
The [`quote`](https://github.com/dtolnay/quote) crate can give you a string of any Syn data structure.

```rust
let v = /* ... */;
quote!(#v).to_string()
```

**Comment by jD91mZM2** [comment]
That seems to space-separate tokens rather than actually format them as runnable code. For example, `use test::Test;` becomes `use test :: Test ;`.

**Comment by dtolnay** [comment]
Space-separated tokens are runnable code. 😉 

```rust
mod test { pub struct Test ; } use test :: Test ; fn main ( ) { let _ = Test ; }
```

There isn't currently a pretty-printer for Syn because we are focused mostly on the procedural macro use case where the tokens are handed straight back to the compiler, but you can pass the output through `rustfmt` if you need.

**Comment by jD91mZM2** [comment]
Alright! Is there any chance we could somehow preserve formatting through some optional feature or such?

**Comment by mystor** [comment]
@jD91mZM2 That would be the work of an external crate - it's outside the scope of syn (which only works with tokens).

**Comment by jD91mZM2** [comment]
Yeah but you would still need to alter the tokens to add whitespace as enum variants?

**Comment by jD91mZM2** [comment]
Ooohhh I just noticed your https://github.com/alexcrichton/proc-macro2/pull/36 PR. If that somehow could be used in syn, that would be amazing!

**Comment by dtolnay** [comment]
Syn uses the same `Span` type as proc-macro2 so that PR should already be usable with Syn. You need to build with `RUSTFLAGS='--cfg procmacro2_semver_exempt'` because the API has not been figured out yet, but once you do, you get a [`start()`](https://doc.rust-lang.org/proc_macro/struct.Span.html#method.start) and [`end()`](https://doc.rust-lang.org/proc_macro/struct.Span.html#method.end) method on every span in the syntax tree giving you the line and column in the input string.

**Comment by jD91mZM2** [comment]
Awesome!

**Comment by jD91mZM2** [comment]
Can't seem to get it to work. Doesn't cfg work with `cargo doc` perhaps?

**Comment by dtolnay** [comment]
I don't think `cargo doc` picks it up but `cargo build` should work.

**Comment by jD91mZM2** [comment]
Ah, bummer. Thanks!
