### ISSUE TITLE
Remove deprecated_default_impl workaround

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#295]
We currently parse `impl Trait for .. {}` into an Item::Verbatim [here](https://github.com/dtolnay/syn/blob/fb95906c9526977bc99c920940d271701df0a6af/src/item.rs#L1086) because it is still used a lot in rust-lang/rust. Those uses are being cleaned up in https://github.com/rust-lang/rust/pull/46480 so we can stop parsing it when that lands.

**Comment by leodasvacas** [comment]
You can do that now.

**Comment by dtolnay** [comment]
Thanks!

**Comment by dtolnay** [comment]
Removed in https://github.com/dtolnay/syn/commit/b21b03437310c1c820625e68de68a4fbfdf4edf0.
