### ISSUE TITLE
Wrong end position for inner type

### ISSUE THREAD

**Issue by antoyo** [dtolnay/syn#296]
Hi.
It seems there's an error for the end position of an inner type.
In my code, I get the following error:
```
error: use of unsupported type name `Option<String>`
  --> $DIR/sql_table.rs:42:28
   |
42 |     nested_options: Option<Option<String>>,
   |                            ^^^^^^^^^^^^^^^
```
(There is one extra ^ .)
This is an error I generate and the span comes from calling the method `span()` on a `syn::Type`.
Thanks to fix this issue.

**Comment by dtolnay** [comment]
Thanks, I filed https://github.com/rust-lang/rust/issues/47226 to follow up on the compiler side.
