### ISSUE TITLE
Syn fails to parse keywords used in attributes.

### ISSUE THREAD

**Issue by sgrif** [dtolnay/syn#300]
The following is completely valid and accepted by Rust, but fails to be parsed by syn.

```rust
#[derive(Stuff)]
#[diesel(foreign_derive, unsized)]
struct StrProxy(str);
```

This is because `unsized` is a keyword. However, keywords are allowed to appear in word positions inside of attributes. `#[cfg(crate)]` is completely valid, even though `crate` can't normally be used as an identifier.

**Comment by dtolnay** [comment]
Thanks! This has been fixed in master and will be in the next release. Previous discussion in #196.
