### ISSUE TITLE
No public way to construct a `synom::ParseError`

### ISSUE THREAD

**Issue by mystor** [dtolnay/syn#311]
This makes it annoying to implement some types of external parsers using the synom infrastructure.

**Comment by mystor** [comment]
I've written `reject!(c,).err().unwrap()` to get a instance of `ParseError` in some code which I'm working on, which is pretty gross.

**Comment by dtolnay** [comment]
The error reporting API in #47 will provide a variety of ways to construct useful Syn errors.
