### ISSUE TITLE
No way to get value of LitStr

### ISSUE THREAD

**Issue by parched** [dtolnay/syn#312]
In 0.11 `StrLit` had a public field, `value`, but there doesn't seem to be such a thing in 0.12. Is there another way to do this now?

**Comment by mystor** [comment]
There's a `value()` method on `LitStr` which returns a `String`. https://docs.rs/syn/0.12.2/syn/struct.LitStr.html#impl

**Comment by parched** [comment]
Not sure how I missed that :(. Sorry for the noise.
