### ISSUE TITLE
Can't `parse_quote!` an Attribute

### ISSUE THREAD

**Issue by mystor** [dtolnay/syn#315]
It's unfortunate that it's not possible to `parse_quote!` an attribute. It'd be good if we could use `parse_quote!` to parse one. I think this would involve implementing `Synom` for `Attribute`, and parsing outer attributes in it.

(It probably makes much more sense to parse outer attributes there than inner ones).

**Comment by dtolnay** [comment]
Why not parse both? `parse_quote!(#[...])` gives you an attribute with style AttrStyle::Outer and `parse_quote!(#![...])` gives you an attribute with style AttrStyle::Inner.

**Comment by mystor** [comment]
I'd be fine with that too. The worry is that `syn!(Attribute)` would Do The Wrong Thing in many cases, and I'm worried about encouraging that.

**Comment by dtolnay** [comment]
Yeah. We could have `parse_quote!` use a different trait that is implemented for all `T: Synom` but also some other types.
