### ISSUE TITLE
Build workflow involving synom

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#322]
Moved from @bryteise's comment in https://github.com/dtolnay/syn/issues/195:

> @dtolnay Maybe this comment should exist somewhere else but becuase synom doesn't exist in the latest release (or a standalone as far as I could tell), it is a real pain to package syn. I need to get the tar file from crates.io of synom and then get the old release of syn because synom requires that version in order to just build the current version of syn. Is this the intended build flow because it is really unpleasant to work with.

**Comment by dtolnay** [comment]
There is no synom crate anymore as of syn 0.12. You should not need to package the old version of synom in order to build the new version of syn.

**Comment by bryteise** [comment]
Ah I see what my problem was, I hadn't patched out the dev-dependencies and rayon was pulling in serde which (as of right now) still was using the 0.11 version of syn. I pulled in the serde patch to use syn 0.12 and removed the dev-dependencies. Sorry for the noise.

**Comment by dtolnay** [comment]
Glad it worked out! Thanks for following up.
