### ISSUE TITLE
Why remove the aster module?

### ISSUE THREAD

**Issue by sgrif** [dtolnay/syn#323]
I'm looking at syn 0.12 now, and I'm really interested in why this module was removed. Diesel uses it a lot for manipulating generics, and it seems incredibly difficult to do any kind of AST manipulation without it. For example, our two most common use cases were "add the type parameters `__ST` and `__DB`" and "Add this trait bound to every type parameter". It's not clear how to accomplish either of those easily in syn 0.12.

**Comment by dtolnay** [comment]
My design preference in 0.12 has been that anyone familiar with Rust grammar should be comfortable traversing the syntax tree and reading code that manipulates it without further background required. For example this is why the syntax tree no longer uses rustc terminology like PolyTraitRef and Rptr.

I believe aster was a dead end against this design approach and quasi-quotation is a better way to expose almost everything it did.

> it seems incredibly difficult to do any kind of AST manipulation without it.

Here is how I would approach the two use cases you mentioned.

```rust
// Add type parameters
generics.params.push(parse_quote!(__ST));
generics.params.push(parse_quote!(__DB));
```

```rust
// Add a trait bound to every type parameter
for param in &mut generics.params {
    if let GenericParam::Type(ref mut type_param) = *param {
        type_param.bounds.push(parse_quote!(diesel::query_builder::QueryId));
    }
}
```

**Comment by sgrif** [comment]
Ok the existence of `parse_quote!` makes that much easier than I expected. I missed the `IntoIterator` impls as well. Do you think it's worth calling out that macro a bit higher in the module docs? Are there some intermediate level guides/reference material that I'm missing?

**Comment by sgrif** [comment]
Also it would be nice to have some methods on `generics` that are at least closer to how they could be accessed in 0.11. So that could be `for param in generics.ty_params_mut() ` instead

**Comment by dtolnay** [comment]
- I filed #326 to follow up on featuring `parse_quote!` more prominently.
- What we have for intermediate level guides/reference material are these [examples](https://github.com/dtolnay/syn/tree/master/examples).
- #327 has added iterator methods on `Generics`. Good idea!
