### ISSUE TITLE
Flaky assertion: assertion failed: self.empty_or_trailing()

### ISSUE THREAD

**Issue by djc** [dtolnay/syn#338]
When trying to run [Askama](https://github.com/djc/askama)'s tests with `--features nightly` and a recent nightly compiler, the first run errored out for me with `assertion failed: self.empty_or_trailing()`. However, the next run (with trivial changes in the source code) succeeded, and after `cargo cleanup`, the next run also succeeded. Reporting here primarily because the assertion seems to originate in `syn`, but I guess there might be an incremental compilation edge case?

**Comment by dtolnay** [comment]
The assertion is in [`Punctuated::push_value`](https://docs.rs/syn/0.12/syn/punctuated/struct.Punctuated.html#method.push_value):

> ### Panics
>
> Panics if the sequence does not already have a trailing punctuation when this method is called.

Askama calls `push_value` once [here](https://github.com/djc/askama/blob/8f216fed4c51f470777a004317ecc09869728fb7/askama_shared/src/generator.rs#L288) which looks like does not ensure there is trailing punctuation.

**Comment by djc** [comment]
Thanks, I've switched to `push()` now, which should solve this problem.

Can you explain why this appeared to be non-deterministic?

**Comment by dtolnay** [comment]
It may have to do with the order that test files are compiled. There are 12 tests in askama/testing/tests only some of which hit this. If the ones that hit this tend to be compiled last, and the earlier ones fail for other reasons, Cargo will abort before attempting to compile every file.

**Comment by djc** [comment]
When I didn't see this failure, I saw all the tests passing -- which still feels wrong.
