### ISSUE TITLE
Using syn for a rust-imports style tool

### ISSUE THREAD

**Issue by gsquire** [dtolnay/syn#341]
Something that I have wished Rust would have is the ability to automatically manage use statements on editor save. The tool I use everyday for Go is [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) which can read the source AST and add/replace/sort imports based on usage in the file. There are a few edge cases where names collide but for the most part it works well.

I thought it would be a good challenge to try and write this in Rust and am wondering if it would make sense to leverage syn to do this? Thanks for your time.

**Comment by dtolnay** [comment]
You could make it work but there is no stable API yet for accessing the whitespace in between tokens, which presumably you would want to preserve. You would need to use part of the [semver exempt](https://github.com/alexcrichton/proc-macro2#unstable-features) API of proc-macro2 to manipulate whitespace.

The syn syntax tree is likely to have less frequent breaking changes than the RLS syntax tree.

**Comment by gsquire** [comment]
Ok thanks for the info. I don't know if I would need to be concerned about the whitespace so much as long as I can just read exported items and rewrite the header of a file. Of course that is trivializing it but I will at least explore it a bit.
