### ISSUE TITLE
Give a better error message when parsing fails because of a missing feature

### ISSUE THREAD

**Issue by Eijebong** [dtolnay/syn#349]
So I just spent half an hour trying to reproduce a bug because syn was failing to parse

```rust
#[derive(Clone, Copy, MallocSizeOf, PartialEq)]
pub struct LonghandIdSet {
    storage: [u32; (168 - 1 + 32) / 32]
}
```

Turns out I was missing the `full` feature.
Would it be possible to give a message that's more precise `Failed to parse` in that case ?

**Comment by dtolnay** [comment]
Thanks! Let's track this under #28. I am also happy to provide support for parenthesized expressions without the `"full"` feature since that has come up a couple times. I filed #351 to follow up.
