### ISSUE TITLE
syn cannot be used with cdylibs due to proc_macro dependency

### ISSUE THREAD

**Issue by Rantanen** [dtolnay/syn#357]
Running

```
cargo init
echo syn = \"0.12\" >> Cargo.toml
echo [lib] >> Cargo.toml
echo crate-type = [ \"cdylib\" ] >> Cargo.toml
echo extern crate syn\; >> src/lib.rs
cargo build
```

Results in

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling unicode-xid v0.1.0
   Compiling proc-macro2 v0.2.2
   Compiling quote v0.4.2
   Compiling syn v0.12.12
   Compiling syn-cdylib v0.1.0 (file:///home/rantanen/test/syn-cdylib)
error: crate `proc_macro` required to be available in rlib format, but was not found in this form

error: crate `syntax` required to be available in rlib format, but was not found in this form

error: crate `rustc_cratesio_shim` required to be available in rlib format, but was not found in this form

error: crate `rustc_errors` required to be available in rlib format, but was not found in this form

error: crate `rustc_data_structures` required to be available in rlib format, but was not found in this form

error: crate `syntax_pos` required to be available in rlib format, but was not found in this form

error: aborting due to 6 previous errors

error: Could not compile `syn-cdylib`.
```

Making `proc_macro` an optional default dependency for `syn` is easy. However `proc_macro2` depends on that as well, and I'm guessing in the (somewhat distant) future the use of `proc_macro2` will be replaced with `proc_macro` in syn so trying to get rid of `proc_macro2` and/or making `proc_macro` optional for `proc_macro2` wouldn't really work as a long term solution.

In my specific use case `syn` is an indirect dependency to the `cdylib` crate and I'm probably able to split the crate that depends on `syn` in two in such a way that the `cdylib` doesn't receive `syn` as a dependency.

However this would still be an issue for any `cdylib` that needs to be able to parse Rust code for example, which might be a case for IDEs and such.

What does `syn` need from `proc_macro2` for usage that depends on `parse_str` instead of parsing `TokenStream`s? It seemed like structs such as `Span` come directly from `proc_macro2`, but I'd imagine that if the number of dependent structs for the `syn` AST is small, these could be re-implemented in syn, with a `not(feature = "proc_macro")` guard or some such.

**Comment by dtolnay** [comment]
I think the correct solution would be making proc_macro available to cdylib crates. We could make that change now if you are interested in working on it: https://github.com/rust-lang/rust/issues/45601.

**Comment by Rantanen** [comment]
Based on the discussion on that issue it seems like the ideal solution is still up in the air. sfackler's "proc macros as binaries with IPC" approach sounds really nice, but it also sounds like a major change in the compiler internals. Left a comment on that issue asking for clarification, if there is any.

I'll most likely split my dependency into two crates, so I can skip syn dependency in the cdylib, which would be a good change for my crate even without this issue. I've meant to move the proc_macro internals into a different crate anyway for unit testing purposes so I could do both of these at the same time.

**Comment by dtolnay** [comment]
This is actively being worked on in https://github.com/rust-lang/rust/issues/45601 and https://github.com/rust-lang/rust/pull/49219, and I don't think there is anything that can be done about it on our end, so I am closing the issue. Please follow up on one of those threads as necessary.
