### ISSUE TITLE
ItemFn `block` modification

### ISSUE THREAD

**Issue by nixpulvis** [dtolnay/syn#361]
A pretty common use case (I'd imagine) is the ability to have a macro like the following modify the function body it's defined on.

```rust
#[foo ...]
fn bar(...) -> ... { ... }
```

It's not currently very clear how to best do this. The idea of pushing and popping values from `input.block.stmts` is cumbersome. It would be great to be able to write something like:

```rust
let input: ItemFn = syn::parse(input).unwrap();
let output = inject_body!(input, <before>, <after>);
output.into()
```

However a more general solution is probably better, I'm just not sure yet what it is. Thoughts?

**Comment by dtolnay** [comment]
If you haven't seen it already, check out [this macro](https://github.com/dtolnay/syn/tree/master/examples/trace-var) which shows an example of an attribute that modifies a function body.

**Comment by nixpulvis** [comment]
@dtolnay oh man, I wasn't compiling with the `fold` feature and totally missed that. I bet this is exactly what I need.
