### ISSUE TITLE
Failed to parse derive input for Box<'a +Fn()->T>

### ISSUE THREAD

**Issue by alanpoon** [dtolnay/syn#364]
Lifetime specification is allowed for closure in Box, when declaring a property for a struct. https://play.rust-lang.org/?gist=d496c1bca4881db342c6e78f5ca50abb&version=stable

However, when I add #[derive(....)], before the struct, it fails to parse the Input.

**Comment by dtolnay** [comment]
I believe this was fixed in #261. The derive macro may still be using an old version of Syn.

**Comment by alanpoon** [comment]
Thanks!
