### ISSUE TITLE
Eq and Hash are not implemented for syn::Type in 0.12.x release

### ISSUE THREAD

**Issue by JelteF** [dtolnay/syn#365]
I was trying to update my `derive_more` crate to the new version of `syn`. So much has changed that I get an insane amount of compilation errors. I was slowly working through them, but I've hit a roadblock.
With the previous version I had a `HashMap` with `Vec<Ty>` as the keys. This does not work anymore with v0.12.13, I'm getting errors that `syn::Type` does not implement `Eq` and `Hash`. Is it possible to get this functionality back?

**Comment by mystor** [comment]
Those trait impls are now behind the `extra-traits` feature :-)

**Comment by JelteF** [comment]
Thanks, that was indeed it.
