### ISSUE TITLE
How do I create a quote::Tokens that contains Ident and Tokens?

### ISSUE THREAD

**Issue by alanpoon** [dtolnay/syn#366]
I am working on a field_initialisers which is initialized by quote::Tokens::new();

I cannot append syn::Ident type and syn::Token::Colon together into the field_initialisers. My field_initialisers.to_string() should look like ident1:None,ident2:None,ident3:None.

**Comment by dtolnay** [comment]
The repetition feature of [`quote!`](https://docs.rs/quote/0.4/quote/macro.quote.html) could be useful if you haven't used it yet.

```rust
#[macro_use]
extern crate quote;

extern crate syn;
use syn::Ident;

fn main() {
    let idents = vec![
        Ident::from("ident1"),
        Ident::from("ident2"),
        Ident::from("ident3"),
    ];

    let field_initializers = quote! {
        #(#idents: None,)*
    };

    println!("{}", field_initializers);
}
```

**Comment by mystor** [comment]
Those are not identifiers, but rather `Member` Expressions

**Comment by alanpoon** [comment]
After I parsed my Tokenstream, destructuring from syn::NestedMeta, "theme.font_size_medium" is syn::LitStr. How do I convert it to syn::ExprField? Currently, I got found "&'static str, expected various Type" error.

**Comment by dtolnay** [comment]
Check out the [`LitStr::parse`](https://docs.rs/syn/0.12/syn/struct.LitStr.html#method.parse) method which lets you parse an `Expr` or many other syntax tree types out of a `LitStr`.

(The demo code below requires the `"full"` and `"extra-traits"` features of Syn.)

```toml
syn = { version = "0.12", features = ["full", "extra-traits"] }
```

```rust
#[macro_use]
extern crate quote;

#[macro_use]
extern crate syn;
use syn::{LitStr, Expr};

fn main() {
    let lit: LitStr = parse_quote!("theme.font_size_medium");
    println!("{:#?}", lit);

    let expr: Expr = lit.parse().unwrap();
    println!("{:#?}", expr);

    println!("{}", quote!(#expr));
}
```

**Comment by alanpoon** [comment]
Thanks, it worked.
