### ISSUE TITLE
How to parse rust code, transorm it through AST and output a new code ?  

### ISSUE THREAD

**Issue by tigitz** [dtolnay/syn#374]
I've been told syn can fit my requirements for my use case described in the title.
Unfortunately I'm having a hard time finding the right methods to output a `File` to actual rust code.

This is where I'm stuck:

```rust
fn main() {

    let src = String::from_str(r#"
    fn main() {
        let string = "line one
        line two";
    }
    "#)
        .expect("Parsing doesn't work");
    let syntax = syn::parse_file(&src).expect("Can't parse rust code");
    
    for into_token in syntax.into_tokens() {
        match into_token.kind {
            Term(T) => { println!("{:#?}", T.as_str() ) },
            _ => { }
        }
    }
}
```
I've also seen both of the visitor trait in the lib but I can't wrap my head around how to use it either.

As a suggestion, from my point of view, something similar to [https://github.com/nikic/PHP-Parser](PHP-Parser)

```php
$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7);
$ast = $parser->parse($code);
$traverser = new NodeTraverser();
$traverser->addVisitor(new NodeVisitorRemovingComment());
$ast = $traverser->traverse($ast);
$prettyPrinter = new PrettyPrinter\Standard;
echo $prettyPrinter->prettyPrintFile($ast);
```
Would be a much clearer API to use for my case, but I can understand if it's out of the syn crate scope.

Thanks in advance for your help.

**Comment by dtolnay** [comment]
Syn does parsing, while printing syntax trees is handled by the [`quote`](https://github.com/dtolnay/quote) crate.

```rust
#[macro_use]
extern crate quote;
extern crate syn;

fn main() {
    let source = r#"
        fn main() {
            let string = "line one
            line two";
        }
    "#;

    let syntax = syn::parse_file(source).unwrap();
    println!("{:#?}\n", syntax);

    println!("{}", quote!(#syntax));
}
```

**Comment by tigitz** [comment]
Arghh! I should have missed it somewhere, thank you.

A following question, since Tokens seems to only provide appending functions what would be your recommendation to mutate the existing Tokens instead?

Let's say I want to change the string to "Hello" in the example.

Do I have to remove the Token and append a new one?

Thanks again for your time.

**Comment by dtolnay** [comment]
`Tokens` is not meant to be a data structure that you would want to mutate. Typically that sort of thing (pattern matching and mutation) would happen at the syntax tree level before printing to tokens.

**Comment by tigitz** [comment]
Alright, I'll try the AST way.

Thanks.
