### ISSUE TITLE
Remove Attribute::is_sugared_doc

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#389]
As of https://github.com/rust-lang/rust/pull/49545 proc macros can no longer tell the difference between sugared vs attribute doc comments, just like macro_rules currently cannot. In Syn 0.13 I believe the is_sugared_doc field is always set to false by the parser.

**Comment by Bert-Proesmans** [comment]
I have a somewhat related issue in my procedural attribute macro, nightly rustc --version = 2018-04-01.
I have a procedural macro attribute which applies to modules and observed the following behaviour:

- Inner OR outer sugared docs on the subject module
  The compiler generates an inner doc-attribute. After ItemMod parsing the resulting tokens contain the same doc-attribute content, but NOT attached to the subject module anymore (it's a regular attribute)

- Inner AND outer sugared docs on the subject module
   The compiler generates outer AND inner doc-attribute, matching the sugared content respectively. ItemMod parsing FAILS with 'failed to parse'.

**Comment by dtolnay** [comment]
Fixed in fe583306aa2a6a8ca9c08f4ed67b49b9e404249b, will be released in 0.15.
