### ISSUE TITLE
Parse async functions

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#395]
https://github.com/withoutboats/rfcs/blob/async-await/text/0000-async_await.md#async-functions

```rust
async fn function(argument: &str) -> usize {
     // ...
}
```

**Comment by steveklabnik** [comment]
Getting this would be awesome 👍

**Comment by dtolnay** [comment]
@ubnt-intrepid or @steveklabnik, to get this working in the near term would one of you be willing to send a PR that parses async functions as a `syn::Item::Verbatim`? We haven't made use of this variant so far but it is designed for short-term handling of unstable syntax without a breaking change.

**Comment by steveklabnik** [comment]
I might be willing to; I'm able to work around this restriction for now so it's not *super* pressing for me, but if I can find the time I'll give it a shot :)

(Or, if it's easy for you to point out the general gist of how it's done; a lot of the effort would be in figuring out how `syn` works at all, since I haven't delved into the code yet)

**Comment by dtolnay** [comment]
Oh, here is a good example of how to do this: you have to swap red and green in your head but https://github.com/dtolnay/syn/commit/b21b03437310c1c820625e68de68a4fbfdf4edf0 shows how we used to parse the unstable syntax `impl Trait for .. {}` as verbatim tokens.

**Comment by ubnt-intrepid** [comment]
@dtolnay and @steveklabnik Sorry for late reply.
I can restart the work during this week for modifying the previous PR to use `ItemVerbatim`.

For closures, should i use [`syn::ExprVerbatim`](https://docs.rs/syn/0.14.5/syn/struct.ExprVerbatim.html)?

**Comment by dtolnay** [comment]
I rebased #450 as f00a3efc7dceef0d57ae01c39a0a39293c80a776 and it will be releasing in 0.15.0.
