### ISSUE TITLE
No longer able leverage println! ?

### ISSUE THREAD

**Issue by jlgerber** [dtolnay/syn#398]
Upgraded from 11.11 to 13.1 . Seems like there are huge differences. As I try and get my footing, I keep running into syn::bla` cannot be formatted using `:?` because it doesn't implement `std::fmt::Debug. 

Is this now behind a feature gate? 

Also, with the big changes to the crate, is there any sort of transition guide?

**Comment by Feliix42** [comment]
@jlgerber Did you solve the problem? I keep running into the same issue.

**Comment by Feliix42** [comment]
Okay, nevermind. I was fooled by the assumption, that the feature `full` would cover the _full_ feature set. But traits like `Debug` require the feature flag `extra-traits`.
