### ISSUE TITLE
Add the rest of Rust syntax behind a feature flag (off by default)

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#4]
Parsing structs and enums is enough for Macros 1.1 but parsing all of Rust may be useful for other things.

## Items

- [x] ExternCrate
- [x] Use
- [x] Static
- [x] Const
- [x] Fn
- [x] Mod
- [x] ForeignMod
- [x] Ty
- [x] Enum (enabled by default)
- [x] Struct (enabled by default)
- [x] Union
- [x] Trait
- [x] DefaultImpl
- [x] Impl
- [x] Mac

## Expressions

- [x] Box
- [x] Vec
- [x] Call
- [x] MethodCall
- [x] Tup
- [x] Binary
- [x] Unary
- [x] Lit
- [x] Cast
- [x] Type
- [x] If
- [x] IfLet
- [x] While
- [x] WhileLet
- [x] ForLoop
- [x] Loop
- [x] Match
- [x] Closure
- [x] Block
- [x] Assign
- [x] AssignOp
- [x] Field
- [x] TupField
- [x] Index
- [x] Range
- [x] Path
- [x] AddrOf
- [x] Break
- [x] Continue
- [x] Ret
- [x] Mac
- [x] Struct
- [x] Repeat
- [x] Paren
- [x] Try

## Statements

- [x] Local
- [x] Item
- [x] Expr
- [x] Semi
- [x] Mac

## Patterns

- [x] Wild
- [x] Ident
- [x] Struct
- [x] TupleStruct
- [x] Path
- [x] Tuple
- [x] Box
- [x] Ref
- [x] Lit
- [x] Range
- [x] Slice
- [x] Mac

## Other

- [x] Workaround for parsing ambiguity https://github.com/rust-lang/rfcs/pull/92

**Comment by dtolnay** [comment]
This would allow serde_codegen to drop its dependency on Syntex entirely.

**Comment by tikue** [comment]
In a plugin I'm using to transform idents, I need to parse traits, trait impls, and type paths. This is because macros can't perform an ident => ident transformation, so instead I have specialized versions of the macro for different contexts.

**Comment by dtolnay** [comment]
## Items

- [x] ExternCrate
- [ ] Use
- [ ] Static
- [ ] Const
- [ ] Fn
- [ ] Mod
- [ ] ForeignMod
- [ ] Ty
- [x] Enum
- [x] Struct
- [ ] Union
- [ ] Trait
- [ ] DefaultImpl
- [ ] Impl
- [ ] Mac

## Expressions

- [x] Box
- [x] Vec
- [x] Call
- [x] MethodCall
- [x] Tup
- [x] Binary
- [x] Unary
- [x] Lit
- [x] Cast
- [x] Type
- [x] If
- [ ] IfLet
- [ ] While
- [ ] WhileLet
- [ ] ForLoop
- [ ] Loop
- [ ] Match
- [ ] Closure
- [x] Block
- [ ] Assign
- [ ] AssignOp
- [ ] Field
- [ ] TupField
- [ ] Index
- [ ] Range
- [ ] Path
- [ ] AddrOf
- [ ] Break
- [ ] Continue
- [ ] Ret
- [ ] Mac
- [ ] Struct
- [ ] Repeat
- [ ] Paren
- [ ] Try

## Statements

- [ ] Local
- [ ] Item
- [ ] Expr
- [x] Semi
- [ ] Mac

**Comment by gregkatz** [comment]
Hi! Could I work on parsing the loop expression? Maybe if I'm able to handle that one fairly easily, I can move on to others.

**Comment by dtolnay** [comment]
Absolutely! Thanks in advance. Let me know if I can help explain anything.
