### ISSUE TITLE
No-op example would be great

### ISSUE THREAD

**Issue by gilescope** [dtolnay/syn#401]
Would be great to have an example showing quote and syn doing a no-op pass through of AST input - all the current examples just take a few bits of the input and include them in quote.
As a newbie it wasn't clear that quote! took in ast objects rather than strings.

**Comment by dtolnay** [comment]
I believe the documentation of the [`quote!`](https://docs.rs/quote/0.6.4/quote/macro.quote.html) macro covers how interpolation applies to a range of syntax tree types and primitive types. Could you take a look? Is there a better place you would recommend providing that explanation?
