### ISSUE TITLE
Parse try { .. } expressions

### ISSUE THREAD

**Issue by Centril** [dtolnay/syn#404]
**Pending** if we merge and implement https://github.com/rust-lang/rfcs/pull/2388, parse:
```rust
fn main() {
    let foo: Result<usize, ()> = try { 42 };
}
```

(`do catch { .. }` will not be supported after implementation...)

Update: The RFC has been merged.

**Comment by kornelski** [comment]
Does the plan include parsing `try` + `!` contextually

**Comment by Centril** [comment]
Elaborate? Not sure what you mean by this. What in particular is it about the combination `try` and `!` *syntactically* that is different?

**Comment by kornelski** [comment]
If try is parsed as a keyword, it will become unavailable as an ident for macros. AFAIK preserving ability to use `try!()` requires special handling in the parser.

**Comment by Centril** [comment]
Status update: The RFC has been merged.

**Comment by dtolnay** [comment]
We currently use [`ExprCatch`](https://docs.rs/syn/0.14/syn/struct.ExprCatch.html) to mean `do catch { ... }` and [`ExprTry`](https://docs.rs/syn/0.14/syn/struct.ExprTry.html) to mean `expr?`. Presumably we will want `ExprTry` to mean `try { ... }` and will need to pick a different name for `expr?`.

**Comment by dtolnay** [comment]
Fixed in fb2dd4b7f4e6c879b7dc7a17f57cc8373ec373d4, will be released in 0.15.
