### ISSUE TITLE
Report line and column positions

### ISSUE THREAD

**Issue by xd009642** [dtolnay/syn#406]
It looks like this isn't possible from looking at the docs, but is there a way for a Span to report the line index and column indexes of the start and end of the span? I'm trying to replace a dependency on `syntex_syntax` which I use to figure out line regions i don't want to process. Ideally, for my use case, this would also be available using only stable features.

If this isn't possible yet, is there any interest in implementing it? I'd be happy to contribute!

**Comment by dtolnay** [comment]
I believe this is already implemented and available on the stable channel but [semver exempt](https://github.com/alexcrichton/proc-macro2#unstable-features) because the API has not had design effort invested yet. That means we are extra interested in feedback!

```toml
[dependencies]
syn = { version = "0.13", features = ["full"] }
```

```rust
extern crate syn;
use syn::Item;

fn main() {
    let source = "extern crate syn;\n";

    let file = syn::parse_file(source).unwrap();
    match file.items.into_iter().next().unwrap() {
        Item::ExternCrate(item) => {
            // span of `syn` token in extern crate item
            let span = item.ident.span();

            let start = span.start();
            let end = span.end();
            println!("start line {} column {}", start.line, start.column);
            println!("end line {} column {}", end.line, end.column);

            // assume line 1
            println!("source code: {:?}", &source[start.column..end.column]);
        }
        _ => unimplemented!(),
    }
}
```

```
$ RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo run
start line 1 column 13
end line 1 column 16
source code: "syn"
```

**Comment by xd009642** [comment]
Awesome! I'll try it out tonight and let you know if there are any issues/feedback :+1:

**Comment by xd009642** [comment]
So one thing I've found that is more of a documentation issue. I haven't reworked the code to the point I can test it and see but from the docs it's not clear if `File::items` is everything or just top level items? Especially since for things like mod items you can get a list of all items below them. 

If it is all the items some function to iterate over and skip items below a certain parent would be useful from a usability perspective. 

Either way some documentation on this would be helpful, but I'm aware as this is an area potentially in flux not wanting to write comprehensive docs for something that may be significantly changed.

**Comment by CodeSandwich** [comment]
I've just used `LineColumn` in my code too and I have some thoughts too. First of all thank you for this feature, it works and works just right :)

My use case is automated source code modification. I load the file, push it into `syn::File` and find spots, where I need to insert small chunks of code. If I insert them into syn syntax tree, stringify it and save, all formatting information is lost and I end up with horrible single-line file. So what I do is keep the original code as a string and use syn to determine insertion points as `LineColumn`s. Then I manually insert my chunks of code into given lines and columns of a string and save it back.

It works just fine, but I have a few details, which would make it a bit easier use (at least in my use case):
1. Line number could be 0-indexed like row number. I know, that error messages use 1-indexed line numbers, but for machine processing consistent 0-indexing is easier to understand and use.
1. Most of my code is finding row and column in a stream of bytes, which is Rust `String`. If `LineColumn` had byte index of the original code, that would blow away 90% of my use case complexity.
1. `Eq` comparing line and then column would be really nice.

**Comment by davidhewitt** [comment]
It looks like LineColumn are now available in nightly proc_macro behind a feature gate. Does that mean it's possible to use these Spans from syn with the nightly feature instead of semver-exempt?

**Comment by davemilter** [comment]
Any news? I try to do nice error reporting,
but ask user for this functionality to build with `RUSTFLAGS='--cfg procmacro2_semver_exempt'` looks not good.

**Comment by davemilter** [comment]
> println!("source code: {:?}", &source[start.column..end.column]);

Looks not good, if there are several lines, 
I have to recalc end of lines by hand?

May be it is possible to add span.position method,
so code like this:
```
&source[start.position()..end.position()]
```
without problems for any numbers of lines in code?

**Comment by dtolnay** [comment]
Proc-macro2 0.4.27 now exposes line and column position on sufficiently new compiler without requiring procmacro2_semver_exempt, so I'll go ahead and close this issue. I would like for any higher level functionality around error rendering to be developed in a separate crate outside of Syn. I put together a basic example of rendering a rustc-style error message [here](https://github.com/dtolnay/syn/blob/ddc51f1c3d1162de03d91fefb2828434fa181399/examples/dump-syntax/src/main.rs#L86) as a starting point.
