### ISSUE TITLE
Allow custom `Stmt`s

### ISSUE THREAD

**Issue by jeremydavis519** [dtolnay/syn#407]
I'm trying to make a macro that adds a few new kinds of statement but otherwise accepts arbitrary Rust code. It currently works as long as everything is in the same scope--I check for my special cases and let `syn!(Stmt)` handle the ones I don't care about. But if there are statements inside other statements, as in the following example, my current code doesn't even check the inside statements.
```rust
if x > 0 {
    custom_statement_that_my_code_never_sees;
}
```

The result is a complete failure to parse, since `Stmt::parse` doesn't know anything about my new statement types.

As a workaround, I can duplicate parts of `syn`'s AST with my own structs that do nothing different except possibly contain my custom statements, but my crate shouldn't have to know about most of Rust's grammar just to add a new statement. And what if Rust's grammar changes and `syn` is updated but my crate isn't?

So, I propose adding (possibly behind a feature gate) a new variant to the `Stmt` enum, called `Custom(Box<std::any::Any>)`, that represents anything the parser wants to call a statement, and adding this parser to `Stmt`'s impl:
```rust
named!(pub parse_custom(custom_parser: fn(Cursor) -> PResult<Synom>), alt!(
      call!(custom_parser) => { |stmt| Stmt::Custom(Box::new(stmt)) }
    | syn!(Stmt)
))
```

This idea could be extended to custom expressions, items, etc. For my use case, though, statements are the only important ones. I'm willing to do it myself if no one has any objections.

**Comment by dtolnay** [comment]
I would be interested in seeing what this would look like in a PR. Thanks!

**Comment by dtolnay** [comment]
Closing because I don't intend to work on this myself, but feel free to send a PR if you get this working and we can evaluate whether it makes sense to expose in Syn.
