### ISSUE TITLE
Failed parsing consumes TokenStream

### ISSUE THREAD

**Issue by CodeSandwich** [dtolnay/syn#421]
### Use case
1. Proc macro asks Syn to parse TokenStream
1. Parsing fails
1. Warning for user is printed, that proc macro will have no effect
1. Unchanged TokenStream is returned

There seems to be no way to recover the original TokenStream. It's consumed during parsing and returned error does not contain it.

The workaround is to always clone TokenStream before parsing. It works, but as far as I know, it's an expensive operation.

**Comment by dtolnay** [comment]
The compiler's TokenStream is internally reference counted so it is pretty much free to clone. This is why e.g. [`Group::stream`](https://doc.rust-lang.org/nightly/proc_macro/struct.Group.html#method.stream) can cheaply return an owned stream.

But as a general point: you never need to worry about performance in a procedural macro. Evaluating the procedural macro is such a minuscule step of compilation that copying some strings here and there makes zero difference. *Especially* in the use case you mentioned which is executed only once per macro invocation.

**Comment by CodeSandwich** [comment]
Awesome, thank you for clarification :)
