### ISSUE TITLE
Pass custom span to parser

### ISSUE THREAD

**Issue by divyahansg** [dtolnay/syn#432]
In my procedural macro, I have a `String` of source code along with a `Span` that spans the string. I'd like to parse the string into `Tokens` (and ultimately use in a `quote! { }`) while preserving the span information. 

Is there a way to pass a `String` and it's `Span` to a `syn` parser and receive `Tokens`?

NB: the `Span` was generated by adding the string to the `syntax::codemap::CodeMap` in the compiler.

**Comment by divyahansg** [comment]
Thanks, that's it! Is it possible to go from a `proc_macro::Span` to a `proc_macro2::Span`? I found `unstable()` goes the opposite way.

**Comment by dtolnay** [comment]
Yes I believe there is a `From` impl in that direction. `proc_macro2::Span::from(unstable_span)`
