### ISSUE TITLE
Having trouble getting the derive attribute

### ISSUE THREAD

**Issue by gpace1** [dtolnay/syn#433]
When implementing a custom derive, the DeriveInput structure generated from parsing the input TokenStream doesn't seem to have any derive attributes.  Doing something like what's in the below code will print an empty vec for the attributes.

```
#[proc_macro_derive(Bar)]
pub fn bar(input: TokenStream) -> TokenStream {
    let input: DeriveInput = syn::parse(input).unwrap();
    panic!( "Attributes:\n{:?}", input.attrs);
}
```
```
#[derive(Bar)]
struct Foo;
```

The above will generate the error:
```
error: proc-macro derive panicked
  -->
   |
   | #[derive(Bar)]
   |          ^^^
   |
   = help: message: Attributes: []
```

I'm looking to try and generate a different implementation of a trait based on the other derived traits on an Item.

Thanks.

**Comment by dtolnay** [comment]
The compiler does not allow custom derives to see other derives on the same struct. To see the list of derives you would need to implement your macro as a `proc_macro_attribute` rather than a `proc_macro_derive`.

```rust
#[bar]
#[derive(Copy, Clone)]
struct Foo;
```

**Comment by gpace1** [comment]
Then this is a non-issue of syn.  I guess a note could be made about this somewhere in the documentation, but I go ahead and close this if you feel otherwise.

Thanks @dtolnay!
