### ISSUE TITLE
Extend `visit` to the full syntax

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#44]
[This is in a pretty sorry state](https://github.com/dtolnay/syn/blob/2201800aab862cf1e7a1e10fb409db87bdcf4bc2/src/visit.rs) - basically the bare minimum required for Serde.

**Comment by shepmaster** [comment]
So... why a separate crate? The `Visitor` trait is going to be *deeply* intertwined with the structures created in this crate and will need to be updated when names and children change. In addition, if you want to keep the feature flags, then those would need to be reflected in both crates, I'd believe.

**Comment by dtolnay** [comment]
Yeah you're right. I've come around on this. Same reasoning as for `fold` (#43):

> I am hesitant to pile more features into syn because if an optional feature requires a breaking change, even people not using that feature suffer from the version bump. With a relatively stable core in syn and an ecosystem of supporting libraries around it, you are only affected by breaking changes to pieces that you use.

> I guess `fold` is core enough and coupled so closely with everything else in syn that the scenario of breaking `fold` without breaking syn seems unlikely, so you're right it could make sense to implement here rather than a separate crate.

**Comment by dtolnay** [comment]
Fixed in #79.
