### ISSUE TITLE
Map from derive to fn impls

### ISSUE THREAD

**Issue by daschl** [dtolnay/syn#446]
Hi,

if this is not the right place to ask questions let me know.

I have a use case where based on a custom derive I need to iterate its fn impls. I know there is no direct mapping easily available.

Imagine I have the following code:

```rust
#[derive(Debug, RoastExport)]
struct Foobar {}

impl Foobar {
    pub fn hello() -> i32 {
        5678
    }
}
```

What I want in the end is a vec of all the function syntax items in the impl since based on that I need to do do codegen for FFI bindings.

I don't mind writing some weird code but I have no idea how to "map" my ident from the derive to iterating over the full syntax from the files:

```rust
#[proc_macro_derive(RoastExport)]
pub fn roast_export(input: TokenStream) -> TokenStream {
    let input: DeriveInput = syn::parse(input).unwrap();

    functions_for_ident(&input.ident);

    let expanded = quote!{};

    expanded.into()
}

fn functions_for_ident(ident: &Ident) {
    let rootdir = env::var("CARGO_MANIFEST_DIR").unwrap();

// iterate all rust files in the dir, looking for the struct/impls
    for entry in WalkDir::new(rootdir) {
        let e = entry.expect("could not decode entry");
        if e.file_name().to_str().unwrap().ends_with("rs") {
            let mut file = File::open(&e.path()).expect("Unable to open file");
            let mut src = String::new();
            file.read_to_string(&mut src).expect("Unable to read file");
            let syntax = parse_file(&src).expect("Unable to parse file");
            for item in syntax.items {
                // ???
            }
        }
    }
}
```

I appreciate any input or pointers to other projects who need something similar!

**Comment by dtolnay** [comment]
This information is not available when custom derives are expanded, and walking and re-parsing the source code may or may not find the right impl blocks. You could look into using an attribute macro on the impl block instead:

```rust
#[roast_export]
impl Foobar {
    pub fn hello() -> i32 {
        5678
    }
}
```

**Comment by daschl** [comment]
@dtolnay but that would require the use of nightly right?

**Comment by daschl** [comment]
Thanks that will do it for now until we get macros on stable - thanks for the help!
