### ISSUE TITLE
Support parsing `union`s for DeriveInput

### ISSUE THREAD

**Issue by Centril** [dtolnay/syn#447]
The parser for `DeriveInput` does currently not support unions: https://github.com/dtolnay/syn/blob/master/src/derive.rs#L84-L127

But a `proc_macro_derive` will pass along a `union Foo { x: usize }` to the macro happily.

**Comment by mystor** [comment]
Unfortunately this change would be breaking, as we'd need to add a new enum variant for unions to the DeriveInput parser. It would also make many derives more complex / ugly as they would need to handle the union case (which most derives can't do in a reasonable manner).

Perhaps we should add a comment to the docs explaining that `DeriveInput` doesn't parse unions, and in the parser for `DeriveInput` check for the `union` keyword and emit an error saying that `union`s are not supported.

What do you think @dtolnay?

**Comment by dtolnay** [comment]
I thought ahead and it's been in the enum since 0.12. https://docs.rs/syn/0.14/syn/enum.Data.html
I was waiting until the compiler allowed derive on unions before we would parse it, but it does now.

**Comment by dtolnay** [comment]
Fixed in b022d0663c3afcc00871fd1685bb77db61435c13.
