### ISSUE TITLE
Parse tool lints

### ISSUE THREAD

**Issue by oli-obk** [dtolnay/syn#464]
`syn` cannot parse `#[deny(clippy::used_underscore_binding)]` 

failing example is https://github.com/rust-lang-nursery/rust-clippy/pull/2977/files#r206082606

**Comment by dtolnay** [comment]
The struct in the error message is already parsed successfully in Syn 0.14.5. Maybe you are using an old version of serde_derive that uses an old version of Syn.

```rust
extern crate syn; // 0.14.5

fn main() {
    let input = "
        /// Test that we do not lint for unused underscores in a `MacroAttribute`
        /// expansion
        #[deny(clippy::used_underscore_binding)]
        struct MacroAttributesTest {
            _foo: u32,
        }";

    println!("{:#?}", syn::parse_str::<syn::DeriveInput>(input).unwrap());
}
```
