### ISSUE TITLE
Compilation mode between "full" and "derive"

### ISSUE THREAD

**Issue by alexcrichton** [dtolnay/syn#467]
I've often found that for `proc_macro_attribute` purposes you often need to parse the function *signature*, but nothing beyond that really needs to be parsed. Namely use cases like `wasm-bindgen` don't need a full expression parser and can get away with the body of a function being internally stored as `TokenStream`.

I'm curious if it would be possible to have an interemediate mode between "full" and "derive" which allows compiling `syn` a bit more quickly. Have others run across this sort of desire before?

**Comment by dtolnay** [comment]
I would be on board with more fine-grained knobs over what you want to support parsing. Do you know of any other attribute macros that would want function signatures only?

**Comment by dtolnay** [comment]
This is now handled by https://github.com/taiki-e/syn-mid.
