### ISSUE TITLE
Converting a TokenStream into a string without inserting spaces

### ISSUE THREAD

**Issue by chinedufn** [dtolnay/syn#468]
## Problem

I'm working on a `css!` procedural macro that takes the CSS that you write and writes it to a file. It currently works fine for a CSS string:

```rust
// Has quotation marks (bad)
static SOME_COMPONENT_CSS: &'static str =  css! {"
    :host {
       color: red;
       background-color: blue;
    }
"};
```

I've found that [using strings is a bit frustrating](https://github.com/chinedufn/percy/issues/17) here, so I want this to instead look like:

```rust
// No quotation marks (good)
static SOME_COMPONENT_CSS: &'static str =  css! {
    :host {
       color: red;
       background-color: blue;
    }
};
```

Calling `token_stream.to_string()` leads to the following output:

`: host { color : red ; background - color : blue ; }`

Note that there are spaces between the hyphens in `background - color`, which for my use case would be invalid CSS.

## Potential Solution

The first potential solution that comes to mind is a second function `to_source_string()` (I'm sure that there's a better nice for this) that uses the `Span` information in order to compose a String that doesn't have spaces in between symbols that didn't have spaces to begin with.

If that's something that would fit into `syn`, I'd be happy to implement it if you could provide a little guidance. Meanwhile I'm poking around the API docs to figure out how I might do such a thing in my own proc macro.

## Questions

- Is that the best way to go about solving my problems here? If not, what is a better / easier approach?

- Would it be possible to convert the token stream into a string **after** getting the identifier values? i.e. would this be do-able?:

```rust
pub static RE_USABLE_COLOR: &'static str = "magenta"l

static HOMEPAGE_HERO_CSS: &'static str = css! {
:host.large#some-id {
    // Use other variables from our macro
    background-color: *RE_USABLE_COLOR
}
};
```

- I'd mainly like to avoid needing to implement `Synom` and writing a real parser for the CSS (mostly because I'm currently unsure about how to go about that and would need to read the docs a bit more), so being able to hackilly turn a token stream into a string would be heavily preferred if it's possible here! If not I can get something working using `syn`.

## Thanks!

For any insight that you might have here!

**Comment by dtolnay** [comment]
I would try it. `first.span().source_file().path() == second.span().source_file().path() && first.span().end() == second.span().start()` will tell you whether two consecutive tokens are not separated by whitespace. Be aware that this approach makes it impossible to build helpers around `css!` such as in the following. If you want to support helper macros, you will need CSS-specific logic to infer where to put spaces without looking at the token spans.

```rust
macro_rules! host_background {
    ($( $k:ident = $v:tt ; )*) => {
        :host {
            $(
                background-$k = $v;
            )*
        }
    };
}
```

Regarding reference to statics by name, I believe that is not possible. Name resolution ("which thing called `RE_USABLE_COLOR` does this refer to?") happens much later after macro expansion.

**Comment by chinedufn** [comment]
Thank you so much for this incredibly helpful guidance. This has certainly saved me hours of time. Much appreciated!

Alright I'm going to close this issue and re-think about the exact API that I want here now that I better understand my options. Thanks so much for the help!
