### ISSUE TITLE
Implement Debug for all types

### ISSUE THREAD

**Issue by Ekleog** [dtolnay/syn#474]
Just thinking it'd be great to have `Debug` implemented for all `syn` types, as that'd make understanding what's going on when debugging much easier :)

Anyway, thank you for your work on `syn`! :)

**Comment by dtolnay** [comment]
Check out https://github.com/dtolnay/syn#optional-features. If you find a type missing a Debug impl, please send a PR.

**Comment by Ekleog** [comment]
Oh indeed, thank you and sorry for the spurious bug report!
