### ISSUE TITLE
codegen sub-crate broken

### ISSUE THREAD

**Issue by djmcgill** [dtolnay/syn#475]
Hi I was looking at the codegen module (to add a FoldSafe trait which passes a Result) but running the codegen crate on a clean master on nightly 2018-08-27 results in:
`'procedural macro API is used outside of a procedural macro', `

Full backtrace is here: https://pastebin.com/raw/SNqRzGmC
What changes has nightly been making to macros? Which nightly version does this sub-crate work on?

Edit: having said that, the file `gen/fold-safe.rs` does seem to have been generated somehow, despite the panic happening at the start of codegen's main? I tried a few different things so it might be a red herring but I'm certainly confused.

**Comment by dtolnay** [comment]
Looks like everything works anyway but the panic message is distracting. I filed https://github.com/alexcrichton/proc-macro2/issues/122 to figure out a better way to handle using proc-macro2 from outside of a procedural macro.
