### ISSUE TITLE
Get the bare name of a raw Ident

### ISSUE THREAD

**Issue by konstin** [dtolnay/syn#478]
Currently, all to string conversions on `Ident` return the ident verbatim, e.g. `r#move` as `r#move`. It would be very useful to have a way to get the bare name, e.g. `move`.

This would be useful e.g. for creating wrappers in pyo3:

```rust
fn function_wrapper_ident(name: &syn::Ident) -> syn::Ident {
    syn::Ident::new(&format!("__pyo3_get_function_{}", name), Span::call_site())
}
```

This version errors when given `r#move` with `"__pyo3_get_function_r#move" is not a valid identifier`. It's possible to work around this by replacing `r#` with an empty string, but I'd prefer it if syn provided a method for that.

**Comment by konstin** [comment]
It seems that using `mashup! { m["method"] = __pyo3_get_function_ $function_name; }` in mashup also doesn't work with raw identifiers, but I couldn't get a proper macro expansion from rustc to confirm this.

**Comment by dtolnay** [comment]
Ah yeah we hit this in serde_derive as well and ended up doing:

```rust
let suffix = ident.to_string().trim_left_matches("r#").to_owned();
let dummy_const = Ident::new(&format!("_IMPL_SERIALIZE_FOR_{}", suffix), Span::call_site());
```

The `syn::Ident` type is just copied from the compiler's [`proc_macro::Ident`](https://doc.rust-lang.org/proc_macro/struct.Ident.html) so this would need to be implemented here first: https://github.com/rust-lang/rust/blob/master/src/libproc_macro/lib.rs before we would pick it up in Syn.
