### ISSUE TITLE
How to parse like format! macro?

### ISSUE THREAD

**Issue by csharad** [dtolnay/syn#483]
I have a case where I need to parse `{ //contents }`, `{{ //escaped }}`, `{{` and `}}` like `format!` macro does but without double quotes.
```rust
html!  {
  <div> Hello { name } </div>
  <div> {{ 1, 2, 3, 4 }} </div>
  <div> Opening brace: {{ </div>
  <div> Closing brace: }} </div>
}
```

But we are not allowed to match against them other than as `braced`. How do you match against a single `{` without converting it to a string (and with a custom parser)? Also, converting it to string loses its Span information.
Do the braces and others come as pairs only? Is matching against a single `{`, `}` possible?

**Comment by dtolnay** [comment]
All macros in Rust enforced balanced delimiters. Otherwise there would be no way to tell where an invocation ends.

```rust
html! {
    }}
}
```

**Comment by csharad** [comment]
Oh! I was trying to do the impossible. Thanks for clarifying it this fast. :smile: :+1:
