### ISSUE TITLE
Is CHANGELOG missing?

### ISSUE THREAD

**Issue by greyblake** [dtolnay/syn#496]
Hey, thanks for the nice crate that enable metaprogramming for us :)

I am tried to migrate my library to a new version of `syn`. 
It looks like there are some breaking changes, so I went to this repo to check CHANGELOG. But I did not find it.

Does it just not exist? What is forgot? Would you consider creating it? Or I am just looking in a wrong place?

Thanks in advance.

**Comment by dtolnay** [comment]
The release notes are linked from the readme. Look for "Release notes".

**Comment by greyblake** [comment]
Ah, cool! Thank you!
