### ISSUE TITLE
Variadic token type

### ISSUE THREAD

**Issue by dhardy** [dtolnay/syn#499]
I am trying to implement a trait using a struct field like so:
```rust
struct MyStruct {
   foo: SpecialType,
   ...
}

// generated derive:
impl SpecialTrait for MyStruct {
   fn x(&self) {
        self.foo.x()
    }
}
```

To do this, I wrote a function like:
```rust
fn find_special_field(data: &Data) -> ??? {
    let ty = ...;
    match data {
        Data::Struct(data) => {
            match data.fields {
                Fields::Named(fields) => {
                    for field in fields.named.iter() {
                        if field.ty == ty {
                            return field.ident.clone();
                        }
                    }
                }
                Fields::Unnamed(fields) => {
                    for (i, field) in fields.unnamed.iter().enumerated() {
                        if field.ty == ty {
                            return Lit::Int(LitInt::new(i, IntSuffix::None, Span::call_site()));
                        }
                    }
                }
            }
        }
       // error handling ...
```

The problem is that in the first case, I want to return an `Ident`, and in the second case a `Lit` (or possibly something else). There is no variadic type (that I can find) which encapsulates this — an `enum` would make sense. Also, since `Token` is a sealed trait, I cannot write such an implementation myself. I also cannot return `Box<Token>` since the trait is not object-safe.

(BTW, why do I feel like everything I want to do with this lib is 10 times harder than it should be? The documentation could be better...)

**Comment by dtolnay** [comment]
I think you are looking for [`syn::Member`](https://docs.rs/syn/0.15/syn/enum.Member.html). For example this is what is used within [`Expr::Field`](https://docs.rs/syn/0.15/syn/struct.ExprField.html) to represent expressions like `obj.k` or `obj.0`.

It doesn't sound like you necessarily need a type that implements the Token trait.

**Comment by dhardy** [comment]
Yes, that sounds like what I was looking for; thanks. I had assumed the `Token` trait was required and checked the implementations — hence didn't see this.
I guess I should have looked at the [quote documentation](https://docs.rs/quote/0.6.8/quote/macro.quote.html) which does explain the required `ToTokens` bound.

Is there a shortcut to obtain an `Expr::Field` from a `Field`, or when iterating over a `Fields`?
