### ISSUE TITLE
Convert &str to syn::Expr

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#505]
Moved from https://github.com/dtolnay/syn/pull/498#issuecomment-425048537:

---

Is there a better way to convert an `&str` to a literal string expression than this?:

```rust
syn::Expr::Lit(syn::ExprLit {
    attrs: Vec::new(),
    lit: syn::Lit::Str(syn::LitStr::new(s, proc_macro2::Span::call_site())),
})
```

@utkarshkukreti

**Comment by dtolnay** [comment]
Yes I would write this as:

```rust
let e: Expr = parse_quote!(#s);
```

https://docs.rs/syn/0.15/syn/macro.parse_quote.html

**Comment by utkarshkukreti** [comment]
That worked great, thanks!

One minor thing. I'm using Rust's 2018 edition beta which allows importing macros using `use`. To make `parse_quote!` work, I had to add `use quote::quote;` to import the quote macro; I was getting "cannot find macro `quote!` in this scope" without it). I see that the definition of `parse_quote!` references `quote!` directly. Can it be changed to support 2018 without breaking the current Rust edition?
