### ISSUE TITLE
Span information is not preserved for enums with variants that have named fields

### ISSUE THREAD

**Issue by Laaas** [dtolnay/syn#508]
Example:

```rust
enum E {
    Variant {
        field: ()
    }
}
```

Attempting to use the span like this:
```rust
quote_spanned!(input.span()=> compile_error!("Bad stuff");)
```
(where input can be `DeriveInput` or `ItemEnum`) the following will be printed as an error:
```
error: Bad stuff

error: aborting due to previous error

error: Could not compile `syn_enum_span`.

To learn more, run the command again with --verbose.
```

This obviously does not provide any useful information to the user: not even a filename is shown.

An example project is available here: 
[syn_enum_span.tar.gz](https://github.com/dtolnay/syn/files/2431035/syn_enum_span.tar.gz)

My version of rustc: `rustc 1.29.1 (b801ae664 2018-09-20)`

**Comment by dtolnay** [comment]
This is a compiler bug -- https://github.com/rust-lang/rust/issues/43081.

As a workaround, you can write `enum E { Variant { field: (), }, }` with that extra comma to preserve span information.

**Comment by dtolnay** [comment]
Good idea, that seems reasonable. I would accept a pull request for that behavior.
