### ISSUE TITLE
Parse macro_rules!() body

### ISSUE THREAD

**Issue by lukaslueg** [dtolnay/syn#510]
There is an out-of-tree [parser](https://github.com/lukaslueg/macro_railroad/blob/master/src/parser.rs) for the body of `macro_rules!()` in `macro_railroad` that I'm contemplating to port to `0.15`. Are there plans to do this in `syn` itself?

**Comment by dtolnay** [comment]
I am not planning to do it in Syn. I would rather see the data structures and parsers in a crate by themselves like https://crates.io/crates/macro_rules.

**Comment by lukaslueg** [comment]
As far as I can see, `syn 0.15` does not have a `Punct`, while it does have a `Lit`. Is there a deeper reason?

**Comment by dtolnay** [comment]
Multi-character punctuation is a macro_rules concept, so if Syn does not provide a macro_rules parser then we also don't need to provide multi-character punctuation support. Literals exist elsewhere in native Rust syntax such as expressions and attributes.
