### ISSUE TITLE
syn::DeriveInput's attribute 'attrs' has always zero length

### ISSUE THREAD

**Issue by fpcsong** [dtolnay/syn#520]
I write a custom derive use **syn** and **quote**, it's very simple, just below 
```rust
#![feature(extern_crate_item_prelude)]
extern crate proc_macro;
extern crate syn;
#[macro_use]
extern crate quote;
use proc_macro::TokenStream;
use syn::{parse_macro_input, DeriveInput};
#[proc_macro_derive(HelloMacro)]
pub fn hello_macro_derive(input: TokenStream) -> TokenStream {

    let ast = syn::parse_macro_input!(input as DeriveInput);
    
    let gen = impl_hello_macro(&ast);
    gen
}
fn impl_hello_macro(ast: &syn::DeriveInput) -> TokenStream {
    let name = &ast.ident;
    let n = &ast.attrs.len();// problem occured here 
    let gen = quote! {
        impl HelloMacro for #name {
            fn hello_macro() {
                println!("Hello, Macro! My name is {}", stringify!(#name));
                println!("I have {} items", #n);
            }
        }
    };
    gen.into()
}

```
the code is worked but whatever struct derived the *HelloMacro*, always get 0 item, I tried hard but anything changed.

**Comment by dtolnay** [comment]
I believe this is by design. Derive macros are intentionally quite limited to force them to have consistent predictable behavior. They don't get to see unrelated attributes on the input item.

A `proc_macro_attribute` may be able to see other attributes but I don't know for sure.

**Comment by fpcsong** [comment]
> A `proc_macro_attribute` may be able to see other attributes but I don't know for sure.

@dtolnay I have test the ```proc_macro_attribute``` but  it doesn't work. Thanks for your quick reply :+1: , so there is no way derive macros to read a type's items?

**Comment by dtolnay** [comment]
If `proc_macro_attribute` doesn't get them either then I guess there isn't.

**Comment by fpcsong** [comment]
Thanks for your help :), I will close this issue.

**Comment by dhardy** [comment]
@fpcsong I think the expected usage is to annotate all other attributes you will use:

`#[proc_macro_derive(HelloMacro, attributes(hello, name))]`

I only discovered this though looking at examples; @dtolnay is it supposed to be documented somewhere?

**Comment by hcpl** [comment]
For me, when I was reading Rust book for the first time, I stumbled on https://doc.rust-lang.org/book/first-edition/procedural-macros.html#custom-attributes which is specifically about attributes that get recognized by a `proc_macro_derive`. That was 1.5 years ago, when only the first version of the book existed.

I can't find an analogous section in its second version, maybe that's why people get confused.
