### ISSUE TITLE
Inconsistent: syn::Ident vs input.peek(Ident)

### ISSUE THREAD

**Issue by limira** [dtolnay/syn#522]
I use `syn` for the first time and at first I was very confused because of this inconsistency:
* `syn::Ident` include Rust's keywords, but
* `input.peek(Ident)` return `false` for the keywords.

I think this should be consistent.

A related side question. Currently, if I want to expect both `keywords` and *legal variable name*, instead of `input.peek(Ident)`, I have to
```rust
let tt: TokenTree = input.fork().parse()?;
let is_ident = if let TokenTree::Ident(_) = tt {
    true
}else{
    false
};
```
Is there a better solution for this?

**Comment by dtolnay** [comment]
`input.parse::<Ident>()?` does not include keywords. It consistently accepts the same set of inputs as `input.peek(Ident)`. You would need to use `input.call(Ident::parse_any)?` to accept keywords. I believe this is the most commonly desired behavior for macros where the input syntax is similar to Rust.

**Comment by limira** [comment]
Thank you!

I know that `parse::<Ident>()` and `peek(Ident)` are consistent. But they are not consistent to `syn::Ident`, despite they are all **appear** to be `Ident`. Do you think it is better to add a special note about it [around here](https://github.com/dtolnay/syn/blob/master/src/parse.rs#L437-L452)?
```
    /// # Special case for Ident
    ///
    /// Please note that `input.peek(Ident)` does not include Rust's keywords.
    /// If you want to peek both variables and keywords, you may have to
    /// ```
    /// input.fork().call(Ident::parse_any)?
    /// ```
    ///
```
