### ISSUE TITLE
Span information for additional attributes parsed by procedural derive

### ISSUE THREAD

**Issue by dhardy** [dtolnay/syn#523]
When implementing `Parse::parse`, if input is required but the stream is empty, there does not appear to be any way of getting the `Span` for the relevant position in the input stream.

For example, a custom derive may attempt to read custom attributes of the form `#[foo(args...)]` and parse the arguments by implementing `Parse` on a custom struct; if `#[foo]` is encountered (no arguments), the error message is confusing because it points to the `derive` argument, not the custom attribute.

**Comment by dtolnay** [comment]
This would need to be a feature request to the compiler. None of the spans in `#` `[` `foo` `]` are currently made available to the procedural macro.

**Comment by dhardy** [comment]
You mean the spans in `attr.tts`? Those do seem to be missing within the parse.

But, for example, for `DeriveInput::attrs`:
```rust
    let mut layout = None;
    for attr in ast.attrs.drain(..) {
        if attr.path == parse_quote!{ layout } {
            if layout.is_none() {
                ...
            } else {
                attr.span()
                    .unstable()
                    .error("multiple #[layout(..)] attributes on type")
                    .emit()
            }
```
will emit:
```
error: multiple #[layout(..)] attributes on type                                                                                       
  --> src/control.rs:12:1                                                                                                              
   |                                                                                                                                   
12 | #[layout]                                                                                                                         
   | ^^^^^^^^^                                                                                                                         
```

**Comment by dtolnay** [comment]
Ah good call. Sorry! I was confused with proc_macro_attribute macros which are handled differently.

So what we'd like is for the following code to produce an error pointing to the `#[layout]` attribute, or to the layout attribute's closing square bracket or something.

#### my_macro/src/lib.rs

```rust
extern crate proc_macro;
use self::proc_macro::TokenStream;

use syn::{DeriveInput, Ident};

#[proc_macro_derive(MyDerive, attributes(layout))]
pub fn derive(input: TokenStream) -> TokenStream {
    let ast = syn::parse_macro_input!(input as DeriveInput);

    let attr = ast.attrs[0].tts.clone();
    syn::parse2::<Ident>(attr).unwrap_err().to_compile_error().into()
}
```

#### testing/src/lib.rs

```rust
#[derive(my_macro::MyDerive)]
#[layout]
struct S;
```

```console
error: unexpected end of input, expected identifier                                                                            
 --> src/lib.rs:1:10                                                                                                          
  |                                                                                                                            
1 | #[derive(my_macro::MyDerive)]                                                                                              
  |          ^^^^^^^^^^^^^^^^^^
```

**Comment by dhardy** [comment]
Precisely. I guess it's a limitation of derive.

BTW how come `proc_macro_derive` supports `attributes(layout)` but `proc_macro_attribute` doesn't?

**Comment by dtolnay** [comment]
There is no good reason. Somebody just needs to implement it. I don't think supporting `attributes(layout)` for `proc_macro_attribute` would be controversial.
