### ISSUE TITLE
Debugging macros: support `Display` or `Debug` on `syn::parse::ParseBuffer`?

### ISSUE THREAD

**Issue by dhardy** [dtolnay/syn#524]
Debugging over `TokenStreams` is easy since they support `Display`. `ParseBuffer` doesn't.

How can I debug the contents of a `ParseBuffer` which doesn't match the parse rules?

**Comment by dtolnay** [comment]
I would be on board with adding Display and Debug for ParseBuffer by formatting the same as a TokenStream. Could you send a PR? You can extra the TokenStream of the remainder of the buffer by writing:

```rust
buffer.step(|cursor| Ok((cursor.token_stream(), *cursor)))
```

**Comment by dhardy** [comment]
I have a patch, but is `cargo test` supposed to fail? Does so on both nightly and 1.30 stable.
