### ISSUE TITLE
`Attribute::parse_meta()` cannot parse expressions

### ISSUE THREAD

**Issue by idanarye** [dtolnay/syn#527]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=319a10314bef3fad777900fa5605aca3

`syn` will cannot parse `#[foo = bar()]` - because `bar()` is an expression and not a literal.

Why is that? Why can't we have `parse_meta()` parse expressions?

**Comment by dtolnay** [comment]
Meta items are structured attributes according to the three cases in https://docs.rs/syn/0.15/syn/enum.Meta.html. `#[foo = bar()]` is not structured in that way. You can confirm that it is not a valid meta item by checking $:meta in macro_rules:

```rust
macro_rules! parse_meta {
    (#[$m:meta]) => {};
}

parse_meta! {
    #[foo = "bar"] // okay
}

parse_meta! {
    #[foo = bar()] // not a meta item
}
```
