### ISSUE TITLE
parsing statements without consuming a trailing semicolon

### ISSUE THREAD

**Issue by CensoredUsername** [dtolnay/syn#528]
The rustc internal parser API would parse statements without parsing the trailing semicolon. When porting a plugin to proc-macro using syn I naively replaced the statement parsing to `input.parse::<syn::Stmt>()`, but this would always consume a trailing semicolon if one was present.

Would it be possible to add an additional parsing function to `syn::Stmt` that never consumes a trailing semicolon?

**Comment by CensoredUsername** [comment]
I've been working on [dynasm](https://github.com/CensoredUsername/dynasm-rs) which has semicolon-delimited syntax like this:

```rust
dynasm!(ops
    ; inc rax
    ;->label:
    ;; a_random_function_call()
    ; jmp ->label
)
```

The double semicolon is syntax for inserting an arbitrary expression inbetween the assembly to be emitted. In the old parser this did not need a trailing semicolon, but for the syn-based one I now either need to special case the leading semicolon handling of the next line or require an extra trailing semicolon for the statement.

Additionally, the rust macro stmt matcher does not consume a semicolon as well. It made the behaviour somewhat surprising.

**Comment by dtolnay** [comment]
The `$:stmt` fragment in macro_rules has pretty broken semicolon behavior so it is not a good model to follow. See below. I think Syn's stmt is doing the right thing.

```rust
macro_rules! m {
    ($($s:stmt);*) => {};
}

m! {
    struct S;; // two semicolons required because $:stmt consumes one of them
    struct S {}; // semicolon shouldn't be required here in Rust syntax
    let a = 1 // Rust grammar always requires semicolon after let-stmt but macro does not
}
```

I would implement this as: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=589cac7bd5ae52c56114913e860dc2ec)

**Comment by CensoredUsername** [comment]
I've implemented your solution and it has solved the issue for me. Thanks for the help!
