### ISSUE TITLE
Error in the documentation for ParseBuffer::step

### ISSUE THREAD

**Issue by jeremydavis519** [dtolnay/syn#529]
The documentation found [here](https://docs.rs/syn/0.15/syn/parse/struct.ParseBuffer.html#method.step) gives this example:

```
use proc_macro2::TokenTree;
use syn::parse::{ParseStream, Result};

// This function advances the stream past the next occurrence of `@`. If
// no `@` is present in the stream, the stream position is unchanged and
// an error is returned.
fn skip_past_next_at(input: ParseStream) -> Result<()> {
    input.step(|cursor| {
        let mut rest = *cursor;
        while let Some((tt, next)) = cursor.token_tree() {
            match tt {
                TokenTree::Punct(ref punct) if punct.as_char() == '@' => {
                    return Ok(((), next));
                }
                _ => rest = next,
            }
        }
        Err(cursor.error("no `@` was found after this point"))
    })
}
```

But the same example for [`StepCursor`](https://docs.rs/syn/0.15/syn/parse/struct.StepCursor.html) is slightly different, with the 10th line being

```
        while let Some((tt, next)) = rest.token_tree() {
```

That is, it uses `rest` instead of `cursor`.

The first example implies that a `StepCursor` automatically advances as you call `token_tree`, which I assume is wrong.

**Comment by dtolnay** [comment]
Thanks! The one on StepCursor was correct. Fixed in db312587463ae53e4917c85559320031cdffabd8 and added a test.
