### ISSUE TITLE
.span() returns Span over the first inner element

### ISSUE THREAD

**Issue by XBagon** [dtolnay/syn#531]
I tried to return an error to signal a wrong function signature with the corresponding span (of the function signature/decleration). First I tried to use `.span()` on the `FnDecl` which sadly isn't implemented, so I just tried the whole `ItemFn`, which returned only a `Span` over the `fn` token. The same thing happens with most things I tried, just the first inner element is included in the returned `Span`. I'm not sure what the use of that is, maybe I'm misunderstanding things.

**Comment by dtolnay** [comment]
This is a limitation of the stable API surface area currently exposed by `proc_macro::Span`. https://doc.rust-lang.org/1.30.0/proc_macro/struct.Span.html provides no stable way to combine adjacent spans into a single span.

You could wait for that functionality to stabilize, or [use it in its current unstable form](https://github.com/alexcrichton/proc-macro2#unstable-features) by setting `RUSTFLAGS='--cfg procmacro2_semver_exempt'` when you compile your project.

**Comment by XBagon** [comment]
Oh I see, I thought `proc-macro2` would enable that by default, couldn't find any information about it, so thank you!
Also is there a reason to `FnDecl` not having an `Spanned` implementation?

**Comment by dtolnay** [comment]
FnDecl is not one contiguous range of adjacent tokens. It includes the `fn` keyword which is left of the function name, and the argument list which is right of the function name, but not the function name itself. There is no such thing as a span with a gap like that.

**Comment by XBagon** [comment]
Oh that makes sense, missed that it's missing the name. I guess I will just combine/make the `Span` manually. Thanks!
