### ISSUE TITLE
Explicit enum discriminants which index into tuples don't parse 

### ISSUE THREAD

**Issue by illicitonion** [dtolnay/syn#533]
I realise this is a bizarre and esoteric piece of rust, and closing this as WontFix would be perfectly reasonable, _but_, rustc compiler is happy with it and `syn` isn't, so I figured I'd file the issue in case anyone's interested... :)

Syn errors with `Unexpected token` if it encounters the following code:
```rust
enum E {
  Zero = (0, 1).0,
}
```

See full self-contained repro at https://github.com/illicitonion/syn-repro-enum-tuple

**Comment by dtolnay** [comment]
You will have to set the `"full"` feature to enable parsing the full range of expression syntax if you need this to work. By default we only parse a basic subset of expression syntax that commonly appears in the length position of array types, to keep compile times sane.

https://github.com/dtolnay/syn#optional-features

**Comment by illicitonion** [comment]
Right you are! Thanks!
