### ISSUE TITLE
how to create an ident from a string

### ISSUE THREAD

**Issue by softprops** [dtolnay/syn#546]
I'm in the process of a crate from 0.11 => 0.15.22 ( the latest as of today ) and am trying to figure out what the equivalent of 0.11's `From` impl for strs is in the latest release. `Ident::from(format!("{}Key", name))` . There is a [new](https://docs.rs/syn/0.15.22/syn/struct.Ident.html#method.new) method but requires proc_macro2 for Span::call_site() however this Span comes from the `proc_macro2` crate which I haven't needed to depend on yet. I see that the rust proper `proc_macro` crate has a stable version of that [here](https://doc.rust-lang.org/1.30.0/proc_macro/struct.Span.html#method.call_site)

Is there a way to construct an Ident in the latest syn _without_ pulling in the proc_macro2 crate?

**Comment by hcpl** [comment]
`syn` depends on `proc-macro2` already, so depending on it yourself shouldn't add a new entry to the dependency set of your crate.

**Comment by softprops** [comment]
👍

**Comment by hcpl** [comment]
One of the main reasons `proc-macro2` exists is to support current `proc-macro` API on all stable Rust versions back to 1.15. I think this particular design restriction is motivated a lot by `serde_derive` which promised to work on Rust >=1.15 since its 1.0.0 release and today is still 1.0.* which disallows breaking changes.

**Comment by dtolnay** [comment]
The 1.15 compatibility is a side benefit. The main reason is that none of the data structures from `extern crate proc_macro` can be used outside of the context of a procedural macro. If Syn were implemented against proc_macro types, that would make it unusable in a build.rs or main.rs. By using proc-macro2 we support those use cases in addition to the procedural macro use case.

I would like to see even more code move to proc-macro2 by having the compiler accept proc-macro2 types in the signature of #[proc_macro_derive] functions. That way nothing would depend on `extern crate proc_macro` except for within the implementation of proc-macro2.

**Comment by dtolnay** [comment]
@hcpl https://github.com/rust-lang/rust/pull/49219 is not related to this. It does not make proc_macro usable outside of a procedural macro. It is still the case that proc-macro2 is required if I want to support build.rs and main.rs use cases. Try running:

```rust
extern crate proc_macro;
use proc_macro::{Ident, Span};

fn main() {
    println!("{}", Ident::new("i", Span::call_site()));
}
```

**Comment by hcpl** [comment]
Huh, I didn't follow the thread and assumed that decoupling `proc_macro` implies refactoring the internals to be like `proc-macro2` and the ability to upload `proc_macro` to crates.io, but IIUC that PR was just about internal modularization to not use dynamic linking. My bad.
