### ISSUE TITLE
Provide a simple visitor example

### ISSUE THREAD

**Issue by Shnatsel** [dtolnay/syn#549]
I'm trying to implement a fairly simple visitor to find all function definitions, then eventually expand it to find only public function definitions.

I'm having a really hard time figuring out how to write the simplest possible visitor. The closest thing I could find is "trace-var" example, but it's very complicated for someone seeing `syn` for the first time and is not really helpful.

The simplest possible visitor example that just finds a specific thing in AST and prints it would be **very** welcome.

A basic example that keeps track of context and can filter for e.g. `pub fn` definitions would also be helpful; I think I know how to implement that, but it took me a while to figure it out.

**Comment by dtolnay** [comment]
Thanks, I agree we need a simple example in https://docs.rs/syn/0.15.23/syn/visit/. Here is one for now:

```rust
// [dependencies]
// quote = "0.6"
// syn = { version = "0.15", features = ["full", "visit"] }

use quote::quote;
use syn::{File, ItemFn, visit::Visit};

struct FnVisitor;

impl<'ast> Visit<'ast> for FnVisitor {
    fn visit_item_fn(&mut self, f: &'ast ItemFn) {
        let name = &f.ident;
        let vis = &f.vis;
        println!("Function with name={} vis={}", name, quote!(#vis));
        syn::visit::visit_item_fn(self, f);
    }
}

fn main() {
    let code = quote! {
        pub fn f() {
            fn g() {}
        }
    };

    let syntax_tree: File = syn::parse2(code).unwrap();
    FnVisitor.visit_file(&syntax_tree);
}
```

**Comment by dtolnay** [comment]
I added some examples in d249c84e8ae01b0b814b4a7dc023d92f28f5714b, 03a4b7047b884970d6b8c5704c98f1a129da42cb, a18805e346b70935356beed00c281f06ba993a82, a483e2bb2ff6551e408e7e6d4a39619ba278031e.
