### ISSUE TITLE
Example like `lazy_static` for Rust 2018?

### ISSUE THREAD

**Issue by dherman** [dtolnay/syn#551]
Hi there! I'm trying to understand how to use `syn` to write a procedural macro in stable Rust, now that they've been stabilized. The `lazy_static` example seems like a really nice entry point, but it seems to be written for unstable Rust. Is it possible to do with stable Rust now? I'm brand new to procedural macros and having a hard time figuring how to get off the ground.

**Comment by dtolnay** [comment]
Lazy-static is the right example to be looking at. Currently the only part that is unstable is emitting diagnostics ([here](https://github.com/dtolnay/syn/blob/ab3ff960ef764cfb6985b48b400729022e0e24d4/examples/lazy-static/lazy-static/src/lib.rs#L68-L71) and [here](https://github.com/dtolnay/syn/blob/ab3ff960ef764cfb6985b48b400729022e0e24d4/examples/lazy-static/lazy-static/src/lib.rs#L83-L86)). Everything else shown is stable as of Rust 1.30 and is how you would implement function-like procedural macros.

For diagnostics on a stable compiler you would either have the macro panic or emit a [`compile_error!`](https://doc.rust-lang.org/std/macro.compile_error.html) into its output token stream.

This search turns up many other good examples of function-like procedural macros (as long as you skip over all the ones that are just vendored copies of syn):

- https://github.com/search?l=Rust&q=%22fn+parse+input+parsestream%22&type=Code

**Comment by dtolnay** [comment]
You should get reasonably good parse errors for free just by using [`syn::parse`](https://docs.rs/syn/0.15/syn/parse/index.html) together with [`syn::parse_macro_input!`](https://docs.rs/syn/0.15/syn/macro.parse_macro_input.html). For example if you break the lazy-static input:

```console
error: expected `ref`
 --> src/main.rs:8:12
  |
8 |     static USERNAME: Regex = {
  |            ^^^^^^^^
```

Notice how the implementation contains no visible error reporting. It's done behind the scenes by the library.

For *custom syntax errors* you want [`Lookahead1::error`](https://docs.rs/syn/0.15/syn/parse/struct.Lookahead1.html#method.error) or [`ParseStream::error`](https://docs.rs/syn/0.15/syn/parse/struct.ParseBuffer.html#method.error) which wire up the spans for you.

For *custom errors during parsing* you want the `Parse` impl to return a `syn::Error` constructed by [`Error::new`](https://docs.rs/syn/0.15/syn/struct.Error.html#method.new) if it spans a single token or [`Error::new_spanned`](https://docs.rs/syn/0.15/syn/struct.Error.html#method.new_spanned) if it spans multiple tokens.

For *errors after parsing* you want `Error::new` or `Error::new_spanned` followed by [`to_compile_error()`](https://docs.rs/syn/0.15/syn/struct.Error.html#method.to_compile_error) and embedding that compile error into the macro output token stream.

**Comment by dherman** [comment]
Update: With some more help from @dtolnay on Discord, I've managed to get some good error messages implemented. If anyone's interested, it's still a work in progress but the PR is here: https://github.com/notion-cli/notion/pull/231

Thanks for the help, Daniel!
