### ISSUE TITLE
match syn::Type, but ignore lifetime names?

### ISSUE THREAD

**Issue by davemilter** [dtolnay/syn#552]
I want match types (`syn::Type`) and generate code depending on type.

For example for `&str` and `&'a str` I want generate the same code.
More complex example `(&'a str, &'a str)` == `(&str, &str)` == `(&'x str, &'x str)`,
but not equal `(&'a str, &'b str)`, while
`(&'a str, &'b str)` = `(&'x str, &'y str)`.

Should I implement it by hands, or there is somewhere such code?

**Comment by dtolnay** [comment]
I don't know of an existing implementation of this. You would need to write the code yourself.

The reference lifetimes are available inside of [`syn::Type::Reference`](https://docs.rs/syn/0.15/syn/struct.TypeReference.html).

**Comment by davemilter** [comment]
Thank you, @dtolnay!
