### ISSUE TITLE
Using parse2 to get quote back to a syn type

### ISSUE THREAD

**Issue by xrl** [dtolnay/syn#553]
I am writing unit tests and I can't compare `quote!{}` output with itself, it does not implement `PartialEq`. I have started using `syn::parse2` to convert the TokenStream back to something I can compare but now I have the issue that a `TokenStream` won't parse back to what I expect.

```
    let something : syn::Expr = syn::parse2(quote! {
      {
        let a = "hello";
      }
    }).unwrap();
```

I expect `something` to be a `syn::Expr::Block` but when I run this I get:

```
thread 'field_info::test::simple_struct_to_writer_snippet' panicked at 'called `Result::unwrap()` on an `Err` value: Error { start_span: Span, end_span: Span, message: "unsupported expression; enable syn\'s features=[\"full\"]" }', src/libcore/result.rs:1009:5
stack backtrace:
```

Is there anyway to ask `syn` what the `quote!{}`'d body should be? Since the parser is exact it should have one possible high level type?

And in my case, any idea what `something` should be in this case?

**Comment by dtolnay** [comment]
At the risk of stating the obvious -- the error message says to enable `features = ["full"]` on your Syn dependency to support parsing the full Rust grammar including block expressions. Once you enable the feature, that input will parse successfully.

Otherwise you could try comparing the token streams as strings by calling to_string() on both sides.

**Comment by xrl** [comment]
🤦‍♂️ I read that error as `set RUST_BACKTRACE=full`. Which I did and did not end up helping!

I didn't realize this was a possibility because I've been able to parse things like `Ident`s. I didn't know there were different classes of parseable expressions. I should have read more closely!

Thanks! Closing.
