### ISSUE TITLE
Macro to quickly parse content in angle brackets, `<..>`

### ISSUE THREAD

**Issue by Lokathor** [dtolnay/syn#555]
There seems to be macros for `(..)`, `{..}`, and `[..]`, but we don't have one for `<..>`

**Comment by totorigolo** [comment]
I played a bit with Yew's `html!` macro, and I wonder how such a macro can handle cases like those ones:

```rust
html! {
    <button onclick=|_| 2 > 1 />
    <div onclick=|_| -> u32 0 ></div>
}
```

**Comment by leontepe** [comment]
@dtolnay isn't it a problem that `>` and `<` are already defined as punctuation, and not as delimiters? Wouldn't this be the first occurrence of "doubly defined" tokens?

**Comment by leontepe** [comment]
I'm thinking that there could be something like `Entry::CustomGroup` containing a `CustomDelimiterPair`, in which pairs of `Token`s are defined that should act as delimited group.

This could allow not only cases like `<...>`, but also more involved custom syntax:

- `#...#`
- `%...%`
- `$...$`

or even asymmetrical ones:

- `[...)` (possible use case: math syntax for a [right-open interval](https://en.wikipedia.org/wiki/Interval_(mathematics)#Terminology)?)

et cetera.

This could also open up a larger field of Rust based syntax extensions, for which `syn` could (behind heavy feature gates) provide ergonomic extension capabilities. Another example that comes to mind would be a `CustomItem`.

**Comment by leontepe** [comment]
I'd be happy to work on this, if it has a realistic chance of being upstreamed @dtolnay :)

**Comment by dtolnay** [comment]
I think this won't work, on account of https://github.com/dtolnay/syn/issues/555#issuecomment-518029851. It matters what kind of content is being parsed in between the angle brackets to determine how they are matched, so we might as well make you parse the angle brackets normally as well.
