### ISSUE TITLE
Allow Error to return both kinds of span

### ISSUE THREAD

**Issue by ivanbakel** [dtolnay/syn#566]
This is the most polished crate I've ever had the joy to use! The one snag I've hit is that the inbuilt `Error` only provides `proc_macro2` spans.

Would it be possible to have a way to get a `proc_macro` span out?
Maybe `span()` and `span2()`? Though that would be a breaking change.

**Comment by dtolnay** [comment]
Check out this method for converting proc_macro2::Span to proc_macro::Span:

https://docs.rs/proc-macro2/0.4.25/proc_macro2/struct.Span.html#method.unstable

**Comment by ivanbakel** [comment]
Handy, thanks! But worth mentioning that I had to specify a much more recent version of proc_macro2 to get it to build.
