### ISSUE TITLE
syn::Error apparently ignoring span?

### ISSUE THREAD

**Issue by TedDriggs** [dtolnay/syn#570]
I have an `Error` struct, which is shown below:

```rust
/// An error encountered during attribute parsing.
///
/// Given that most errors darling encounters represent code bugs in dependent crates,
/// the internal structure of the error is deliberately opaque.
#[derive(Debug)]
#[cfg_attr(test, derive(Clone))]
pub struct Error {
    kind: ErrorKind,
    locations: Vec<String>,
    /// The span to highlight in the emitted diagnostic.
    span: Option<Span>,
}

impl Error {
    /// Check if this error is associated with a span in the token stream.
    pub fn has_span(&self) -> bool {
        self.span.is_some()
    }

    pub fn with_span<T: Spanned>(mut self, node: &T) -> Self {
        if !self.has_span() {
// DBG: Check that we're setting the right span
            eprintln!("{:?}", node.span());
            self.span = Some(node.span());
        }

        self
    }

    /// Recursively converts a tree of errors to a flattened list.
    pub fn flatten(self) -> Self {
        Error::multiple(self.into_vec())
    }

    fn into_vec(self) -> Vec<Self> {
        if let ErrorKind::Multiple(errors) = self.kind {
            let mut flat = Vec::new();
            for error in errors {
                flat.extend(error.prepend_at(self.locations.clone()).into_vec());
            }

            flat
        } else {
            vec![self]
        }
    }

    pub fn write_errors(self) -> TokenStream {
        self.flatten()
            .into_iter()
            .map(|e| e.single_to_syn_error().to_compile_error())
            .collect()
    }

    fn single_to_syn_error(self) -> syn::Error {
// DBG: Check that we're still holding the right span
        eprintln!("{:?}", self.span);
        match self.span {
            Some(span) => syn::Error::new(span, self),
            None => syn::Error::new(Span::call_site(), self),
        }
    }
}
```

This struct can be converted either to `syn::Error` or to `proc_macro::Diagnostic`, based on a crate feature flag. When I use it with the `diagnostics` feature flag, it emits compiler errors that point to the correct span in the input. However, when I switch to using `write_errors`, it points to `Span::call_site()`, despite showing via println that it knows the correct span. 

I looked at serde's use of `Error::new_spanned`, but I don't want to keep more than is necessary in the error struct, and boxing up the syntax node seems wasteful. Am I using `Error::new` incorrectly?

**Comment by dtolnay** [comment]
Would you be able to put together a minimal example that reproduces the problem? What you showed looks like a lot of moving pieces to debug.

**Comment by TedDriggs** [comment]
I should have read my own comment on #523. For some reason, `derive_builder` was roundtripping the tokens to being strings after the code that created the errors, and wiping out the spans. Removing that fixed the issue and everything's working properly now. I'm going to go purge every string roundtrip out of `derive_builder`.
