### ISSUE TITLE
Tests that need rust-lang/rust checkout don't run on Windows

### ISSUE THREAD

**Issue by CAD97** [dtolnay/syn#572]
Specifically, `test_precedence::test_rustc_precedence` and `test_round_trip::test_round_trip` both call `common::clone_rust` which runs `tests/clone.sh`, which obviously doesn't work on Windows.

There are several ways this could be addressed:

- Detect Windows and fail the test with a more useful error than ``called `Result::unwrap()` on an `Err` value: Os { code: 193, kind: Other, message: "%1 is not a valid Win32 application." }``
- Detect Windows and ignore the tests (`#[cfg_attr(target_os = "windows", ignore)]`)
- Rewrite `clone.sh` using Rust
- Provide a Powershell equivalent of `clone.sh` and use that on Windows

**Comment by dtolnay** [comment]
Thanks! I would accept a PR for any of your four suggestions (especially RIIR).

**Comment by dtolnay** [comment]
Repurposing under a different title because ideally these tests could be run on Windows.

**Comment by dtolnay** [comment]
I would accept a PR to rewrite clone.sh in Rust in a way that works on Windows.

**Comment by mati865** [comment]
Clone.sh could be easily made to run on Windows gnu targets.

**Comment by AndyGauge** [comment]
I'd like to dig into this (for hacktoberfest!)

**Comment by dtolnay** [comment]
Okay! Thanks @AndyGauge.
