### ISSUE TITLE
Docs for Spanned::span should mention that it only returns the span of the first token

### ISSUE THREAD

**Issue by TedDriggs** [dtolnay/syn#575]
I just spent some time trying to figure out why errors I emitted were attaching to the `#` of the first attribute in a `Field` before finding [this note](https://github.com/dtolnay/syn/blob/master/src/spanned.rs#L138) in the code for `Spanned`:

> We can't join spans without procmacro2_semver_exempt so just grab the first one.

Having this more clearly called out in the docs for the `span` function would have saved me a considerable amount of confusion.

**Comment by dtolnay** [comment]
Seems reasonable. Probably you should be using [`Error::new_spanned`](https://docs.rs/syn/0.15/syn/struct.Error.html#method.new_spanned) instead of `Spanned::span`.

**Comment by TedDriggs** [comment]
In this case I wasn't directly emitting the error; I was emitting code that would later cause a compile error because the user-provided type didn't implement the required trait. Therefore I had to use `quote_spanned!`.

**Comment by dtolnay** [comment]
Ah that's too bad. Hopefully we can get the span joining stabilized soon!

**Comment by hcpl** [comment]
FWIW, I made this crossbreed of `quote_spanned!` and `syn::Error::new_spanned`:

```rust
macro_rules! quote_spanned_by {
    ($expr:expr=> ) => { ::proc_macro2::TokenStream::new() };
    ($expr:expr=> $($tt:tt)+) => {{
        use std::iter::FromIterator;

        let mut span_tokens = ::quote::ToTokens::into_token_stream($expr).into_iter();
        let start_span = span_tokens.next().map_or_else(::proc_macro2::Span::call_site, |t| t.span());
        let end_span = span_tokens.last().map_or(start_span, |t| t.span());

        let mut end_tokens = quote_spanned!(end_span=> $($tt)*).into_iter();
        let mut start_token = end_tokens.next().unwrap();
        start_token.set_span(start_span);

        ::proc_macro2::TokenStream::from_iter(::std::iter::once(start_token).chain(end_tokens))
    }};
}
```

Example usage:

```rust
// In proc-macro crate
#[proc_macro]
pub fn foo1(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    use syn::spanned::Spanned;
    let input2 = proc_macro2::TokenStream::from(input);
    quote_spanned!(input2.span()=> compile_error!("foo");).into()
}

#[proc_macro]
pub fn foo2(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input2 = proc_macro2::TokenStream::from(input);
    quote_spanned_by!(input2=> compile_error!("foo");).into()
}
```

```rust
// In user crate
macros::foo1!(a + 1);
macros::foo2!(a + 1);
```

Result:

```
error: foo
 --> src/lib.rs:4:15
  |
4 | macros::foo1!(a + 1);
  |               ^

error: foo
 --> src/lib.rs:5:15
  |
5 | macros::foo2!(a + 1);
  |               ^^^^^
```

@dtolnay, should I made a PR that adds this to `quote` (macro name is bikesheddable)?

**Comment by goto40** [comment]
When not using a nightly compiler, only the span of the first token of the syntax tree node is returned.
