### ISSUE TITLE
Macro for constructing Punctuated?

### ISSUE THREAD

**Issue by joshlf** [dtolnay/syn#582]
I find myself frequently doing something like

```
let mut segments = Punctuated::new();
segments.push(ident);
...
```

It'd be great if this could be shortened to `punctuated![ident]` or something similar.

**Comment by dtolnay** [comment]
I recommend using syn::parse_quote. [*playground*](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5c3848448765b2e033f16395ee25d20a)

```rust
use proc_macro2::Span;
use quote::quote;
use syn::{parse_quote, Ident, Token};
use syn::punctuated::Punctuated;

fn joshlf() -> Punctuated<Ident, Token![::]> {
    let ident = Ident::new("joshlf", Span::call_site());
    parse_quote!(std :: #ident)
}

fn main() {
    println!("{:?}", joshlf());
}
```

**Comment by joshlf** [comment]
Ah that works; thanks!
