### ISSUE TITLE
Syn data structures do not implement std::fmt::debug

### ISSUE THREAD

**Issue by dutchmartin** [dtolnay/syn#583]
While trying to build a new procedural macro, I wanted to see what data I was working with, so I tried to use the debug macro and the print line macro, but this does not compile (rust 1.32) since the Debug trait is not implemented. 
For reference, see the code below:

```rust
extern crate proc_macro;

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, DeriveInput};


#[proc_macro_derive(do_stuff)]
pub fn do_stuff(input: TokenStream) -> TokenStream {
// Parse the input tokens into a syntax tree
    let input = parse_macro_input!(input as DeriveInput);

    let name = &input.ident;
    // this line below does not compile.
    dbg!(input);

    let expanded = quote! {
        impl #name {
            pub fn do_some_stuff()  {
                println!("macro fn executed");
            }
        }
        };

    TokenStream::from(expanded)
}
```
Looking at the [declaration](https://github.com/dtolnay/syn/blob/6f1b7f2ee9ae44b73ad7aa3d87f4c7bd07ef7849/src/derive.rs#L4) of the struct, it should have been added since the [`ast_struct`  macro](https://github.com/dtolnay/syn/blob/6f1b7f2ee9ae44b73ad7aa3d87f4c7bd07ef7849/src/macros.rs#L2) Adds the debug derive. So I am clueless what causes this.
###### TLDR: `syn::derive::DeriveInput` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug``

**Comment by Dushistov** [comment]
Look at README, optional features sections, you should enable "extra-traits" feature.

**Comment by dtolnay** [comment]
The "extra-traits" cfg exposes the Debug impl. The feature is off by default because having all those impls increases compile time quite substantially, so you would normally only want it during debugging.

From your second link:

https://github.com/dtolnay/syn/blob/6f1b7f2ee9ae44b73ad7aa3d87f4c7bd07ef7849/src/macros.rs#L37

the `derive(Debug)` only applies if "extra-traits" is enabled.
