### ISSUE TITLE
parse_str cannot handle arbitrary text

### ISSUE THREAD

**Issue by canndrew** [dtolnay/syn#585]
I want to implement a DSL which contains Rust expressions intermingled with my own syntax which can't be handled by Rust's tokenizer. There doesn't seem to be any way to do this since `ParseStream` fails immediately if created with text which contains invalid Rust tokens, even if those tokens are far outside of the text that I want to parse.

**Comment by dtolnay** [comment]
I would like to consider this out of scope for Syn. It may be reasonably easy to implement this on a fork of Syn if no other approach does what you need.

Thanks anyway!
