### ISSUE TITLE
No way to parse something off the front a string

### ISSUE THREAD

**Issue by canndrew** [dtolnay/syn#586]
I'm trying to implement a DSL as a proc macro. I have a string which should start with a valid rust expression. I want to parse the expression off the front of the string and also get the remainder of the string.

eg.

    "123 blah blah blah" => (Expr::Lit(123), " blah blah blah")

This doesn't seem possible.

The first problem is https://github.com/dtolnay/syn/issues/585 - since " blah blah blah" might not consist of valid Rust tokens I can't create a `ParseStream` to read off the expression from the front.

If I could determine where the valid Rust tokens end I could just create a `ParseStream` from those, but https://github.com/alexcrichton/proc-macro2/issues/168 makes this impossible.

I could also try parsing progessively larger strings until something successfully gets parsed, but https://github.com/dtolnay/syn/issues/584 makes this impossible.

Even if these attempts had worked though, there doesn't seem to be a way to get the position of a `ParseStream` in terms of the original string I created it with. I can get a `Cursor`, but from there I can only get tokens.

Is there any way to do this? Ideally it would be nice if there was a `syn::parse_front_of_str<T>(&str) -> (T, &str)` function but right now I'd settle for any gross hack at all.

**Comment by dtolnay** [comment]
Since I don't plan to address #585 in Syn, I'll close this as well because it doesn't sound like it will be useful to you by itself. I would recommend forking Syn and implementing whatever changes you need to make it work for your DSL.
