### ISSUE TITLE
Parsing utilities such as do_parse!, alt!, many!

### ISSUE THREAD

**Issue by Ploppz** [dtolnay/syn#587]
I see that in an older version of `syn`, there were macros like `do_parse!` and `alt!`. I find that those macros would be very convenient for me now, but they are not there anymore.
How do I go about parsing several possible things (`alt!`)?
And how do I go about parsing something any number of times (until it fails), like `many0!`?

**Comment by dtolnay** [comment]
Please check out the link under Parsing (third bullet point at the top of the readme). Let me know if you still have remaining questions after that.

**Comment by dtolnay** [comment]
In particular, the example code in the link parse a struct *or* enum (which would have been `alt` before) and structs can have zero or more fields (which would have been `many0` before).

**Comment by Ploppz** [comment]
Ok, thanks!
