### ISSUE TITLE
No way to easily parse the contents of (...) without much ceremony

### ISSUE THREAD

**Issue by nox** [dtolnay/syn#589]
I'm implementing a `proc_macro_attribute` for `struct` types, where I extract field attributes of the form `#[inert::field(pub foo)]` with the following code:

```rust
struct FieldAttr {
    vis: Visibility,
    name: Option<Ident>,
}

impl Parse for FieldAttr {
    fn parse(input: ParseStream) -> Result<Self, Error> {
        let vis = input.parse()?;
        let name = input.parse()?;
        Ok(Self { vis, name })
    }
}
```

There is no `syn` API to reproduce what `rustc` does itself with the first argument of a `proc_macro_attribute` function as described in the `show_streams` example in the [documentation](https://doc.rust-lang.org/reference/procedural-macros.html#attribute-macros), where the delimiters are ignored and the function is passed only the contents of the token tree.

**Comment by nox** [comment]
I ended up doing that:

```rust
struct AttrArgument<T> {
    argument: T,
}

impl<T> Parse for AttrArgument<T>
where
    T: Parse,
{
    fn parse(input: ParseStream) -> Result<Self, Error> {
        let content;
        if input.peek(Paren) {
            syn::parenthesized!(content in input);
        } else if input.peek(Brace) {
            syn::braced!(content in input);
        } else if input.peek(Bracket) {
            syn::bracketed!(content in input);
        } else {
            unreachable!()
        }
        let argument = T::parse(&content)?;
        Ok(Self { argument })
    }
}
```

**Comment by dtolnay** [comment]
Glad you got it working! That looks like a reasonable solution.

In my experience, it has been uncommon to want to parse any of `(`...`)` / `{`...`}` / `[`...`]` without caring which one is present, so I am okay with `AttrArgument<T>` living in your code rather than something provided by Syn.

**Comment by nox** [comment]
The issue here is that there is no way to parse the contents of `(`…`)` in an attribute without going through an additional type. The snippet was just for my specific case, but even if I wanted to only parens I would need to either use `syn::parenthesized!` in the implementation of `Parse` for `FieldAttr` or go through a separate type.

I guess my point is that there should be some sort of `Parenthesized<T>` type that parses a `T` surrounded by parentheses, but if you think that's too niche, that's fine.

**Comment by dtolnay** [comment]
> I would need to either use `syn::parenthesized!` in the implementation of `Parse` for `FieldAttr`

This also sounds like a fine solution, and does not require an additional type.

> there is no way to parse the contents of `(`…`)` in an attribute without going through an additional type

I don't fully understand the opposition to an additional type, or what you consider to be an additional type, but if you are willing to use one then [`Group`](https://docs.rs/proc-macro2/0.4/proc_macro2/struct.Group.html) is also an option. Something like:

```rust
let group: Group= syn::parse2(input)?;
let content: T = syn::parse2(group.stream())?;
```

**Comment by NikosEfthias** [comment]
I am really confused theres a type called `UseGroup` however it does not implement parse for some reason

**Comment by NikosEfthias** [comment]
@dtolnay are we supposed to parse the groups character by character? Seems there's no way to peek into or parse Groups
