### ISSUE TITLE
Parse paths in Meta

### ISSUE THREAD

**Issue by nhynes** [dtolnay/syn#597]
[MWE](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2977a11e2a94ea1e92ac2c76f99bb681)

The following is valid syntax, but is not parseable by `syn`. I'm not sure if this is expected behavior.
```rust
#[macro_use]
extern crate quote;

fn main() {
    let attr: syn::Attribute = syn::parse_quote!(#[derive(serde::Serialize)]);
    attr.parse_meta().unwrap();
}
```

**Comment by dtolnay** [comment]
Thanks! I would accept a PR to fix this.

**Comment by azriel91** [comment]
Working on this, am halfway there.
However, haven't figured out how to create the tests snapshots.

**Comment by dtolnay** [comment]
Sure thing, the snapshot stuff is quite new and not fully figured out yet so I would be happy to take care of updating them. Or alternatively if you want to try, it should be the steps shown in https://github.com/mitsuhiko/insta#snapshot-updating.

**Comment by dtolnay** [comment]
#605 has an implementation that will need to be included in the next round of breaking changes.

**Comment by topecongiro** [comment]
@dtolnay Would you mind sharing the plan for the next release in which this gets included? I really would like to use this.
