### ISSUE TITLE
Self might actually be an Ident

### ISSUE THREAD

**Issue by nhynes** [dtolnay/syn#600]
[MWE](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1f6248c7282a01c9a81b65af801d3f41)

```rust
fn main() {
    let s: syn::Expr = syn::parse_quote!(Self {});
    println!("{:#?}", s); // PathSegment { ident: Ident(Self), .. }
    let i: syn::Ident = syn::parse_quote!(Self); // panics. Self is not an ident
}
```

Parsing an `ExprStruct` `Self {}` yields a `PathSegment` with `ident: Self`. Unfortunately it's not possible to test the ident against `parse_quote!(Self): syn::Ident` because [Self is explicitly disallowed as an ident](https://github.com/dtolnay/syn/blob/ddc51f1c3d1162de03d91fefb2828434fa181399/src/ident.rs#L30). Still not sure if this is supposed to be the case. I guess there's always `... == format!("{}", quote!(...))`.

**Comment by dtolnay** [comment]
Could you say more about what you mean by "test the ident against"?

It sounds like you may want to use `Path::is_ident`:

```rust
if let Expr::Struct(e) = parse_quote!(Self {}) {
    println!("{}", e.path.is_ident("Self"));
}
```

**Comment by nhynes** [comment]
Yep, that works. I didn't see the `impl PartialEq<T: AsRef<Str>> for Ident`. The nomenclature is misleading, but there's not much to be done about that, I suppose. Thanks!

**Comment by dtolnay** [comment]
`Self` is an interesting case because it is a reserved keyword but for pretty much all purposes at the syntax level it behaves like a non-reserved identifier. It may be harmless to have Ident's parser accept it (unlike other keywords). I filed https://github.com/dtolnay/syn/issues/602 to follow up.
