### ISSUE TITLE
[feature request] r#-aware apis

### ISSUE THREAD

**Issue by Gankro** [dtolnay/syn#603]
Currently syn seems be largely ignorant of the existence of `r#`. This is correct in some situations, and incorrect in others. It would be good if the API of Ident (and others?) be adjusted/augmented to make it easier to correctly handle this.

Some notable examples with an `Ident("r#match")`:

* prefixing: `new_name = format!("prefix_{}", ident);` => `"prefix_r#match"` **(wrong)**
* exporting: `fn_name = ident.to_string();` => `void r#match(int32_t x, bool y);` **(wrong)**
* generating rust: `format!("struct {}", ident);` => `struct r#match` **(right!)**

At minimum having a to_unescaped_string() fn that strips r#'s would be nice, but I'm not an expert in the domain so it might be possible there's a more elegant/helpful solution here.

**Comment by dtolnay** [comment]
I think the behavior of `format!("{}", ident)` needs to match `ident.to_string()` (no choice on this one) which needs to match `TokenTree::Ident(ident).to_string()` which needs to match `TokenStream::from_iter(vec![TokenTree::Ident(ident)]).to_string()`. Anything else would be too confusing. The last one pretty obviously needs to include r# if the ident is raw, so I would conclude that we need to keep the r# in `format!("{}", ident)`.

I would be on board with adding:

```rust
impl Ident {
    pub fn unraw(&self) -> Ident;
}
```
