### ISSUE TITLE
Provide a crate of data structures for processing syn.json

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#607]
These need to be moved from [*codegen/src/types.rs*](https://github.com/dtolnay/syn/blob/0.15.29/codegen/src/types.rs) to a new `syn-json` crate, probably in a top-level *json* directory in this repo.

We may or may not want the syn.json file itself to be packaged and exposed in the same crate in some way along with the data structures.

**Comment by RReverser** [comment]
This is only semi-relevant issue, but in the process of writing the mentioned custom codegen from `syn.json`, I've found that few declared structs don't implement `Spanned`, making it hard to generate `self.span()` on each node to assign locations recursively.

These structs are:
 - `syn::derive::DataEnum`
 - `syn::derive::DataStruct`
 - `syn::derive::DataUnion`
 - `syn::item::FnDecl`
 - `syn::path::QSelf`

`Spanned` is automatically implemented for types that implement `ToTokens`.

I see these types falling into two categories with different solutions:

1. It seems that semantically all of `DataEnum`, `DataStruct` and `DataUnion` could have `ToTokens` implemented, but currently are defined with `do_not_generate_to_tokens` - is the only reason for that avoiding code bloat or something else? Would you be open to a PR implementing `ToTokens` for these?
2. `FnDecl` and `QSelf` are both partial types that only make sense in a larger context, and so they can't reasonably have `ToTokens` implemented. However, it seems that implementing `Spanned` could still make sense for them - would you be open for such addition?

**Comment by RReverser** [comment]
Actually, I misunderstood, it looks like `Data` and its variants is also a partial type. Hmm...

Would it be worth to mark them with something like `"node": false` or `"spanned": false` or `"partial": true` in `syn.json`?

**Comment by dtolnay** [comment]
`Spanned` is sort of neglected for now due to lack of compiler support. [`proc_macro::Span::join`](https://doc.rust-lang.org/1.33.0/proc_macro/struct.Span.html#method.join) is unstable so there isn't any way to implement `Spanned` correctly. For now I think it just returns the span of the first token. So I would prefer if you could solve this in a different way if possible. Would a [visitor](https://docs.rs/syn/0.15/syn/visit/) with a visit_span method work?

<details>
<summary>Prototype</summary>

```rust
struct TotalSpan {
    lo: LineColumn,
    hi: LineColumn,
}

impl<'ast> Visit<'ast> for TotalSpan {
    fn visit_span(&mut self, span: &Span) {
        let start = span.start();
        let end = span.end();
        if (start.line, start.column) < (self.lo.line, self.lo.column) {
            self.lo = start;
        }
        if (end.line, end.column) > (self.hi.line, self.hi.column) {
            self.hi = end;
        }
    }
}

...

let mut span = TotalSpan {
    lo: LineColumn {
        line: usize::max_value(),
        column: usize::max_value(),
    },
    hi: LineColumn { line: 0, column: 0 },
};

span.visit_expr(&expr);
```
</details>

There are a few cases of missing visit_span calls that we will need to fix -- https://github.com/dtolnay/syn/issues/462#issuecomment-476001680 -- but I am comfortable defining the contract to be that every Span in the input gets visited.

**Comment by RReverser** [comment]
> For now I think it just returns the span of the first token.

Yeah, this one actually gave me a hard time finding out the reason and personally would much rather not have any fallback at all to make it easier to debug...

But, anyway, by now I enabled `procmacro2_semver_exempt` which allows to return correct spans, so the only problem I have is with these few types not implementing it.

Visitor could perhaps work, but I guess that means making 3rd-party codegen even more slightly complicated? It will need to convert types to corresponding `visit_*` methods, and generate code to join spans back for each node... I'm not yet sure how that will look like yet.

**Comment by RReverser** [comment]
> But, anyway, by now I enabled procmacro2_semver_exempt which allows to return correct spans, so the only problem I have is with these few types not implementing it.

In case you're curious, btw, I'm pretty happy with the progress so far:

![image](https://user-images.githubusercontent.com/557590/54887916-f5a48300-4e8f-11e9-96d1-4d5bc43211eb.png)

For now I worked around this issue above by manually blacklisting types that I know don't have `Spanned`, but would really like a more future-proof solution instead:

```rust
fn has_spanned(ty: &str) -> bool {
    match ty {
        "DataStruct" | "DataEnum" | "DataUnion" => false,
        "FnDecl" => false,
        "QSelf" => false,
        _ => true,
    }
}
```

**Comment by RReverser** [comment]
@dtolnay It's live! https://twitter.com/RReverser/status/1120757975860350977

I'd still love to flesh out integration, but pretty happy with how it works overall for now.

**Comment by dtolnay** [comment]
Published in https://docs.rs/syn-codegen/.

I would prefer to consider this an aide to make writing syntax tree related code more efficient, rather than something intended to capture everything about the syntax tree. So I don't mind if applications need to attach their own extra information about the syntax tree that they need, such as the list of missing ToTokens impls, because that is only a very small factor in how efficiently those applications can be developed.

**Comment by lancejpollard** [comment]
@RReverser I am not sure I totally am following what has been done here, but how did you end up implementing the AST Explorer for rust ASTs? How do you take the Rust code and convert it into a JSON AST exactly? I would like to play with the AST of the Rust stdlib in JSON (in Node.js) so I can build visualizations and write transpiler-like things from Rust to X language.
