### ISSUE TITLE
LitStr::parse spans within literal?

### ISSUE THREAD

**Issue by dbeckwith** [dtolnay/syn#609]
From the docs of `LitStr::parse`:

> All spans in the syntax tree will point to the span of this `LitStr`.

Why is this? After parsing tokens out of a `LitStr`, I was expecting the spans to point to sub-spans of the `LitStr`, but every token points to the whole `LitStr` as documented. Is there a specific reason it's like this, or any plan to change this behavior?

**Comment by dtolnay** [comment]
There is no such thing as sub-spans. There is no API on `Span` that would produce a smaller span.
https://doc.rust-lang.org/1.33.0/proc_macro/struct.Span.html

The most recent work on sub-spans that I know of was in https://github.com/rust-lang/rust/pull/53930.

**Comment by dbeckwith** [comment]
Hmm I see. Wouldn't it still be possible by creating a new span that's offset from the `LitStr`'s `Span::start`?
As an example, let's say you have this `LitStr`: `"foo,bar,qux"`, whose span starts at line 123, column 42. Let's say I parse out a punctuated list of identifiers from it. Couldn't you give the first identifier (`foo`) a span from line 123, column 43 to line 123, column 46, and the second identifier (`b`) a span from line 123, column 47 to line 123, column 50?

**Comment by dtolnay** [comment]
> Wouldn't it still be possible by creating a new span that's offset from the `LitStr`'s `Span::start`?

There is no API for creating a span at a location: https://doc.rust-lang.org/1.33.0/proc_macro/struct.Span.html.

**Comment by dbeckwith** [comment]
Oh haha. I guess spans are much less flexible than I thought... well, definitely something for the future when they're made more manipulable.
