### ISSUE TITLE
No copyright statement in license file

### ISSUE THREAD

**Issue by MF1-MS** [dtolnay/syn#613]
The MIT License file omits the copyright notice usually present, and this notice is referred to in the license text itself. This makes it harder to properly acknowledge use of this software.

**Comment by bossmc** [comment]
(IANAL either, but I've been looking into my company's use of OSS code recently)

Using https://opensource.org/licenses/MIT as a canonical template, I don't see how the middle clause:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

can be conformed to where there is no copyright notice (the rust codebase has https://github.com/rust-lang/rust/blob/master/COPYRIGHT to provide a copyright statement, even if it's not at the top of the license statement.  Contribution licenses are indeed complex - a literal interpretation of copyright law suggests that, unless explicitly licensed, external contributions remain copyright of the author and cannot be used by anyone else.  In practice this is never a problem, and contributions are assumed to be provided under the same license as the original product, but that still leaves the issue of who the copyright owners are...  Maybe

> Copyright @dtolney and external contributors (see <gihub>)

?

**Comment by dtolnay** [comment]
I am comfortable sticking with the current setup until I hear from a lawyer that there is something wrong.

In "copies or substantial portions" of Syn, please include one or both of the LICENSE files as-is depending which license you choose to accept the code under. Thanks!
