### ISSUE TITLE
[Question] How to know if Field.ty is one of the TypeParams?

### ISSUE THREAD

**Issue by tyranron** [dtolnay/syn#617]
Hi, would you be so kind to provide some tips for my situation?

```rust
[#derive(MyTrait)]
struct Foo<A, B, C>(C, String, B, usize, Box<A>, u8);
```

I'd like to imply some trait bounds for my deriving implementation, like:
```rust
impl<A, B, C> MyTrait for Foo<A, B, C>
where A: MyTrait,
      B: MyTrait,
      C: MyTrait,
```

However, I've stuck at the place where I have [`Fields`](https://docs.rs/syn/0.15.30/syn/struct.Field.html) and [`TypeParam`s](https://docs.rs/syn/0.15.30/syn/struct.TypeParam.html) of the `Foo` struct, and cannot figure out the way how to check if the`Field` uses a `TypeParam` inside.

If there are examples of doing this somewhere out there I'll be very thankful for providing them.

**Comment by dtolnay** [comment]
This is a hard problem in general. Most macros would emit a bound on every type parameter to keep things simple, possibly with an inert attribute that can be used to override the inferred bounds such as `#[my_trait(bound = "A: OtherTrait, C: MyTrait")]`.

An implementation more along the lines of what you are asking can be found in serde_derive:
https://github.com/serde-rs/serde/blob/v1.0.90/serde_derive/src/bound.rs#L83-L217

**Comment by tyranron** [comment]
@dtolnay oh, thank you very much! At the first glance it's exactly what I was looking for. I'll try to play and adopt it for my case.
