### ISSUE TITLE
Multiple calls make Span information lost

### ISSUE THREAD

**Issue by doxjs** [dtolnay/syn#622]
Hi，I'm new gay using syn. I'm developing proc_macro_attribute, and I found something strange. It's my bug or syn's bug?
My code:
```rust
#[proc_macro_attribute]
pub fn myTest(_: TokenStream, fun: TokenStream) -> TokenStream {
    let fun: ItemFn = parse_macro_input(fun as ItemFn);
    
    // something I want to do...
    
    TokenStream::from(quote! {
        #fun
        // some other codes generated by me
    })
}
```

If I use it like below, it's okay:
```rust
#[myTest]
fn error_report() {
    println!("{}", 1 + "2");
}
```
Compiler will tell me that something wrong happend and indicate where it happens.
But I want to let it support multiple calls, so I write another code like this:
```rust
#[myTest]
#[myTest]
fn error_report() {
    println!("{}", 1 + "2");
}
```
Compiler will tell me that something wrong happend, but it will not tell me where it happens.
It makes my development difficult. My solution is moving codes inside `error_report` into another function, and calling it in `error_report`. Like this:
```rust
fn _error_report() {
    println!("{}", 1 + "2");
}

#[myTest]
#[myTest]
fn error_report() {
    _error_report();
}
```
It works well. But it's not beautiful. Everyone loves beauty, so do I. I tried to find out why, so I printed `ItemFn` instance and found that all `Span` information are lost after the first call.
My code:
```rust
#[proc_macro_attribute]
pub fn myTest(_: TokenStream, fun: TokenStream) -> TokenStream {
    let fun: ItemFn = parse_macro_input(fun as ItemFn);
    
   // here I printed. Only the first call wil display the expected span information
   // after the first call, all span information became 0..0
    println!("{:#?}", fun);
    // something I want to do...
    
    TokenStream::from(quote! {
        #fun
        // some other codes generated by me
    })
}
```
I dont know why, and I dont know that should I open issue here or `quote`'s github. 
Help please, thank you very much. Forgiving my poor English.

**Comment by dtolnay** [comment]
Unfortunately this is a compiler bug and we can't do anything about it in syn or quote. In short, the compiler will randomly lose the spans of everything.

I am told the fix will require https://github.com/rust-lang/rust/issues/43081.
