### ISSUE TITLE
Raw identifier marker "r#" is lost when parsing from a proc_macro::TokenStream

### ISSUE THREAD

**Issue by shepmaster** [dtolnay/syn#628]
**alpha/src/main.rs**

```rust
use beta::Beta;

#[derive(Beta)]
enum Dummy {
    #[foo(bar(r#value))]
    Variant
}

fn main() {}
```

**alpha/beta/src/lib.rs**

```rust
#[macro_use]
extern crate syn;
extern crate proc_macro;

use proc_macro::TokenStream;

#[proc_macro_derive(Beta, attributes(foo))]
pub fn beta_derive(input: TokenStream) -> TokenStream {
    let d: syn::DeriveInput = syn::parse(input).unwrap();

    let e = match d.data {
        syn::Data::Enum(e) => e,
        _ => unimplemented!(),
    };

    for v in e.variants {
        for attr in v.attrs {
            syn::parse2::<Target>(attr.tts).unwrap();
        }
    }

    TokenStream::new()
}

#[derive(Debug)]
struct Target;

impl syn::parse::Parse for Target {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        println!("{:?}", input);

        let inside;
        parenthesized!(inside in input);

        let _name: syn::Ident = inside.parse()?;
        let _: Target2 = inside.parse()?;

        Ok(Target)
    }
}

#[derive(Debug)]
struct Target2;

impl syn::parse::Parse for Target2 {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let inside;
        parenthesized!(inside in input);

        let _name: syn::Expr = inside.parse()?;

        Ok(Target2)
    }
}
```

**Output**

Note that the ident has the raw marker `r#`stripped and is now just `value`:

```
TokenStream [
  Group {
    delimiter: Parenthesis,
    stream: TokenStream [
      Ident {
        ident: "bar",
        span: #0 bytes(0..0)
      },
      Group {
        delimiter: Parenthesis,
        stream: TokenStream [
          Ident {
            ident: "value",
            span: #0 bytes(0..0)
          }
        ],
        span: #0 bytes(0..0)
      }
    ],
    span: #0 bytes(0..0)
  }
]
```

This does not appear to happen when using `syn::parse_str` on a string of the equivalent code.

- Rust 1.34.0
- syn 0.15.29

**Comment by dtolnay** [comment]
This is a compiler bug -- https://github.com/rust-lang/rust/issues/43081. If you add `println!("{}", input); println!("{:#?}", input);` to the top of beta_derive, notice how the r# is already gone and all the spans are missing.

**Comment by shepmaster** [comment]
> This is a compiler bug

I assumed that, but didn't know exactly where to look — I (sadly) didn't even think that the compiler's `TokenStream` would implement `Debug` so I didn't try 🙈 

I skimmed through the comments on the linked issue, but didn't see anything specific about raw idents — is it worth me making an explicit comment there?

**Comment by dtolnay** [comment]
Yep, go ahead and mention raw idents on the thread.

The issue manifests as "the compiler randomly but reproducibly forgets all the spans and potentially significant formatting details in macro input" and there are infinite ways to trigger it.

**Comment by shepmaster** [comment]
Is there a way traverse the AST and "promote" every `Ident` into a raw ident? That is, make `r#foo` into `r#foo` and `bar` into `r#bar`? That might allow me to workaround the problem without affecting end-users.

**Comment by dtolnay** [comment]
Promoting every ident into a raw ident isn't necessarily correct if you are parsing expressions, so it would be a tradeoff. For example `x as T` may be fine while `r#x r#as r#T` would not parse.

The conversion could be done something like this:

```rust
use proc_macro2::{Ident, Span};
use syn::ext::IdentExt; // syn 0.15.33

fn make_raw(ident: &Ident) -> Ident {
    let unraw = ident.unraw();
    let raw_string = format!("r#{}", unraw);
    let mut raw_ident: Ident = syn::parse_str(&raw_string).unwrap();
    raw_ident.set_span(ident.span());
    raw_ident
}

fn main() {
    let ident = Ident::new("type", Span::call_site());
    println!("{} -> {}", ident, make_raw(&ident));

    let ident = syn::parse_str::<Ident>("r#type").unwrap();
    println!("{} -> {}", ident, make_raw(&ident));
}
```

**Comment by dtolnay** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/43081. The compiler is invoking a macro with the wrong input tokens so this isn't a syn issue.
