### ISSUE TITLE
`mut` keyword is lost when parsing a `fn`

### ISSUE THREAD

**Issue by kjvalencik** [dtolnay/syn#632]
```rs
if let syn::Item::Fn(mut function_item) = syn::parse(item.clone()).unwrap() {
```

```
$ rustc --version
rustc 1.36.0-nightly (3f5152e20 2019-05-08)
$ cargo version
cargo 1.36.0-nightly (759b6161a 2019-05-06)
```

Interestingly, `&mut` works fine.

**Comment by dtolnay** [comment]
Could you share a minimal runnable piece of code for me to reproduce what you are seeing?

Here is what I tried, and the `mut` keyword was not lost:

```rust
use proc_macro2::TokenStream;
use quote::quote;
use syn::Item;

fn main() {
    let code = "fn f(mut x: u8) {}";
    let tokens = code.parse::<TokenStream>().unwrap();
    if let Item::Fn(function_item) = syn::parse2(tokens.clone()).unwrap() {
        println!("tokens: {}\nfunction_item: {}", tokens, quote!(#function_item));
    } else {
        panic!("expected fn");
    }
}
```

**Comment by kjvalencik** [comment]
I'll see if I can come up with something minimal a bit later. This is the macro I was using when I encountered the issue: https://github.com/trezm/Thruster/blob/master/thruster-proc/src/lib.rs#L53-L79

If I rollback to nightly 2019/05/01, the issue does not exist.

**Comment by kjvalencik** [comment]
Doing some quick testing, it appears like it's related to an `async fn`.

**Comment by kjvalencik** [comment]
Closing this issue since it's a problem with `rustc`. Adding a debug print to the macro shows that the `TokenStream` is incorrect.
