### ISSUE TITLE
Expose private items

### ISSUE THREAD

**Issue by swfsql** [dtolnay/syn#636]
Is there a way to use some private items from this crate?  
Some macros may tweak (or re-define) some structures from `syn` but still re-utilize other items and private functions from it.  
I wouldn't know if an alternative branch would be better, but I'm currently using a "patched" version of `syn`: https://crates.io/crates/syn-pub-items

Thanks in advance, and for your work on `syn`!

**Comment by dtolnay** [comment]
All of the items in https://github.com/swfsql/syn/commit/76636a6f02e73760b2bf75bd1f9579d9b6b76cc1 and https://github.com/swfsql/syn/commit/f8cf358ff569537da039cbfd77ce7bbdba320a75 are private intentionally and we can't provide a backward compatibility guarantee for them. Forking is fine, or copying out whatever private things you need into the macro crate.
