### ISSUE TITLE
Is it possible to write custom messages for the token as rustc does?

### ISSUE THREAD

**Issue by vityafx** [dtolnay/syn#640]
Let's say I parse some code:

```rust
fn main() {
    use proc_macro2::TokenStream; // 0.4.30;

    let t: TokenStream = syn::parse_str("let v = 5u64;").unwrap();
    
    println!("{:#?}", t);
}
```

If `rustc` sees a problem in the code, it can show it like this:

```
error: <Some error>
  --> src/main.rs:36:9
   |
35 |         let v = 5u64;v
   |                       - expected one of 8 possible tokens here
```

I think it would be nice if we could use `TokenTree` and `Span` to write a message like that one. I assume it could be done, by, for example, adding a method either to the `TokenTree` or to the `Span` structures like:

```rust
fn message(&self, error: &str, message: &str) {
    println!("...");
}
```

**Comment by dtolnay** [comment]
Syn doesn't deal with drawing diagnostics so this would not be something in Syn. Check out the diagnostics API in the proc_macro crate. It is unstable for now and may or may not support the exact formatting you showed; I don't know much about it. If there is something missing please call it out on the feature's tracking issue.

**Comment by vityafx** [comment]
Thank you for the help.
