### ISSUE TITLE
Add help messages to Error

### ISSUE THREAD

**Issue by mzabaluev** [dtolnay/syn#641]
It would be nice if `Error` could be adorned with help messages including optional source span information, replicating the similar feature in compiler error messages.

**Comment by Mrowqa** [comment]
+1 for the idea of spans in error messages. In my current project I have long files that are parsed with this crate and in case you have a syntax error, well, other people were doing binary search by commenting out some parts of the code just to learn they missed semicolon somewhere.

**Comment by mzabaluev** [comment]
@Mrowqa `syn::Error` allows a custom span for the error itself, but help messages could point at other locations.

**Comment by Mrowqa** [comment]
@mzabaluev sorry for not enough explanation. The spans works well for me inside a proc macro, but I also parse the code in the build script and there, despite of having a span, I can't extract any information from the span. Debug formatter for the `proc_macro2::Span` just prints `Span` and the formatter for `syn::Error` just skips the span in the message.

**Comment by mzabaluev** [comment]
I think the feature I want will be available, in a more flexible form, once https://github.com/rust-lang/rust/issues/54140 stabilizes; I will try how it works in nightly.

**Comment by dtolnay** [comment]
Help messages should be done via the proc macro Diagnostics API, not syn::Error. https://github.com/rust-lang/rust/issues/54140
