### ISSUE TITLE
Missing `Token![$]` rule for `token::Dollar`

### ISSUE THREAD

**Issue by jix** [dtolnay/syn#647]
The documentation for `token::Dollar` says one should use `Token![$]` (as all tokens do). The `Token!` macro doesn't have a rule for `$` though, so this doesn't work.

**Comment by dtolnay** [comment]
Thanks! I would accept a PR to make `Token![$]` work, or to fix the documentation if that turns out to be impossible.

**Comment by jix** [comment]
On current stable rust, it seems to be possible to match the literal dollar token as the last token of a macro rule (or the last token of a repetition). See [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8a3a907f76b8eb1817b986b0615fa6d9).

This would be sufficient here. I'm not sure if it should be used though, as in general matching on literal dollar tokens is not supported. The [reference](https://doc.rust-lang.org/reference/macros-by-example.html) even claims that it is not possible at all:

> The character $ cannot be matched or transcribed literally.

If it only works by accident, it might be a bad idea to depend on this. Given that, I'm not sure whether to change the macro or the documentation. If you have a preference for either choice, I can make a PR for it.

**Comment by dtolnay** [comment]
I would be comfortable changing the macro and relying on the approach in the playground to work. On old compilers where it doesn't work, we can keep the existing macro without $.
