### ISSUE TITLE
Inclusive range patterns are always output as `...`, which is linted against.

### ISSUE THREAD

**Issue by jebrosen** [dtolnay/syn#650]
At https://github.com/dtolnay/syn/blob/master/src/expr.rs#L3706, `...` is output even if the input was `..=` in range patterns. It looks like this was decided on in #275.

In rust-lang/rust#61342 the use of `...` was upgraded to a warn-by-default lint.

Reproduction example:

```rust
#[proc_macro]
pub fn passthru(input: TokenStream) -> TokenStream {
    let parsed: syn::Item = syn::parse(input).unwrap();
    let tokens = quote! { #parsed };
    tokens.into()
}

passthru!{
    fn a() {
        match 1 {
            2..=3 => {},
            _ => {},
        }
    }
}
```

```
warning: `...` range patterns are deprecated
  --> consumer2018/src/main.rs:23:14
   |
23 |             2..=3 => {},
   |              ^^^ help: use `..=` for an inclusive range
   |
```

The error is especially confusing because the `Span` is preserved.

Discovered via SergioBenitez/Rocket#1033.

**Comment by dtolnay** [comment]
I would accept a PR to emit ranges as `..=` now that the new syntax is well supported.

**Comment by jebrosen** [comment]
I'd be more than happy to work on adding that.

What is `syn`'s policy on version support for these cases? IOW, does it need to be done conditionally based on whether the running rustc supports `..=` in patterns?

**Comment by dtolnay** [comment]
Ah, good thought! I would be okay with either way. It would also be fine to make the behavior conditional later only if the simple change turns out to be disruptive.
