### ISSUE TITLE
Parsing `Punctuated<Field, Token![,]>` from a `TokenStream`

### ISSUE THREAD

**Issue by jimmycuadra** [dtolnay/syn#651]
I am trying to create some AST nodes by creating a `TokenStream` with the quote macro and then parsing it, but I haven't been able to find the right incantation to get this to work. Ultimately I'm trying to create `Vec<syn::Field>` and I thought it would be simpler to approach it this way than by building the entire structure by constructing the fields out of all the deeply nested syn AST types.

The input is:

``` rust
let tokens = quote! {
    /// The event's content.
    pub content: #content_name,
};
```

(Note that only one field definition is shown here, but this will be done in a few places where there may be multiple fields.)

The documentation for the `parse` module explains the use of the `Parser` trait for cases like `Punctuated` where there isn't a sensible default for parsing. I tried the approach there, but wasn't able to modify the example to fit my case:

``` rust
let parser = Punctuated::<Field, Token![,]>::parse_terminated;
let more_fields = parser.parse(tokens)
    .unwrap()
    .into_iter()
    .collect();
```
```
error[E0277]: the trait bound `syn::data::Field: syn::parse::Parse` is not satisfied
  --> src/gen.rs:85:18
   |
85 |     let parser = Punctuated::<Field, Token![,]>::parse_terminated;
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `syn::parse::Parse` is not implemented for `syn::data::Field`
   |
   = note: required by `syn::punctuated::Punctuated::<T, P>::parse_terminated`
```

The above error makes sense to me as `Field` is also a type with no sensible default. In other cases I've done this:

``` rust
// body: ParseStream
let fields = body.parse_terminated::<Field, Token![,]>(Field::parse_named)?
```

but it's unclear to me in this case how to either specify `Field::parse_named` as the way to parse `Field` in the first example or how to create a `ParseStream` for use in the second example.

The documentation for `ParseStream` (via `ParseBuffer`) says you can only create a `ParseStream` via one of the following:

1. The `parse_macro_input!` macro if parsing input of a procedural macro;
1. One of the `syn::parse*` functions; or
1. A method of the `Parser` trait.

The first approach gives me this error:

```
error[E0308]: mismatched types
  --> src/gen.rs:85:24
   |
85 |     let token_stream = syn::parse_macro_input!(tokens as Vec<Field>);
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `proc_macro::TokenStream`, found struct `proc_macro2::TokenStream`
   |
   = note: expected type `proc_macro::TokenStream`
              found type `proc_macro2::TokenStream`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

(I'm guessing `Vec<Field>` isn't the right type to be parsing into, but as you can see I didn't even get that far.)

The second approach isn't applicable because of the "default" issue mentioned before. The third approach is what I was trying to do originally.

How do I achieve what I'm trying to do here? I'm interested in not only how to do it, but also what I'm missing in the documentation that should have led me to the solution. If this is an unusual case that is not currently well explained in the docs, then hopefully learning the answer here will help me put together a documentation PR that will help the next person who runs into this.

Thanks!

**Comment by dtolnay** [comment]
Could you explain more about your use case that requires creating these as syn::Field syntax trees? Usually macros would only create syntax trees for the input, and do all output only in terms of TokenStream.

If you need Vec\<Field\> as a syntax tree, I think you would need to write a Parse impl using input.parse_terminated as you mentioned.

**Comment by jimmycuadra** [comment]
The macro input looks like this (irrelevant details omitted):

``` rust
ruma_event! {
    /// A redaction of an event.
    RedactionEvent {
        kind: RoomEvent,
        event_type: RoomRedaction,
        fields: {
            /// The ID of the event that was redacted.
            pub redacts: ruma_identifiers::EventId
        },
    }
}

```

The braced content of `fields` will populate the definition of a struct called `RedactionEvent`, with additional fields auto-generated based on the `kind`. In this case, for a "room event", the final struct output will look like this:

``` rust
pub struct RedactionEvent {
    /// The event's content.
    pub content: RedactionEventContent,

    /// The unique identifier for the event.
    pub event_id: ruma_identifiers::EventId,

    /// Timestamp (milliseconds since the UNIX epoch) on originating homeserver when this
    /// event was sent.
    pub origin_server_ts: js_int::UInt,

    /// The ID of the event that was redacted.
    pub redacts: ruma_identifiers::EventId

    /// The unique identifier for the room associated with this event.
    pub room_id: Option<ruma_identifiers::RoomId>,

    /// Additional key-value pairs not signed by the homeserver.
    pub unsigned: Option<serde_json::Value>,

    /// The unique identifier for the user who sent this event.
    pub sender: ruma_identifiers::UserId,
}
```

The fields supplied by the user are parsed into `Vec<Field>` like this in a `Parse` impl:

``` rust
// input: ParseStream
let body;
braced!(body in input);
let fields = body
    .parse_terminated::<Field, Token![,]>(Field::parse_named)?
    .into_iter()
    .collect();
```

The goal is to get a `Vec<Field>` of the auto-generated fields and combine them with the user-supplied fields into one vector, and then to sort them alphabetically by field name. At first I was trying to construct these auto-generated fields by importing all the types from syn and doing it manually, but there are so many types nested within a `Field` that it was pretty unwieldy, and hence I decided to try creating the fields in a more quick and dirty way by parsing them out of a `TokenStream` created by the quote macro. (This is basically the quote macro's raison d'être, so it doesn't seem that strange a use case.)

You're suggesting that the right approach is to create a newtype around `Vec<Field>` and then impl `Parse` for it?

**Comment by dtolnay** [comment]
Ah, combining some fields parsed from the input and some fields generated by the macro and sorting the combined set is an interesting case. Yes, you could define Parse for a wrapper around Vec\<Field\>. Alternatively you could define Parse for a wrapper around just Field, and then use [parse_quote](https://docs.rs/syn/0.15.36/syn/macro.parse_quote.html) which is able to parse Punctuated directly unlike syn::parse2.

**Comment by jimmycuadra** [comment]
That did the trick. Do you see any takeaway from this in terms of documentation, or was this just too unusual a use case?

For anyone else who comes across this issue in the future, here's the code I ended up with:

``` rust
struct ParsableNamedField {
    pub field: Field,
}

impl Parse for ParsableNamedField {
    fn parse(input: ParseStream<'_>) -> parse::Result<Self> {
        let field = Field::parse_named(input)?;

        Ok(ParsableNamedField {
            field,
        })
    }
}
```

Which is used like this:

``` rust
fn populate_event_fields(content_name: Ident, mut fields: Vec<Field>) -> Vec<Field> {
    let punctuated_fields: Punctuated<ParsableNamedField, Token![,]> = parse_quote! {
        /// The event's content.
        pub content: #content_name,
    };

    let mut additional_fields = Vec::with_capacity(punctuated_fields.len());

    for punctuated_field in punctuated_fields {
        additional_fields.push(punctuated_field.field);
    }

    fields.extend(additional_fields);

    fields
}
```

The `for` loop was necessary because the `syn::Field` doesn't implement `std::iter::FromIterator<syn::Field>` so I couldn't do this:

``` rust
let additional_fields = punctuated_fields
    .into_iter()
    .map(|p| p.field)
    .collect();
```

**Comment by dtolnay** [comment]
I think I will avoid making a documentation change for now, but I will keep in mind that parsing Field (which does not implement Parse) inside of Punctuated (which does not implement Parse) is complicated. If there is a pattern of related use cases that people get stuck on then we will figure out a way to make this work better or figure out how the documentation can be more helpful.

Regarding the for-loop and extend, the one line version would be:

```rust
fields.extend(punctuated_fields.into_iter().map(|p| p.field));
```

**Comment by AurelienFT** [comment]
I think this use case can help a lot of people (it helped me). A little doc or a test on how to append a field with an `proc_macro_attribute` could be great.

What do you think ? @dtolnay

**Comment by chipsenkbeil** [comment]
Echoing agreement here. If documentation has been updated somewhere, I didn't see it. Had to do the same approach described here (after finding this issue) instead of just doing something like `let field: syn::Field = parse_quote!(my_field: u32);` in order to produce an attribute macro that injects a couple of new fields into an existing struct.
