### ISSUE TITLE
Can't parse expressions containing $crate

### ISSUE THREAD

**Issue by Ralith** [dtolnay/syn#661]
When a proc macro is used inside a macro_rules macro, it may be legitimately passed expressions like `$crate::FOO`, which can occur anywhere in a compound expression but seems to make `ParseBuffer::parse::<Expr>(input)` fail with "error: expected expression". It's not clear if there's any reasonable way to parse such an expression at all.

**Comment by Ralith** [comment]
Minimal repro:
```rust
fn main() {
    syn::parse2::<syn::Expr>(quote::quote! { frob($crate::FOO) }).unwrap();
}
```

**Comment by dtolnay** [comment]
I believe this already works correctly. See [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a55b9777b9ae5a593661554d36cc2cbe). Note that $crate is only meaningful if it originates inside of macro_rules. Your previous comment shows the same error as you would get without a procedural macro involved at all: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=745a82ff52e32a89574de5154f25c774).

**Comment by Ralith** [comment]
This is clearly not working in the example case, which is representative of and consistent with the error I'm getting in my more complex real-world use case.

To be clear, are you saying that it is intended behavior that the repro I posed fails?

**Comment by dtolnay** [comment]
Correct, it's intended that the input in your comment is not accepted as valid syntax, neither by rustc nor by Syn. $crate refers to "the crate containing the enclosing macro_rules macro", which is not meaningful or legal when there is no enclosing macro_rules macro.

```rust
fn main() {
    frob($crate::FOO);
}
```

```console
error: expected expression, found `$`
 --> src/main.rs:2:10
  |
2 |     frob($crate::FOO);
  |          ^ expected expression
```

**Comment by Ralith** [comment]
Strange, maybe this is breakage caused by proc-macro-hack? I'll try to put together a more faithful repro.
