### ISSUE TITLE
Integer literals out of range for their type are accepted

### ISSUE THREAD

**Issue by abonander** [dtolnay/syn#662]
While I'm not exactly sure what I think `syn` should do about this, I think it's worth discussing because it affects users of `syn` as well as consumers of macros built on `syn`. 

Simply put, even with a suffixed integer literal, `syn` allows values far out of range:

```rust
use syn;

fn main() {
    let val = syn::parse_str::<syn::LitInt>(&format!("{}i32", u64::max_value())).unwrap();
    println!("{:?}", val.value() as i32);
}
```

This prints `-1` as you might expect for truncating an integer that's all 1-bits, but there's no error or warning reported to the user that this is out of range. It is on the macro author to check that the literal is in-range. For literals without a suffix this is more than fair enough, as the semantics depend entirely on context, but I feel like `syn` should provide some easy way to validate this for any given integer width and print a correctly spanned error, and even perform this automatically if the literal has a type suffix.

Now that `TryFrom`/`TryInto` is stable, the former is relatively trivial and most of the work involves just emitting a nice error:

```rust
// I'm pretty sure this impl is coherent
impl<I> TryFrom<LitInt> for I where I: TryFrom<u64> {
    type Error = syn::Error;

    pub fn try_from(lit_int: LitInt) -> Result<I, syn::Error> where I: TryFrom<u64> {
        lit_int.value().try_into().map_err(/* convert to syn::Error with span */)
    }
}
```

It actually may be better to have a separate impl per integer type so we can include the expected integer type in the error message as the error type for `TryFrom` with ints does not contain this information.

**Comment by dtolnay** [comment]
Yep, the API of LitInt is not good. I had written about how I want the design to work previously in https://github.com/dtolnay/syn/pull/574#issuecomment-457499745 but forgot to file issues. I filed #663 and #664 now to follow up. Let me know what you think.
