### ISSUE TITLE
Incorrect Span when printing error / warning

### ISSUE THREAD

**Issue by gnzlbg** [dtolnay/syn#665]
To reproduce:

```
git clone git@github.com:gnzlbg/libm.git
cd libm
git checkout libm_verify
git checkout 0d329849c3efea9bdf709315b8165dce22452b93
cd crates/libm-verify
cargo test
```

prints:

```
warning: public libm function is not `extern "C"
 --> crates/libm-verify/tests/musl.rs:3:1
  |
3 | libm_analyze::for_each_api!(const X: i32 = 0;);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

But in `../crates/libm-analyze/src/lib.rs` the functions from `../crates/libm/src/*` are being parsed from files, and the Span used are from those files, and should point there. That is, the expected warning should be 

```
warning: public libm function is not `extern "C"
 --> crates/libm/src/math/api_foo.rs:3:1
  |
3 | fn bar() { 
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dtolnay** [comment]
> the functions from `../crates/libm/src/*` are being parsed from files, and the Span used are from those files

I'm not sure what you mean by this. They are parsed from a &str https://github.com/gnzlbg/libm/blob/0d329849c3efea9bdf709315b8165dce22452b93/crates/libm-analyze/src/lib.rs#L47 and get the default call_site span. The warning you see is correctly pointing to the call site i.e. the place where the currently executing macro was invoked.

**Comment by gnzlbg** [comment]
Is there a way to give them the span of where File::read_to_string read them from ?

**Comment by dtolnay** [comment]
No, spans are only for data loaded and tokenized by the compiler. You would need to write your own library for rendering warnings based on the file contents and span's line/column.

**Comment by gnzlbg** [comment]
I see, thanks!
