### ISSUE TITLE
Deterministic (reproducible) build

### ISSUE THREAD

**Issue by gandrewstone** [dtolnay/syn#667]
This library is being used as a dependency in a project that needs reproducible builds.  By reproducible build, I mean that you can build multiple times on the same machine, or in mostly-the-same environments (say a docker image) and produce exactly the same bits as output.

Common causes of non-reproducible builds are embedding some part of the environment into the output .rlib, for example the build time and date.

Can you think of anything like that in this library?

**Comment by dtolnay** [comment]
I don't know of anything like that in Syn or its dependencies.

**Comment by gandrewstone** [comment]
I am checking out syn and building with:
cargo build --release --target=x86_64-unknown-linux-gnu
I just build, move target to tgt1 and then build again.
I then check the sha256sum of libsyn-*.rlib and they are different in the 2 directories (target and tgt1).
I opened the .rlib files using "ar x", and a .rcgu.o file miscompares (the number is sometimes different).
I wrote a quick python program to compare the symbols in the one miscomparing file.  The problem is always .text._ZN3syn3lit5value13parse_lit_int17hd4273e85aeeb8db4E (syn::lit::value::parse_lit_int). It is different as follows:

.text._ZN3syn3lit5value13parse_lit_int17hd4273e85aeeb8db4E
b'41574156534883ec604885f60f84f00300008a0f4883fe010f85fd00000031c080f9300f84fe00000080c1d080f90a0f83cd03000041b80a00000031c04989c14c8d56ff31c031c90f1f8400000000004c8d1c0f4c8d3c060fb61c0f89da80c2d080fa09764a80fb5f0f85130100004c895c24184c897c242048c7442408010000004c897c24104939ca740b807c0f01bf0f8e410300004883c1014883c0ff4839ce75ace9d50200000f1f8000000000440fb6f24c897424284d39f00f86550200004c89c849f7e00f80d10000004c01f00f82c80000004c895c24184c897c242048c7442408010000004c897c24104939ca740b807c0f01bf0f8ed90200004829ce4883c6ff4801cf4883c7014939ca0f8527ffffffe9a80200008a470180f9300f8502ffffff3c62747b3c6f0f84500200003c780f85fafeffff48897c2418488974242048c74424080200000048897424104883fe0274144883fe030f8275020000807f02bf0f8e6b0200004883c70241b8100000004883c6fe756fe93f02000080fb2e740e80fb45740980fb650f85310200004983f80a0f852702000031c0e92502000048897c2418488974242048c74424080200000048897424104883fe0274144883fe030f820a020000807f02bf0f8e000200004883c70241b8020000004883c6fe0f84d50100004983f80b0f8245feffff31c04989c14c8d56ff31c94989f3662e0f1f8400000000006690488d1c0f0fb6040f89c280c2d080fa0a725e3c60760a3c677314e9bc0000009089c280c2bf80fa050f86c30000003c5f0f858001000048895c24184c895c242048c7442408010000004c895c24104939ca740b807c0f01c00f8c6a0100004983c3ff4883c1014839ce7595e9fe000000440fb6f24c897424284d39c60f83850000004c89c849f7e00f8001ffffff4c01f00f82f8feffff48895c24184c895c242048c7442408010000004c895c24104939ca740b807c0f01c00f8c090100004829ce4883c6ff4801cf4883c7014939ca0f8512ffffffe9d8000000049f440fb6f04983c60a4c897424284d39c67293eb16440fb6f24983c60a4c897424284d39c60f827bffffff488d4424284889442418488b05000000004889442420488d0500000000488944243048c744243802000000488d0500000000488944244048c744244801000000488d442418488944245048c744245801000000488d3500000000488d7c2430ff15000000000f0b4c89c8eb4348897c2418488974242048c74424080200000048897424104883fe02740c4883fe037231807f02bf7e2b4883c70241b8080000004883c6fe0f852bfeffff31c04989c1b8010000004c89ca4883c4605b415e415fc3488d4424184889442430488d4424084889442438488d4424104889442440488d7c2430e8000000000f0b488d3d00000000488d1500000000be28000000e8000000000f0b'

.text._ZN3syn3lit5value13parse_lit_int17hd4273e85aeeb8db4E
b'4156534883ec584885f60f84d70300008a0f4883fe010f85fe00000031c080f9300f84ff00000080c1d080f90a0f83b403000041b80a00000031c04989c14c8d56ff31c94889f3660f1f8400000000004c8d1c0f0fb6040f89c280c2d080fa09764e3c5f0f85160100004c895c241048895c241848c704240100000048895c24084939ca740b807c0f01bf0f8e2e0300004883c3ff4883c1014839ce75b2e9c5020000662e0f1f8400000000000f1f00440fb6f24c897424204d39f00f863f0200004c89c849f7e00f80cc0000004c01f00f82c30000004c895c241048895c241848c704240100000048895c24084939ca740b807c0f01bf0f8ec10200004829ce4883c6ff4801cf4883c7014939ca0f8526ffffffe9920200008a470180f9300f8501ffffff3c6274773c6f0f843b0200003c780f85f9feffff48897c2410488974241848c704240200000048897424084883fe0274144883fe030f825e020000807f02bf0f8e540200004883c70241b8100000004883c6fe756be92a0200003c2e740c3c4574083c650f851f0200004983f80a0f851502000031c0e91302000048897c2410488974241848c704240200000048897424084883fe0274144883fe030f82f7010000807f02bf0f8eed0100004883c70241b8020000004883c6fe0f84c40100004983f80b0f8249feffff31c04989c14c8d56ff31c94989f36690488d1c0f0fb6040f89c280c2d080fa0a725d3c60760a3c677314e9ba0000009089c280c2bf80fa050f86c10000003c5f0f857901000048895c24104c895c241848c70424010000004c895c24084939ca740b807c0f01c00f8c620100004983c3ff4883c1014839ce7596e9f9000000440fb6f24c897424204d39c60f83800000004c89c849f7e00f800dffffff4c01f00f8204ffffff48895c24104c895c241848c70424010000004c895c24084939ca740b807c0f01c00f8c020100004829ce4883c6ff4801cf4883c7014939ca0f851effffffe9d3000000049f440fb6f04983c60a4c897424204d39c67294eb12440fb6f24983c60a4c897424204d39c67280488d4424204889442410488b05000000004889442418488d0500000000488944242848c744243002000000488d0500000000488944243848c744244001000000488d442410488944244848c744245001000000488d3500000000488d7c2428ff15000000000f0b4c89c8eb4248897c2410488974241848c704240200000048897424084883fe02740c4883fe03722f807f02bf7e294883c70241b8080000004883c6fe0f853cfeffff31c04989c1b8010000004c89ca4883c4585b415ec3488d44241048894424284889e04889442430488d4424084889442438488d7c2428e8000000000f0b488d3d00000000488d1500000000be28000000e8000000000f0b'

We pull lots of rust libs into our code via chains of dependencies.  Strangely, yours is the ONLY one that is nondeterministic!  Yeah, you are probably rolling your eyes right now and looking at the parse_lit_int it seems pretty crazy to me as well.  But I am no rust expert.  

Any help/ideas would be tremendously appreciated!

**Comment by dtolnay** [comment]
Thanks for narrowing this down. That seems like it would be nondeterminism in rustc or llvm. The next thing I would recommend trying is minimizing this down by removing unrelated code from Syn until it is no longer possible to remove anything while retaining the nondeterminism. At that point the minimal test case may be specific enough that it helps you find an already filed bug reporting the same thing, or file a new one for the compiler folks to investigate.

**Comment by gandrewstone** [comment]
Looking at the routine, a possible source of ambiguity is the types of certain constants.  I tried this diff and got consistent builds 4 times:
diff --git a/src/lit.rs b/src/lit.rs
index 3a66cb7..5564cc1 100644
--- a/src/lit.rs
+++ b/src/lit.rs
@@ -1021,17 +1021,17 @@ mod value {
         let base = match (byte(s, 0), byte(s, 1)) {
             (b'0', b'x') => {
                 s = &s[2..];
-                16
+                16u64
             }
             (b'0', b'o') => {
                 s = &s[2..];
-                8
+                8u64
             }
             (b'0', b'b') => {
                 s = &s[2..];
-                2
+                2u64
             }
-            (b'0'...b'9', _) => 10,
+            (b'0'...b'9', _) => 10u64,
             _ => unreachable!(),
         };
 
@@ -1040,16 +1040,16 @@ mod value {
             let b = byte(s, 0);
             let digit = match b {
                 b'0'...b'9' => u64::from(b - b'0'),
-                b'a'...b'f' if base > 10 => 10 + u64::from(b - b'a'),
-                b'A'...b'F' if base > 10 => 10 + u64::from(b - b'A'),
+                b'a'...b'f' if base > 10u64 => 10u64 + u64::from(b - b'a'),
+                b'A'...b'F' if base > 10u64 => 10u64 + u64::from(b - b'A'),
                 b'_' => {
                     s = &s[1..];
                     continue;
                 }
                 // NOTE: Looking at a floating point literal, we don't want to
                 // consider these integers.
-                b'.' if base == 10 => return None,
-                b'e' | b'E' if base == 10 => return None,
+                b'.' if base == 10u64 => return None,
+                b'e' | b'E' if base == 10u64 => return None,
                 _ => break,
             };

Do you know whether the language is unambiguously specified WRT numeric literals, and if so, what is the spec?

**Comment by dtolnay** [comment]
The language is not ambiguous about the type of numeric literals. `digit` is inferred as u64 because it is only ever assigned a value of type u64. `base` is inferred as u64 because that is the only PartialOrd impl that makes `digit >= base` legal.

**Comment by gandrewstone** [comment]
ok thanks for your help!
