### ISSUE TITLE
Token macro is broken in 0.15.39

### ISSUE THREAD

**Issue by nrc** [dtolnay/syn#668]
Any use of the `Token` macro gives the error: `error[E0433]: failed to resolve: unresolved import`, `help: a similar path exists: `syn::token``.

This can be worked around by adding `use syn::token;` to the use site. I assume the `Token` implementation just needs an absolute path somewhere.

This caused compilation errors with derive-new.

**Comment by dtolnay** [comment]
This is a compiler bug: https://github.com/rust-lang/rust/issues/62562. Please use an older compiler for now.
