### ISSUE TITLE
How to create an escaped Ident

### ISSUE THREAD

**Issue by ggriffiniii** [dtolnay/syn#669]
I'm generating code for struct definitions and some of the struct fields are going to use keywords unfortunately. How do I create an Ident using the escape syntax with syn?

```rust
// Code that doesn't currently work
use syn::Ident;
use quote::quote;
use proc_macro2::Span;

fn main() {
    let ident = Ident::new("r#match", Span::call_site());
    println!("{}", quote!{#ident});
}
```
This fails with `thread 'main' panicked at '"r#match" is not a valid Ident',`
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d6fcb2c3928f265221383b31f9548804)

Does there already exist a way to do this? If not would you be open to patches to allow Ident::new to accept this syntax?

**Comment by dtolnay** [comment]
The compiler's proc macro api does it with [`Ident::new_raw`](https://doc.rust-lang.org/proc_macro/struct.Ident.html#method.new_raw), but it isn't stable yet. For now the stable way would be `syn::parse_str::<Ident>("r#...").unwrap()`.

**Comment by ggriffiniii** [comment]
Thank you very much for the prompt response and the solution.
