### ISSUE TITLE
Fails to clone

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#69]
I noticed this in IRC:

> **\<panicbit>** For some reason cargo fails to clone https://github.com/dtolnay/syn for me :/

@panicbit did this get sorted out? What was going on?

**Comment by panicbit** [comment]
Not sure what happened. I could clone it via git but not via cargo. It started to work after a few tried though.

**Comment by dtolnay** [comment]
Strange, must have been a GitHub glitch. Sounds like there is nothing to follow up on. Thanks!

**Comment by panicbit** [comment]
Yeah, looks like GH has had some issues 
![screenshot_20161127-201609](https://cloud.githubusercontent.com/assets/628445/20651086/71dd722c-b4de-11e6-9b20-b62d87ab0665.png)
