### ISSUE TITLE
RFC: exhaustive matching idiom

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#694]
Here is the pattern I would like to document and recommend for use cases that require exhaustive matching (which is uncommon, but they exist):

```rust
match expr {
    Expr::Array(e) => {...}
    Expr::Assign(e) => {...}
    ...
    Expr::Yield(e) => {...}

    #[cfg(test)]
    Expr::TestExhaustive => unimplemented!(),
    #[cfg(not(test))]
    _ => { /* some sane fallback */ }
}
```

This way we fail your tests but don't break your library when adding a variant. I believe this has all the benefits of an exhaustive enum and all the benefits of a nonexhaustive enum for only a little effort.

FYI @zerakun @phaylon @BurntSushi from the reddit thread.
FYI @mystor for brainstorming.
FYI @Centril because language support for nonexhaustive would need to have at least these benefits before I would want to pick it up.

**Comment by CAD97** [comment]
Just out of curiosity, is there a simple (ish) example of a case for external code to be matching enough cases for test-exhaustive matching to be used?

**Comment by BurntSushi** [comment]
Interesting. Presumably this means that the `Nonexhaustive` variant becomes a proper part of the public API? I'm not quite sure how I feel about that, but I can see how that would be a good thing.

I would also like to see use cases where it's critical/important for folks to do exhaustive matching on a non-exhaustive enum.

**Comment by dtolnay** [comment]
For example a prettyprinter. I think there is room for a low-effort formatted printing library that just does a newline and indentation level on every open curly brace, with a small number of other heuristics. I would use such a thing [here](https://github.com/dtolnay/syn/blob/1.0.0/codegen/src/file.rs) so we don't have to build all of rustfmt and don't have to rely on the system's rustfmt which is inconsistent across different developers' machines and sometimes missing from nightly.

**Comment by CAD97** [comment]
For the simple pretty printer example specifically, I'd expect it to work [directly on `TokenStream` rather than on a syn AST](https://github.com/rust-lang/gll/blob/355fe4293a8a7ae884dc054adaf58a499c7e549a/src/generate/src.rs#L261-L328).

That said, I could see the syntax version of `#[non_exhaustive]` (i.e. `enum E { A, B, .. }`) supporting this "warn about actual non exhaustion". With similar semantics to this: `match e { A => {}, B => {}, .. }` would warn on unmatched variants or if the enum is not nonexhaustive, and otherwise behave as `_ => unimplemented!()`.

**Comment by dtolnay** [comment]
I think the sweet spot for fast-compiling code generators is somewhere between what that TokenStream code does and what rustfmt does. For example things like the punctuation in closures really needs there to be a syntax tree for structure rather than just TokenStream.

```rust
let out = tokens.unwrap_or_else(|err| err.to_compile_error());
//                              ^^^^^
```

**Comment by Centril** [comment]
>  FYI @Centril because language support for nonexhaustive would need to have at least these benefits before I would want to pick it up.

What `#[non_exhaustive]` on `pub enum Foo { ... }` (defined in crate A) does is to force crates depending on A to always have an arm with a pattern which will always match, e.g. `_ => $expr` or `$ident => $expr`.

This would let crate B have:

```rust
match expr {
    Expr::Array(e) => {...}
    Expr::Assign(e) => {...}
    ...
    Expr::Yield(e) => {...}

    #[cfg(test)]
    not_matched => unimplemented!("{:#?}", not_matched),

    #[cfg(not(test))]
    not_matched => { /* some sane fallback */ }
}
```

**Comment by dtolnay** [comment]
@Centril that's definitely less good because downstream's tests will continue to pass even after we add a variant. The point is for them to notice that a variant has been added so that they can update their code, without breaking downstream's users in the interim.

**Comment by dtolnay** [comment]
I had a chat with @Centril and here is my language based alternative proposal: https://github.com/rust-lang/rust/issues/44109#issuecomment-521781237.

**Comment by programmerjake** [comment]
https://github.com/dtolnay/syn/blob/436eb2208d7e8e4a6f2b5a898e2af92980edd449/src/expr.rs#L247-L251

Maybe change the links in the code to instead point to https://github.com/rust-lang/rust/issues/81657

**Comment by ModProg** [comment]
> Maybe change the links in the code to instead point to [rust-lang/rust#81657](https://github.com/rust-lang/rust/issues/81657)

I think it would be https://github.com/rust-lang/rust/issues/89554 as that is actually in work
