### ISSUE TITLE
Consider using `FnMut` instead of `fn` for things like `Punctuated::parse_terminated_with`

### ISSUE THREAD

**Issue by Popog** [dtolnay/syn#697]
These are the functions I found that take a bare function type as an argument:
`Punctuated::parse_terminated_with`
`Punctuated::parse_separated_nonempty_with`
`ParseBuffer::call`
`ParseBuffer::parse_terminated`

This proposal is to change from:
```
impl<'a> ParseBuffer<'a> {
    pub fn call<T>(&self, function: fn(ParseStream) -> Result<T>) -> Result<T> {
    ...
    }
}
```

To:
```
impl<'a> ParseBuffer<'a> {
    pub fn call<T, F: FnOnce(ParseStream) -> Result<T>>(&self, function: F) -> Result<T> {
    ...
    }
}
```

This change would break references to these functions, so it may be better to introduce new functions and just change the existing functions to call the new functions.

Maybe suffix new functions with `_fn`?

**Comment by dtolnay** [comment]
The API is intentionally limited to prevent complicated code that should be written a clearer way.

Could you give an example of parsing code that you would like to able to write that needs the FnMut signatures?

**Comment by Popog** [comment]
I'm writing a macro which declares a bunch of field prototypes which can then be used to declare a bunch of structures that essentially remix from those prototypes. To cut down my code as much as possible:
```rust
struct Item {
    _brace_token: token::Brace,
    fields: Punctuated<Field, Token![,]>,
    structures: Punctuated<ItemStruct, Empty>,
}
struct ItemStruct {
    _struct_token: Token![struct],
    _brace_token: token::Brace,
    fields: Punctuated<Ident, Token![,]>,
}
```

When I was writing this it seemed like the easiest way to emit errors was to turn `Item.fields` into a hash map keyed on `ident` and error parsing any `ItemStruct.fields`.

There's not anything preventing me from just looping through all the parsed fields and then validating them. It just felt more natural to do it on the parse via a lambda that binds a parse helper on `ItemStruct`, i.e. `fn parse_with_ident(fields: &HashSet<Fields>, input: ParseStream) -> Result<Self>` being called in as `input.parse_terminated(|input| ItemStruct::parse_with_idents(&fields, input))`

**Comment by jplatte** [comment]
I've also just run into this. I've still got a bunch of refactoring to do though, not sure whether it would ultimately be useful for me to be able to use a closure with `parse_terminated`.

**Comment by jjl** [comment]
the combination of not having closures in callbacks (e.g. for `ParseBuffer.call`) and the `Parse` trait makes it essentially impossible to implement data-driven parsing within syn's framework.

The simplified version of my problem is essentially implementing `macro_rules`, When matching, i need to be able to perform parsing according to what the pattern says. in the absence of closure, my only two options seem to be:

1. thread locals (eww!)
2. do most of the parsing myself and only call syn to parse e.g. the 'item' fragspec. which is basically what i'm doing, but which involves cloning lots of `TokenTree`s converting to and from `TokenStream`s.

**Comment by dtolnay** [comment]
I have written a huge amount/variety of parsing using syn's API by this point, so I am not convinced that the API is too limiting. I'll go ahead and close this issue.

**Comment by dtolnay** [comment]
> the combination of not having closures in callbacks (e.g. for `ParseBuffer.call`)

I don't see any way that the signature of ParseBuffer::call would be limiting to anything. This should be clear from the implementation: https://github.com/dtolnay/syn/blob/1.0.69/src/parse.rs#L504-L506. Write a simple function call and pass whatever args you would feel are relevant. `parse_thing(input, arg1, arg2)`

> and the `Parse` trait not having a method taking `&self`

Again "parse trait with arguments" is just a function call. `parse_whatever(input, arg1, arg2)`
