### ISSUE TITLE
Return a result instead of panicking

### ISSUE THREAD

**Issue by sgrif** [dtolnay/syn#7]
I'm looking at possibly using this in Diesel as we switch to Macros 1.1. I was surprised to see that there's a lot of `panic!` in the parser. I'd expect this function to return a Result and allow the caller to decide how to handle the error.

**Comment by dtolnay** [comment]
For the Macros 1.1 use case the compiler guarantees that the input will be a valid struct or enum so the panics "can't happen," and besides, the way Macros 1.1 implementations signal failure is by panicking. From the RFC:

> If a macro cannot process the input token stream, it is expected to panic for now, although eventually it will call methods in `rustc_macro` to provide more structured errors.

The way I think about it, panics are for situations where a program realizes it contains a bug, and Results are for expected failures. In this case if syn fails to parse an input, that indicates a bug.

If you disagree or have a different use case, I would be open to returning a Result as long as it is not nom-specific, allowing us to swap out the implementation later (like LALRPOP or something else).

**Comment by dtolnay** [comment]
I added you as a collaborator on the repo and a crate owner on crates.io so you can make any changes you need. I don't want me to be a bottleneck on getting Diesel running. We can sort out the API later.

**Comment by dtolnay** [comment]
I made the change to `Result` because even though we don't need it for structs and enums, we do need it when parsing [attributes](https://serde.rs/attributes.html) that contains paths or where-clauses, and it was better to be consistent.
