### ISSUE TITLE
The ReturnType enum contains an explicit Box

### ISSUE THREAD

**Issue by reuvenpo** [dtolnay/syn#701]
The `ReturnType` type contains a variant that holds a boxed `Type`.
This makes matching against `ReturnType` impossible in stable rust (it would require the box_patterns feature).

Is this an intentional layout? if so, what is the reason?

**Comment by dtolnay** [comment]
Here is how you would match on the ReturnType:

```rust
use syn::{parse_quote, ItemFn, ReturnType, Signature, Type};

fn returns_result(sig: &Signature) -> bool {
    match &sig.output {
        ReturnType::Default => false,
        ReturnType::Type(_, ty) => match ty.as_ref() {
            Type::Path(ty) => ty.path.segments.last().unwrap().ident == "Result",
            _ => false,
        },
    }
}

fn main() {
    let method: ItemFn = parse_quote! {
        fn demo() -> Result<u8> {}
    };
    dbg!(returns_result(&method.sig));
}
```

**Comment by reuvenpo** [comment]
Oh! Ok, i see, that's pretty elegant. Thanks for the answer! :)

Still, is there a benefit to doing it this way? At face value it just feels redundant, but I'm pretty sure there's just something I'm missing.

**Comment by dtolnay** [comment]
It can't contain an unboxed Type. syn::Type contains syn::TypeBareFn which contains syn::ReturnType. You can't have a cycle of types containing themselves inline.

**Comment by reuvenpo** [comment]
Oh! Of course! I missed that... 😅
Thanks for clarifying that. I think we can close this issue.
