### ISSUE TITLE
Consider adding Error::into_compile_error

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#702]
This is commonly useful when lowering Result\<TokenStream\> to TokenStream.

```rust
// before
fallible(input)
    .unwrap_or_else(|err| err.to_compile_error())

// after
fallible(input)
    .unwrap_or_else(Error::into_compile_error)
```

**Comment by CreepySkeleton** [comment]
Honestly, I don't see much difference between the two.

Maybe we should attach `.unwrap_or_compile_error()` to `Result<TokenStream, syn::Error>` instead?
