### ISSUE TITLE
Parsing (more) custom syntax

### ISSUE THREAD

**Issue by alexschrod** [dtolnay/syn#704]
The `lazy-static` example claims to be "[a]n example of parsing a custom syntax," but the syntax shown in that example is like 99% similar to Rust's own syntax. I'm struggling to even get off the ground with my own macro, because one of the things I want to do are seemingly impossible. I want to take `expr : expr`, where `expr` is any valid expression (so, e.g. `"hello" : "world"` or `(5 - 2) : function_call()` and get a hold of each expression.

So, as one might, I tried doing
```rust
struct Test {
    left: Expr,
    right: Expr,
}

impl Parse for Test {
    fn parse(input: ParseStream) -> Result<Self> {
        let left: Expr = input.parse()?;
        input.parse::<Token![:]>()?;
        let right: Expr = input.parse()?;

        Ok(Test {
            left,
            right
        })
    }
}
```
Of course, it couldn't be that simple, right?
```
error: expected one of: `for`, parentheses, `fn`, `unsafe`, `extern`, identifier, `::`, `<`, square brackets, `*`, `&`, `!`, `impl`, `_`, lifetime
 --> sandbox\src\main.rs:8:29
  |
8 |     let x = test!("hello" : "world");
  |                             ^^^^^^^
```
Turns out, the `Expr` is too eager and tries to parse this as an `ExprType` expression (which are not even done using `"strings"`, right?!)

By the way, this `ExprType` seems infinitely eager; if I do `let x = test!(a: f64);` I get "error: expected `:`". Okay, that's fair, I did say I wanted a `:` after the first expression. But if I add another `:`, I go right back to this error message:
```
error: unexpected end of input, expected one of: `for`, parentheses, `fn`, `unsafe`, `extern`, identifier, `::`, `<`, square brackets, `*`, `&`, `!`, `impl`, `_`, lifetime
 --> sandbox\src\main.rs:8:13
  |
8 |     let x = test!(a: f64 :);
  |             ^^^^^^^^^^^^^^
  |
```
This error comes from the first `.parse()` call it turns out, because I debug print `left` after it's done parsing, and that never gets printed for this particular case.

Now, I don't **want** type expressions to be legal there. In fact, are they even legal expressions at all? Can you even ever do things like `let x = a: f64` or `if b: u32 { ... }`?

Is there some way for me to coerce `syn` into not trying to parse an `ExprType` there? I'd like anything that at some point or another becomes a valid value (i.e. something you can put as `rhs` in `let x = rhs` to be parsed there; nothing else. What do?

I tried looking through the documentation as best I could before coming here, but I'm at a loss, so I'm giving this a shot.

**Comment by dtolnay** [comment]
> In fact, are they even legal expressions at all? Can you even ever do things like `let x = a: f64` or `if b: u32 { ... }`?

Yes, `a: f64` is an expression. Playground:
https://play.rust-lang.org/?version=nightly&gist=06cae2d57978aeafcb546f2fb7995e1c

To parse anything before a `:` as an expression you would need to use `input.peek(Token![:]) && !input.peek(Token![::])` and `input.parse::<TokenTree>()` to read one token at a time until a colon, then parse those tokens using `syn::parse2::<Expr>`.

**Comment by alexschrod** [comment]
@dtolnay Oh, wow. That's a syntax I hadn't seen before. Good to know.

Your suggestion works perfectly, thanks!
