### ISSUE TITLE
Sharp edge with `Attribute` documentation for doc comments

### ISSUE THREAD

**Issue by yaahc** [dtolnay/syn#708]
# The Problem

In the documentation for `Attribute` it mentions that docs are promoted to attributes but it doesn't really explain how, or what that entails. I ended up wasting an hour looking through the documentation for some enum or variable that would indicate that the attribute was a doc comment attribute because that's how I expected it to be expressed.

In the end I had to try debug printing the attributes, which made me figure out about the feature to enable debug impls, which ultimately made it clear that syn is inserting a `doc` path on doc attributes.

# The Proposal

I think it would be helpful to add a little blurb explaining how it's transformed. Something along the lines of

Doc comments of the form `/// blah blah blah` are represented as though they had been written as `#[doc = "blah blah blah"]`.

I'm not sure this is actually correct or what happens, but you get the gist and I'm sure you can explain this properly to someone unfamiliar with syn.

**Comment by dtolnay** [comment]
Thanks, I agree this needs to be documented better. FWIW this is exactly the transformation that happens in macro_rules too.

AST Explorer is good for figuring out this sort of thing.
https://astexplorer.net/#/gist/9dd6f6d9d2d75afce806b7479a5adbc3/057c4d5864ccd53aaa583b1f7b41ca28cb48d091
