### ISSUE TITLE
No parse_ident?

### ISSUE THREAD

**Issue by Arnavion** [dtolnay/syn#71]
Unless I'm missing something, there's no function to parse a `&str` as an `Ident` with validation, like the other `parse_*` family of functions.

My proc macro constructs `Ident`s from user-supplied strings, so it would be nice to fail early instead of letting the non-ident bubble up all the way to the final `TokenStream` and fail with a non-descriptive `LexError`.

**Comment by dtolnay** [comment]
I added [`syn::parse_ident`](https://docs.rs/syn/0.10.4/syn/fn.parse_ident.html) in 0.10.4.
