### ISSUE TITLE
Syn::File documentation example does not compile with given instructions

### ISSUE THREAD

**Issue by skreimeyer** [dtolnay/syn#710]
Attempting to build the following code from the documentation as instructed (with `full` feature enabled):
```
use std::env;
use std::fs::File;
use std::io::Read;
use std::process;

fn main() {
    let mut args = env::args();
    let _ = args.next(); // executable name

    let filename = match (args.next(), args.next()) {
        (Some(filename), None) => filename,
        _ => {
            eprintln!("Usage: dump-syntax path/to/filename.rs");
            process::exit(1);
        }
    };

    let mut file = File::open(&filename).expect("Unable to open file");

    let mut src = String::new();
    file.read_to_string(&mut src).expect("Unable to read file");

    let syntax = syn::parse_file(&src).expect("Unable to parse file");
    println!("{:#?}", syntax);
}
```
Results in the following error:
```
error[E0277]: `syn::file::File` doesn't implement `std::fmt::Debug`
  --> src/main.rs:24:23
   |
24 |     println!("{:#?}", syntax);
   |                       ^^^^^^ `syn::file::File` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `syn::file::File`
   = note: required by `std::fmt::Debug::fmt`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```
Which surprised me because the documentation states:
```
Example
A complete file of Rust source code.

This type is available if Syn is built with the "full" feature.
```
However, this is fixed by enabling the "extra-traits" feature:
```
[dependencies.syn]
version = "^1"
default-features = true
features = ["full", "extra-traits"]
```
Because `ast_struct!`  [link for brevity](https://docs.rs/crate/syn/1.0.5/source/src/macros.rs) only derives debug with the `extra-traits` feature (full by itself doesn't appear to derive any traits). Since the macro doesn't appear on the sidebar of the docs.rs, I had to clone the repository and grep for it to figure out where `ast_struct!` was defined.

So this isn't so much a "problem," but rather I'm submitting the issue and how I found the solution in case somebody else wonders why this example doesn't "just work", like I did.

**Comment by dtolnay** [comment]
Thanks! The type is indeed available whenever "full" is enabled. "extra-traits" is covered separately in the readme: https://github.com/dtolnay/syn#optional-features.
