### ISSUE TITLE
parse Pat for closure inputs

### ISSUE THREAD

**Issue by DevinR528** [dtolnay/syn#717]
Not sure if this is a bug or just me. I'm using syn version 1.0.8 I have tried this multiple ways
using `syn::parse2()` on a `quote! { co: Co<'_> }` also fails.
```rust
let arg = parse_str::<Pat>("co: Co<'_>").expect("Pat parse failed Co<'_>");
// then push it into the input `Vec<Punctuated<Pat, Comma>`
```
for adding an argument to
```rust
let hello = async || {
        co.yield_("hello").await;
    };
```
in order to get it to compile without giving me `unknown token` error I have to destructure
a `FnArg`
```rust
    let arg = match parse_str::<FnArg>("co: Co<'_>") {
            Ok(FnArg::Typed(x)) => x,
            _ => panic!("string Pat parse failed Co<'_>"),
        };
    punct.push(Pat::Type(arg))
```

**Comment by taiki-e** [comment]
I guess that `parse::<Pat>` is intentionally not parsed as `Pat::Type` because it is ambiguous whether the argument  `<pattern>: <type>` is `Pat` + `:` + `Type` or just `Pat::Type`.

**Comment by DevinR528** [comment]
I started to suspect it might be something like that. Thanks for getting back!
