### ISSUE TITLE
Broken doc link

### ISSUE THREAD

**Issue by Luro02** [dtolnay/syn#728]
The link to `TokenStream` in https://docs.rs/syn/1.0.11/syn/enum.Type.html is broken.
This is the link: https://docs.rs/proc-macro2/1.0.6/proc_macro2/struct.TokenStream.html

**Comment by mystor** [comment]
I believe this is caused by docs.rs erroring while building docs for `proc-macro2` (https://github.com/alexcrichton/proc-macro2/issues/203, https://github.com/rust-lang/docs.rs/issues/440).

**Comment by taiki-e** [comment]
Seems to have already fixed in the latest documents: https://docs.rs/syn/1.0.23/syn/enum.Type.html
