### ISSUE TITLE
How to add to ImplGenerics?

### ISSUE THREAD

**Issue by dhardy** [dtolnay/syn#732]
For a generated implementation I need to augment the list of generics (because the trait being implemented has its own generic parameters, while the type it is being implemented for also does).

Since ImplGenerics includes `< .. >` characters (if not empty), I think the only way of achieving this with the current API is to tokenise the thing, parse the tokens, then modify that.

Suggestion: add a method like this?
```rust
fn add_param(&mut self, tokens: TokenStream);
```

**Comment by dtolnay** [comment]
You should add to the original Generics before making ImplGenerics. For example: https://github.com/serde-rs/serde/blob/d540e72fc784e459c75d167973a9ac54ef1bd731/serde_derive/src/de.rs#L2915

**Comment by dhardy** [comment]
Thanks for the fast response!
