### ISSUE TITLE
parsing issue noticed in cbindgen

### ISSUE THREAD

**Issue by NickeZ** [dtolnay/syn#733]
Hello,

I ran into a problem when trying to use cbindgen. It fails at parsing protobuf. See more details here: https://github.com/eqrion/cbindgen/issues/429#issuecomment-565196321

I don't know how to easily reproduce the issue with more debug info.

```
ERROR: Parsing crate `protobuf`:`/home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.8.1/src/reflect/accessor.rs`:
Error("expected one of: identifier, `::`, `<`, `_`, literal, `ref`, `mut`, `&`, parentheses, square brackets, `..`")
Try running `rustc -Z parse-only /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.8.1/src/reflect/accessor.rs` to see a nicer error message
ERROR: Couldn't generate bindings for ../../.
```

**Comment by dtolnay** [comment]
We don't support parsing 2015-only code in general.

It looks like the complete error from syn is:

```console
error: expected one of: identifier, `::`, `<`, `_`, literal, `ref`, `mut`, `&`, parentheses, square brackets, `..`
   --> protobuf/src/reflect/accessor.rs:126:30
    |
126 |     fn get_field<'a>(&self, &'a M) -> &'a R;
    |                              ^^
```

Rustc's 2018 parser rejects that as well:

```console
error: unexpected lifetime `'a` in pattern
   --> protobuf/src/reflect/accessor.rs:126:30
    |
126 |     fn get_field<'a>(&self, &'a M) -> &'a R;
    |                              ^^ unexpected lifetime
```

**Comment by NickeZ** [comment]
OK, so would you say that cbindgen is using syn wrong? Should I open an issue there again?

**Comment by dtolnay** [comment]
The best fix would be to make protobuf use modern syntax for trait methods (even if they stay on 2015 edition).

**Comment by NickeZ** [comment]
What is the new syntax if I may ask? does it have something to do with lifetime eilison?

**Comment by dtolnay** [comment]
No, it's https://doc.rust-lang.org/edition-guide/rust-2018/trait-system/no-anon-params.html.

**Comment by NickeZ** [comment]
OK, then I think protobuf already is fixed on master. Thanks for helping me
