### ISSUE TITLE
Get span of inside of string literal in attributes

### ISSUE THREAD

**Issue by 95th** [dtolnay/syn#735]
In https://github.com/95th/defaults/issues/1, I want to get inner span of string literal.

For e.g. for this:

```
#[derive(Defaults)]
#[def = "Foo::A"]
enum Foo {
    A(usize),
    B,
}
```

I want to get span of `Foo::A`  but I get span of `"Foo::A"` instead.

https://github.com/95th/defaults/blob/e90cf084bc25b3adc3ce3ae74582163bbe42f320/src/lib.rs#L95

Is there a way to get the inner span?

**Comment by dtolnay** [comment]
You may be able to parse the attribute's contents to proc_macro2::Literal (instead of Meta) and then use https://docs.rs/proc-macro2/1.0.4/proc_macro2/struct.Literal.html#method.subspan. I haven't tested this recently.

Longer term this would be handled seamlessly by #621.

**Comment by 95th** [comment]
>Warning: the underlying proc_macro::Literal::subspan method is nightly-only. When called from within a procedural macro not using a nightly compiler, this method will always return None.

Seems like `subspan` works only in Nightly. Is there a stable alternative?

**Comment by dtolnay** [comment]
No.
