### ISSUE TITLE
Losing span when GenericMethodArgument itself is a generic

### ISSUE THREAD

**Issue by elslooo** [dtolnay/syn#736]
I am not sure if this goes wrong in syn, quote or proc_macro, but I'm losing compiler error source information when transforming a nested item that contained a generic method argument prior to the transformation.

Given this identity transformation (which simply outputs the input):

```rust
extern crate proc_macro;

use proc_macro::TokenStream;
use quote::quote;

#[proc_macro_attribute]
pub fn transformer(_args: TokenStream, input: TokenStream) -> TokenStream {
    // Note: `return input;` (i.e. skipping the parser) does work but isn't really a solution.
    let input: syn::Item = syn::parse(input).unwrap();
    (quote! {#input}).into()
}
```

This does not work in the following cases where I explicitly access a non-existent property of a struct.

```rust
use transformer::*;

struct Foobar;

#[transformer]
impl Foobar {
    #[transformer]
    fn does_not_work_1() -> usize {
        let result = vec![].into_iter().collect::<Vec<_>>();
        result.sizeee() // macbook keyboard
        // error[E0599]: no method named `sizeee` found for type `std::vec::Vec<_>` in the current scope
    }

    #[transformer]
    fn does_not_work_2() -> usize {
        let result = vec![].into_iter().collect::<Vec<usize>>();
        result.sizeee()
        // error[E0599]: no method named `sizeee` found for type `std::vec::Vec<usize>` in the current scope
    }
}
```

Observe that the compiler does not give accurate source info for the errors (not even the filename).

Currently, there are three work-arounds that I know of that can a) make it work in the meantime and b) potentially help in tracing the bug.

1. Don't use generic method arguments.
2. Use a type alias for generic types.
3. Don't wrap in another item.

```rust
use transformer::*;

type UsizeVec = Vec<usize>;

struct Foobar;

#[transformer]
impl Foobar {
    #[transformer]
    fn works_1() -> usize {
        let result: Vec<_> = vec![].into_iter().collect();
        result.sizeee()
        // error[E0599]: no method named `sizeee` found for type `std::vec::Vec<_>` in the current scope
        // --> src/lib.rs
        // 33 | result.sizeee()
        //             ^^^^^^ method not found in `std::vec::Vec<_>`
    }

    #[transformer]
    fn works_2() -> usize {
        let result = vec![].into_iter().collect::<UsizeVec>();
        result.sizeee()
        // error[E0599]: no method named `sizeee` found for type `std::vec::Vec<usize>` in the current scope
        // --> src/lib.rs
        // 43 | result.sizeee()
        //             ^^^^^^ method not found in `std::vec::Vec<usize>`
    }
}


#[transformer]
fn works_3() -> usize {
    let result = vec![].into_iter().collect::<Vec<_>>();
    result.sizeee()
    // error[E0599]: no method named `sizeee` found for type `std::vec::Vec<_>` in the current scope
    // --> src/lib.rs
    // 54 | result.sizeee()
    //             ^^^^^^ method not found in `std::vec::Vec<_>`
}
```

I would like to help fix this bug but I can't really find where things go wrong. I looked at the `ToTokens` implementation of `GenericMethodArgument` but that looks fine. It could also be that the same tokens are essentially parsed and synthesized twice (once by the `impl`-transformer, once by the `fn`-transformer) but I don't understand why it would specifically cause problems when using generic method arguments.

Any help would be greatly appreciated! This is a [gist](https://gist.github.com/elslooo/d931e7d929caf15086f6bfe167cdbfb5) with everything you need to reproduce this issue.

**Comment by dtolnay** [comment]
This is a compiler bug: https://github.com/rust-lang/rust/issues/43081. You can insert `eprintln!("{:#?}", input)` at the top of `transformer` and see that the compiler has already screwed up the spans before syn even sees the input -- they are passed in as `#0 bytes(0..0)`.

Unfortunately it doesn't seem likely that this will be getting fixed soon, and it makes many attribute-macros like #\[transformer\] pretty useless since they can't reliably produce error messages inside the code they are called on.

**Comment by elslooo** [comment]
Yep, thought as much after I did some more research.

It's really unfortunate indeed because e.g. wasm-bindgen errors are close to impossible to trace back ...

For anyone _writing_ (not using) a macro that wants better error messages, a possible (though restricted) workaround is concatenating token streams (leaving the original stream largely intact).

For example, for the bindgen usecase, a possible solution would be to do:

```diff
- quote! {
-     impl #name {
-         #body
-         
-         #helpers
-     }
- }
+ TokenStream::from_iter(vec![
+     input,
+     quote! {
+         impl #name {
+             #helpers
+         }
+     }.into(),
+ ])
```

This way, you do get the original unmodified spans of the `input` stream and only the spans of the `helpers` are useless. This of course only works if you can separate them cleanly (i.e. only synthetic, known-good code in `helpers`).

Anyway, thanks for the help and everyone's work on this awesome library!
