### ISSUE TITLE
Use `proc-macro2` with `span-locations` feature 

### ISSUE THREAD

**Issue by botika** [dtolnay/syn#737]
I open this issue to request a new improvement, we can locate span outside the macro. 

You collect the span from `proc-macro2`. then it would be easy to locate each slice by bounding it with my own Span. Since each cursor is created [it will be mapped to a new file](https://github.com/alexcrichton/proc-macro2/blob/master/src/fallback.rs#L36-L48).

The implementation in `syn` would consist of adding `syn` and `proc-macro2`, `span-locations` feature and warning of the limitations of the rust versions in the documentation

**Comment by dtolnay** [comment]
It sounds like you are asking for syn to enable proc-macro2's span-locations feature.

We don't need to do that, any downstream crate that wants syn to use span-locations can add its own dependency on proc-macro2 and enable the feature.
