### ISSUE TITLE
wrong span for error

### ISSUE THREAD

**Issue by Dushistov** [dtolnay/syn#739]
If compile and run code bellow with syn 1.0.11 it prints:

> err expected `:` span LineColumn { line: 1, column: 0 } LineColumn { line: 1, column: 0 }

But error location is near `String` it is not 'line 1, column: 0'.
If fix syntax: `_: String`, and print spans of arguments of function `b` all spans are correct.
So something wrong with error span calculation.

```Rust
fn main() {
    let code = r#"
impl Foo {
   fn b(a: i32, String) {}
}
"#;
    let ast = match syn::parse_file(code) {
        Ok(x) => x,
        Err(err) => {
            println!(
                "err {} span {:?} {:?}",
                err,
                err.span().start(),
                err.span().end()
            );
            return;
        }
    };
}
```

**Comment by dtolnay** [comment]
Thanks! Fixed in 1.0.12.
