### ISSUE TITLE
Throwing errors when using macros 1.1

### ISSUE THREAD

**Issue by JelteF** [dtolnay/syn#74]
With my previous derive code I used `cx.span_bug` and `cx.span_fatal` in cases where an unsuppported structure was passed to my derive code. Now I'm using `panic!`, is this indeed the best way or am I missing something better?

**Comment by dtolnay** [comment]
That is the best way. In the future Macros 2.0 will provide more sophisticated ways of reporting errors, for example being able to tie errors to a specific span of the input like a single field.

**Comment by dtolnay** [comment]
From [the RFC](https://github.com/rust-lang/rfcs/blob/master/text/1681-macros-1.1.md):

> If a macro cannot process the input token stream, it is expected to panic for now, although eventually it will call methods in `rustc_macro` to provide more structured errors. The compiler will wrap up the panic message and display it to the user appropriately. Eventually, however, `librustc_macro` will provide more interesting methods of signaling errors to users.

**Comment by JelteF** [comment]
Thanks
