### ISSUE TITLE
Can we get only few items from enum item?

### ISSUE THREAD

**Issue by AchalaSB** [dtolnay/syn#745]
We can get complete AST with `full` feature for Rust code it contains below fields. 

Is there any way to exclude some of the items from the list. 
ex: exclude externCrate, Use etc.
```
pub enum Item {
    ExternCrate(ItemExternCrate),
    Use(ItemUse),
    Static(ItemStatic),
    Const(ItemConst),
    Fn(ItemFn),
    Mod(ItemMod),
    ForeignMod(ItemForeignMod),
    Type(ItemType),
    Existential(ItemExistential),
    Struct(ItemStruct),
    Enum(ItemEnum),
    Union(ItemUnion),
    Trait(ItemTrait),
    TraitAlias(ItemTraitAlias),
    Impl(ItemImpl),
    Macro(ItemMacro),
    Macro2(ItemMacro2),
    Verbatim(ItemVerbatim),
}
```
Thanks

**Comment by dtolnay** [comment]
Hi @AchalaSB, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community. Syn is one of the most widely used crates so lots of people will have experience with it.
