### ISSUE TITLE
Span of `FnArg` is too narrow during errors

### ISSUE THREAD

**Issue by nrxus** [dtolnay/syn#754]
When emitting an error using `syn::Error::to_compile_error` with the Span from an `FnArg`, only the pattern of the argument is underlined, which is not necessarily where the error lies. 

For a macro like this:
```rust
#[proc_macro_attribute]
pub fn method(_args: TokenStream, method: TokenStream) -> TokenStream {
    let method = syn::parse_macro_input!(method as syn::ImplItemMethod);
    let receiver = method.sig.inputs.first().unwrap();
    syn::Error::new(receiver.span(), "this error should also cover the type")
        .to_compile_error()
        .into()
}
```

And a usage like this:
```rust
struct SomeStruct;

impl SomeStruct {
    #[method]
    fn some_method(self: std::rc::Rc<Self>) {}
}
```

The compile error displayed is: 

```
error: this error should also cover the type
 --> tests/method.rs:9:20
  |
9 |     fn some_method(self: std::rc::Rc<Self>) {}
  |                    ^^^^

error: aborting due to previous error
```

Ideally the error should be:
```
error: this error should also cover the type
 --> tests/method.rs:9:20
  |
9 |     fn some_method(self: std::rc::Rc<Self>) {}
  |                    ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

as that is the entire argument, the "self" portion is just the ident. 

[Link to repo with repro](https://github.com/nrxus/macro-playground)

**Comment by dtolnay** [comment]
You would need to write this using [Error::new_spanned](https://docs.rs/syn/1.0.14/syn/struct.Error.html#method.new_spanned) because rustc does not expose a way to combine multiple Spans into a single Span.

```rust
syn::Error::new_spanned(receiver, "this error should also cover the type")
```

**Comment by nrxus** [comment]
Ah! That makes sense, sorry for not going through the docs on `Error` closely enough.
