### ISSUE TITLE
Getting unused import warnings when deriving enums

### ISSUE THREAD

**Issue by rushmorem** [dtolnay/syn#76]
When deriving an enum I'm getting `unused import` warnings. I'm not getting this warning with structs or enums with no variants. You can see an example of this [in this Travis build](https://travis-ci.org/rust-rethinkdb/reql/jobs/192124007#L317).

- [Here](https://github.com/rust-rethinkdb/reql/blob/5c8f129e405b6152df09020c776c89f89430a3de/reql-derive/src/command.rs#L13) is the function that's generating the tokens
- [Here](https://github.com/rust-rethinkdb/reql/blob/5c8f129e405b6152df09020c776c89f89430a3de/src/commands/append.rs#L1) is where I'm calling the `derive` macro
- Also note that I have a [Command struct](https://github.com/rust-rethinkdb/reql/blob/5c8f129e405b6152df09020c776c89f89430a3de/src/lib.rs#L17) in the library in case it is somehow contributing to this

/cc @dtolnay

**Comment by dtolnay** [comment]
This is what your generated code looks like. (I got this by running [`cargo expand`](https://github.com/dtolnay/cargo-expand) in your crate.)

```rust
pub trait Append {
    fn append<T>(self, value: T) -> ::Command where T: ::IntoArg;
}
impl Append for ::Command {
    fn append<T>(self, value: T) -> ::Command
        where T: ::IntoArg
    {
        let mut term = ::ql2::proto::Term::new();
        term.set_field_type(::ql2::proto::Term_TermType::APPEND);
        if let Some(cmd) = self.term {
            let args =
                ::protobuf::repeated::RepeatedField::from_vec(<[_]>::into_vec(box [cmd]));
            term.set_args(args);
        }
        use IntoArg;
        for arg in value.into_arg() {
            term.mut_args().push(arg);
        }
        ::Command {
            term: Some(term),
            idx: self.idx + 1,
        }
    }
}
```

The unused import is the `use IntoArg` line. IntoArg is already in scope for `value` because value is of type T and has the bound `T: IntoArg`. If you get rid of all three places you have `use IntoArg` in command.rs, the warnings go away!

**Comment by rushmorem** [comment]
Awesome. Thanks for the quick response! Somehow, I just assumed that since the error message was saying ```warning: unused import: `Command`, #[warn(unused_imports)] on by default``` it was complaining about importing the `Command` struct.
