### ISSUE TITLE
The Unsafe Code in TokenBuffer

### ISSUE THREAD

**Issue by jhwgh1968** [dtolnay/syn#769]
While running [``cargo geiger``](https://github.com/rust-secure-code/cargo-geiger) on a project which uses this crate, I was surprised to see it contained unsafe code. The biggest chunk of unsafe code is in ``TokenBuffer``.

After having spent 15 minutes studying the implementation with my C chops, it seems to me the same semantics and speed could be achieved entirely in safe code. The new ``Pin`` trait could be used to ensure the ``Box[Entry]`` didn't move, and clever use of sub-sliced offsets could replace the pointer math.

Would a PR to do this be welcome? Or is there a reason all this unsafe code is necessary? (I missed something, rust version compatibility concerns, etc.)

**Comment by dtolnay** [comment]
I would consider a PR if one were sent claiming no difference in compile time and performance and API, but it's not something that I would pursue. Also I am skeptical that Pin would be applicable.
