### ISSUE TITLE
Why are doc comments parsed as raw string?

### ISSUE THREAD

**Issue by magurotuna** [dtolnay/syn#771]
Hi. I have a question.

https://github.com/dtolnay/syn/blob/master/src/attr.rs#L119-L150
The above code tells me that doc comments like `/// foobar` are transformed into `#[doc = r"foobar"]`.

However, [The Rust Reference](https://doc.rust-lang.org/stable/reference/comments.html#doc-comments) says:

> /// Foo turns into #[doc="Foo"] and /** Bar */ turns into #[doc="Bar"].

Why does this crate parse doc comments as raw string, unlike the rust compiler?

**Comment by dtolnay** [comment]
The reference is wrong. ;)

**Comment by dtolnay** [comment]
Here is how to see rustc's parse:

```rust
macro_rules! m {
    (#[doc = $tt:tt]) => { stringify!($tt) };
}

fn main() {
    println!(m! {
        ///test
    });
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=072e5762ca130412b992b55d4e87ccb8

**Comment by magurotuna** [comment]
Thanks for the quick reply with a great example!
I've never thought the reference is wrong.  The playground output is exactly raw string.
My question have been completely solved, so I close it.
