### ISSUE TITLE
#752 (raw) changes behaviour of existing code

### ISSUE THREAD

**Issue by xd009642** [dtolnay/syn#773]
https://github.com/xd009642/tarpaulin/issues/354 Just wondering if syn's behaviour with this code snippet is correct:

```Rust
pub fn foo(raw: Foo) -> () {
    let _ = &raw;
}
```

I suppose the question is, with the raw references will you be unable to take a reference to a variable named raw? Or is the above code still valid?

**Comment by dtolnay** [comment]
Sorry about the bug! This is fixed in 1.0.16.

**Comment by xd009642** [comment]
No problem, thanks for the fast response :smile:
