### ISSUE TITLE
Missing `File` in Documentation without `full` Feature

### ISSUE THREAD

**Issue by nixpulvis** [dtolnay/syn#775]
The documentation talks about a `syn::File` parser for parsing a complete file:

> The syntax tree is rooted at syn::File which represents a full source file, ...

However this is a broken link without the `full` feature. I'm not sure how best to handle this, but thought I'd let you know since it caused me a moments confusion.

**Comment by dtolnay** [comment]
This crate is only meant to be documented with all features enabled, matching https://docs.rs/syn.

https://github.com/dtolnay/syn/blob/ee66f12d9154b984531eacfb084fd4fe8a87b466/Cargo.toml#L64-L67
