### ISSUE TITLE
Given `ItemFn`, determine if `Fn`, `FnOnce`, or `FnMut`

### ISSUE THREAD

**Issue by nikclayton-dfinity** [dtolnay/syn#781]
Given an `ItemFn`, is it possible to determine if it's an `Fn`, `FnOnce`, or `FnMut`? I don't think so, after reading the docs, but there may be something I missed.

**Comment by dtolnay** [comment]
Yes it's possible -- every ItemFn implements all three of those. Only closures don't implement all three but closures are not ItemFn.

**Comment by nikclayton-dfinity** [comment]
Is it possible to tell which one of those it is though?

I have a work-in-progress macro that only works for things that are `FnMut` or `Fn` -- if you try and apply it to something that is `FnOnce` then you get very confusing errors from the compiler. I'd like to make the errors less confusing by detecting that the user has tried to use the macro on an `FnOnce` and bailing out with a more useful error message.

**Comment by dtolnay** [comment]
Sorry I still don't understand what you are asking. Every ItemFn is all three of those.

Here's the code:

```rust
pub enum WhichIsIt {
    Fn,
    FnMut,
    FnOnce,
}

pub fn which_is_it(f: ItemFn) -> Vec<WhichIsIt> {
    let _ = f; // ignore
    return vec![WhichIsIt::Fn, WhichIsIt::FnMut, WhichIsIt::FnOnce];
}
```

**Comment by nikclayton-dfinity** [comment]
Probably some of my relative new-ness to Rust coming through.

How about -- is there a straightforward way to tell, if this `ItemFn` was actually a closure, would it be an `FnOnce`, `Fn`, or `FnMut`?

I suspect not -- if http://huonw.github.io/blog/2015/05/finding-closure-in-rust/ is still correct then this would entail duplicating the work the compiler does to inspect the function body to figure out how the parameters are used.

**Comment by dtolnay** [comment]
As a closure it would still be all three of them. The difference between the three fn traits is only how they act on internal state and an ItemFn can never store internal state. Only closures have state, not functions.

**Comment by dtolnay** [comment]
Demo:

```rust
fn assert_is_fn<T: Fn()>(_: T) {}
fn assert_is_fn_mut<T: FnMut()>(_: T) {}
fn assert_is_fn_once<T: FnOnce()>(_: T) {}

fn main() {
    fn f() {}
    assert_is_fn(f);
    assert_is_fn_mut(f);
    assert_is_fn_once(f);

    // as a closure
    assert_is_fn(|| f());
    assert_is_fn_mut(|| f());
    assert_is_fn_once(|| f());
}
```
