### ISSUE TITLE
syn parse_file triggers assert instead of returning parse error for bad unicode

### ISSUE THREAD

**Issue by xd009642** [dtolnay/syn#785]
https://github.com/xd009642/tarpaulin/issues/409 So I'd expect any invalid code to return a parse error not trigger a panic but this ui test in rust causes an assert to happen https://github.com/rust-lang/rust/blob/master/src/test/ui/parser/new-unicode-escapes-2.rs 

Just wondering if this is something you'd be willing to have syn handle without the assert? Or if there's an alternative to using parse_file or way to disable the asserts?

**Comment by dtolnay** [comment]
Good catch. I would accept a PR to fix this.

**Comment by dtolnay** [comment]
Fixed by https://github.com/alexcrichton/proc-macro2/pull/256.
