### ISSUE TITLE
Expose TokenStream/Cursor->ParseBuffer API

### ISSUE THREAD

**Issue by handicraftsman** [dtolnay/syn#786]
Here is my problem: i am in parse func of Parse trait.
I operate on ParseStream to parse incoming tokens. Then there's a group.
Say a `{}` delimited one.
So I am trying to recurse one of my parsing functions on it, so i could continue scanning
for my special structures. But i cannot - you can get a Cursor from a group.
You can get a TokenStream. That's it - you cannot just use the same parsing
code as with root ParseStream, as there is no ParseStream.
A workaround could be making a separate struct and implementing Parse for it, but its painful.
And that's the only choice because top-level struct contains extra, top-level data.

**Comment by handicraftsman** [comment]
To be more exact on what i am trying to do (since people keep asking in such cases often):

I am trying to write a macro which takes a template (just rust tokens with additional syntax on when you need to capture tokens) and implements Parse trait for a struct in a way that compares input ParseStream with template and tries to extract tokens/AST from input when it notices that additional syntax i mentioned above.

Its usage looks like that:

```rust
use nys::quote_template; // yes i just reversed syn

use crate::listener_definition::*;
use crate::broadcaster_definition::*;

pub struct ServiceDefinition {
  pub pub_token: Option<syn::Token![pub]>,
  pub service_name: syn::Ident,
  pub listeners: Vec<ListenerDefinition>,
  pub broadcasters: Vec<BroadcasterDefinition>
}

quote_template! {
  #<FOR: ServiceDefinition>
  #<pub_token?> service #<service_name> {
    #<SEQ: @listeners | @broadcasters>
  }
}
```

**Comment by dtolnay** [comment]
This is exposed by https://docs.rs/syn/1/syn/parse/trait.Parser.html#method.parse. There is an example in https://docs.rs/syn/1/syn/parse/index.html#the-parser-trait showing calling `Attribute::parse_outer` (which takes &amp;ParseBuffer) with an input `tokens` which is a TokenStream.
