### ISSUE TITLE
Hooks for existing Parse implementations to support custom syntax

### ISSUE THREAD

**Issue by stoically** [dtolnay/syn#793]
Thanks for the work on `syn`! Impressive crate.

My goal was to build a custom proc macro attribute that basically allows doing this:

```rust
#[html]
fn app() {
  let foo = <div></div>;
}
```

As far as I understand this would currently mean, that I'd have to basically re-implement how blocks are parsed, since trying to parse with the existing functionality will break because of syntax errors. So I was wondering if it might be possible to allow "hooking" existing parsers (maybe similar to the visitor, or in combination with the visitor?), that would probably allow to add just some special-casing instead of "re-implementing" the whole thing. I'd also be interested to work on this if it sounds feasible.

Maybe I missed something obvious and this is already possible, in which case I'd appreciate any pointers.

**Comment by dtolnay** [comment]
Hi @stoically, this is not currently supported but I would be interested in someone exploring this in a fork of this crate.

**Comment by stoically** [comment]
After looking into this a bit I realized that rust will only pass on token streams if the syntax is valid to begin with, regardless of macro definitions. Given this, my issue actually doesn't make much sense, so closing this one.
