### ISSUE TITLE
Consider implementing Ord for all types

### ISSUE THREAD

**Issue by matklad** [dtolnay/syn#794]
This is fun issue. In rust-analyzer, we observed a couple of crashes with experimental proc-macro support enabled. Investigation showed that the root cause here is a non-determenistic derive-more proc macro -- rust-analyzer's incremental computation framework assumes that everything is pure and just dies in flames if it is not the case.

The non-determinism in derive-more was due to the usage of `std::collection::HashMap`, which is not something `syn` can help with. However, a trivial fix of using `BTreeMap` instead of `HashMap` didn't work, because not everything is `Ord`, and so a more involved fix with a custom hasher was implemented: https://github.com/JelteF/derive_more/issues/124#issuecomment-624843857

I wonder if it makes sense for `syn` to provide `Ord` impls, so that obvious way to make stuff deterministic just works?

**Comment by Mark-Simulacrum** [comment]
This would probably be a big performance hit - nondeterministic proc macros because of HashMaps should use deterministic hashers.

(It's actually amazing that rust-analyzer is catching these cases).

**Comment by matklad** [comment]
>This would probably be a big performance hit

Not sure -- I think time to expand proc macros is usually not that important? I haven't measured this, but my gut feeling is that the impact of proc-macro itself is usually dwarfed by the time to compile the macro itself + the time to compile the code, generated by macro. So, I'd say "when writing proc macros, use `BTreeMap`" is a sound advice. It also has a minor benefit that the output is sorted naturally, and not pseudo random, which helps when you look at the output of proc macros. 

>It's actually amazing that rust-analyzer is catching these cases

Kudos to @edwin0cheng for connected the dots on this one. The original crash was quite bewildering and not obviously connected to non-determinism somewhere deep inside proc macro. To clarify, we already "fixed" the issue on rust-analyzer's side by making sure that we never GC expansions from proc-macros, though, long-term, I hope we'll have deterministic-by-construction proc macros in the future, via wasm.

**Comment by Mark-Simulacrum** [comment]
> Not sure -- I think time to expand proc macros is usually not that important?

Er, sorry, I meant a performance hit on compile times for syn to implement these traits. syn already has a feature `extra-traits` which has "Debug, Eq, PartialEq, Hash impls for all syntax tree types.". I guess adding Ord to that wouldn't necessarily be bad, but would likely increase compiletimes quite a bit I imagine.

**Comment by edwin0cheng** [comment]
Although it is not directly related to `syn` crate, But I would like to point out that, as mention by @bjorn3 in the original RA [issue][1], one of the problems of non-deterministic build in proc-macro is,  crates using it have non reproducible builds. And it is very hard to find out.

[1]: https://github.com/rust-analyzer/rust-analyzer/issues/4315#issuecomment-624607789

**Comment by dtolnay** [comment]
I think I would prefer not to do this, and instead recommend a deterministic hasher as the recommended approach.
