### ISSUE TITLE
Improve documentation of item availability depending on feature flags.

### ISSUE THREAD

**Issue by teymour-aldridge** [dtolnay/syn#796]
I've been writing a procedural macro recently (and thinking about how much harder it would be without `syn` – this crate is awesome!). Most of the documentation contains comments about the availability of features which look a little like this:
<img width="557" alt="Screenshot 2020-05-15 at 18 43 55" src="https://user-images.githubusercontent.com/42674621/82080062-d09a5180-96db-11ea-8676-6c19a005b141.png">

`"This type is available if Syn is built with the "derive" or "full" feature."`

I find that these would be clearer if they said something like `This type is available only if Syn is built with the "derive" or "full" feature.` or `This type is available iff Syn is built with the "derive" or "full" feature.` 

I'd be happy to do this (with find and replace or changing doc comments about availability of features to be generated through a macro).

**Comment by dtolnay** [comment]
I would accept a PR to insert 'only'.

In the medium term this will be replaced by #731.
