### ISSUE TITLE
Can I get the attributes of the called function?

### ISSUE THREAD

**Issue by liangyongrui** [dtolnay/syn#802]
```rust
#[foo_attr]
fn foo() {
    bar()
    //...
}
#[bar_attr]
fn bar() {
    //...
}
```

Can I get the attribute `bar_attr` of `bar()` through `foo_attr`?

**Comment by dtolnay** [comment]
This is not supported because it would require name resolution to know what `bar` refers to. Name resolution only happens after macro expansion in Rust.

**Comment by liangyongrui** [comment]
Do I have another way to know whether a called function is marked with an attribute?

**Comment by dtolnay** [comment]
No I don't know of a way to know that. It's possible you may need to go with a different design for your macro.
