### ISSUE TITLE
`full` feature breaks `parse_macro_input!` with custom Parse objects

### ISSUE THREAD

**Issue by KireinaHoro** [dtolnay/syn#817]
When custom `impl Parse` objects are defined, the `full` feature can break `parse_macro_input!` to fail with cryptic error messages.  An MWE is at https://github.com/KireinaHoro/syn-bug (the full, and quite complicated, use case can be found [here](https://github.com/KireinaHoro/khemu/blob/master/macros/src/lib.rs) and [here](https://github.com/KireinaHoro/khemu/blob/master/src/ir/op.rs)).  The macro call site looks like the following (can be found here https://github.com/KireinaHoro/syn-bug/blob/master/src/main.rs):

```rust
macros::gen_ops! {
    ValueType::Label {  // control flow related special
        custom: Setlbl, label;  // set label to current location in IR
    },
    ValueType::U64 {  // q - 64bit word
        unary: Neg, Not, Mov, Bswap;
    },
    ValueType::U32 {  // w - 32bit word
        unary: Negw, Movw;
    },
    ValueType::F64 {  // d - double float
        unary: Movd;
    }
}
```

The master commit fails with a cryptic error message:

```text
    Checking syn-bug v0.1.0 (/home/jsteward/work/syn-bug)
error: expected curly braces
 --> src/main.rs:7:6
  |
7 |     },
  |      ^

error: aborting due to previous error

error: could not compile `syn-bug`.

To learn more, run the command again with --verbose.
```

Meanwhile, removing the `"full"` feature will make the macro successfully expand.  I'm not familiar with how to trace `parse_macro_input` though; I would love to provide any more information if needed.

**Comment by dtolnay** [comment]
I moved the error in 1.0.24.

```console
error: expected `,`
 --> src/main.rs:6:30
  |
6 |         custom: Setlbl, label;  // set label to current location in IR
  |                              ^
```

`ValueType::Label { custom: Setlbl, label }` is syntactically an expression so that is what is being parsed by https://github.com/KireinaHoro/syn-bug/blob/dcefaa793403ba4fbfb59ac7eac742bbdb73610d/macros/src/lib.rs#L21, and after it, "expected curly braces" is from https://github.com/KireinaHoro/syn-bug/blob/dcefaa793403ba4fbfb59ac7eac742bbdb73610d/macros/src/lib.rs#L22.

If you want reg_type to only parse `ValueType::Label` and not whatever is after it that may be part of an expression, you would need to use e.g. `reg_type: input.call(Path::parse_mod_style)?` instead of Expr.

**Comment by KireinaHoro** [comment]
I see.  So the behavior difference is introduced by the extended Expr parsing rules found in "full"?

**Comment by dtolnay** [comment]
Yeah; in general it's incorrect for a macro to rely on something not to parse. They should parse only what they mean. For example this proc macro would also be "broken" by enabling full syntax for expr, but that just means the macro is bad.

```rust
#[proc_macro]
pub fn m(_input: TokenStream) -> TokenStream {
    if syn::parse_str::<syn::Expr>("..").is_ok() {
        panic!("??");
    }
    TokenStream::new()
}
```

**Comment by KireinaHoro** [comment]
Got the point, thanks!
