### ISSUE TITLE
Consider adding type for partial parsing

### ISSUE THREAD

**Issue by Koxiaet** [dtolnay/syn#835]
Sometimes I need to parse one item, and then keep the rest of the tokens for later. I would like a struct in `syn::parse`:

```rust
pub struct ParseStart<T: Parse> {
    pub item: T,
    pub rest: TokenStream,
}
```

I'm not certain about the name, it could also be called `PartialParse` or `ParseOne`, and there is also the question of whether to have a separate `ParseStart` and `ParseStart2` for `proc_macro::TokenStream` and `proc_macro2::TokenStream` respectively. We could even blanket impl `Parse` for `(T, U)` for maximum flexibility and minimum API surface.

Previous discussion has happened [here](https://github.com/dtolnay/syn/issues/492#issuecomment-420202090) and [here](https://github.com/dtolnay/syn/issues/81) but this is a slightly different approach.

If you think this is a good idea and can answer my above questions I'm happy to go ahead and make a PR.

**Comment by dtolnay** [comment]
I think I would prefer not to build this into Syn. But if there is an abstraction along these lines that is reasonably widely used in downstream crates, I would be interested to know (with links).

**Comment by tqwewe** [comment]
Is this still not possible currently? It would be very useful in my case, and I'm not sure what the alternatives approaches are
