### ISSUE TITLE
Question: Parsing types from other libraries

### ISSUE THREAD

**Issue by SirWindfield** [dtolnay/syn#841]
Given the following example:
```rust
use other_crate::Foo;

#[derive(CustomName)]
struct Bar {
    #[name(...)]
    inner: Foo
}
```

Is it somehow possible to access all available methods of `Foo`? The goal is to create a macro that can delegate methods from other structs. For this I need to know how the method signatures look inside of `Foo`.

I guess I am basically asking for a way to tell `syn` to parse some specific struct.

**Comment by dtolnay** [comment]
All you get is the tokens of the macro input. Name resolution in Rust happens entirely after macro expansion so Foo doesn't refer to anything in particular until later, and macro expansion can even change what it refers to.
