### ISSUE TITLE
`to_compile_error` don't work in generating new fields of struct using `quote!`

### ISSUE THREAD

**Issue by kingrongH** [dtolnay/syn#845]
## What
When I am trying to implement `#[derive(Builder)]` in [proc-macro-workshop](https://github.com/dtolnay/proc-macro-workshop), I want to check if `#[builder(each='arg')]` is properly attributed on a field with type `Vec<T>` and with collect name `each`, and output a correct builder type `Vec<T>` instead of `Option<Vec<T>>` or a compile error. But then I `cargo expand`, I didn't get the error I want, but got 
![image](https://user-images.githubusercontent.com/42315902/83660419-664c4100-a5f7-11ea-8c06-19f24b42abf7.png)

## Minimal Example

I create a minimal example: 

lib.rs
```rust
/// lIb.rs

use syn::{ DeriveInput, parse_macro_input };
use quote::{ quote, format_ident };
use proc_macro::TokenStream;

#[proc_macro_derive(ErrorTest)]
pub fn derive(input: TokenStream) -> TokenStream {
    let _ = input;

    let input = parse_macro_input!( input as DeriveInput );
    let out = expand(&input); 
    println!("{:#?}", out.to_string());
    out.into()
}


fn expand(input: &DeriveInput) -> proc_macro2::TokenStream {
    let ident = &input.ident;
    if let syn::Data::Struct(syn::DataStruct { ref fields, .. }) = input.data {
        let new_ident = format_ident!("New{}", ident);
        
        let new_struct_fileds = fields.iter().map(|f| {
            let err = syn::Error::new_spanned(f, "error message in creating new field");
            err.to_compile_error()
        });
        
        return quote!{
            struct #new_ident {
                #(#new_struct_fileds),*
            }
        }
    }
    
    unimplemented!()
}
```
main.rs
```rust
///main.rs

use rust_test::ErrorTest;

#[derive(ErrorTest)]
struct Test {
    field1: String,
    field2: Vec<String>
}

fn main() {}
```

In this example I epect the output of compile with error message `error message in creating new field`, but I got output:

![image](https://user-images.githubusercontent.com/42315902/83661261-6ef14700-a5f8-11ea-9a77-15e122d29ef5.png)

## Version

rustc 1.43.1 (8d69840ab 2020-05-04)

**Comment by dtolnay** [comment]
This is intended; compile_error is a macro so it needs to be placed somewhere that a macro invocation is allowed. Usually that means if there is a compile_error anywhere then your macro should emit nothing other than that compile_error.

**Comment by kingrongH** [comment]
This explanation works for me, thanks for your efforts
