### ISSUE TITLE
Strange importing issue with ItemFn, Item and other enums

### ISSUE THREAD

**Issue by VoR0220** [dtolnay/syn#846]
I'm trying to create my first proc macro using syn and I decided to use the following example as a sort of template:

https://github.com/dtolnay/syn/blob/master/examples/trace-var/trace-var/src/lib.rs#L9

however when I try to import an ItemFn struct definition I'm running into errors saying it can't find it even though the documentation suggests that it should be there. Why is this weird thing happening? 

dependencies in cargo.toml

```
[lib]
proc-macro = true

[dependencies]
syn = "1.0.30"
```

and the proc macro itself:

```
extern crate proc_macro;
use self::proc_macro::TokenStream;
use syn::{parse_macro_input, ItemFn};
//use neutron_star::syscalls::*;

#[proc_macro_attribute]
pub fn neutronify(_attr: proc_macro::TokenStream, item: proc_macro::TokenStream) -> proc_macro::TokenStream {
    //println!("attr: \"{}\"", _attr.to_string());
    println!("item: \"{}\"", item.to_string());
    let func = parse_macro_input!(item as ItemFn);
	let input_funcs = func.sig.inputs
			.into_iter()
			.map(|item| println!("{}", item.to_string()))
			.collect();
	
    input_funcs
}
```

yields me 

```
use syn::{parse_macro_input, Item};
  |                              ^^^^ no `Item` in the root
```

any suggestions for what I might be doing wrong?

**Comment by dtolnay** [comment]
The documentation suggests it should be there if "full" is enabled.

<p align="center"><img alt="screenshot" src="https://user-images.githubusercontent.com/1940490/83694109-3592ea00-a5ac-11ea-8bcd-3b134be7f237.png" width="70%"></p>

See also https://github.com/dtolnay/syn#optional-features.

**Comment by VoR0220** [comment]
I was looking around for that but I now realize that the full feature has to be defined in the Cargo.toml manifest. Sorry for the noobish comment.
