### ISSUE TITLE
Parse an optional closure expr

### ISSUE THREAD

**Issue by XAMPPRocky** [dtolnay/syn#847]
Hey I was trying to use `syn` to create a procedural function macro that accepts two str literals and a closure as the final argument, however I was surprised that `ExprClosure` and in fact all the `Expr*` types do not implement `syn::Parse` so as far as I can tell you can't actually use them at all for parsing. Would it be possible to add a `Parse` implementation for the expression types, or would you be able to explain how you're supposed to parse expressions like closures with syn?

Example of what I expected to work.
```rust
// Would map to a function like `fn #name(locales_directory: &str, fallback_language: &str, customise: Fn(Args) -> ());`
struct StaticLoader {
    name: Ident,
    first_comma: token::Comma,
    locales_directory: syn::LitStr,
    second_comma: token::Comma,
    fallback_language: syn::LitStr,
    third_comma: Option<token::Comma>,
    customise: Option<syn::ExprClosure>,
}

impl Parse for StaticLoader {
    fn parse(input: ParseStream) -> Result<Self> {
        Ok(Self {
            name: input.parse()?,
            first_comma: input.parse()?,
            locales_directory: input.parse()?,
            second_comma: input.parse()?,
            fallback_language: input.parse()?,
            third_comma: input.parse()?,
            customise: input.parse()?,
        })
    }
}
```

Error Message
```
error[E0277]: the trait bound `syn::expr::ExprClosure: syn::token::CustomToken` is not satisfied
  --> macros/src/lib.rs:36:30
   |
36 |             customise: input.parse()?,
   |                              ^^^^^ the trait `syn::token::CustomToken` is not implemented for `syn::expr::ExprClosure`
   |
   = note: required because of the requirements on the impl of `syn::token::Token` for `syn::expr::ExprClosure`
   = note: required because of the requirements on the impl of `syn::parse::Parse` for `std::option::Option<syn::expr::ExprClosure>`
```

**Comment by dtolnay** [comment]
Those types implement Parse according to https://docs.rs/syn/1.0.30/syn/enum.Expr.html and https://docs.rs/syn/1.0.30/syn/struct.ExprClosure.html.

Option implements Parse for single tokens where the lookahead rule is implicitly whether the next token in the parse stream is that specific token. Anything else consisting of multiple tokens would have a more complicated lookahead rule specific to the use case, which the macro needs to implement according to what they want.

**Comment by XAMPPRocky** [comment]
Yeah thank you for the explanation. it was not initially obvious to me that what I needed was `input.parse().ok()`. Right now though this parse struct is pretty brittle overall. Do you know of a better way to have a struct field syntax with some required and some optional arguments? As an example of what writing the macro would look like.
```rust
fluent_templates::static_loader! {
    static LOCALES = {
        locales: "./templates/tests/locales",
        // Optional
        fallback_language: "en-US",
        // Optional
        core_locales: "./templates/tests/locales/core.ftl",
        // Optional
        customise: |bundle| bundle.set_use_isolating(false),
    };
}
```

**Comment by dtolnay** [comment]
`input.parse().ok()` would pretty much never be appropriate in a macro. That says to parse as far as possible and then silently ignore an error but accept whatever tokens in the input have been parsed up to that point. The caller could write any broken input that this would pretend to parse successfully. As a rule, never ignore an error in a macro parser.

**Comment by dtolnay** [comment]
Based on https://github.com/dtolnay/syn/issues/847#issuecomment-640094062 it sounds like you always want a closure after `customize`? If so then the closure would never be optional when you parse it, but you wouldn't parse it except after seeing `customize`.

```rust
let mut customize = None;
while !input.is_empty() {
    let k = input.parse::<Ident>()?;
    input.parse::<Token![:]>()?;
    if k == "customize" {
        customize = Some(input.parse()?);
    } else if ... {
    } else {
        return Err(...);
    }
    if input.is_empty() {
        break;
    }
    input.parse::<Token![,]>()?;
}
```

**Comment by XAMPPRocky** [comment]
Thannk you that worked perfectly and helped me refactor the code to be a lot cleaner!
