### ISSUE TITLE
Allow Path in NameValue for AttributeArgs

### ISSUE THREAD

**Issue by Robbepop** [dtolnay/syn#851]
I am not sure if this feature request makes sense to implement for `syn`:
Currently when using `AttributeArgs` in order to parse the argument list to a proc. attribute macro you cannot do something like this:
```rust
#[my_attribute_macro(
    my_config: some::config::Path,
)]
```
The above is not possible to implement using the `syn` provided `AttributeArgs` because the `value` part of the `NameValue` (the `my_config: some::config::Path,`) is required to be a literal. I don't think that allowing paths would cause some troubles.

Or is there a problem since paths in this location are not allows by the non-existing Rust spec? And if so where can I find more about this information?

I am aware that I could also write my own `Parse` for my own AST definitions to allow for this syntax. But this is way more work than destructuring an already parsed `AttributeArgs` instance.
Also I am aware that I could work around this issue by using a `Meta::List` since it allows for paths and identifiers in its body. However, this would not really fit into my config arguments syntax style and scheme where everything is a `name = value`.

My current work around that I actually use is to fallback to use a string literal instead of a proper path and then simply parse the string literal using the `syn::parse_str::<syn::Path>` function. While this is definitely not too bad not having to wrap everything in a string would be a significant improvement.

Would you accept a PR that implements this feature?

**Comment by dtolnay** [comment]
This is by design; see https://github.com/dtolnay/syn/issues/687#issuecomment-517933347 - https://github.com/dtolnay/syn/issues/687#issuecomment-517943389 for a bit of rationale. You should write a `Parse` impl.
