### ISSUE TITLE
ItemFn parse regression from 1.0.27 

### ISSUE THREAD

**Issue by la10736** [dtolnay/syn#852]
I noted a regression introduced with 1.0.27 release on parsing ItemFn with attributes. Of course, this occurs  just in some rare cases but I found a simple example. I've a funktion-like procedural macro that merge the function attributes `merge_attr`. 

If I call it by:

```rust
merge_attrs! {
    #[test]
    fn template() {},
    #[should_panic]
    fn merge_ok() {assert!(false)}
}
```
works ok. 

But if I wrap it by macro like follow:

```rust
macro_rules! merge_some {
            ( $test:item ) => {
                        merge_attrs! {
                            #[test]
                            fn template() {},
                            $test
                        }
                    }
        }

merge_some! {
    #[should_panic]
    fn merge_fail() {assert!(false)}
}
```
`merge_attrs` fail on parse the second functions and tell that expect a `fn`... but works if I remove the attributes from this function.

This behavior is raised up from 1.0.27 version. (I see two commit that looks like very close to this issue).

Anyway if dump the token streams in both cases I can see that in the macro one case we have a
```
Group {
        delimiter: None,
        stream: TokenStream [
....
```
that wrap the function. 

In 1.0.27 a new check ` !input.peek(token::Group)` was introduced but I guess that we should consider the _void_ `Group` as valid.

`merge_attr` code:

```rust
struct MergeAttrs {
    template: ItemFn,
    function: ItemFn,
}

impl Parse for MergeAttrs {
    fn parse(input: parse::ParseStream) -> syn::Result<Self> {
        let template = input.parse()?;
        let _comma: Token![,] = input.parse()?;
        let function = input.parse()?;
        Ok(Self { template, function })
    }
}

#[proc_macro]
pub fn merge_attrs(item: TokenStream) -> TokenStream {
    let mut merge = parse_macro_input!(item as MergeAttrs);
    let mut attrs = merge.template.attrs.clone();
    attrs.append(&mut merge.function.attrs);
    merge.function.attrs = attrs;

    let f = merge.function;

    let tokens = quote! {
        #f
    };
    tokens.into()
}
```

**Comment by dtolnay** [comment]
Sorry about the breakage! Fixed in syn 1.0.32.
