### ISSUE TITLE
Make pat::parsing::multi_pat_with_leading_vert public in some form

### ISSUE THREAD

**Issue by udoprog** [dtolnay/syn#857]
This is used in the [`Parse` impl for `Arm`](https://github.com/dtolnay/syn/blob/80c6889684da7e0a30ef5d0b03e9d73fa6160541/src/expr.rs#L2586), and would be useful when building custom parsing inside and around match statements.

CC: udoprog/genco#12

**Comment by dtolnay** [comment]
This is now available as [`Pat::parse_multi_with_leading_vert`](https://docs.rs/syn/2/syn/enum.Pat.html#method.parse_multi_with_leading_vert).
