### ISSUE TITLE
What the reasons to have `ParseMacroInput` trait

### ISSUE THREAD

**Issue by katyo** [dtolnay/syn#875]
If I understand right this trait only helps parsing `AttributeArgs` which is an alias for `Vec<NestedMeta>`.
https://github.com/dtolnay/syn/blob/8b460ba0294625a5b9069ad361cdac5d30689a7d/src/parse_macro_input.rs#L99-L101

What about re-defining `AttributeArgs` in a newtype style to implement `Parse` trait for it. I mean something like so:
```rust
pub struct AttributeArgs(Vec<NestedMeta>);

impl Deref for AttributeArgs {
    type Target = Vec<NestedMeta>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl DerefMut for AttributeArgs {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

impl Parse for AttributeArgs {
    fn parse(input: ParseStream) -> Result<Self> {
        let mut metas = Vec::new();

        loop {
            if input.is_empty() {
                break;
            }
            let value = input.parse()?;
            metas.push(value);
            if input.is_empty() {
                break;
            }
            input.parse::<Token![,]>()?;
        }

        Ok(Self(metas))
    }
}
```
Thanks to dereferencing this type can be used as so as aliased one.
Of course, also we can select another name for this type for full back compatibility.

Similar [solution](https://github.com/katyo/android-ndk-rs/blob/d273e0b7aee4e81471c3daebbe9774989495309a/ndk-macro/src/helper.rs#L11-L39) helps me test parsing attribute args using `parse_quote` macro.

**Comment by dtolnay** [comment]
That would work, but I think I would prefer to keep this as currently implemented, without a newtype wrapper.
