### ISSUE TITLE
Using a reference to a closure lose the span info

### ISSUE THREAD

**Issue by antoyo** [dtolnay/syn#878]
Hi.
I made a reproducer for this bug [here](https://github.com/antoyo/proc-macro-bug).

It seems the issue is caused when having a reference to a closure `&|| {}` in the code.

It makes the error looks like:
```
 --> src/main.rs:8:1
  |
8 | #[hello_macro_derive]
  | ^^^^^^^^^^^^^^^^^^^^^
  | |
  | expected `i32`, found struct `std::string::String`
  | expected due to this
```

If you use instead a reference to a variable which contains the closure (i.e. the commented code), it works well:
```
  --> src/main.rs:11:25
   |
11 |         let test: i32 = String::new();
   |                   ---   ^^^^^^^^^^^^^ expected `i32`, found struct `std::string::String`
   |                   |
   |                   expected due to this
```
Thanks to fix this issue.

**Comment by mystor** [comment]
This appears to be an instance of the compiler bug https://github.com/rust-lang/rust/issues/43081, rather than being a bug in `syn`.

**Comment by dtolnay** [comment]
Yeah this is rust-lang/rust#43081. If you insert `println!("{:#?}", input)` as the first line of hello_macro_derive you'll see that the spans all come in as `#0 bytes(0..0)` so it isn't syn losing them.
