### ISSUE TITLE
Span for FnArg::Receiver in proc_macro seems to point to first token not whole receiver

### ISSUE THREAD

**Issue by illicitonion** [dtolnay/syn#888]
See [this repo](https://github.com/illicitonion/repro-syn-receiver-span) for a repro.

I tried to point an error message at a function receiver. Parsing the code as a string, this seems to work fine. Parsing it from a `TokenStream`, in a `proc_macro`, the `Span` for the `FnArg::Receiver` appears to point to the first token of the receiver, rather than the whole thing:
```
error: Saw receiver with span #0 bytes(63..64)
 --> example/src/lib.rs:7:19
  |
7 |     fn by_mut_ref(&mut self) -> bool {
  |                   ^

error: Saw receiver with span #0 bytes(126..130)
  --> example/src/lib.rs:12:12
   |
12 |     fn own(self) -> bool {
   |            ^^^^

error: Saw receiver with span #0 bytes(188..191)
  --> example/src/lib.rs:17:16
   |
17 |     fn own_mut(mut self) -> bool {
   |                ^^^

error: Saw receiver with span #0 bytes(253..254)
  --> example/src/lib.rs:22:15
   |
22 |     fn by_ref(&self) -> bool {
   |               ^
```

If I parse the same code from a `str`, I get the spans I expect (or at least, :
```
bytes(21..30)
bytes(86..90)
```

**Comment by dtolnay** [comment]
Hi @illicitonion, this matches the documented behavior -- please see https://docs.rs/syn/1.0.38/syn/spanned/index.html#limitations.
