### ISSUE TITLE
parsing panics with "Unrecognized literal"

### ISSUE THREAD

**Issue by sameer** [dtolnay/syn#893]
Hello,

I'm doing some fuzzing with [AFL](https://github.com/rust-fuzz/afl.rs) and ran into the following input that causes syn to panic during parsing:

```
fn a() {
  9E9999E999  mod aimp;
}
```

Resulting in:

```
thread 'main' panicked at 'Unrecognized literal: `9E9999E999`', /home/purisame/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.39/src/lit.rs:960:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Let me know if there is any other information I can provide, or if it would be helpful if I PR'd a fix for it!

**Comment by dtolnay** [comment]
Thanks, fixed in 1.0.40.
