### ISSUE TITLE
panic at Unrecognized literal 

### ISSUE THREAD

**Issue by alexanderkjall** [dtolnay/syn#897]
Hi, I'm going over all the dependencies in my dependency-tree with a fuzzer, and found this panic in syn:

thread 'main' panicked at 'Unrecognized literal: `6E--5458`', /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.41/src/lit.rs:955:13

It can be reproduced with this program:

```
use syn::Expr;

fn main() {
    let s = "6E--5458";
    let _ = syn::parse_str::<Expr>(s);
}
```

I would have expected it to return an Error instead.

**Comment by dtolnay** [comment]
Thank you! I've published syn 1.0.42 with a fix. This issue involved some bugs in proc-macro2 as well so you'll need to update both.
