### ISSUE TITLE
Compilation errors on FreeBSD between syn and proc-macro2

### ISSUE THREAD

**Issue by phyber** [dtolnay/syn#902]
Hi,

I was attempting to update the crates in one of my [projects](https://github.com/scalefactory/hcdl) today and started hitting a compilation failure on FreeBSD when using `syn` 1.0.42 with `proc-macro2` 1.0.24. To get around this, I have currently locked `proc-macro2` at version 1.0.23 in my crate.

The issue manifests when both `syn` and `proc-macro2` are at their latest versions (1.0.42 and 1.0.24 respectively). If either crate is a version lower than this (1.0.41 or 1.0.23), the issue disappears.

## Working

`cargo test` with `syn` 1.0.42 and `proc-macro2` 1.0.23

```
$ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.33s
     Running target/debug/deps/hcdl-566131c36a0410d6

# Omitted test lines

test result: ok. 25 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

`cargo test` with `syn` 1.0.41 and `proc-macro2` 1.0.24

```
$cargo test
    Finished test [unoptimized + debuginfo] target(s) in 2m 15s
     Running target/debug/deps/hcdl-56345b830ae38a33

# Omitted

test result: ok. 25 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

## Broken

with `syn` 1.0.42 and `proc-macro2` 1.0.24

Large error output at: https://gist.github.com/phyber/1266967e28987258b263ebb0926c1464

OS and `rustc` versions:

```
$ freebsd-version && rustc --version
12.1-RELEASE-p10
rustc 1.46.0 (04488afe3 2020-08-24)
```

I apologise if this isn't the correct repo to be posting this issue against, the errors have a lot of information and `syn` was mentioned the most.

  - `tokio-macros` is the crate that cannot be compiled
  - `cc` is throwing the error
  - `syn` is mentioned a lot in the given errors

The issue does not manifest on a Linux system. I have not been able to test on macOS.

Individually, the test suites of `tokio-macros`, `syn`, and `proc-macro2` all pass. There is only a single version of each of these crates displayed in `cargo tree` for my crate.

Thanks, and apologies again if I've got the wrong repo here.

**Comment by dtolnay** [comment]
This appears like an LLVM bug or rustc bug -- I doubt that there is any possible change in syn or proc-macro2 that would reliably avoid it. Someone who can reproduce the failure will need to put together a minimal repro and report it in rust-lang/rust probably to start with. :confused:

**Comment by phyber** [comment]
No problem, I can attempt to work out a minimal test case and report it there. Thanks for pointing me in the right direction.  👍
