### ISSUE TITLE
Feature request: determining early/late bound lifetime parameters

### ISSUE THREAD

**Issue by antonok-edm** [dtolnay/syn#905]
I'm the author of the `enum_dispatch` procedural macro. Recently I added better support for generic parameters, but in some cases specifying them explicitly produces warnings like the following:

```
warning: cannot specify lifetime arguments explicitly if late bound lifetime parameters are present
  --> examples/late_dispatch.rs:11:1
   |
6  |     fn foo<'a>(&mut self) -> &'a u32 {
   |                - the late bound lifetime parameter is introduced here
...
11 | #[enum_dispatch(FooAPI)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(late_bound_lifetime_arguments)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #42868 <https://github.com/rust-lang/rust/issues/42868>
   = note: this warning originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

The warning appears due to an explicitly specified lifetime parameter in the generated code:

```diff
--- 0.3.2.rs
+++ 0.3.3.rs
@@ -31,7 +31,7 @@
     #[inline]
     fn foo<'a>(&mut self) -> &'a u32 {
         match self {
-            Foo::Something(inner) => FooAPI::foo(inner),
+            Foo::Something(inner) => FooAPI::foo::<'a>(inner),
         }
     }
```

The explicit specification is useful in general, but begins causing issues when late-bound lifetime parameters are present in a method's signature (as they are here).

According to [the linked issue](https://github.com/rust-lang/rust/issues/42868), the recommendation is "Just removing the lifetime arguments pointed to by the lint". That's not an option in a procedural macro, which doesn't get to look at compiler warnings. That means I need some way to check if there are any late-bound lifetime parameters in a function signature when I'm generating its implementation.

What I'm proposing is something along the lines of `syn::Signature::has_late_bound_lifetimes(&self) -> bool`. The rules for determining early/late bound lifetimes are fairly complex, which is why I figure it would be nice to have a single canonical implementation in `syn` that is available to any procedural macro author.

More context: https://gitlab.com/antonok/enum_dispatch/-/issues/34

**Comment by dtolnay** [comment]
I think I would prefer not to build this into this crate.
