### ISSUE TITLE
Meta does not parse paths with leading double-colon

### ISSUE THREAD

**Issue by dbeckwith** [dtolnay/syn#909]
[Minimal reproduction](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1508a2e72c3c32bdab119f0957815bb1):

```rust
use syn;

fn main() {
    // correctly parses
    let attr: syn::Attribute = syn::parse_quote!(#[derive(serde::Serialize)]);
    let _ = dbg!(attr.parse_meta());
    
    // error, expected identifier or literal
    let attr: syn::Attribute = syn::parse_quote!(#[derive(::serde::Serialize)]);
    let _ = dbg!(attr.parse_meta());
}
```

I would expect the second example to parse since it's a valid path. I think the [meta parsing code](https://github.com/dtolnay/syn/blob/master/src/attr.rs#L581) does a lookahead expecting only a literal or an identifier, but paths can start with the non-identifier `::`.

I read the [previous discussion](https://github.com/dtolnay/syn/issues/687#issuecomment-517929902) about not wanting `Meta` to have to cover all possible attribute syntaxes, but I think this fits solidly within the current expectations of what `Meta` should parse. Given that it stores `Path`s, it should be able to parse any kind of `Path`.

**Comment by dtolnay** [comment]
Fixed in 1.0.46.
