### ISSUE TITLE
Can't compare two `syn::Type`s for equality.

### ISSUE THREAD

**Issue by trbednarzyk** [dtolnay/syn#911]
As the title says, the following code is not valid (with the `"full"` feature enabled, of course):
```rust
use proc_macro::TokenStream;
use syn::{parse_quote, Type};

#[proc_macro]
pub fn eq_test(input: TokenStream) -> TokenStream {
  let type_a: Type = parse_quote! { i32 };
  let type_b: Type = parse_quote! { u8 };

  let is_eq = type_a == type_b;

  input
}

```
The compiler will complain with the following message:
```
error[E0369]: binary operation `==` cannot be applied to type `syn::Type`
  --> src/lib.rs:9:22
  |
9 |   let is_eq = type_a == type_b;
  |               ------ ^^ ------ syn::Type
  |               |
  |               syn::Type
```
Despite this, the documentation for `syn` claims that `syn::Type` implements the `Eq` trait, as can be seen [here](https://docs.rs/syn/1.0.46/syn/enum.Type.html#impl-Eq).

Not being able to do this makes validation that something is using the proper type much harder and more verbose.

While I've highlighted the issue for `syn::Type`, the same issue applies to similar types, such as `syn::ReturnType`, which also [claims](https://docs.rs/syn/1.0.46/syn/enum.ReturnType.html#impl-Eq) to implement `Eq`.

**Comment by dtolnay** [comment]
Please see https://github.com/dtolnay/syn#optional-features -- you'd need "extra-traits" also enabled to get Eq impls since they add significant compile time.

**Comment by trbednarzyk** [comment]
Whoops, sorry that I missed that.
