### ISSUE TITLE
Failed to parse unit type as Path

### ISSUE THREAD

**Issue by Evian-Zhang** [dtolnay/syn#913]
# Background

In my proc macro, user need to pass a string representing a type:

```rust
#[my_proc_macro(my_key = "path::to::MyType")
pub foo: usize
```

I use

```rust
syn::parse_str::<syn::Path>(&my_key_value_str)
```

to get the corresponding type. It works well for most situations (`path::to::MyType` or simply `MyType`).

# Problem

If I pass unit type `()` to the proc macro as:

```rust
#[my_proc_macro(my_key = "()")
pub foo: usize
```

It turns out a `expected identifier` error.

It can be easily checked by the following code:

```rust
use syn;

fn main() {
    println!("{:?}", syn::parse_str::<syn::Path>("()"));
}
```

Its output is

```rust
Err(Error("expected identifier"))
```

What can I do if I want to accept `()` as well?

**Comment by botika** [comment]
A path at which a named item is exported. `()` is not a `syn::Path` https://docs.rs/syn/1.0.48/syn/struct.Path.html

**Comment by Evian-Zhang** [comment]
> A path at which a named item is exported. `()` is not a `syn::Path` https://docs.rs/syn/1.0.48/syn/struct.Path.html

@botika But other types, such as `usize` (primitive type), `String` (prelude imports), or simply `MyStruct` (user defined type), can be parsed as `Path` successfully. Since `usize` can be parsed successfully, I can't understand why `()` can't be parsed successfully.

**Comment by botika** [comment]
Yes because this cases are the same that `PathSegment`. Use this https://docs.rs/syn/1.0.48/syn/enum.Type.html for parse types.

**Comment by Evian-Zhang** [comment]
> Yes because this cases are the same that `PathSegment`. Use this https://docs.rs/syn/1.0.48/syn/enum.Type.html for parse types.

Thanks, this solves my problem.
