### ISSUE TITLE
Failed to run custom build command on Apple Silicon

### ISSUE THREAD

**Issue by Patcher56** [dtolnay/syn#935]
I wanted to try out `actix-web` with the new Apple Silicon MacBook and ran into some errors.

One of them was an error when compiling the `syn` crate:
```
patrickkuen@mbp-von-patrick clime-server % cargo build
    Updating crates.io index
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.52
error: failed to run custom build command for `syn v1.0.52`

Caused by:
  process didn't exit successfully: `/Users/patrickkuen/Developer/cloudacy/clime/clime-server/target/debug/build/syn-68e8dc1d3fac40d1/build-script-build` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

rustup-toolchain:
```
beta-aarch64-apple-darwin (default)
rustc 1.49.0-beta.2 (bd26e4e54 2020-11-24)
```

### Steps to reproduce
1. Create a new project using `cargo new`
1. Add the `syn = "1.0"` package under `Cargo.toml`
1. Run `cargo build`

**Comment by dtolnay** [comment]
Thanks -- I'm sure I won't be able to reproduce this, but I would accept a PR to fix it.

**Comment by Patcher56** [comment]
Thanks for your fast answer. I would be glad to help - I am not a rust pro, so where can I find clearer error messages to start with?

**Comment by Patcher56** [comment]
After some tests with different packages it seems that every package using a custom `build.rs` crashes with this error. Therefore I created a new issue on the cargo package (rust-lang/cargo#8913).
