### ISSUE TITLE
Removal of previously public API breaks downstream crate

### ISSUE THREAD

**Issue by cpcloud** [dtolnay/syn#953]
It looks like https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7 breaks `enumset_derive` as unfortunately that crate has a reference to `syn::export`.

**Comment by cpcloud** [comment]
xref: https://github.com/Lymia/enumset/issues/17

**Comment by dtolnay** [comment]
syn::export has never been a public API. It's hidden and commented "not public API".

https://github.com/dtolnay/syn/blob/d58d7cbe55a3160045db000802ca4c097bf774a1/src/lib.rs#L789-L791
