### ISSUE TITLE
Hidden public modules are still part of your public API :(

### ISSUE THREAD

**Issue by phaazon** [dtolnay/syn#954]
Hi,

I just want to come provide a bit of feedback of something that just happened to me lately. [I merged a PR containing a usage of your `syn::export` API](https://github.com/phaazon/cargo-sync-readme/pull/35/files#diff-e8c8d6a56f26a8d9721181b30407ec7a5cc81d5c509e50e6ed00871abf9e7fa5R6-R7). Back then the code compiled and I didn’t really bother looking at what this module was doing… I just checked and realized you [moved this API from `pub` to private](https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R790-R792), resulting in `cargo-sync-readme` to now not compile anymore.

I just wanted to let you know that this might happen. I don’t expect you to yank 6 versions just because of this (and I think you shouldn’t) — honestly I think the author of that PR should have warned me about the usage of a hidden API, and I didn’t do my job checking on what they were doing, and damn doing this on my spare time while I have millions of projects is no easy task.

Sorry for the “bad story” feedback. Feel free to close my issue, I don’t expect anything else than just letting you know some other people might have the problem too. :slightly_smiling_face:

**Comment by dtolnay** [comment]
This is the point of renaming it to `__private`, to make it clearly visible in code review.
