### ISSUE TITLE
Cannot split TokenStream on Token using Punctuated

### ISSUE THREAD

**Issue by Shadow53** [dtolnay/syn#955]
As part of trying to implement a procedural macro, I am trying to split a TokenStream on commas. Essentially, I have some `Meta::List` containing normal items and some containing items with a custom syntax. I am trying to write a function that takes the contents of such a list (`bar` in `#[foo(bar(...))]`) and splits the items without attempting to parse them further.

[This playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=14bb7da318e783ecd638f4f979aca2cf) shows what I am trying to do, using paths as the example content. I expect to get a list of `TokenStream`s, but instead I get a `Vec` of length 1, containing the entire input `TokenStream`.

**Comment by botika** [comment]
You have to define some type that implements [`Parse`](https://docs.rs/syn/1.0.58/syn/punctuated/struct.Punctuated.html#method.parse_terminated), for example `syn::Expr`, `syn::Path`. 

For this case use `Punctuated::<syn::Path, syn::Token![,]>`.

**Comment by Shadow53** [comment]
I understand for the case of the example that I would use `syn::Path`. I'm wanting to be able to split the `TokenStream` for *later* parsing. Though I may rewrite portions of my macro code that assume I can split the `TokenStream`...

**Comment by botika** [comment]
You cannot split a TokenStream with Punctuated. 

https://github.com/dtolnay/syn/blob/c100b1ef82ce1adbf2a87972500cc33803a74e70/src/buffer.rs#L301-L309 If you look at the implementation it does not stop unless it does not find another TokenTree and everything here is.

**Comment by Shadow53** [comment]
Thanks for the clarification. Looks like I'll be refactoring my code, then.

**Comment by dtolnay** [comment]
@Shadow53: here is how to split tokens on comma:

```rust
fn split_comma(input: ParseStream) -> Result<Punctuated<TokenStream, Token![,]>> {
    let mut split = Punctuated::new();
    let mut element = TokenStream::new();
    while !input.is_empty() {
        if input.peek(Token![,]) {
            split.push_value(element);
            split.push_punct(input.parse()?);
            element = TokenStream::new();
        } else {
            let token: TokenTree = input.parse()?;
            element.extend(iter::once(token));
        }
    }
    if !element.is_empty() {
        split.push_value(element);
    }
    Ok(split)
}
```

Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9b1327f0ec3daa1e944a87238db28e28
