### ISSUE TITLE
Expand macro expression

### ISSUE THREAD

**Issue by edgarogh** [dtolnay/syn#957]
I'm making an expression/function macro that takes a string literal, transforms it, and returns a new string literal. The problem I'm having is that string-literal-returning macros like `concat!`, `env!`, `stringify!` (and I might forget some) cannot be given as a parameter to my macro due to the order in which macros are expanded (they're passed as macro expressions, not expanded). I spent quite a bit of time in the doc and didn't find any way to expand a `ExprMacro` into the expanded macro's TokenStream, so I can use this in place.

Is there such a feature ? If no, is it planned, or impossible to do ?

**Comment by dtolnay** [comment]
I wouldn't want this to be built into syn, which is only supposed to be a parser. However it would be reasonable to address in a different crate.

**Comment by malobre** [comment]
@edgarogh Did you find a crate that could do this ?

**Comment by Nemo157** [comment]
You can proxy your proc-macro through a macro-rules-macro using <https://docs.rs/with_builtin_macros> to support a subset of the std macros. I have [an example using it](https://github.com/Nemo157/stylish-rs/blob/pr%C4%ABmum/core/src/lib.rs#L103-L105) and also extended that with optional support for the `proc-macro-expand` feature too in <https://github.com/Nemo157/stylish-rs/pull/5>.
