### ISSUE TITLE
parsing variables

### ISSUE THREAD

**Issue by flipchan** [dtolnay/syn#963]
Hi!
I'm trying to get my macro in my lib.rs file to read a variable in my main.rs file a pub const test: &str = "test";

How can I pass variables into a proc macro?

is there a way to have the const variable as an attr? like this:
```rust
pub const test: &str = "k9k9";
#[my_proc_macro(token = $test)]
fn runme() {}
```

The problem is that it takes all characters within the () as a long string, is there a way to bypass/solve this?

**Comment by dtolnay** [comment]
Hi @flipchan, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community. Syn is one of the most widely used crates so lots of people will have experience with it.

**Comment by lauti7** [comment]
@flipchan hey! did u get it to work? I'm trying something similar. My issue #1241
