### ISSUE TITLE
parsing functions triggers STATUS_STACK_BUFFER_OVERRUN when "panic = 'abort'" is set in workspace

### ISSUE THREAD

**Issue by gabdube** [dtolnay/syn#966]
Title says it all. Here's a simple project to replicate the issue:

[wtf.zip](https://github.com/dtolnay/syn/files/5920225/wtf.zip)

Just execute `cargo run` in the "hello" directory and watch the result. Removing `panic = 'abort'` in the workspace cargo.toml fixes the issue.

I'm running Windows 10. Tested with 

* rustc 1.49.0 stable-x86_64-pc-windows-msvc
* rustc 1.49.0 stable-x86_64-pc-windows-gnu
* rustc 1.51.0 nightly-x86_64-pc-windows-msvc (04caa632d 2021-01-30)

**Comment by dtolnay** [comment]
This is a proc-macro2 thing, not a syn thing. You need to add `proc_macro2::fallback::force()` to the top of main if using proc-macro2 in a panic=abort binary.
