### ISSUE TITLE
cargo metadata fails to verify the checksum of `syn-test-suite v0.0.0`

### ISSUE THREAD

**Issue by matthiaskrgr** [dtolnay/syn#967]
If i download syn `1.0.60` from crates.io `https://crates.io/api/v1/crates/syn/1.0.60/download` , extract it and run `cargo metadata` on the crate sources, I get an error:
````
  Downloaded syn-test-suite v0.0.0
error: failed to verify the checksum of `syn-test-suite v0.0.0`
````
It seems that I don't have the sources of the crate in my cargo cache (in `~/.cargo/registry/src/github.com-1ecc6299db9ec823/`).
There is only `syn-test-suite-0.0.0+test` but not `syn-test-suite-0.0.0`.

Maybe something went wrong while packaging?

**Comment by dtolnay** [comment]
Closing as this seems like a Cargo bug, not anything to do with syn specifically. If somebody does look into this and there is an easy workaround that syn would be able to do, I would welcome a PR.

**Comment by aidanhs** [comment]
For reference, this is to do with https://github.com/rust-lang/cargo/issues/7180
