### ISSUE TITLE
Match type (or alternative approach) for selecting a function based on field type

### ISSUE THREAD

**Issue by alvatar** [dtolnay/syn#968]
Hi,
First of all, thank you for this great project!
I'd like to ask if something is possible. It seems to me that probably someone else has thought of a solution for this before, but I wasn't able to find anything in search engines or in the issues of this project.

I want to be able to instantiate one function or another depending on the type. That would require checking the type, which seems to be impossible (is that correct?). It seems like just checking what's f.ty should be enough, but I can't get it to work.
My next try was to stitch together the name of the function with the type, to instantiate its variatn, but I wasn't successful either. What is below doesn't work:

```
#[proc_macro_derive(GenEncoder)]
pub fn gen_encoder(input: TokenStream) -> TokenStream {
    let DeriveInput { ident, data, .. } = parse_macro_input!(input);

    let fields = match data {
        Data::Struct(s) => match s.fields {
            Fields::Named(ref fields) => {
                let recurse = fields.named.iter().map(|f| {
                    let name = &f.ident;
                    let ty = &f.ty;
                    quote! { write_#ty(self.#name); }
                });
                quote! {
                    #(#recurse)*
                }
            }
            _ => unimplemented!(),
        },
        _ => unimplemented!(),
    };

...
```

So that's the idea: to instantiate one function or another depending on the type of each field.
I'm trying to create a custom serializer of structs.

**Comment by dtolnay** [comment]
Hi @alvatar, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community. Syn is one of the most widely used crates so lots of people will have experience with it.
