### ISSUE TITLE
Parse error for traits without parameter names

### ISSUE THREAD

**Issue by Manishearth** [dtolnay/syn#972]
Discovered in https://github.com/eqrion/cbindgen/issues/665, breaks on https://github.com/japaric/cast.rs. Minimal example:

```rust
trait Foo {
    fn bar(i32) -> i32;
}
```

```
error: Syn unable to parse file
 --> test.rs:2:14
  |
2 |     fn bar(i32) -> i32;
  |               ^ expected `:`
```

**Comment by Manishearth** [comment]
This is basically because `TraitItem::Method` just reuses `Signature`. I'm not sure what the best route forward is here, we can either create a separate `Signature`, or treat `Signature` to parse this as `_: ty`

**Comment by mystor** [comment]
Support for this deprecated trait syntax was actually intentionally (IIRC) removed a while back pre-1.0, in https://github.com/dtolnay/syn/commit/9b98fcec15a07b641338bd51c33eb6deb49c2899. I can't find the associated issue, though.

I think it was to simplify types before the 1.0 release, but I'm sure @dtolnay remembers more context.

**Comment by Manishearth** [comment]
Hmm. I have wished before that there be a context object proc macros can get this information from :/

This should at _least_ be a future incompat lint on the older edition. Oh well.

**Comment by Manishearth** [comment]
Also opened https://github.com/rust-lang/rust/pull/82918 so crates get nudged to newer editions

**Comment by dtolnay** [comment]
Yeah this is intentionally omitted from the 1.0 series.
