### ISSUE TITLE
Cannot parse trait associated type with empty bounds

### ISSUE THREAD

**Issue by SNCPlay42** [dtolnay/syn#974]
```rust
trait Foo {
    type Bar: ;
}
```

This is accepted by the compiler but is rejected by `syn` with the message "expected identifier" [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c9862499de800f64575a5384641a3d89).

**Comment by dtolnay** [comment]
Fixed in 1.0.63.
