### ISSUE TITLE
Infinite loop with syn::parse_str::<syn::Expr>("q^0:");

### ISSUE THREAD

**Issue by catenacyber** [dtolnay/syn#978]
You can reproduce this bug with default features by calling 
`syn::parse_str::<syn::Expr>("q^0:");`

This bug does not happen with feature `full` as this case seems handled here https://github.com/dtolnay/syn/blob/master/src/expr.rs#L1355

A fix could be to remove the check for `input.peek(Token![as])` at https://github.com/dtolnay/syn/blob/master/src/expr.rs#L1402
(but I am not sure if it breaks other things)

**Comment by dtolnay** [comment]
Thanks! I published a fix in 1.0.66.
